### ISSUE TITLE
Can't access JValue properties

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/jint#1001]
Given this `JObject` payload:

```json
"Properties": {
"x": {
"Type": "Content",
"ContentId": "4m1pcbaa6t6gzr87qebcw0ysc1"
},
"expirationDate": {
"Value": "2021-10-09T00:00:00Z"
}
}
```

Trying to access the `Value` fails when the JValue contains a DateTime

**Comment by lahma** [comment]
Caused by the fact that `JObject`is `IDictionary<string, JToken>` instead of the latest fix targeting `IDictionary<string, object>`

**Comment by lahma** [comment]
I'm working on a generic fix.

**Comment by sebastienros** [comment]
Thought about it since I had to handle it in Fluid, but didn't want to pay the price.
