### ISSUE TITLE
Operator overloading and string concatenation

### ISSUE THREAD

**Issue by biwa** [sebastienros/jint#1004]
Jint version: 1426408817.0.0

Usually when using the `+` operator on a class/struct and a string it concatenates the result of the class/struct `ToString()` method and the string. However, when enabling operator overloading and implementing an override for `+` this automatic conversion stops working.

Have a look at this example:

```cs
using System;
using Jint;
using Jint.Runtime.Interop;

namespace jinttestx
{
	struct Vector2D
	{
		public double X { get; set; }
		public double Y { get; set; }

		public Vector2D(double x, double y)
		{
			X = x;
			Y = y;
		}

		public static Vector2D operator +(Vector2D lhs, Vector2D rhs)
		{
			return new Vector2D(lhs.X + rhs.X, lhs.Y + rhs.Y);
		}

		public override string ToString()
		{
			return $"({X}, {Y})";
		}
	}

	class Program
	{
		static void Main(string[] args)
		{
			Engine engine = new Engine(cfg => cfg.AllowOperatorOverloading());
			engine.SetValue("Vector2D", TypeReference.CreateTypeReference(engine, typeof(Vector2D)));
			engine.SetValue("log", new Action<object>(Console.WriteLine));

			engine.Execute(@"

let v1 = new Vector2D(1, 2);
log(v1); // Works fine, prints '(1, 2)'
log('### ' + v1 + ' ###'); // Results in InvalidCastException

				");

			Console.WriteLine("End of progream reached");
			Console.ReadLine();
		}
	}
}
```
The example shows that the `+` operator is overloaded to add two `Vector2D`. In the JS portion I use the `+` operator with the intention of string concatenation, but doing so throws an `InvalidCastException`. It works fine when commenting out the overloading method.

This can be prevented by adding more overloading method, i.e. ones that accept strings for the left hand and right hand side:

```cs
public static string operator +(Vector2D lhs, string rhs)
{
	return lhs.ToString() + rhs;
}

public static string operator +(string lhs, Vector2D rhs)
{
	return lhs + rhs.ToString();
}
```

Is it intentional that the automatic string concatenation fails and has to be implemented manually?

**Comment by lahma** [comment]
Sounds like a bug to me.

**Comment by biwa** [comment]
My workaround is actually not 100% correct, because it'll only work with strings, but the expected behavior would be that it works with any object, so it should be something like this:

```cs
public static string operator +(Vector2D lhs, object rhs)
{
	return lhs.ToString() + rhs.ToString();
}

public static string operator +(object lhs, Vector2D rhs)
{
	return lhs.ToString() + rhs.ToString();
}
```

**Comment by lahma** [comment]
Should now work better., failing operator overload proceeds to normal code path.
