### ISSUE TITLE
Wrong overloaded method is called under certain circumstances

### ISSUE THREAD

**Issue by biwa** [sebastienros/jint#1008]
Jint version: 1439970634.0.0

When using overloaded method Jint usually choses the correct method to call depending on the parameters given in the JS code. However, this stops working when one of the overloaded methods accepts `object`. In that case the method accepting `object` is always called, except for - as far as I can tell - a version that accepts `ExpandoObject`.

Example:

```cs
using System;
using System.Dynamic;
using Jint;
using Jint.Runtime.Interop;

namespace jinttestx
{
	struct Class1
	{
		public static void Print(ExpandoObject eo)
		{
			Console.WriteLine("Class1: method Print(ExpandoObject eo)");
		}

		public static void Print(double[] a)
		{
			Console.WriteLine("Class1: method Print(double[] a)");
		}

		public static void Print(int i)
		{
			Console.WriteLine("Class1: method Print(int i)");
		}
	}

	struct Class2
	{
		public static void Print(ExpandoObject o)
		{
			Console.WriteLine("Class2: method Print(ExpandoObject eo)");
		}

		public static void Print(double[] a)
		{
			Console.WriteLine("Class2: method Print(double[] a)");
		}

		public static void Print(int i)
		{
			Console.WriteLine("Class2: method Print(int i)");
		}

		public static void Print(object o)
		{
			Console.WriteLine("Class2: method Print(object o)");
		}
	}

	class Program
	{
		static void Main(string[] args)
		{
			Engine engine = new Engine(cfg => cfg.AllowOperatorOverloading());
			engine.SetValue("Class1", TypeReference.CreateTypeReference(engine, typeof(Class1)));
			engine.SetValue("Class2", TypeReference.CreateTypeReference(engine, typeof(Class2)));
			engine.SetValue("log", new Action<object>(Console.WriteLine));

			engine.Execute(@"

Class1.Print([ 1, 2 ]); // Calls Print(double[] a)
Class1.Print({ x: 1, y: 2 }); // Calls Print(ExpandoObject eo)
Class1.Print(5); // Calls Print(int i)
log('-----');
Class2.Print([ 1, 2 ]); // Calls Print(object o), but should call Print(double[] a)
Class2.Print({ x: 1, y: 2 }); // Calls Print(ExpandoObject eo) as expected
Class2.Print(5); // Calls Print(object o), but should call Print(int i)

				");

			Console.WriteLine("End of progream reached");
			Console.ReadLine();
		}
	}
}
```

This example has two classes, `Class1` and `Class2`. Both have a method called `Print` that's overloaded with several different parameter types. Unlike `Class1`, `Class2` also has a method that accepts `object` as a parameter. When called the methods just print out their name and parameter.

The JS code calls all those methods of both classes, and while it calls the appropriate method in `Class1` as expected, for `Class2` it calls the method accepting `object` for the first and third call, while I'd expect it to call the methods accepting `double[]` and `int`, just as for `Class1`.

**Comment by lahma** [comment]
I'm unsure if this can be ever determined reliably using search and matching. 

For example js array full of strings but one number. We would need to traverse the array to ensure correct match, only `object[]` or `object` is valid parameter type in CLR method.

**Comment by biwa** [comment]
Well, it *does* work in my `Class1` example, as it choses the correct method. When writing something like

```js
Class1.Print([ 1, 2, 'qwe' ]);
```
it throws a `Jint.Runtime.JavaScriptException: No public methods with the specified arguments were found.` exception. However, when adding a new method to the class with `object[]` as argument that method will be called for the mixed array:

```cs
public static void Print(object[] o)
{
	Console.WriteLine("Class1: method Print(object[] o)");
}
```

But that will be called for *all* arrays, even if they just contain one type. So it seems to prefer a method that accepts `object` over all other methods, even though those worked fine without the `object` method.

**Comment by lahma** [comment]
You could also configure a `MemberFilter` to skip the one taking object as parameter if its always the wrong choice.

**Comment by biwa** [comment]
But I *do* want that method as a type of catch-all method ;) I ran into it while trying to work around #1004.

**Comment by lahma** [comment]
When Jint finds match looking good enough, it uses conversions trying to get data match signature. Object and object array win as they work without need of conversions that could error, like happens in numbers + string case.

**Comment by biwa** [comment]
I see. If it's not considered a bug, maybe an option could be added to make Jint choose the most appropriate method instead of going the path of least resistance? But on the other hand it's probably such an edge case that it might not be worth putting work into it (except maybe for #1004 ;) ).

**Comment by lahma** [comment]
`object` parameter now has less weight than `JsValue` or `ArrayInstance` going against CLR array. At least test case and problem here is now circumvented.
