### ISSUE TITLE
StackOverflowException when running Jint.Tests.CommonScripts

### ISSUE THREAD

**Issue by juliandeange** [sebastienros/jint#1017]
Hello,

I've been running the Unit Test projects included with the library and found out that Jint.Tests.CommonScripts fails with a StackOverflowException when using `dotnet test`.

Running in verbose mode it seems like the script `controlflow-recursive.js` is the one which is failing. If I comment out line 42 in `SunSpiderTests.cs` the tests are able to execute without any issues.

Is there any plan to fix this test case or could it even be removed entirely?

Thanks!

**Comment by sebastienros** [comment]
Snap, don't we run these in the CI ?

**Comment by sebastienros** [comment]
Actually we do run them and they passed.
Do you have a special environment that it fails on? What version of dotnet are you using, and are you on the main branch?

https://github.com/sebastienros/jint/runs/4385801313?check_suite_focus=true#step:4:28

**Comment by juliandeange** [comment]
Im using version 5.0.303 also this is with Jint version 3.0.0-beta-2035

![image](https://user-images.githubusercontent.com/10216135/144478010-d28bea93-fc08-4056-a475-6a2e755b6d4b.png)

**Comment by juliandeange** [comment]
This is only an issue when running the Debug configuration. Release there are no problems.

**Comment by lahma** [comment]
Yes recursive is hard in debug mode when no inlining happens.

**Comment by juliandeange** [comment]
I see. Should the Debug config be disabled when running these unit test projects then?

**Comment by lahma** [comment]
It's now run only when it's a release build, thanks for reporting this.
