### ISSUE TITLE
Error Message for 2 level deep property which do not exist

### ISSUE THREAD

**Issue by adeel41** [sebastienros/jint#102]
The following code throws an exception but the exception message is not very helpful.

``` csharp
            const string source = @"
var $user = {};
var myData = $user.storage.myData;";
            _engine.Execute( source );
```

The exception message is **Jint.Runtime.JavaScriptException**

I believe that error message should be more descriptive.

**Comment by lahma** [comment]
This should have been now fixed in 3.x series:

```
jint> var myData = $user.storage.myData;
TypeError: storage is undefined
```
