### ISSUE TITLE
Jint Error:  TypeError: Object has no method 'values'TypeError: Object has no method 'values

### ISSUE THREAD

**Issue by anshul-jain23** [sebastienros/jint#1029]
Jint is throwing error on compiling Object.values

**Comment by lahma** [comment]
Care to tell more details like version you are using? Probably works in v3 beta.

**Comment by lahma** [comment]
`Object.keys({ "a": 1, "b": 2 })` work in Jint 3 beta, please use the pre-release version from NuGet.
