### ISSUE TITLE
ParserException instead of SyntaxError?

### ISSUE THREAD

**Issue by resnickj** [sebastienros/jint#1034]
I have noticed some cases where I would have expected to see a `JavaScriptException` with an error of type `SyntaxError`, but instead a `ParserException` is seen:

        [Test]
        public void Test1()
        {
            var engine = new Engine();
            engine.Execute("{a: 1"); // throws ParserException
        }

        [Test]
        public void Test2()
        {
            var engine = new Engine();
            engine.Execute("JSON.parse('{\"a\":1');"); // throws ParserException
        }

Is this behaviour intended, or is it a bug? Particularly in the second example, it would seem appropriate to have a proper `SyntaxError` with a script stack trace (at least, this is what V8 does).

**Comment by resnickj** [comment]
Re the second case (`JSON.parse`), I took a look into the `JsonParser` class, and notice that there are a bunch of cases where it calls `ExceptionHelper.ThrowSyntaxError` and then other cases where it throws a `ParserException`. I'd be happy to work on a PR to make the behaviour consistent in all cases, but I'd like to get some guidance on your preferred approach:

1. Use `ExceptionHelper.ThrowSyntaxError` everywhere in the class, and never throw `ParserException`, or
2. Throw `ParserException` everywhere, and make the caller (i.e. `JsonInstance.Parse`) responsible for catching the `ParserException` and calling `ExceptionHelper.ThrowSyntaxError`. This would arguably keep the `JsonParser` class more "pure".

**Comment by lahma** [comment]
Jint should never throw `ParserException` as *runtime* behavior, it's an Esprima concept that Jint should translate to `SyntaxError` (JS concept). Generally when Jint uses Esprima to parse at runtime (like Function constructor) there's a try-catch. When Engine is given an invalid script then `ParserException` is OK as it's invalid JS which we cannot evaluate.

So I belive in these two test cases `Test1` behavior is valid, but `Test2` should throw `JavascriptException` which is of type `SyntaxError`.

I think only `JsonParser.ThrowError` is throwing `ParserException`, would it be enough to change it to use the `ExceptionHelper.ThrowSyntaxError`?

All PRs are always welcome 👍🏻

**Comment by resnickj** [comment]
@lahma Thanks for your reply, and to you and the Jint team for this awesome project.

You are correct that changing `JsonParser.ThrowError` would be enough to resolve the issue, although I would suggest a few other changes to improve the error messages: 
1. include information about the position within the JSON data, and 
2. don't include the full JSON string (as is done in some places), as it may be arbitrarily large.

I will try to work on a PR for this sometime in the next week or so.

**Comment by lahma** [comment]
Sounds great, thank you for helping out!

**Comment by lahma** [comment]
Fixed by #1038
