### ISSUE TITLE
RavenDB: referenceResolver.TryGetCallable is not called after switching to new Jint version

### ISSUE THREAD

**Issue by shlomo-ildar** [sebastienros/jint#1041]
Hi! 
We have switched to new Jint version in branch RavenDB-16912 (is to get into release 6.0):
old jint: https://github.com/ravendb/jint/commit/4b9c78e3fc3e1c96a8e54838a6181c3b519352f1
5:33
new jint: https://github.com/ravendb/jint/commit/d84af69871637c15e5db8a42fe5edb09cb397604

The test CanProjectFromCollectionNotInJson passes in v5.3 branch and fails in RavenDB-16912 on executing x.Tags.filter(...) in case x.Tags === undefined. Previously engine._referenceResolver.TryGetCallable() was called, but now it doesn't get called in line 184, as method EvaluateCall returns in line 170 after TryUnresolvableReference got called twice (first time in GetValue method):
https://github.com/sebastienros/jint/blob/main/Jint/Runtime/Interpreter/Expressions/JintCallExpression.cs#L166:171

**Comment by lahma** [comment]
Would you like to create a PR fixing the issue with a test case so it doesn't get broken again?

**Comment by shlomo-ildar** [comment]
I am not sure for which cases this block in lines 166:171 is intended for:
                    // deviation from the spec to support null-propagation helper
                    if (baseValue.IsNullOrUndefined()
                        && engine._referenceResolver.TryUnresolvableReference(engine, referenceRecord, out var value))
                    {
                        return value;
                    }

Can we just remove it?

**Comment by lahma** [comment]
Well the entire feature was built to support RavenDB ( https://github.com/sebastienros/jint/pull/410 ) so whatever makes it work I guess.

**Comment by shlomo-ildar** [comment]
here is your commit "Add support for Optional Chaining (#881)" where that block has appeared:
https://github.com/sebastienros/jint/commit/0dbcdb03958a35eb29b56956d7adf52e949d49d8#diff-831fc71b8f2f0e75ed36fa7a9271679b453f5a580e3d23295ecdb69f9672ae7d

**Comment by shlomo-ildar** [comment]
I could just return in TryUnresolvableReference false, but GetValue throws in this case:
https://github.com/sebastienros/jint/blob/main/Jint/Runtime/Interpreter/Expressions/JintCallExpression.cs#L120

Maybe it shouldn't throw.

**Comment by ayende** [comment]
See https://github.com/sebastienros/jint/pull/1042 for the fix.
The idea is that when we have a call on a null, we shouldn't short circuit.
