### ISSUE TITLE
Expose a canonical way to construct a user-defined class

### ISSUE THREAD

**Issue by markroth8** [sebastienros/jint#1046]
Assume I have a user-defined class, Test, defined as follows:

```
engine.Execute(
          "Test = /** @class */ (function() {\n" +
          "  function Test(a) {\n" +
          "    this.a = a;\n" +
          "  }\n" +
          "  return Test;\n" +
          "}());");
```

What is the canonical way to construct an instance of this class?

The closest answer seems to be:

```
var jsValue = engine.GetValue("Test");
var args = ...;
var instance = ((IConstructor)jsValue).Construct(args, jsValue);
```

According to @sebastienros, from our gitter chat https://gitter.im/sebastienros/jint?at=61dcd02446529077f57ac218

> the "issue is that we can't call Construct like this on the engine directly
> it expected an environment context to be created, which we don't have when calling it directly
> only if invoked from an Execute method
> I had to hard-code it in the Construct method
> I believe this method should be internal knowing this. And expose a new one specifically to simulate a new() and create the necessary context like Execute is doing."

@lahma, what are your thoughts? I'm happy to code up a PR if given some direction.

**Comment by lahma** [comment]
I'll whip up a proposal later this evening (your midday I guess).

**Comment by lahma** [comment]
https://github.com/sebastienros/jint/pull/1047 should address this.

**Comment by markroth8** [comment]
So cool - thank you for resolving this so quickly, @lahma!
