### ISSUE TITLE
Allow extending ES6 class from a base CLR type; currently throws with JavascriptException (message: "null")

### ISSUE THREAD

**Issue by christianrondeau** [sebastienros/jint#1048]
I'd like to implement a base class in C# that users will be able to inherit from, but it looks like it's not supported. Because the error message throws with "null", I'm not sure if it should be supported, if I'm doing something wrong, or if at least there should be a better error message.

To reproduce:

```c#
public class MyBaseType
{
    public string Value { get; set; } = "Hello World!";
}

[Test]
public void CanInheritFromClrType()
{
    var engine = new Engine();
    engine.SetValue("MyBaseType", TypeReference.CreateTypeReference<MyBaseType>(engine));
    // This line fails with JavascriptException, message = null
    engine.Execute("class MyExtendedType extends MyBaseType {}");
    engine.Invoke("let obj = new MyExtendedType();");
    var value = engine.Invoke("obj.Value");

    Assert.That(value.AsString(), Is.EqualTo("Hello World!"));
}
```

I think this is related to #165

Note that I can achieve a similar result by implementing the base class using `engine.Invoke("class MyBaseType { ... }")` but it's more practical to make a base class in C# in this case.

**Comment by lahma** [comment]
Should work now with changes made in #1049 , please see the test case which shows usage. For further improvements we do take PRs 😉

**Comment by christianrondeau** [comment]
Wow that was fast! I did clone the Jint source and will definitely look at contributing whenever I can; this looks perfect for what I needed at the moment. Thanks! <3
