### ISSUE TITLE
Jint.Runtime.JavaScriptException: 'require is not defined'

### ISSUE THREAD

**Issue by unruledboy** [sebastienros/jint#1065]
Hi,

I tried to use the latest version of jint 3.0.0-beta-2037 to run a js file that is currently running file with nodejs, a code snippet as shown below:

```
'use strict';

const jsdom = require("jsdom");
```

Jint complains: 

> Jint.Runtime.JavaScriptException: 'require is not defined'

I searched the issue history and found Jint.CommonJS but it does not support node packages: https://github.com/sebastienros/jint/issues/430

What I can come up with right now, is to use browserify to bundle all dependent npm packages into 1 gigantic js file.

**Comment by lahma** [comment]
Loading modules with require unfortunately isn't currently supported.

**Comment by unruledboy** [comment]
That's bit said. As it's quite often used. Thanks.

**Comment by lahma** [comment]
There's `Options.RegisterRequire` (at least currently, not sure if it will be there forever). This can be used to wire require call into module loader, but such module loader needs to be manually implemented that would handle all NPM path searching. 

Closing this and PRs welcome to improve NPM interop story.
