### ISSUE TITLE
Integer addition/subtraction leading to an overflow is not converted to Number

### ISSUE THREAD

**Issue by conicgames** [sebastienros/jint#1088]
Hello,

The following code doesn't behave as expected:

```
var result = new Jint.Engine().Evaluate("2147483647 + 1");
// Actual: 'result' is of type Integer with value -2147483648
// Expected: 'result' would be of type Number with value 2147483648
```
Subtraction has a similar behaviour.

Thanks for your time.

**Comment by conicgames** [comment]
I'll take care of the fix and make a pull request. As I understood, both operations should follow the same pattern as the multiplication operator: cast the first operand to long before the operation in JintBinaryExpression.cs at lines 271 and 318. I'm just not sure where to put the unit test. I'll try to figure it out.

**Comment by lahma** [comment]
Great find! The unit test location isn't that big of a deal than what's to have one. EngineTests maybe is a general thow-it-all file.
