### ISSUE TITLE
Exception when trying to pass object as method parameter

### ISSUE THREAD

**Issue by KubaZ2** [sebastienros/jint#1094]
Cannot pass [DiscordId](https://github.com/KubaZ2/NetCord/blob/alpha/NetCord/DiscordId.cs) as method parameter. It throws `System.ArgumentException: 'Object of type 'System.String' cannot be converted to type 'System.UInt64'.'`

**Comment by KubaZ2** [comment]
I'm new to jint and I don't really know how it works. I don't think I can fix it 😕

**Comment by lahma** [comment]
@KubaZ2 there was a bug in resolution algorithm that caused Jint to choose wrong overload in this case. You also need to set `AllowOperatorOverloading` to true in order for implicit/explicit conversions to kick in. 

https://github.com/sebastienros/jint/blob/0231800a0261f2f09a3d1e953c62ad219b73d8a5/Jint.Tests/Runtime/InteropTests.cs#L2770-L2780

There should be a build on MyGet feed soon (on NuGet later), see README on repo root how to access it.

**Comment by lahma** [comment]
And with #1099 merged you shouldn't even need to allow operator overloading, it's allowed by default with latest soon to be on MyGet version.
