### ISSUE TITLE
Custom CLR indexers are not working

### ISSUE THREAD

**Issue by xpg934** [sebastienros/jint#110]
Hello.

Sample code: https://gist.github.com/xpg934/0535961140166636b12d
Steps:

1) run it and you got an exception:
Unhandled Exception: System.FormatException: Input string was not in a correct format.

2) remove from js-code X[2]; (or just comment it) and run program again:
Unhandled Exception: System.InvalidOperationException: No matching indexer found

3) remove from SomeObject indexer (or comment it) and run program again:
Unhandled Exception: Jint.Runtime.JavaScriptException: Object has no method 'someMethodZZZ'

I think in all three cases, the behavior should be as in the third case.

FormatException is thrown because Jint try to convert 'someMethodZZZ' to int32 and use _knownConversions to convert... without try...catch.
If _knownConversions is empty (case 2) then TryConvert returns false, and it's ok.

But in any case, why Jint throws exception about no matching indexer, when I just call unknown method?

**Comment by kozec** [comment]
sooo... I gues he didn't? :)

**Comment by sebastienros** [comment]
omg, is that still an issue, can someone try to repro?

**Comment by sebastienros** [comment]
I changed the title to reflect the issue

**Comment by lahma** [comment]
Closing as obsolete. Jint now understand int indexers can can handle the conversion. The error about object not having the function is correct as there is no such function. We can reopen if we need to reiterate.
