### ISSUE TITLE
MyGet package version numbers

### ISSUE THREAD

**Issue by backfromexile** [sebastienros/jint#1101]
I just wanted to install the latest version including module support from MyGet. 
However, I noticed that that the versioning seems off there since 3.0.0-beta-2083.
Every version afterwards looks like this:
1373589813.0.0
1374627514.0.0
1375323328.0.0
...
1929335616.0.0
1940698957.0.0
1940977664.0.0

Is there a reason for these different version numbers since 3.0.0-beta-2083?

**Comment by lahma** [comment]
The publish pipeline changed from AppVeyor to GH Actions back then I believe.

**Comment by sebastienros** [comment]
It's easier to generate since we don't have to define a custom logic with prefixes in myget. And since these are just for intermediate consumption this doesn't matter much.
