### ISSUE TITLE
<parameter name> is not defined

### ISSUE THREAD

**Issue by source-transformer** [sebastienros/jint#1109]
### Discussed in https://github.com/sebastienros/jint/discussions/1108

<div type='discussions-op-text'>

<sup>Originally posted by **source-transformer** March 17, 2022</sup>
JINT will sometimes fail with a JavaScriptException

```
"<parameter name> is not defined"
```

There is a unit test that replicates this failure.  
</div>

**Comment by source-transformer** [comment]
It looks like this _might_ be a symptom of using the JINT engine across multiple threads.

When I changed the above setTimeout implementation to be on the main thread - the issue doesn't occur.

Just wanted to call that out since I think we can restrict our usage of each Engine to a single thread.

**Comment by lahma** [comment]
Jint is by design not thread-safe, so "odd things happening" might stem with multi-threaded usage.

**Comment by source-transformer** [comment]
As a way to give a "fail early, fail fast" exception - I've created a PR with a "thread check":

https://github.com/sebastienros/jint/pull/1110

I'm happy to put this "thread safety" check behind an optional config when you initialize the Engine if this seems overly precautious.

**Comment by lahma** [comment]
I've added API documentation on Engine level and in main README in #1489  to highlight the fact that engine is not thread-safe. The PR can be used for possible development, but as noted in https://github.com/sebastienros/jint/pull/1110#issuecomment-1449210351 it's not very simple to implement correctly.

Easiest path probably to make things evident enough via docs etc the same way like .NET's `Dictionary<T, K>` not being thread-safe.
