### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by resnickj** [sebastienros/jint#1120]
Just updated my local to latest main (650c0cb) and I'm getting build errors in VS2022. Should I be using a different development environment?

![image](https://user-images.githubusercontent.com/3383923/160972898-0b4434fa-2ce8-4e17-aaad-963ec07bae6b.png)

**Comment by resnickj** [comment]
After updating VS2022 to version 17.1.2, I'm down to 3 errors:

![image](https://user-images.githubusercontent.com/3383923/160976977-b91db0aa-197a-4ad3-a3fe-d0cca712e43d.png)

**Comment by lahma** [comment]
@resnickj check [Jint.Tests.Test262](https://github.com/sebastienros/jint/tree/main/Jint.Tests.Test262) for build instructions, the test suite needs to be generated.
