### ISSUE TITLE
Exception at destructuring assignment of tuple return values

### ISSUE THREAD

**Issue by biwa** [sebastienros/jint#1134]
I ran into a problem when trying to do a destructuring assignment of the tuple return value of a C# method. It causes an Jint.Runtime.JavaScriptException ("the value is not iterable").

The C# method returning the tuple:

```cs
static (int a, int b) TwoValues()
{
	return (1, 2);
}
```

Setting up the method in the engine:
```cs
engine.SetValue("twoValues", new Func<(int, int)>(TwoValues));
```

Calling it in JS:
```cs
engine.Execute(@"let [ a, b ] = twoValues();"); // Causes Jint.Runtime.JavaScriptException: 'The value is not iterable'
```

I'd expect `a` and `b` to have to respective values of the tuple returned by the method.

Here's a fully working example:

```cs
using System;
using Jint;

namespace jinttestx
{
	class Program
	{
		static (int a, int b) TwoValues()
		{
			return (1, 2);
		}

		static void Main(string[] args)
		{
			Engine engine = new Engine();
			engine.SetValue("log", new Action<object>(Console.WriteLine));
			engine.SetValue("twoValues", new Func<(int, int)>(TwoValues));

			Console.WriteLine("C#");
			var x = TwoValues();
			Console.WriteLine($"x.Item1: {x.Item1}"); // Prints 1
			Console.WriteLine($"x.Item2: {x.Item2}"); // Prints 2
			Console.WriteLine($"x.a: {x.a}"); // Prints 1
			Console.WriteLine($"x.b: {x.b}"); // Prints 2

			Console.WriteLine("\nC# - Destructuring");
			(int a, int b) = TwoValues();
			Console.WriteLine($"a: {a}"); // Prints 1
			Console.WriteLine($"b: {b}"); // Prints 2

			Console.WriteLine("\nJavaScript");
			engine.Execute(@"
let x = twoValues();
log(`x.Item1: ${x.Item1}`); // Prints 1
log(`x.Item2: ${x.Item2}`); // Prints 2
log(`x.a: ${x.a}`); // Prints undefined
log(`x.b: ${x.b}`); // Prints undefined
");

			Console.WriteLine("\nJavaScript - Destructuring");
			engine.Execute(@"
let [ a, b ] = twoValues(); // Causes Jint.Runtime.JavaScriptException: 'The value is not iterable'
log(`a: ${a}`); // Expected to print 1
log(`b: ${b}`); // Expected to print 2
");

			Console.WriteLine("\nEnd of progream reached");
			Console.ReadLine();
		}
	}
}
```

**Comment by lahma** [comment]
I think a, b is syntactic sugar by complier over Item1, Item2. Would you like to offer a PR to support this?

**Comment by biwa** [comment]
I knew you'd ask that ;) I'm just a clueless amateur, I have no idea where to even start looking. If you can point me in the right direction I can take a shot at it, but I can't promise that anything sensible will come from it.

**Comment by lahma** [comment]
I think it would require [some attribute sniffing](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGAzAATakDCpA3oaQ+TkqQBQCWAdgC6kCGAGlJdewAJSkAKgHcIANT4AbAK4wAzqzH1GdAo33kA7GxxCsYgNzaGAX0I2gA==) and creating translation lookups based on method signature, it won't be easy and probably quite brittle.

A far easier alternative would just declare a helper type like `readonly record struct AB(int a, int b);` and utilize such instead of tuples (which I usually use for private methods and such where "proper types" are not usually needed.

**Comment by lahma** [comment]
@biwa is this something you'd want to pursue in form of PR or is using a custom type enough?

**Comment by biwa** [comment]
I'm afraid I'm not skilled enough to make a PR for that. So the other route sounds fine, too. It's fine for me if you want to close this issue.

**Comment by lahma** [comment]
OK, I'm closing this as it would be considerable effort trying to support the metadata via reflection and would probably just cause more issues because of things not supported. Thanks for your understanding.
