### ISSUE TITLE
An incorrect double value is returned from a static method of the .NET type via interop

### ISSUE THREAD

**Issue by Taritsyn** [sebastienros/jint#1142]
Hello!

In Jint version 3.0.0 Beta 2038 an incorrect double value is returned from a static method of the .NET type via interop. Moreover, this error occurs only in version for .NET Framework (everything works correctly in .NET Core). If you run the following console application:

```csharp
using System;

using Jint;
using Jint.Runtime.Interop;

namespace TestJint
{
    class Program
    {
        static void Main(string[] args)
        {
            var engine = new Engine();
            TypeReference mathTypeReference = TypeReference.CreateTypeReference(engine, typeof(Math));
            engine.SetValue("Math2", mathTypeReference);
            double result = engine.Evaluate("Math2.Max(5.37, 5.56)").AsNumber();

            Console.WriteLine("Result: {0}", result);
        }
    }
}
```

Previous version (version 3.0.0 Beta 2037) and current version for .NET Core output a correct result:

```
Result: 5,56
```

Current version for .NET Framework outputs an incorrect result:

```
Result: 5,55999994277954
```

**Comment by lahma** [comment]
Thanks for the bug report, you seem to have quite the QA harness 🙂 I think this is probably something caused by adding support for `BigInt`...

**Comment by Taritsyn** [comment]
Hello, Marko!

> …, you seem to have quite the QA harness 🙂

I just have a large set of tests to guarantee the identical results of work of different JS engines.

**Comment by lahma** [comment]
The culprit was changes to method parameter scoring logic. `Math.Max(float, float)` was chosen instead of `Math.Max(double, double)` in this case and conversions were being made.

**Comment by Taritsyn** [comment]
@lahma Thank you!
