### ISSUE TITLE
Jint.Runtime.JavaScriptException: null

### ISSUE THREAD

**Issue by MeikelLP** [sebastienros/jint#1150]
```csharp
const string script = @"export function onPlay (ctx) {
    ctx.player.health += 500
}";
var engine = new Engine();
engine.AddModule("abc", script);
var ctx = new EffectContext{Player = new PlayerWrapper{Health = 500}};
var args = JsValue.FromObject(engine, ctx).AsObject();

var effect = engine.ImportModule("abc");
effect.Call("onPlay", args);
```

```
Jint.Runtime.JavaScriptException: null
```

I don't know what's actually not working. The exception is not helping.

**Comment by lahma** [comment]
This seems to work:

```csharp
var engine = new Engine();
engine.AddModule("abc", @"export function onPlay (ctx) { ctx.player.health += 500 }");
var ctx = new EffectContext { Player = new PlayerWrapper { Health = 500 } };
var args = JsValue.FromObject(engine, ctx);

var effect = engine.ImportModule("abc");
var onPlay = effect.Get("onPlay");
engine.Invoke(onPlay, args);
```

**Comment by lahma** [comment]
Closing as answered, if there's still something to act upon we can reopen.

**Comment by MeikelLP** [comment]
@lahma Thanks for the quick answer. Yes this does indeed work. I still find the error message not really helpful...

**Comment by lahma** [comment]
@MeikelLP you unfortunately went into pit of darkness there, when there's no engine and you directly call something "out of engine" things get awry really fast (from debugging I couldn't tell what error message would make sense in that point of code)).

When you use `Engine` methods you should usually get things you'd expect. So if you steer on the "JS side of things", things are usually easier. Inject CLR object - use JS to evaluate.

**Comment by MeikelLP** [comment]
Ah thanks. Maybe a warning in the exception would be helpful? If the message is `null` maybe say something like "Did you forget to call this from the engine?" or something like that might be really helpful for beginners :)

**Comment by lahma** [comment]
The `null` message usually mean that an exception was just thrown from somewhere inside the engine - it could have meaningful explanation or might not (in this case it was violating some expectations so there's no good message). But indeed, there are too many places where message is being omitted as "this should never happen".
