### ISSUE TITLE
Cannot declare methods on types extending from CLR

### ISSUE THREAD

**Issue by christianrondeau** [sebastienros/jint#1166]
Problem: JS types extending CLR types cannot declare function; they seem to be dropped completely. See the assertions at the end, I personally need the `.Get("method")` variation but you can see it also doesn't work with `Invoke`.

```c#
        [Fact]
        public void ShouldAllowMethodsOnClrExtendedTypes()
        {
            _engine.SetValue("ClrBaseType", TypeReference.CreateTypeReference<TestClass>(_engine));
            _engine.Evaluate(@"
                class JsBaseType {}
                class ExtendsFromJs extends JsBaseType {
                    constructor() {
                        super();
                        this.a = 1;
                    }

                    getA() {
                        return this.a;
                    }
                }

                class ExtendsFromClr extends ClrBaseType {
                    constructor() {
                        super();
                        this.a = 1;
                    }

                    getA() {
                        return this.a;
                    }
                }
            ");

            // This works
            var extendsFromJs = _engine.Construct("ExtendsFromJs");
            Assert.Equal(1, _engine.Evaluate("new ExtendsFromJs().getA();"));
            Assert.NotEqual(JsValue.Undefined, extendsFromJs.Get("getA"));

            // This does not work
            var extendsFromClr = _engine.Construct("ExtendsFromClr");
            Assert.Equal(1, _engine.Evaluate("new ExtendsFromClr().getA();")); // Crash: Property 'getA' of object is not a function
            Assert.NotEqual(JsValue.Undefined, extendsFromClr.Get("getA")); // Crash: Assert.NotEqual() Failure; Expected: Not undefined; Actual:   undefined
        }
```

The class that extends the CLR type is actually of type `ObjectWrapper` instead of `ObjectInstance`, if that helps!

I can take a look, but if you have ideas that would be welcome :)

**Comment by lahma** [comment]
Man you're evil 😉 Thanks for the bug report, I think I could have some time next weekend to check what's this about, but probably not sooner (if then!). 

Generally with interop it was originally created as "get/set values, call methods on CLR objects" kind of a thing and you are pushing it a bit further. The `extends` is a recent addition via class support so a lot of things can be lacking w.r.t. interop.

**Comment by christianrondeau** [comment]
Haha I didn't mean to ruin your day :) And no rush, I feel like you'll probably know where to look, but I can take care of making a PR later, I'll wait for your opinion on the matter!
