### ISSUE TITLE
Should i make Engine object singleton or create Engine object every call when i need eval script? Is Engine object thread safety when i eval script in multi thread using one Engine object?

### ISSUE THREAD

**Issue by yongxin100** [sebastienros/jint#1167]
Thanks of your awesome work!
Thanks very much.

**Comment by sebastienros** [comment]
Engine is not thread safe. You can pool them if you reuse the same base script and that the state can be recycled between each call, or you if you manage the scripts that run in it, i.e. if you don't run user-provided scripts that could hack the global state.

**Comment by yongxin100** [comment]
> Engine is not thread safe. You can pool them if you reuse the same base script and that the state can be recycled between each call, or you if you manage the scripts that run in it, i.e. if you don't run user-provided scripts that could hack the global state.

thanks
