### ISSUE TITLE
It's not possible to enumerate Object properties with leading zeros in names

### ISSUE THREAD

**Issue by lekrus** [sebastienros/jint#1180]
Hello,

When an object has properties that all numeric and start with zero, they cannot be enumerated.
There is no way to get them in Object.keys or in for..in
And Object.getOwnPropertyNames returns them as numbers.
The same code run in nodeJs or any browser will return expected result.

Please check the sample below:
```c#
var engine = new Engine();
var code = @"
  const testObj = { '02100' : true };
  var objKeys = Object.keys(testObj).length;
  var objPropNames = JSON.stringify(Object.getOwnPropertyNames(testObj));
";

engine.Execute(code);
Assert.Equal(1, engine.GetValue("objKeys").ToObject()); // returns 0
Assert.Equal("[\"02100\"]", engine.GetValue("objPropNames").ToObject()); // returns ["2100"]
```

**Comment by lahma** [comment]
Thanks for reporting, seems like a bug.

**Comment by lekrus** [comment]
Thank you for the quick fix! It works as expected now.
