### ISSUE TITLE
unsupported statement type 'VariableDeclaration' with Esprima v2.1.3

### ISSUE THREAD

**Issue by huantianad** [sebastienros/jint#1182]
When trying to execute a statement where we declare a variable, e.g. `var x = 10;`, it fails with a `ArgumentOutOfRangeException: unsupported statement type 'VariableDeclaration'`. This was resolved by downgrading Esprima to v2.1.2. As such, the nuget dependency for Esprima should specify exactly 2.1.2.

**Comment by lahma** [comment]
Can you share a full script that reproduces the problem?

**Comment by huantianad** [comment]
Something like this seems to give the error:
```cs
using Jint;

var engine = new Engine();
engine = engine.Execute("var x = 10;");

var x = engine.GetValue("x").AsNumber();
Console.WriteLine(x);
```

After a bit more testing it seems that it's an issue with using Jint nuget version `3.0.0-beta-2038` with Esprima `2.1.3`, the same doesn't happen with `3.0.0-preview-284` which has a requirement of Esprima `3.0.0-beta-1`. I'd assume the nuget package is older and made before Esprima `2.1.3`?

**Comment by lahma** [comment]
I understand now. There's infortunately no version of Jint built against Esprima 2.1.3. If you want to use newer package, then the MyGet feed is the way to go. 

I'm closing this one as I think there will not be a special servicing release to include 2.1.3 as dependency.
