### ISSUE TITLE
Compiler Errors: No Defining Declaration

### ISSUE THREAD

**Issue by source-transformer** [sebastienros/jint#1196]
Hi there, I just got the latest from the main branch and locally (on mac - Visual Studio Preview) - I'm getting the following two compiler errors:

```
/Users/tcassidy/github/jint/Jint.Tests.Test262/TestHarness.cs(33,33): Error CS0759: No defining declaration found for implementing declaration of partial method 'TestHarness.InitializeCustomState()' (CS0759) (Jint.Tests.Test262)

/Users/tcassidy/github/jint/Jint.Tests.Test262/Test262Test.cs(26,26): Error CS0759: No defining declaration found for implementing declaration of partial method 'Test262Test.ShouldThrow(Test262File, bool)' (CS0759) (Jint.Tests.Test262)
```

**Comment by source-transformer** [comment]
If I back out to commit:

013a78a4526c4ffbd8ee8e82ed1f33d6c7fe2471

(April 27th) - the compiler error concerning ShouldThrow(..) is no longer happening

**Comment by source-transformer** [comment]
And if I back out to commit:

3fa1f8343cf68952132621c9d2d2d9faa66eeeb0

(March 23rd) - the compiler error concerning InitializeCustomizeState is gone.

Again - this is on Mac OS X - both from within visual studio and using the command line.

I have both .NET 6.0 and 3.1 installed locally.  Validated by a coworker on their local machine.

**Comment by lahma** [comment]
Did you check the readme in test262 project about how to generate the tests?

**Comment by source-transformer** [comment]
ah - sorry - yes that resolved it.

I made the mistake for not noticing the doc update.

For others - it is probably worthwhile adding:

1. a build script for windows and linux/mac
2. a section on the top level README.md called "Build Instructions" which references that script

Just a suggestion - as I say - this was my mistake - but would likely help others.

**Comment by lahma** [comment]
@source-transformer I've merged a change to main that should now generate the missing test cases on first `dotnet build`, running `dotnet clean` should remove old ones and next build again should re-generate with current config.
