### ISSUE TITLE
Support defining properties on C# type prototypes.

### ISSUE THREAD

**Issue by AudriusButkevicius** [sebastienros/jint#1197]
Given I have my own type:
```
class Foo {
   public int x => 5;
   public int y => x * 2;
}
```

I can't think of a reason why I should not be allowed to do
```
Object.defineProperty(Foo, "z", {
   get: function() { return this.y * 2 }
});
```

Granted, I can do that from C#, but if there is some legacy code that relies on adding extensions to existing types (which are now delivered via Jint type references), it would make this much easier.

I agree that this might get confusing if you start re-definining things that exist in C#, but feels like this could be supported via some flag.

**Comment by lahma** [comment]
You are right about the confusing part. Interop in CLR is meant to generally reflect 1:1 state and shape between engine and CLR. If you come up with an elegant design to support such a PR would be appreciated 👍🏻

**Comment by AudriusButkevicius** [comment]
Do you have any pointers of how would one go about this?
Presumably there needs to be some sort of type proxy?

**Comment by lahma** [comment]
Basically everything related to proxying CLR object is inside `ObjectWrapper`. Basically [in this PR](https://github.com/sebastienros/jint/pull/1168/files#diff-85b22be3af5bd1c3c93b7445b3b9bed69b6ad241636b547857cb3df9b0b32625) such feature was removed as better way was found to cope with inheriting from CLR classes inside JS. So in other words you could inject CLR type to JS and inherit from it in JS as a class and then use the inherited version with the added features.

**Comment by lahma** [comment]
Can you try out the class inheritance route and report back if that fits the bill? Way easier and already supported.

**Comment by AudriusButkevicius** [comment]
```
        public class Foo
        {
            public int X => Y * 2;
            public int Y => 2;
        }

        [Fact]
        public void ExtendTypeTest()
        {

            _engine.SetValue("Foo", TypeReference.CreateTypeReference<Foo>(_engine));
            _engine.Execute("class Foox extends Foo { constructor() { super(); } }; Object.defineProperty(Foox, \"z\", { get: function() { return this.x * 2 }});");
            Assert.Equal(_engine.Evaluate("new Foox().y").AsInteger(), 2);
            Assert.Equal(_engine.Evaluate("new Foox().x").AsInteger(), 4);
            Assert.Equal(_engine.Evaluate("new Foox().z").AsInteger(), 8);
        }
    }
```

Does not seem to pass.

**Comment by lahma** [comment]
In that case it would just be

```javascript
class Foox extends Foo { constructor() { super(); } get z() { return this.x * 2 } };
````

**Comment by AudriusButkevicius** [comment]
The problem I have is that a legacy system with customer scripts already does `Foo.prototype.__defineGetter__` all over the place, which is what I need to replicate.

I could add `__defineGetter__` to redirect to `Object.defineProperty`, but I can't magically extend the class once the customer scripts call `Foo.prototype.__defineGetter__`.

**Comment by lahma** [comment]
So is this everything already working in this legacy system? I'm confused what needs to be fixed if something is already using APIs and expect them to do things and they do?

**Comment by AudriusButkevicius** [comment]
It's a legacy system written years ago in C that nobody wants to maintain. It had an embedded JS engine for scripting.
We're trying to move that to something more modern, yet not have to spend too much effort porting the scripts.

**Comment by lahma** [comment]
So what about defining a custom prototype? This would again require code changes and removing the `__defineGetter__` calls, but in the long run - if you really want to get legacy to this millenia, it might require some work anyway.

```csharp
var e = new Engine(cfg => cfg
    .SetWrapObjectHandler((engine, target) =>
    {
        var instance = new ObjectWrapper(engine, target);
        if (isTheTypeIWantToHaveMoreMembers)
        {
            instance.SetPrototypeOf(new MyPrototypeInstance(engine));
        }

        return instance;
    })
);
```

**Comment by AudriusButkevicius** [comment]
This only seems to work on instances, the goal is to set it on the type prototype so that the extensions/getters are there for all instances of the type.

**Comment by AudriusButkevicius** [comment]
Ok, I guess I could add `__defineGetter__` function to my type prototypes, capture the functions that supposedly get registered, and then upon wrapping objects, look those up based on type, and do Object.defineProperty on each instance?

**Comment by AudriusButkevicius** [comment]
I guess in the new standard, there is no way to do this for the whole type?

**Comment by lahma** [comment]
My idea was about exposing a prototype with all possible defined things, so they would in place without needing the defineGetter. I don't know the scale of your project but if you're jumping from unmanaged to managed language you could also tweak the scripts too be more modern?

**Comment by AudriusButkevicius** [comment]
The problem is that I want to maintain compatibility with existing legacy system, as there is still active script development going on that are outside of my control.


This seems to work, even though it's incredibly grim:
````
            var cacheProps = new Dictionary<string, Dictionary<string, JsValue>>();
            var e = new Engine(cfg => cfg
                .SetWrapObjectHandler((engine, target) =>
                {
                    var instance = new ObjectWrapper(engine, target);
                    if (target is Foo)
                    {
                        if (cacheProps.TryGetValue("Foo", out var props))
                        {
                            foreach (KeyValuePair<string,JsValue> keyValuePair in props)
                            {
                                instance.DefineOwnProperty(keyValuePair.Key, new GetSetPropertyDescriptor(keyValuePair.Value, null));
                            }
                        }
                    }

                    return instance;
                })
            );
            e.SetValue("Foo", TypeReference.CreateTypeReference<Foo>(e));
            e.SetValue(
                "registerExtension", new Action<JsValue, JsValue, JsValue>(
                    (a, b, c) =>
                    {
                        var typeName = a.AsString();
                        if (!cacheProps.TryGetValue(typeName, out var props))
                        {
                            props = new Dictionary<string, JsValue>();
                            cacheProps[typeName] = props;
                        }

                        props[b.AsString()] = c;
                    }
                )
            );
            e.Execute("Foo.prototype.__defineGetter__ = function(prop, cb) { registerExtension(\"Foo\", prop, cb); }");

            // Legacy code...
            e.Execute("Foo.prototype.__defineGetter__(\"z\", function() { return this.x * 2 });");

            Console.WriteLine(e.Evaluate("new Foo().y").AsNumber());
            Console.WriteLine(e.Evaluate("new Foo().x").AsNumber());
            Console.WriteLine(e.Evaluate("new Foo().z").AsNumber());
```

**Comment by AudriusButkevicius** [comment]
Uff, additional grimness. There is a chicken and egg problem whereby depending on the order some types might get instantiated early, and then extension attributes get registered further down the line, so I also have to track creation of each instance, and if a new extension is registered, add it to all existing instances of an object. 

Not sure how well this will work, as I assume this prevents any sensible form of GC.

**Comment by lahma** [comment]
My thinking would something like as follows, given that CLR instances can have normal JS prorotype:

```csharp
            var e = new Engine(cfg => cfg
                .SetWrapObjectHandler((engine, target) =>
                {
                    var instance = new ObjectWrapper(engine, target);
                    if (target is Foo)
                    {
                         var proto = engine.Get("__myProto");
                          target.SetPrototypeOf(proto);
                    }
                    return instance;
                })
            );
            e.SetValue("Foo", TypeReference.CreateTypeReference<Foo>(e));
            e.SetValue("__myProto", new PrototypeThingieWhichExtendsObjectInstance(e)));
           // OR e.Execute("__myProto = {};")
           // maybe a polyfill? or a custom CLR Func, anyway attach to just declared prototype
            e.Execute("__myProto.__defineGetter__ = function(prop, cb) { registerExtension(\"Foo\", prop, cb); }");
```` 
So I would create a global prorotype, attach it as prototype to wrapper instances and register needed __defineGetter__ to it. If there are more types on top of Foo, each would need their own global prototype instance.

**Comment by lahma** [comment]
I just copied your example for the register extension. Basically it should be enough to add the  any getter you need to prototype instance which is shared with Foo instances. If property is not found from Foo instance, its prototype will be checked.

```csharp
Object.defineProperty(__myProto, "z", {
   get: function() { return this.y * 2 }
});
```
So you just need to target the global instance of prototype. Any Foo instance will get the property via prototype check when own property retrieval fails, then prototype will be checked.

**Comment by AudriusButkevicius** [comment]
Great, I'll try it out later today.

**Comment by AudriusButkevicius** [comment]
Seems that I don't even need to set the prototype on the instances?

This simply seems to work, so I guess I just need to set an empty object as the type prototype?
Will something stop working because of that?

```c#
        public class Foo
        {
            public int X => Y * 2;
            public int Y => 2;

            public int bah()
            {
                return 3;
            }
        }

        public static void Main(string[] args)
        {
            var e = new Engine();
            e.SetValue("Foo", TypeReference.CreateTypeReference<Foo>(e));
            e.Execute("Foo.prototype = {};");
            e.Execute("Foo.prototype.__defineGetter__ = function(prop, cb) { Object.defineProperty(Foo.prototype, prop, { get: cb }); };");
            e.Execute("Foo.prototype.__defineGetter__(\"z\", function() { return this.x * 2 });");
            e.Execute("Foo.prototype.boo = function() { return 10; };");
            e.Execute("var instance = new Foo()");

            Console.WriteLine(e.Evaluate("instance.y").AsNumber());
            Console.WriteLine(e.Evaluate("instance.x").AsNumber());
            Console.WriteLine(e.Evaluate("instance.bah()").AsNumber());

            Console.WriteLine(e.Evaluate("instance.z").AsNumber());
            Console.WriteLine(e.Evaluate("instance.boo()").AsNumber());

            e.Execute("instance.bar = function() { return 10; };");
            Console.WriteLine(e.Evaluate("instance.bar()").AsNumber());

            e.SetValue("instance2", new Foo());

            Console.WriteLine(e.Evaluate("instance2.y").AsNumber());
            Console.WriteLine(e.Evaluate("instance2.x").AsNumber());
            Console.WriteLine(e.Evaluate("instance2.bah()").AsNumber());

            Console.WriteLine(e.Evaluate("instance2.z").AsNumber());
            Console.WriteLine(e.Evaluate("instance2.boo()").AsNumber());
        }
```

**Comment by lahma** [comment]
That probably works yeah, see also [Object.create](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create).

**Comment by AudriusButkevicius** [comment]
Thanks for your help.

While I have you here, is there a way to execute a statements iteratively like a coroutine? 

Given the engine takes a cancellation token, I assume there should be a way?

Namely I am doing `engine.Execute("main();");` which  which blocks for a long while, and I'd like to have some sort of way to suspend and resume execution, lets say after N statements return back to my C# code, do something and then continue executing where I left off.

**Comment by lahma** [comment]
> Given the engine takes a cancellation token, I assume there should be a way?

> Namely I am doing `engine.Execute("main();");` which which blocks for a long while, and I'd like to have some sort of way to suspend and resume execution, lets say after N statements return back to my C# code, do something and then continue executing where I left off.

Cancellation is part of terminating script if it takes too long or recurses too much. You could try to build your own constraint and it will be called from time to time to check whether execution is still allowed, you would keep allowing and running your own code in constraint callback. Other options could be (ab)using debugger hooks or injecting a custom CLR function and manually calling it from JS (requires JS changes).
