### ISSUE TITLE
__defineGetter__/__defineSetter__ leaks and overrides global prototype

### ISSUE THREAD

**Issue by AudriusButkevicius** [sebastienros/jint#1207]
Given:
```c#
class FooUnit
{
}

var engine = new Engine();
engine.SetValue("Foo", TypeReference.CreateTypeReference<FooUnit>(engine));
engine.SetValue("log", new Action<string>(Console.WriteLine));
engine.Execute("Foo.prototype.__defineGetter__('bar', function() { log('called'); return 5 });");
engine.SetValue("instance", new FooUnit());
engine.Execute("log(instance.bar)");

engine.Execute("var z = {};");
engine.Execute("z['bar'] = 20;");
engine.Execute("log(z['bar']);");
```

I would expect the output to be:
```
called
5
20
```

actual output is:
```
called
5
called
5
```

so seems that defining that getter somehow shadows that property on every object.

**Comment by AudriusButkevicius** [comment]
Equivalent in Chrome developer console:

![image](https://user-images.githubusercontent.com/1144861/176307411-a0e797b1-d557-4f7c-96af-6fa95731b85b.png)

**Comment by lahma** [comment]
Your JS sample is not equivalent though. `class Foo` has distinct prototype, when you inject `Foo` as C# class it get's `Object.prototype` as prototype - that's why the pollution.

**Comment by AudriusButkevicius** [comment]
I guess thats unexpected.

I guess I need to do the wrapping trick I did before to make sure I get a unique prototype per type?

Is there a reason why all class wrappers use the same prototype?

**Comment by lahma** [comment]
> I guess thats unexpected.

`TypeReference` was there long before `class` support was added. So that's probably the reason the current design differs.

> I guess I need to do the wrapping trick I did before to make sure I get a unique prototype per type?

Currently, yes.

> Is there a reason why all class wrappers use the same prototype?

Conceptually when using `CreateTypeReference` it probably would be logical to create distinct per-type prototype instance into engine to mimic `class` behavior. Would you like to create a PR with some test coverage?

**Comment by AudriusButkevicius** [comment]
I'm currently wondering how to do that. Do I just need to create a new function prototype in the typeref constructor? Or do I need a new object prototype as part of the function prototype?

**Comment by AudriusButkevicius** [comment]
I'm happy to make a PR with some tests in the evening europe.

Sorry, js internals is not my strong side, so I guess I need to understand what I need to do first.

Do I just change the typeref prototype to an ObjectInstance or do I change the backing prototype for FunctionPrototype?

Feels like you still should be able to do Foo.call() etc, hence feels like the prototype on the typeref should stay a function prototype, just perhaps not reuse the same global instance of the prototype?

**Comment by lahma** [comment]
I think it's this part in the file `// TODO should inject prototype that reflects TypeReference's target's layout`. So probably need to have a field in class that is always used for the prototype instead of `intrinsics.Object.PrototypeObject`.

**Comment by AudriusButkevicius** [comment]
I guess I am still lost as to what I need to do.
Tried:
```diff
diff --git a/Jint/Runtime/Interop/TypeReference.cs b/Jint/Runtime/Interop/TypeReference.cs
index bddfdc0d..a8059af4 100644
--- a/Jint/Runtime/Interop/TypeReference.cs
+++ b/Jint/Runtime/Interop/TypeReference.cs
@@ -25,7 +25,7 @@ namespace Jint.Runtime.Interop
         {
             ReferenceType = type;

-            _prototype = engine.Realm.Intrinsics.Function.PrototypeObject;
+            _prototype = new FunctionConstructor(engine, engine.Realm, engine.Realm.Intrinsics.Object.PrototypeObject);
             _length = PropertyDescriptor.AllForbiddenDescriptor.NumberZero;
             _prototypeDescriptor = new PropertyDescriptor(engine.Realm.Intrinsics.Object.PrototypeObject, PropertyFlag.AllForbidden);

```

But this doesn't seem to do much.

**Comment by AudriusButkevicius** [comment]
Nor does:
```diff
diff --git a/Jint/Runtime/Interop/TypeReference.cs b/Jint/Runtime/Interop/TypeReference.cs
index bddfdc0d..6c467fb7 100644
--- a/Jint/Runtime/Interop/TypeReference.cs
+++ b/Jint/Runtime/Interop/TypeReference.cs
@@ -25,9 +25,10 @@ namespace Jint.Runtime.Interop
         {
             ReferenceType = type;

-            _prototype = engine.Realm.Intrinsics.Function.PrototypeObject;
+            var proto = new ObjectPrototype(engine,  engine.Realm, new ObjectConstructor(engine, engine.Realm));
+            _prototype = new FunctionConstructor(engine, engine.Realm, proto);
             _length = PropertyDescriptor.AllForbiddenDescriptor.NumberZero;
-            _prototypeDescriptor = new PropertyDescriptor(engine.Realm.Intrinsics.Object.PrototypeObject, PropertyFlag.AllForbidden);
+            _prototypeDescriptor = new PropertyDescriptor(proto, PropertyFlag.AllForbidden);

             PreventExtensions();
         }

```

**Comment by lahma** [comment]
Thanks for the update, can't give much more pointers from top of my header. Probably requires some debugging and testing.

**Comment by lahma** [comment]
Hopefully latest MyGet version will have a remedy for this.

**Comment by AudriusButkevicius** [comment]
Thanks!
