### ISSUE TITLE
params Action[] delegate throws System.ArgumentException

### ISSUE THREAD

**Issue by luttje** [sebastienros/jint#1215]
Hope you're well! I'm still happily using Jint :)

## The bug / missing feature

Using anything other than an object array (`object[]`) for `params` in a method signature will throw an `ArgumentException`.

**Version tested:** 2.11.58
**Version affected:** both 2.x and 3.x (inferred by looking at DelegateWrapper code)

## Demonstration
This example demonstrates a method with `params Action[]`, but the problem also occurs with any element datatype other than object.

```csharp
using Jint;
using Jint.Runtime.Interop;
using System;

namespace TestJintParams
{
    internal class Program
    {
        delegate void ParamsTestDelegate(params Action[] callbacks);

        static void Main(string[] args)
        {
            var method = typeof(Program).GetMethod("ParamsTest");

            var engine = new Engine();
            engine.SetValue("print", new Action<string>(Console.WriteLine));
            engine.SetValue("callAll", new DelegateWrapper(engine, new ParamsTestDelegate(ParamsTest)));

            engine.Execute(@"
                callAll(
                    function() { print('a'); },
                    function() { print('b'); },
                    function() { print('c'); }
                );
            "); // Throws System.ArgumentException exception
        }

        static void ParamsTest(params Action[] callbacks)
        {
            foreach (var callback in callbacks)
            {
                callback.Invoke();
            }
        }
    }
}

```

The above code will throw this Exception: `System.ArgumentException: 'Object of type 'System.Object[]' cannot be converted to type 'System.Action[]'.'`

## Problematic code

This line of code in DelegateWrapper builds an object[] array for parameters: https://github.com/sebastienros/jint/blob/68bad5061d285f03feee35ecc4068755a1c87a31/Jint/Runtime/Interop/DelegateWrapper.cs#L105

That causes the exception a bit later when invoking: https://github.com/sebastienros/jint/blob/68bad5061d285f03feee35ecc4068755a1c87a31/Jint/Runtime/Interop/DelegateWrapper.cs#L134

## Proposed solution

Creating an array of the proper type would fix the problem in the above demonstration.

To do that I moved line 105 down one line and changed it from: https://github.com/sebastienros/jint/blob/68bad5061d285f03feee35ecc4068755a1c87a31/Jint/Runtime/Interop/DelegateWrapper.cs#L105

To: 
```csharp
var paramsParameterType = parameterInfos[paramsArgumentIndex].ParameterType.GetElementType(); // moved before array instantiation
var paramsParameter = Array.CreateInstance(paramsParameterType, paramsCount); // create array of correct type dynamically
```

Because the result of `Array.CreateInstance` is of the type `Array` (which can't be indexed using [ ]) this also requires changing this line: https://github.com/sebastienros/jint/blob/68bad5061d285f03feee35ecc4068755a1c87a31/Jint/Runtime/Interop/DelegateWrapper.cs#L126

To:
```csharp
paramsParameter.SetValue(converted, paramsIndex);
```

## Pull Request

I can't quickly figure out how to build and test this project so right now I won't make a PR with a unit test. Nevertheless I hope the above information helps you.

**Comment by lahma** [comment]
Thanks for the wonderfully detailed problem report, it made working on the fix easy! Please use the 3.x release as 2.x is no longer being maintained, you should see this fix available on MyGet feed documented in repo main readme quite soon!
