### ISSUE TITLE
Script delegates with params are called with object[]

### ISSUE THREAD

**Issue by luttje** [sebastienros/jint#1218]
Here to report more quirky behaviour with `params`, however I'm not sure if this one is as easy to fix as the last one...

I'm trying to implement [setInterval](https://developer.mozilla.org/en-US/docs/Web/API/setInterval) which accepts a variable amount of arguments after the delay:
```js
setInterval(func, delay, arg0, /* ... ,*/ argN)
```
However in my code, when invoking the func and providing the parameters, those parameters are passed as a single object array (`object[]`) instead of being "unpacked" to a series of variable parameters for use in the function.

## Demonstration
This demonstrates how invoking a delegate with params incorrectly servers all params in a single object[]
```csharp
using Jint;
using Jint.Runtime.Interop;
using System;

namespace TestParams
{
    internal class Program
    {
        public delegate void RegisterCallbackDelegate(CallbackAction callback, params object[] arguments);
        
        public delegate void CallbackAction(params object[] arguments);

        static void Main(string[] args)
        {
            var engine = new Engine();
            engine.SetValue("registerCallback", new DelegateWrapper(engine, new RegisterCallbackDelegate(RegisterCallback)));

            engine.Execute(@"
                var argsConcat = '';
                registerCallback((valTest, valOther, valNumber) => {
                    argsConcat+=typeof valTest;
                    argsConcat+=' ' + typeof valOther;
                    argsConcat+=' ' + typeof valNumber;
                }, 'test', 'other', 1337);
            ");

            if (engine.Evaluate("argsConcat === 'string string number'") == true)
                Console.WriteLine("Params in delegates work as expected");
            else
            {
                Console.WriteLine(engine.Evaluate("argsConcat"));
                Console.WriteLine("Params for delegates are incorrectly served as a single object[]");
            }

            Console.ReadKey();
        }

        static void RegisterCallback(CallbackAction callback, params object[] arguments)
        {
            callback.Invoke(arguments);
        }
    }
}
```

## Problematic code
I've spent quite sometime trying to figure out what is wrong and I suspect it's around here: https://github.com/sebastienros/jint/blob/110ea56bce734fad575becc1bd475283947c440d/Jint/Runtime/Interop/DefaultTypeConverter.cs#L210

It seems to me like at some point in this BuildDelegate function, the information that the argument has a [ParamsArrayAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.paramarrayattribute?view=net-6.0) is lost/ignored.
That or it's being passed incorrectly to the lambda here:
https://github.com/sebastienros/jint/blob/110ea56bce734fad575becc1bd475283947c440d/Jint/Runtime/Interop/DefaultTypeConverter.cs#L256

Sadly I have no experience with Linq.Expressions. Neither trial and error nor looking online has yielded positive results or anymore understanding of where the problem lies. Perhaps it's not even here, but where the Expression.Lambda is eventually called?

Hope this helps in some way! 

Have a nice Sunday.

PS: I'm on the latest 3.x version

**Comment by mainlyer** [comment]
Hi, I created a PR #1520 and now the DelegateWrapper constructor accepts one more parameter (spreadParameters). When is set to true, the callback behavior is as expected by @luttje.

Regards.
