### ISSUE TITLE
Jint doesn't identify literal regular expression

### ISSUE THREAD

**Issue by fadoaglauss** [sebastienros/jint#1224]
I use Jint library in version v3.0.0-beta-1715 in my application and today I'm trying to migrate to the latest version (v3.0.0-beta-2038), but when running some tests I found bug when executing literal regular expression as below, because Jint doesn't identify it.

![image](https://user-images.githubusercontent.com/21226741/179085785-e54e7202-1fa5-4536-8f12-24aec0c48390.png)
![image](https://user-images.githubusercontent.com/21226741/179086661-42390906-3637-447e-b629-54da7b3c8969.png)

**Comment by lahma** [comment]
So is it a problem to have `AdaptRegexp = true`? That's basically the case needed usually to transfer some JS code to .NET CLR.

**Comment by lahma** [comment]
Closing as adapt mode should be used basically always.
