### ISSUE TITLE
Jint doesn't' run when the "main" function is const

### ISSUE THREAD

**Issue by fadoaglauss** [sebastienros/jint#1225]
I use Jint library in version v3.0.0-beta-1715 in my application and today I'm trying to migrate to the latest version (v3.0.0-beta-2038), but unfortunately Jint doesn't recognize "main" function when its type is const and it's a critical bug considering my application scenario.
![image](https://user-images.githubusercontent.com/21226741/179088196-d215a357-292f-4c0f-a4f5-919f44b6b865.png)
![image](https://user-images.githubusercontent.com/21226741/179088203-228c1ed1-7a24-4170-9ff7-96b71ffdbaa9.png)

I created the test below to facilitate the error execution:
```
public void ShouldAllowInvokeALambdaFunctionUsingConstantType()
{
    RunTest(@"
        const get = (x) => { return x; }
    ");

    var add = _engine.GetValue("get");
    string str = "1";
    Assert.Equal(str, add.Invoke(_engine, str));
}
```

**Comment by lahma** [comment]
`let/const` will fall out of scope after exiting the current call `RunTest`, so `get` will be undefined. There's no `get` function after the call. You need to declare it as global or declare and call it as part of your engine call.
