### ISSUE TITLE
Howto : How do I call a function of a JavaScript object?

### ISSUE THREAD

**Issue by rolandroos** [sebastienros/jint#123]
Home page example is:
var engine = new Engine()
        .Execute("function add(a, b) { return a + b; }")
        ;
var add = new Engine()
        .Execute("function add(a, b) { return a + b; }");
        .GetValue("add")
        ;

    add.Invoke(1, 2); // -> 3

Thats fine, but how do I call an instance method?

var engine = new Engine()
        .Execute("function A()
            {
            }
A.prototype.DoSomething =
function (x)
{
    return x + 1;
};");

 The answer is:
    engine.Execute("var aInstance = new A();");
    JsValue valInstance = backEngine.GetValue("aInstance");
            JsValue valDoSomething  = backEngine.GetValue(valInstance, "DoSomething");
            JsValue result =  valDoSomething.Invoke(1);
            //result  == 2!

By the way, where can I add examples that I found out?
Like, documentation examples?
That may help others in using it.
Or can I add Unittests to the project?

**Comment by postromantic** [comment]
Hi @rolandroos.
You do it in a strange way. The last block could be as simple as that:

    var value = engine.Execute("new A().DoSomething(1);").GetCompletionValue();
There are a lot of good unit tests so i don't feel lack of documentation. BTW, GetCompletionValue example is the first code example in readme.md =)
