### ISSUE TITLE
Proxy with template literals does not use toString property

### ISSUE THREAD

**Issue by omegatmm** [sebastienros/jint#1249]
```javascript
const proxy = new Proxy({}, {})
proxy.toString = () => 'Test'
const test = `${proxy}`

test === 'function () { [native code] }'
```

I would expect test === 'Test'. This works with an online tester I tried. 

I see that this was changed with https://github.com/sebastienros/jint/pull/736, should the ToString override look for toString properties first, then fall back to 'function () { [native code] }'?

**Comment by lahma** [comment]
A PR with proposed fix would be most welcome!
