### ISSUE TITLE
Object has no method 'find'

### ISSUE THREAD

**Issue by DecapitatedKneecap** [sebastienros/jint#1254]
I am passing an array into a script and trying to use the `find` function to locate an element. I am getting the error `Object has no method 'find'` in the below code. However, I can use `map` without issue.

    var people = new[] {
        new { Name = "bob" },
        new { Name = "mary" },
        new { Name = "john" },
        new { Name = "suzy" },
    };

    var engine = new Engine().SetValue("people", people);

    object value = null;

    //Object has no method 'find'
    value = engine.Execute("people.find(function(x) { return x.Name == 'mary';})").GetCompletionValue();

    //map works fine, though
    value = engine.Execute("people.map(function(x) { return x.Name + 'aaa';})").GetCompletionValue();

**Comment by lahma** [comment]
Please try with v3 beta.

**Comment by DecapitatedKneecap** [comment]
Thanks, that worked. Changed the code to:

    engine.Evaluate("people.find(function(x) { return x.Name == 'mary';})").ToObject()

Am I correct in seeing that v3 has been in beta since May 2021? Any idea when this will make it to latest stable?

**Comment by lahma** [comment]
You can also use arrow functions and other goodies with v3. Don't know when it will be out of beta, hard to get people to do free work anr finalize missing bits it seems 🤷🏻‍♂️

**Comment by pkanavos** [comment]
Does this work with JArray? There's [a related question at SO](https://stackoverflow.com/questions/74731030/deserializing-embedded-array-list-to-array-in-c-sharp-as-expandoobject/74731846)where the poster insists the problem is Expando or JArray. 

This simplified example 👍 

```
var v = new JArray(1, 2, 5);
engine.SetValue("value", v);
var result=engine.Evaluate(" return value.filter( it => it===5)");
```

Throws 

`Accessed JArray values with invalid key value: "filter". Int32 array index expected.
`

**Comment by lahma** [comment]
@pkanavos there's some discussion about Newtonsoft problems here: https://github.com/sebastienros/jint/issues/1305
