### ISSUE TITLE
Compiling 3.0.0 beta with .Net Native makes the compiler crash (works with 2.11.58)

### ISSUE THREAD

**Issue by ianier** [sebastienros/jint#1256]
Linking Jint into an app compiled with .Net Native makes the compiler crash with error message "ILT0005: nutc_driver.exe returned exit code 2", which basically means an internal compiler error. This probably isn't an issue with Jint itself, but still something you might want to have a look at. 

To reproduce the issue:
-Create an empty UWP app using the "Blank App (Universal Windows)" VS template.
-Add the Jint nuget package 3.0.0-beta-2039 to the app; no need to add any code.
-Build the app in Release|x64 mode. Compilation will fail with the above message.

The same works with Jint package version 2.11.58.
Any ideas?

**Comment by ianier** [comment]
Looks like the problem is caused by Esprima. Same idea as above for a repro: Esprima 2.1.3 compiles fine but 3.0.0-beta-4 crashes the compiler.
I'm currently trying to find how/where to report this issue to Microsoft.

**Comment by lahma** [comment]
Sounds interesting, I have no familiarity with UWP development so thanks for looking into this!

**Comment by ianier** [comment]
> Sounds interesting, I have no familiarity with UWP development so thanks for looking into this!

I sent an email to dotnetnative at microsoft dot com as this is certainly a compiler bug. If/when they reply I'll post their answer here.

In the meantime, I cloned both Esprima and Jint, added them to the same solution and referenced them from an empty UWP app. Should anyone want to try this, to be able to reference the assemblies directly from the UWP project you have to remove the net462 targets from them, leaving only the netstandard ones.

Compiling the project with the .Net Native toolchain results in the same issue, either in Debug or Release mode. I could make compilation succeed by adding the following lines to Default.rd.xml:

      <Assembly Name="Esprima" Dynamic="Excluded"/>
      <Assembly Name="Jint" Dynamic="Excluded"/>

However, the internal compiler error comes back as soon as I try to instantiate Jint or Esprima, by adding either of the following lines anywhere in the code:

var parser = new Esprima.JavaScriptParser("2*2");
var engine = new Jint.Engine();

Surprisingly, though, compilation of the following succeeds:

Jint.Engine engine = null;
var exe = engine.Execute("4 * 5");

I also tried several older versions of .Net Native and they all result in the same problem, though the error message for older versions is sometimes related to a null pointer exception, as opposed to the internal compiler error message of newer versions.

So I'd say there's something in the Jint.Engine type or its constructor that the toolchain doesn't like, but so far I've been unable to figure out what it is. If I find a workaround I'll make a suggestion here or a PR.

BTW, this project is amazing work! I'm considering using it in my UWP app and that's why I'm looking at it.

**Comment by ianier** [comment]
So far no response from Microsoft. 
In case anyone is interested in an alternative: I resorted to using one of the lightweight OSS native JS engines available. Both _duktape_ and _mujs_ can be compiled for uwp targeting all CPU architectures effortlessly via [vcpkg](https://vcpkg.io/en/packages.html). I chose the former and built a simple interop layer including just the features I wanted.

**Comment by lahma** [comment]
Cool, thanks for the update. These two alternatives were new to me. I hope they serve a purpose - hopefully Jint would also fill the gap at some point.

Maybe @sebastienros can at some point reach some connections at the Big Company for some insights, if needed.

**Comment by ianier** [comment]
> These two alternatives were new to me. 

FYI, chakracore is another one compilable for uwp via vcpkg, though not really lightweight.

> Maybe @sebastienros can at some point reach some connections at the Big Company for some insights, if needed.

That would be great, though MS already declared .net native legacy tech so I'm not sure how far they'll go to support us.
I guess the issue is related to the fact that Jint/Esprima, while compliant with netstandard20, uses newer C# language features (e.g. static anonymous functions, patterns) that confuses the .net native toolchain. Keep in mind that .net native needs to look behind just IL to account for differences between .net framework code and the equivalent native library implementation.

**Comment by lahma** [comment]
@ianier can you also check the latest beta, it fixed an AOT issue, but unfortunately probably won't help here.

**Comment by ianier** [comment]
> @ianier can you also check the latest beta, it fixed an AOT issue, but unfortunately probably won't help here.

Thanks for following up on this. I just gave it a try and unfortunately got the same compiler error. Linking to the latest Esprima beta alone, without Jint, also triggers the same issue.
As I mentioned above, the most likely reason is the .net native toolchain not understanding the recent C# idioms. I suggest closing this issue as not being specific to Jint, unless someone from Microsoft can have a look at it.
