### ISSUE TITLE
Enhance Date parsing

### ISSUE THREAD

**Issue by ianier** [sebastienros/jint#1257]
Consider the following script, which you can run on your browser or use something like https://playcode.io/empty_javascript/ to run it online:

            console.debug(new Date("Thursday January 01 1970 00:00:25 UTC") * 1); //should result in 25000
            console.debug(new Date("Wednesday 31 December 1969 18:01:26 MDT") * 1); //86000
            console.debug(new Date("Wednesday 31 December 1969 19:00:08 EST") * 1); //8000
            console.debug(new Date("Wednesday 31 December 1969 17:01:59 PDT") * 1); //119000
            console.debug(new Date("December 31 1969 17:01:14 MST") * 1); //74000
            console.debug(new Date("January 01 1970 01:46:06 +0145") * 1); //66000
            console.debug(new Date("December 31 1969 17:00:50 PDT") * 1); //50000

Currently in Jint most (if not all) of the above dates result in NaN.

An implementation strategy could be to replace the time zone by the actual offset:
MST => -0700
UTC => +0000
MDT => -0600
EST => -0500
PDT => -0700
...
and then add at least the following format strings to the secondary parsing formats (and parse as UTC of course):
"dddd MMMM dd yyyy HH:mm:ss zzz"
"dddd dd MMMM yyyy HH:mm:ss zzz"
"MMMM dd yyyy HH:mm:ss zzz"

**Comment by lahma** [comment]
I think this somewhat duplicates #766

**Comment by ianier** [comment]
> I think this somewhat duplicates #766

Totally agree. I'm closing this one as a duplicate of #766 (at least we have a few more test cases here).

**Comment by ianier** [comment]
Totally agree. I'm closing this one as a duplicate of https://github.com/sebastienros/jint/issues/766 (at least we have a few more test cases here).

**Comment by lahma** [comment]
Fixes for this just landed main and soon available on MyGet feed. All test cases provided here now pass. Thanks for the report!
