### ISSUE TITLE
Adding non-CLR type

### ISSUE THREAD

**Issue by chrisdrobison** [sebastienros/jint#126]
Is it possible to add a non-CLR type? For instance, I want to create a stub of XMLHttpRequest that other scripts can call, but those scripts do 'new XMLHttpRequest()'. Does this work with Jint?

**Comment by ala53** [comment]
It's quite easy. Add a CLR type:

`engine.SetValue("XMLHttpRequest", typeof(MyNamespace.XMLHttpRequestImpl));`

Then you can call new `XMLHttpRequest` and it should work.

**Comment by mcintyre321** [comment]
Hi @chrisdrobison  - did you get anywhere with this?

**Comment by peymanmortazavi** [comment]
@ala53 engine.SetValue("XMLHttpRequest", typeof(MyNamespace.XMLHttpRequestImpl)); doesn't work for me. I add my type just like that but I get an error about not being able to construct an object.

**Comment by WinInsider** [comment]
engine.SetValue("XMLHttpRequest", typeof(MyNamespace.XMLHttpRequestImpl)); ... did not work for me either... it would be good if there was more explicit method to accomplish this scenario... but in meantime this is what works for me...

engine.SetValue("XMLHttpRequest", TypeReference.CreateTypeReference(engine, typeof(XMLHttpRequest)));

**Comment by mcintyre321** [comment]
I've got some code here: https://gist.github.com/mcintyre321/4e86e2e00944c028ce75 which works for XMLHttpRequest, not been thoroughly tested though

**Comment by sebastienros** [comment]
@mcintyre321 The code you are showing is using Jurassic, how is that related to this issue?

**Comment by mcintyre321** [comment]
Whoops! I did this ages ago and tried out Jurassic/Jint etc. and got mixed
up as my Gist didn't have any namespace imports. Sorry for any time wasted.

**Comment by lahma** [comment]
Closing as obsolete. One can define new'able types with both `TypeReference` (C#) and by using classes or functions (JS).
