### ISSUE TITLE
Unable to ResgisterRequire with AddModule

### ISSUE THREAD

**Issue by KCFindstr** [sebastienros/jint#1262]
I exposed some C# code as JS modules with `AddModule`, and I want to use `require` in JS code to load these modules. I find that the way to enable this is to set `Option.Modules.RegisterRequire = true`, however when I set this in options, I got an error saying that RegisterRequire can only be used if modules are enabled. Therefore, I called `EnableModules` on some dummy path that contains no module, and set `RegisterRequire` to `true`. This workaround allows me to use `require` in JS.

However, the documentation says
> Note that you don't need to EnableModules if you only use modules created using AddModule.

My understanding is that I should be able to `RegisterRequire` even if I don't `EnableModules` but `AddModule`. Is there anything I'm missing?

**Comment by lahma** [comment]
Yes, I think you are correct. The implementation/validation probably did keep up with other module development.

**Comment by lahma** [comment]
@KCFindstr this test case passes for me:

```csharp
[Fact]
public void CanUseRequireForLoadingModules()
{
    var engine = new Engine(options =>
    {
        options.Modules.RegisterRequire = true;
    });

    engine.AddModule("imported-module", @"export const value = 'exported value';");
    var value = engine.Evaluate("require('imported-module').value;");
    Assert.Equal("exported value", value);
}
```
Can you share a repro for your problem?

**Comment by KCFindstr** [comment]
Sorry for the trouble, I checked again and it turns out to be a mismatch between my exported module name and the name used in JS. The error I got was actually `InvalidOperationException: Module loading has been disabled, you need to enable it in engine options` which made me think it was a problem with EnableModules. I came up with the wrong conclusion and applied both fixes together. Apologize for taking you time!

**Comment by lahma** [comment]
No worries,  thanks for the follow-up!
