### ISSUE TITLE
RegExp String Iterator always returns false

### ISSUE THREAD

**Issue by vicr123** [sebastienros/jint#1263]
Spreading an iterator after using `matchAll()` does not work properly:

```js
let string = "one two three";
let matches = [...string.matchAll(/t/g)];
// matches.length should be 2, but Jint returns 0
```

After doing some digging, the source of the problem seems to be that `RegExpStringIterator` may be returning the wrong thing:
https://github.com/sebastienros/jint/blob/8b89a992415aa2c598e01b5b3ad666dc48696493/Jint/Native/Iterator/IteratorInstance.cs#L273
Should this line be `return true;`?

**Comment by lahma** [comment]
Your reasoning might very well be correct. Would you like to create a PR containing a test case and the fix?
