### ISSUE TITLE
Calling generic methods

### ISSUE THREAD

**Issue by npenin** [sebastienros/jint#127]
Hi Seb,

I could not find anywhere whether it was possible to call generic methods. I found contructors, but not methods. Is it the same syntax ?

Thanks,
See you,
Nicolas

**Comment by sebastienros** [comment]
Look at the readme, there is an example

**Comment by BigBadBleuCheese** [comment]
I see an example of instantiating a generic type, but not invoking a generic method. Went back to [the version of the readme when you answered this issue](https://github.com/sebastienros/jint/tree/e6b06b70fdc2485b5f909a5360858cca9ebe58bd), couldn't find the example you're talking about.
