### ISSUE TITLE
Add benchmark results to Readme.

### ISSUE THREAD

**Issue by SebastianStehle** [sebastienros/jint#1278]
Would be great if you could the benchmark results to the Readme. I had a look to the latest commit and I could not see it.

**Comment by lahma** [comment]
Good idea, I'll try to cleanup and maybe widen the test suite a bit.

**Comment by sebastienros** [comment]
There should be a column with single usage script, and reused script, to show the impact of pre-compilation. Similar to first-request cost on web apps. Just for the cases where apps run dynamically provided scripts (not only because Jint should fare better).

**Comment by lahma** [comment]
You can see now the benchmark results in [benchmark directory readme](https://github.com/sebastienros/jint/tree/main/Jint.Benchmark), will probably be updated occasionally when needed. All PRs to improve are welcome!
