### ISSUE TITLE
IndexDescriptor.Value throws Exception if Indexed Object doesn't have the key

### ISSUE THREAD

**Issue by albyrock87** [sebastienros/jint#128]
Test case:
```csharp
var engine = new Engine();
var dict = new Dictionary<string, object>() { { "foo", "bar" } };
// you can also use:
// var dict = new { foo = "bar" };
engine.SetValue("obj", dict);
engine.Execute("obj.undefinedProperty ? 1 : 0");
```

The last instruction throws an Exception because internally it calls *Dictionary [index]* method which throws an exception if index does not exist.

This can be fixed in IndexDescriptor.Value.get:
```csharp
object[] parameters = { _key };
try
{
    return JsValue.FromObject(_engine, getter.Invoke(_item, parameters));
}
catch
{
    return JsValue.Undefined;
}
```

Using try-catch statement there is not fast... we could use something like ContainsKey (if that method exists in the class definition).

Thank you for this awesome project!

**Comment by sebastienros** [comment]
Landed, thanks.
