### ISSUE TITLE
JSON.stringify fails with JArray properties

### ISSUE THREAD

**Issue by andreabalducci** [sebastienros/jint#1305]
I'm trying to serialize a variable with a JArray property, JInt fails throwing an exception
`Accessed JArray values with invalid key value: \"toJSON\". Int32 array index expected.`

Repro:

```
var engine = new Engine();
var arr = new JArray();

engine.SetValue("testSubject", arr);
var fromEngine = engine.Evaluate("return JSON.stringify(testSubject);");
```

**Comment by andreabalducci** [comment]
Created a repro, not sure about the fix. 
https://github.com/sebastienros/jint/commit/2100e7c7e5505ac873c2bfbc60459f27191fea1a

**Comment by lahma** [comment]
I think generally the logic for .NET interop should be that we shouldn't serialize methods.

**Comment by andreabalducci** [comment]
The issue is that toJSON was picked as indexer, should be fine as method to override default array serialization.

Don't know the internals of jint, patched the code to make the test pass. Have to add a test for toJSON overrides and check if workaround still works.

**Comment by lahma** [comment]
The underlying problem here is that Newtonsoft's JValue abstraction is quite awful when it comes to indexing. 

https://github.com/JamesNK/Newtonsoft.Json/blob/f7e7bd05d9280f17993500085202ff4ea150564a/Src/Newtonsoft.Json/Linq/JArray.cs#L230-L242

The API promises that you can index with string key (`toJson`) and Jint records this, And then later when the actual access is tried Newtsonsoft throws like you can see in the code. Horrible API.

**Comment by lahma** [comment]
One workaround:

```csharp
var engine = new Engine(options =>
{
    options.Interop.MemberAccessor = (_, target, member) =>
    {
        if (target is JArray && !int.TryParse(member, out var _))
        {
            return JsValue.Undefined;
        }

        return null;
    };
});
```

**Comment by lahma** [comment]
@andreabalducci is the workaround enough for you or is something more needed?

**Comment by andreabalducci** [comment]
Thank you for your suggestion, it's enough as workaround, I'll update the Elsa Issue with your snippet.

Tested JArray serialization with a custom toJSON function (scripted js) and breaks with an `System.InvalidCastException: Object must implement IConvertible.` when Jint try to assign the function to toJSON (works with Array)

```
  var fromEngine = engine.Evaluate
  (
      @"testSubject.toJSON = () => '*';
      return JSON.stringify(testSubject);"
  );
```

Same indexer issue, added failing test in my branch 
https://github.com/sebastienros/jint/commit/0eb08db9e4b023b4dd27d0a29fa83e8043388b5d

**Comment by lahma** [comment]
If Jint would know about Newtonsoft it would be easy to add checks, but as it's not a dependency (and never will be), it's harder.

**Comment by lahma** [comment]
So this thing makes my head hurt... It's a bit hard to add behavior to CLR types as they generally are considered read-only shape-wise (you cannot easily add methods to types when they don't have them). So your use case really needs to add new methods and behavior to CLR type, like `toJSON`?

**Comment by andreabalducci** [comment]
My use case is ok with suggested workaround, no need to override / add CRL type methods so far.
Thanks again @lahma .
