### ISSUE TITLE
Ability to mark properties and method as hidden on TypeReference (or allowlist which methods can be accessed)

### ISSUE THREAD

**Issue by christianrondeau** [sebastienros/jint#1311]
# The problem

I have a use case where objects make some methods available to the user in the JavaScript realm, but some others are required for the underlying C# code. For example:

```c#
public class MyListBuilder
{
    // This should be available for JS scripts
    public void Add(int value) {...}
    // This should not
    public List<int> Build() {...}
}
```

So, in JS...

```javascript
function build(builder) {
  // This should be ok:
  builder.add(1);
 // But this should not:
 builder.build();
}
```

Right now, the `TypeReference` is "all or nothing", so the only way to prevent unwanted methods from being called by the JS script is to do something like:

```c#
// This one is only used by C#...
public class MyListBuilder
{
    public void Add(int value) {...}
    public List<int> Build() {...}
}

// And this one is made available for the js script.
public class MyListBuilderForJs
{
    private MyListBuilder _builder;

    public MyListBuilderForJs(MyListBuilder builder) {
        _builder = builder;
    }

    public void Add(int value) {
        _builder.Add(value);
    }
}
```

# Proposal 1

Add an attribute on methods.

```c#
[JavaScriptInteropType(DefaultVisibility = JavaScriptInterop.Private)]
public class MyListBuilder
{
    [JavaScriptInteropProperty(Visibility = JavaScriptInterop.Public)]
    public void Add(int value) {}
    public List<int> Build() {}
}
```

Or, inversely

```c#
[JavaScriptInteropType(DefaultVisibility = JavaScriptInterop.Public)]
public class MyListBuilder
{
    public void Add(int value) {}
    [JavaScriptInteropProperty(Visibility = JavaScriptInterop.Private)]
    public List<int> Build() {}
}
```

It's a rough idea but you get the gist of it.

# Proposal 2

```c#
TypeReference.CreateTypeReference<T>(Engine, string[] properties)
```

Then we can manually specify all properties we want; by default, it populates them automatically.

# Opinions?

This is a rough idea, but I'd like to hear your thoughts before designing this any further.

Thanks!

**Comment by lahma** [comment]
I think we already have the generic means for this via [TypeResolver](https://github.com/sebastienros/jint/blob/main/Jint/Runtime/Interop/TypeResolver.cs), [the tests](https://github.com/sebastienros/jint/blob/main/Jint.Tests/Runtime/InteropTests.MemberAccess.cs) show hiding and filtering capabilities.

Can't remember how `TypeReference` obeys it but I think the concept and configuration should be the same?

**Comment by christianrondeau** [comment]
It actually solves my problem perfectly, I thought I did my homework but I didn't think of looking at Engine options!

If someone else finds this issue, here's my solution:

```c#
options.SetTypeResolver(new TypeResolver
{
    MemberFilter = m => Attribute.IsDefined(m, typeof(JsApiAttribute)),
});
```

And the attribute is simply
```c#
public class JsApiAttribute : Attribute {}
```

It can then be used to manually flag methods that are meant to be consumed for JavaScript:

```
[JsApi]
public void Something() {}
```

Thanks @lahma!
