### ISSUE TITLE
Math.random is not random

### ISSUE THREAD

**Issue by fvaneijk** [sebastienros/jint#133]
the following change in MathInstance.cs fixes this:

Original code:
        private static JsValue Random(JsValue thisObject, JsValue[] arguments)
        {
            return new Random().NextDouble();
        }

New code:
        private static JsValue Random(JsValue thisObject, JsValue[] arguments)
        {
          return _random.NextDouble();
        }

**Comment by sebastienros** [comment]
Already reported and fixed by the past
https://github.com/sebastienros/jint/blob/41494caac73f7d44a927cdf2e1270211c4898be6/Jint/Native/Math/MathInstance.cs#L443
