### ISSUE TITLE
new Date()/1 returns 2 decimal points

### ISSUE THREAD

**Issue by sea0920** [sebastienros/jint#1337]
new Date()/1 is suppose to return the number of milliseconds elapsed since January 1, 1970 00:00:00 UTC in integer.
In jint-3.0.0-beta-2041, new Date()/1 is returned with two decimal places e.g., 1667286883626.51
It wasn't like this in Jint.3.0.0-beta-2040.

**Comment by lahma** [comment]
Thanks for the report, should now be fixed in main and appear soon on MyGet feed too.
