### ISSUE TITLE
Why delete not working?

### ISSUE THREAD

**Issue by volkanalkilic** [sebastienros/jint#1339]
An error occurs when I want to delete an element from a dictionary.

**Cannot delete property 'a' of System.Collections.Generic.Dictionary`2[System.String,System.Object]**

```
var engine = new Engine(cfg =>
{
cfg.Strict(true);
cfg.AllowClr();
cfg.CatchClrExceptions(ex => ex is Exception);
});
engine.SetValue("getData", new Func<IDictionary<string, object>>(() => {
var props = new Dictionary<string, object> {
{"a", 1},
{"b", 2},
};
return props;
}));
engine.Execute("var data = getData(); delete data['a'];");
var value = engine.GetValue("data");
```

**Comment by lahma** [comment]
I think it's simply because it hasn't been implemented. Probably needs some check if interop options has `AllowWrite = true` and then should make sure that the object wrapper overrides `Delete`.

**Comment by lahma** [comment]
This should now be fixed in main and should also be soon available on MyGet feed.
