### ISSUE TITLE
Can't invoke a method of an ExecutionContext with engine.Invoke()

### ISSUE THREAD

**Issue by frostycpu** [sebastienros/jint#134]
Does not work:
`engine.EnterExecutionContext(env, env, obj);`
`engine.Execute("function test(){return \"success\";}");`
`engine.Invoke("test");`

Works:
`engine.EnterExecutionContext(env, env, obj);`
`engine.Execute("function test(){return \"success\";}");`
`engine.Execute("test()");`

Not sure if this is intended, but engine.Invoke() will only invoke functions on the Global object instead of the current execution context.
The first example always throws an ArgumentException("Can only invoke functions")

**Comment by totoroyyb** [comment]
Basically, I get the same issue.

I tried to load a third party js file by using `engine.Execute(SomeFileStr)`

And then when I `Invoke` , always Can only invoke functions.

But as you said, I tried the second example and it works.

According to the example listed in README, the first example should be right

**Comment by lahma** [comment]
Custom execution contexts are hard to support especially due to scoping (let/const), the ExterExecutionContext method might even be removed so I'll close this as unsupported.
