### ISSUE TITLE
Dependency injection in TypeReference

### ISSUE THREAD

**Issue by Andrei-NZ** [sebastienros/jint#1354]
Would it be safe/good idea to add dotnet dependency injection into dotnet interop function (TypeReference)?

Much like Quartz allows for a custom JobFactory in here: https://github.com/quartznet/quartznet/blob/main/src/Quartz/SPI/IJobFactory.cs

What I am trying to achieve is to be able to use DI services of dot net in the referenced types.

**Comment by lahma** [comment]
Should now be possible, [see test case for sample](https://github.com/sebastienros/jint/blob/0f898f89ac2691067f4f75d0071062fd707973c7/Jint.Tests/Runtime/InteropTests.TypeReference.cs#L164-L199).
