### ISSUE TITLE
Memory leak in V3?

### ISSUE THREAD

**Issue by bluewalk** [sebastienros/jint#1368]
Hi,

I am currently using v2 without any issues, but I just tried to use 3.0.0-beta-2044 in my software to take advantage at all the improvements. But unfortunately after the change, the software is hogging memory. Clearly it has something to do with v3.

**_Background_**
The software is my own home automation software where devices have a state determination script (javascript) which gets evaluated every minute or when there's a change in a datasource it uses (eg a switch).

This is done by looping over the devices and evaluate it's script (per scenario (day, night, away) it has it's own functions in the script.

I have written a helper that makes some thing easy by adding helper classes and enums to the context (static functions):
```csharp
    public static Engine GetEngine()
    {
        var engine = new Engine()
            .SetValue("Log", new Action<string>(p => GetServiceProvider.GetServiceOrCreateInstance<ILogger<JavascriptEvaluator>>().LogInformation(p)))
            .SetValue("Settings", GetServiceProvider.GetServiceOrCreateInstance<Settings>())
            .SetValue("Cache", GetServiceProvider.GetServiceOrCreateInstance<Cacher>());

        engine.SetValue("$", new JavascriptTools(engine));

        // Add all enums
        AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => a.FullName?.StartsWith("MyNamespace") == true)
            .SelectMany(a =>
                a.GetTypes().Where(t => t.IsEnum && t.IsPublic))
            .OrderBy(t => t.Name)
            .ForEach(e => engine.SetValue(e.Name, TypeReference.CreateTypeReference(engine, e)));

        return engine;
    }
```

And here's the evaluate function (`EvaluateFunction`) which gets called multiple times a minute (around 50 times) and another evaluate function that is called by some scheduled tasks.

```csharp
    public static T Evaluate<T>(string script, object variables = null)
    {
        if (string.IsNullOrEmpty(script)) return default;
        
        var engine = GetEngine();
        PopulateVariables(engine, variables);

        var result = engine.Evaluate(script)
            .ToObject();
        
        engine.Dispose();

        return (T)Convert.ChangeType(result, typeof(T));
    }

    private static void PopulateVariables(Engine engine, object variables)
    {
        if (variables is Dictionary<string, object> dictionary)
            dictionary.ForEach(p => engine.SetValue(p.Key, p.Value));
        else
            variables?.GetType()
                .GetProperties()
                .Where(p => p.GetIndexParameters().Length == 0)
                .ForEach(p => { engine.SetValue(p.Name, p.GetValue(variables)); });
    }

    public static T EvaluateFunction<T>(string script, string function, params object[] parameters)
    {
        if (string.IsNullOrEmpty(script)) return default;

        if (!script.Contains(function)) throw new UndefinedJavascriptFunctionException(function);

        var engine = GetEngine();
        var result = engine
            .Execute(script)
            .Invoke(function, parameters)
            .ToObject();
        
        engine.Dispose();

        return (T)Convert.ChangeType(result, typeof(T));
    }
```

The `GetServiceProvider.GetServiceOrCreateInstance` function basically gets the instance of a singleton via DPI.
`JavascriptTools` is a class that adds functions to use in the script, which has subtools for eg. devices and datasources.

_**Issue**_
Memory keeps increasing over time (hour to two hours it leaks around 400MB) even though disposing the engine. I am surely missing something simple at the moment but can't quite put my finger on it.

The app is running in a docker container so remote debugging is quite the hassle. But I am certain it has something to do with V3 as V2 is rock stable when it comes to memory usage.

Any ideas?

**Comment by lahma** [comment]
Thanks for the detailed report. Does the leak occur outside of docker? Can you get a memory snapshot for investigation?

**Comment by lahma** [comment]
Looking at the code my only suspicion comes from GetServiceProvider usage , maybe try creating the design manually for testing.  Memory dump would of course be ideal.

**Comment by bluewalk** [comment]
Here's the GetServiceProvider class, nothing special:
```csharp
public static class GetServiceProvider
{
    public static IServiceProvider _ { get; set; }

    public static T GetServiceOrCreateInstance<T>()
    {
        return ActivatorUtilities.GetServiceOrCreateInstance<T>(_);
    }

    public static object GetServiceOrCreateInstance(Type type)
    {
        return ActivatorUtilities.GetServiceOrCreateInstance(_, type);
    }

    public static IEnumerable<T> GetServicesOrCreateInstances<T>()
    {
        return ActivatorUtilities.GetServiceOrCreateInstance<IEnumerable<T>>(_);
    }
}
```

Where `_` is set in program
```csharp

        GetServiceProvider._ = host.Services;

        DbInitializer.Initialize();

        await host.RunAsync();
```

Unfortunately I am unable to run it out of docker as all the dependent services are spun up with a docker-compose.
I am quite certain it's not because of that as the exact same code works with V2 without any problems.

Has something been changed on how it manages memory? Maybe the Esprima is causing the issue?

I will try to set it up on windows later and have DotMemory have a look at it or try to make a memory dump from within the container.

**Comment by Genteure** [comment]
It might be easier for you to use [dotnet-dump](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump) and/or [dotnet-gcdump](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-gcdump) directly in docker container.
You can then analyze the dump file directly in the container, or copy it out to a Windows machine and open it with Visual Studio.

**Comment by bluewalk** [comment]
It seems to be related to the tools I set here: `engine.SetValue("$", new JavascriptTools(engine));` somehow it seems Jint is holding on to these, every time I create a new Engine, it doesn't get freed. Judging the gcdump.

![gc-jint](https://user-images.githubusercontent.com/6522477/204098961-1d73a96c-f7a0-4878-9a43-ca4679f150d2.jpg)

The memory dump doesn't want to load in VS
![vs-error](https://user-images.githubusercontent.com/6522477/204099024-13ccc69e-35e0-4a68-b08f-60a0069bdf45.jpg)

Investigating further. If you want the dump to check I can send it to you.

**Comment by lahma** [comment]
By looking at the numbers I can see that Engine instances are kept in memory. Can you find the root that is holding the reference(s)? If Jint were registered to DI as transient it would be held in dispose queue as it implements `IDisposable` but based on your code samples engine is really short-lived.

**Comment by bluewalk** [comment]
> Well first of all, the `Dispose` is a lie, in a sense 😉 Engine currently doesn't currently do anything in `Dispose`, but it's a point for things to happen and it's a good idea to account for it. It's part of getting the API "right", hopefully. We are iterating here.

I see, didn't look into the code yet :) no worries

> Sure, I have a bit of a cold at the moment so mostly looking things from mobile/bed and probably will take a day or two for me to get back in business.

Ditto here, feeling good enough to tinker though. How would you like to receive them, should I send you an email so we don't share it to the world 😌

> Ideally if you could create a minimal repro that starts to grow the memory. I guess your code is not something that you want to share so something minimalistic might be nice.

Correct; I can give it a shot to see if I can create something that behaves the same although there's a lot done in the project that is being used by the Engine (eg JavascriptTools, DataSourceTools etc). Maybe one of those stay alive or referenced which prevents the Engine from being cleaned up. Although I don't understand why it's all fine and dandy with V2.

> Engine is _not_ thread safe, so don't access engine from multiple threads.
> So create a new one or lock access. There's also [ShadowRealm](https://github.com/sebastienros/jint/blob/main/Jint.Tests.PublicInterface/ShadowRealmTests.cs) that might interest you if you want to use an engine that been initialized but don't want executions to pollute it.

As it's not thread safe, isn't creating a Realm also going to cause issues?

**Comment by lahma** [comment]
> Ditto here, feeling good enough to tinker though. So no worries if it takes time, for now just running V2. How would you like to receive them, should I send you an email so we don't share it to the world 😌

You can reach me at marko -dot- lahma -at- gmail -dot- com with a link if you would like to share the latest memory dumps.

> Correct; I can give it a shot to see if I can create something that behaves the same although there's a lot done in the project that is being used by the Engine (eg JavascriptTools, DataSourceTools etc). Maybe one of those stay alive or referenced which prevents the Engine from being cleaned up. Although I don't understand why it's all fine and dandy with V2.

V3 is very different, so it could be anything - Jint bug, your code, anything. There's been a lot of things moving and you should get better performance and features - and unfortunately some growing / teething pains. V3 should offer superior performance, features etc, but might have issues.

> As it's not thread safe, isn't creating a Realm also going to cause issues?

Realm is not thread safe (it's the same Engine instance), just a suggestion if you would pool engines in thread-safe manner.

**Comment by bluewalk** [comment]
> > Ditto here, feeling good enough to tinker though. So no worries if it takes time, for now just running V2. How would you like to receive them, should I send you an email so we don't share it to the world 😌
> 
> You can reach me at marko -dot- lahma -at- gmail -dot- com with a link if you would like to share the latest memory dumps.
Sent, appreciate your time!

> V3 is very different, so it could be anything - Jint bug, your code, anything. There's been a lot of things moving and you should get better performance and features - and unfortunately some growing / teething pains. V3 should offer superior performance, features etc, but might have issues.
Yes I did indeed see better performance and most importantly, the latest features which is why I decided to upgrade.

> Realm is not thread safe (it's the same Engine instance), just a suggestion if you would pool engines in thread-safe manner.
I figured, that is still a good workaround though. I can create a pool of engines and reuse those. Will look into that.

**Comment by bluewalk** [comment]
I've added many improvements to prevent memory leaks by my own code. This night the process rose from 200MB to 2.2GB and restarted (docker).

I will keep an eye on it today and create a new dump when it reaches 1GB and will add it to the share I sent you earlier.

**Comment by lahma** [comment]
@bluewalk can you check if there's any difference if you disable object identity tracking (combined with your other options):

`var engine = new Engine(options => options.Interop.TrackObjectWrapperIdentity = false);`

**Comment by bluewalk** [comment]
I have added it to the code, will let it run again for tonight and check tomorrow 👍🏻

**Comment by sebastienros** [comment]
> Realm is not thread safe (it's the same Engine instance), just a suggestion if you would pool engines in thread-safe manner.

But can two distinct realms from the same engine be used concurrently?

**Comment by lahma** [comment]
> > Realm is not thread safe (it's the same Engine instance), just a suggestion if you would pool engines in thread-safe manner.
> 
> But can two distinct realms from the same engine be used concurrently?

The realms are kind of shims over the normal execution context, like their parent is the immutable global so I don't think they can be accessed in that way unfortunately.

**Comment by sebastienros** [comment]
Ideally a realm would not be thread-safe, and own all the logic that is not thread-safe, while the engine would be immutable once a realm is created. At least for read-only operations, so we can guaranty that if Engines are pooled, as long as all evaluations are done on a realm then it is thread safe to reuse engines (then ideally a single one). Or like using a `Freeze` method to identify that an engine state can't be mutated anymore (throwing an exception) and only Realms can.

**Comment by sebastienros** [comment]
Is this repos open for PRs?

**Comment by lahma** [comment]
> Is this repos open for PRs?

I'm sure such PR would be appreciated 😌

**Comment by bluewalk** [comment]
Update @lahma: it seems to do something, memory only risen from 145MB to 202MB.

I forgot to build the container with sdk tools so can't make a dump. So I just recreated the container with sdk tools; will create another dump tonight to see what is causing the 55MB, maybe still some Jint stuff as with V2 it's rock solid around 145-155MB but we'll see 😀

**Comment by bluewalk** [comment]
So far so good @lahma, memory isn't growing like crazy anymore, albeit a little.
I have uploaded two more dumps (memory and gc) to the share I sent you earlier.

**Comment by bluewalk** [comment]
@lahma Two days running now and memory is still stable (aside from a CancellationTokenSource leak from MQTTnet).

**Comment by lahma** [comment]
Thanks for the update. I'm still a bit puzzled why this happens by using conditional weak table, but maybe the circular references can cause the trouble when wrapped object itself has a reference to engine.

**Comment by bluewalk** [comment]
I did update the code a bit to now use singletons and not pass the Engine to an instantiated class anymore.
Instead I define an action that calls the engine (to add snippets of code), maybe that still causes an issue?

```csharp
        engine.SetValue("Require", new Action<string>(name =>
        {
            var snippet = _javascriptService.GetByName(name);
            if (snippet == null) return;

            engine.Execute(snippet.Code);
        }));
```

**Comment by lahma** [comment]
Hard to say with partial snippets of the full picture. Such capturing lambda should be released with the engine but maybe you can experiment with different tactics, mixing lifecycles like transient and singleton can of course cause trouble. Did you also update other bits in the process if the MQTTnet started to leak in this new iteration?

**Comment by bluewalk** [comment]
None of the bits that touches the MQTTnet implementation (basically changed a lot from non DI classes to singleton classes). I see plenty of issues there that match mine (including one that has a fix 6 days ago but not yet released) so I call that unrelated to jint 😀

The jint issues I was having have completely been resolved with that minor change, so happy with that!

**Comment by lahma** [comment]
Closing this as I've been unable to repro locally even with million engines created in a loop and disposed using object wrappers, must be something specific to this setup.

**Comment by bluewalk** [comment]
> Closing this as I've been unable to repro locally even with million engines created in a loop and disposed using object wrappers, must be something specific to this setup.

Your help has been much appreciated. Still trying to figure out what's specific about my setup; but for now I can finally use v3!

Keep up the good work!

**Comment by lahma** [comment]
Object instance tracking isn't enabled by default anymore which should reduce memory pressure, but you had it off already. Nothing else comes to mind from the top of my head.

**Comment by bluewalk** [comment]
Hmm that's odd. I will keep an eye on it (takes about 20 hours to fill up the memory).
If it happens again I will make a dump and check what items are being left into memory and report back. Thanks for the quick response 👍🏻
