### ISSUE TITLE
Change in behavior of implicit conversion for Date

### ISSUE THREAD

**Issue by h15ter** [sebastienros/jint#1370]
Hi Guys,

I have noticed the following change in behavior when upgraded from JINT 2.x to 3: when I pass a javascript `Date` object into a Clr function that expects `System.String`, then the date object is being implicitly converted to js date representation first (like it has called `date.toString()` implicitly). 

It was different in JINT 2.x: the javascript `Date` object was converted to the matching Crl type `System.DateTime` first, and then the argument of Clr type `System.DateTime` was converted to `System.String`. 

Below are some repro code examples and JINT source links:
```
// outputs Sun Nov 27 2022 22:52:42 GMT+0100 (W. Europe Standard Time)
namespace Jint3Test
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var engine = new Engine(cfg => cfg
                .AllowClr()
            );

            engine.SetValue("MyClass", TypeReference.CreateTypeReference(engine, typeof(MyClass)));
            var ret = engine.Evaluate(@"
function test(){
    const date = new Date();
    return new MyClass().MyMethod(date);
}
test();
");
            Console.WriteLine(ret);
            Console.ReadKey();
        }

        public class MyClass
        {
            public string MyMethod(string input)
            {
                return input;
            }
        }
    }
}
```

```
// outputs 11/27/2022 22:01:33
namespace Jint2Test
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var engine = new Engine(cfg => cfg
                .AllowClr()
            );

            engine.SetValue("MyClass", TypeReference.CreateTypeReference(engine, typeof(MyClass)));
            var ret = engine.Execute(@"
function test(){
    const date = new Date();
    return new MyClass().MyMethod(date);
}
test();
").GetCompletionValue();
            Console.WriteLine(ret);
            Console.ReadKey();
        }

        public class MyClass
        {
            public string MyMethod(string input)
            {
                return input;
            }
        }
    }
}
```

Here it tries to coerce `JsDate` to `System.String`:
https://github.com/sebastienros/jint/blob/main/Jint/Runtime/Interop/MethodInfoFunctionInstance.cs#L204

And here it handles strings in a very special way (that's good for numeric primitives etc, but not for dates):
https://github.com/sebastienros/jint/blob/main/Jint/Extensions/ReflectionExtensions.cs#L146

If you are going to keep it this way, what's the workaround to control the format of incoming string? Since ClrTypeConverter is out of play on this execution path, the only one I could think of is to add an override with a `DateTime` argument for all Clr functions that malfunction now because of date format mismatch, but if you have a better idea, please let me know.

Thanks!

**Comment by lahma** [comment]
Without yet digging into the code,  why wouldn't you want to declare your input parameter as DateTime and skip intermediate string converting?

**Comment by h15ter** [comment]
@lahma That's the workaround I used to fix one specific Clr method.
The problem is that there are lots of Clr methods accepting string arguments, and lots of custom user scripts that may feed dates into them. I simply don't know what methods/args I have to override until someone complains their script fails/misbehaves after the upgrade. So I either sit and wait until something fails somewhere, or generate a hell lots of useless overrides (M methods x N string arguments = M x N overrides). Even worse for methods from 3rd-party libs, because they will need proxies/decorators.
The problem is not too painful for me (yet). However it may potentially hit hard, that's why I'm letting you know about this change in behavior.
And in general it's a bit strange that conversion to `System.String` completely bypasses ClrTypeConverter: one might easily have a custom converter like the one below and expect it to work until Jint v3...
```
        public class MyConverter : DefaultTypeConverter
        {
            public MyConverter(Engine engine) : base(engine)
            {
            }

            public override object? Convert(object? value, Type type, IFormatProvider formatProvider)
            {
                if (type == typeof(string))
                {
                    return JsonSerializer.Serialize(value);
                }
                return base.Convert(value, type, formatProvider);
            }
        }
```

**Comment by lahma** [comment]
I have no objections to have a PR  to patch the behavior to more desired one if old expectations in tests are still fulfilled and fix is verified with new test(s).

With v3 we did a lot of work on interop side to make it just work - that's why I suggested  the strongly typed interface and let Jint figure out the conversions and overload resolution. But I can see that in your case that would require a lot of work (yet I still recommend considering it in the long run).

**Comment by lahma** [comment]
Checked this once again and I think it's just configuration issue. If you don't want the JS semantics, you just need to configure:

```c#
var engine = new Engine(cfg => cfg
    .AllowClr()
    .Interop.ValueCoercion = ValueCoercionType.None
);
```
I'm this closing as there's a workaround.

**Comment by h15ter** [comment]
@lahma Thank you! It looks like Jint3 has a lot more config options than it was before.
