### ISSUE TITLE
Unable to change a property when the name of the property is "value"

### ISSUE THREAD

**Issue by GLI14** [sebastienros/jint#1375]
I am not able to change the value of a property when the name of the property is "value".
The next example code illustrates this:

        [Fact]
        public void UnableToChangePropertyWithNameValue()
        {
            var engine = new Engine();

            var json = @"{
                  ""value"": ""ORIGINAL"",
                  ""otherProperty"": ""Changing this works as expected""
                }";
       
            var input = Newtonsoft.Json.JsonConvert.DeserializeObject(json);
            var result = engine
                .SetValue("input", input)
                .Evaluate("input.value = \"CHANGED\"; input.value")
                .AsString(); 

            Assert.Equal("CHANGED", result);  // Error: here the value is still "ORIGINAL"
        }

Note that this only applies when the property name is exactly "value".
Since "value" is not a reserved word (see https://www.w3schools.com/js/js_reserved.asp), I would expect this to work.

Tested using version 3.0.0-beta-2044

**Comment by lahma** [comment]
Jint probably resolves this to `JObject` `Value()` method, so that's ambiguity that Jint cannot easily solve. Configuring `TypeResolver`'s `MemberNameComparer` to case-sensitive might help here.

**Comment by lahma** [comment]
Another option could be `MemberFilter` configuration which rejects all methods in `JObject`.
