### ISSUE TITLE
jint first match c# overload method with params attribute will raise bug 

### ISSUE THREAD

**Issue by changhaohao** [sebastienros/jint#138]
.net first match method without params attribute
jint first match method with params attribute

**Comment by changhaohao** [comment]
test case to throw new JavaScriptException(Engine.TypeError, "No public methods with the specified arguments were found.");
===========
class MyCsharpClass
{
}
 var engine = new Engine(cfg => cfg.AllowClr(typeof(MyCsharpClass).Assembly));
 engine.SetValue('myvalue',new MyCsharpClass());
 engine.Execute(@"var log = System.Console.WriteLine;log(myvalue);");

=========
fail reason:
c#
class Console
{
public static void WriteLine(object value);
public static void WriteLine(string format, object arg0);
public static void WriteLine(string format, params object[] arg);
}

log(myvalue);  expect to  call  WriteLine(object value);

but ProcessParamsArrays will convert the myvalue to  [ myvalue ,[myvalue] ]
so jint find two WriteLine:
                 WriteLine(string format, object arg0);
                 WriteLine(string format, params object[] arg);
but none of these two can match the type of  [ myvalue ,[myvalue] ]

**Comment by changhaohao** [comment]
another test case
==============
    class MyTypeConvert : Jint.Runtime.Interop.DefaultTypeConverter
    {

        public MyTypeConvert(Jint.Engine engine) : base(engine) { }
        public override object Convert(object value, Type type, IFormatProvider formatProvider)
        {
            if (value.GetType() == typeof(Object[]) && type == typeof(String[]))
            {
                Object[] vals = (Object[])value;
                String[] rtn = new string[vals.Length];
                for (int i = 0; i < rtn.Length; i++)
                {
                    rtn[i] = (String)base.Convert(vals[i], typeof(String), formatProvider);
                }
                return rtn;
            }
            return base.Convert(value, type, formatProvider);
        }
    }
    public class MyData 
    { 
        public void myfunc(params String[] strs) { Console.WriteLine("myfunc1 "+String.Join("|",strs));  }
        public void myfunc(String strs){ Console.WriteLine("myfunc2 " + strs); }
    }

public static void Main(String[] arg)
{
      var engine = new Engine(cfg => cfg.AllowClr(typeof(MyData).Assembly));
      engine.ClrTypeConverter = new MyTypeConvert(engine);
 MyData mydata=new MyData();
            mydata.myfunc("c");
            mydata.myfunc("c","d");
            engine.SetValue("mydata", mydata);
           engine.Execute(@"mydata.myfunc('a');mydata.myfunc('a','b');");
}
======output==========
myfunc2 c
myfunc1 c|d
myfunc1 a
myfunc1 a|b
=====conclusion============
.net first match method without   params
jint first match method with params
that is why the above test case throw Exception

**Comment by changhaohao** [comment]
ProcessParamsArrays  is ok , new Invoke will fix the bug
================
        public JsValue Invoke(MethodInfo[] methodInfos, JsValue thisObject, JsValue[] jsArguments)
        {
            var arguments = ProcessParamsArrays(jsArguments, methodInfos);
            var converter = Engine.ClrTypeConverter;
            JsValue[][] matchOrder = arguments == jsArguments ? new JsValue[][] { jsArguments } : new JsValue[][] { jsArguments, arguments };
            for (int j = 0; j < matchOrder.Length; j++)
            {
                arguments = matchOrder[j];
                var methods = TypeConverter.FindBestMatch(Engine, methodInfos, arguments).ToList();

                foreach (var method in methods)
                {
                    var parameters = new object[arguments.Length];
                    var argumentsMatch = true;

                    for (var i = 0; i < arguments.Length; i++)
                    {
                        var parameterType = method.GetParameters()[i].ParameterType;

                        if (parameterType == typeof(JsValue))
                        {
                            parameters[i] = arguments[i];
                        }
                        else
                        {
                            if (!converter.TryConvert(arguments[i].ToObject(), parameterType, CultureInfo.InvariantCulture, out parameters[i]))
                            {
                                argumentsMatch = false;
                                break;
                            }

                            if (typeof(System.Linq.Expressions.LambdaExpression).IsAssignableFrom(parameters[i].GetType()))
                            {
                                parameters[i] = (parameters[i] as System.Linq.Expressions.LambdaExpression).Compile();
                            }
                        }
                    }

                    if (!argumentsMatch)
                    {
                        continue;
                    }

                    // todo: cache method info
                    return JsValue.FromObject(Engine, method.Invoke(thisObject.ToObject(), parameters.ToArray()));
                }
            
            }


            throw new JavaScriptException(Engine.TypeError, "No public methods with the specified arguments were found.");
        }

**Comment by postromantic** [comment]
Looks like an issue. Feel free to create pull request

**Comment by sebastienros** [comment]
And please improve add a unit test for this case.
