### ISSUE TITLE
bug: cannot load Jint assembly in partial trusted IIS environment

### ISSUE THREAD

**Issue by postromantic** [sebastienros/jint#139]
Got IIS with Medium trust level. Jint 2.1.0.0 worked fine, but latest Jint failed to load with:

    System.TypeLoadException: Could not load type 'Jint.Native.JsValue' from assembly 'Jint, Version=2.4.0.0, Culture=neutral, PublicKeyToken=2e92ba9c8d81157f' because objects overlapped at offset 8 and the assembly must be verifiable.

**Comment by postromantic** [comment]
PullRequest created: #140

**Comment by sebastienros** [comment]
I accepted the PR but you know that partial trust is no more "supported" by IIS? The idea is that it's not a valid way to ensure security in an app, so you should just use Full trust and add correct security.

**Comment by postromantic** [comment]
I know IIS doesn't support partial trust anymore. It's just a repro for the problem with explicit field offsets overlapping.
