### ISSUE TITLE
System.MissingFieldException: Field not found: 'Esprima.ParserOptions.Default'

### ISSUE THREAD

**Issue by CharlieEriksen** [sebastienros/jint#1399]
Hey,

I just upgraded to Jint 3-beta-2044. And just initiating the `Engine` causes this exception:
```
System.MissingFieldException: Field not found: 'Esprima.ParserOptions.Default'.
   at Jint.Engine..ctor(Action`2 options)
   at Jint.Engine..ctor(Action`1 options)
   at Jint.Engine..ctor()
   at jswzl.JsReferences.ChunkExtractor..ctor() in 
```

Here's my code:
```
 private ChunkExtractor()
    {
        Engine = new Engine();
    }
```

**Comment by lahma** [comment]
You probably have some old Esprima reference dangling as dll file somewhere.

**Comment by CharlieEriksen** [comment]
That's what I figured as well. I've cleared out all DLLs in my project folder, and I've cleared nuget cache. No luck. Am I missing anything?

**Comment by CharlieEriksen** [comment]
Oh, I see what's going on. jint 3-beta-2044 references esprima beta9, whereas I'm running esprima preview 99. That would explain.
