### ISSUE TITLE
Wrong nullable annotation on Engine.Invoke

### ISSUE THREAD

**Issue by mus65** [sebastienros/jint#1402]
The `Engine.Invoke` methods only accept `object[]` as arguments, but should allow `object?[]` . We are already passing `null` here in our code and it works fine. We only noticed this when we migrated our own code to Nullable Reference Types.

**Comment by lahma** [comment]
Would you like to create a PR to improve the nullable annotations?

**Comment by mus65** [comment]
@lahma opened #1403
