### ISSUE TITLE
cfg.LocalTimeZone not work

### ISSUE THREAD

**Issue by hyzx86** [sebastienros/jint#1424]
Jint Version: 3.0.0-beta-2043

this is my code 

```C#
            var siteService = serviceProvider.GetRequiredService<ISiteService>();
            var siteSettings = siteService.GetSiteSettingsAsync().Result;
            var siteTimeZone = TimeZoneInfo.FindSystemTimeZoneById(siteSettings.TimeZoneId);
            var engine = new Engine(options =>
            {
                //TODO: 更新 Jint 版本后可移除
                options.Interop.TrackObjectWrapperIdentity = false;
                options.AddExtensionMethods(typeof(FreeSQLExtensions));
                options.TimeZone= siteTimeZone;
                options.LocalTimeZone(siteTimeZone);//"Asia/Shanghai"
            });
```
input : new Date("2022-1-1")

result : "2021-12-31T16:00:00Z"

Is it because my configuration method is wrong?

Thanks !

**Comment by lahma** [comment]
Please provide a test case that does not involve other dependencies, like service provider or site services.

**Comment by hyzx86** [comment]
use  https://dotnetfiddle.net/#   to run below code

```
using Jint;
using System;

public class Program {
	public static void Main() {
		using var engine = new Engine(
		conf=>{
			conf.LocalTimeZone(TimeZoneInfo.FindSystemTimeZoneById("Asia/Shanghai"));//
		});
		
		System.Console.WriteLine(engine.Evaluate("new Date(2022,1,1)"));
		System.Console.WriteLine(engine.Evaluate("new Date(2022,1,1).toString()"));
	}
}


```

![image](https://user-images.githubusercontent.com/15613121/216968289-40e79e43-2165-4642-812e-e0fc68e7fa60.png)

**Comment by lahma** [comment]
The result seems to be the same moment, first one is in UTC and second is in China Standard Time. You probably will get the result you *might* want to see by calling TimeZoneInfo.FromUtc(datetime from jint)
