### ISSUE TITLE
Incompatible with Unity 2022.2 because C# 10 is not supported

### ISSUE THREAD

**Issue by achimmihca** [sebastienros/jint#1427]
I am looking for a JS engine for a Unity game to allow modding.

Sadly, newer versions of Jint and Esprima use C# 10 language features that are not yet supported by Unity 2022.2. I get the following error messages:

```
Feature 'file-scoped namespace' is not available in C# 9.0. Please use language version 10.0 or greater.
Feature 'record structs' is not available in C# 9.0. Please use language version 10.0 or greater.
```

The last Jint version that seems to work is `v3.0.0-beta-2036` and Esprima `v2.0.4`

Even with these older versions, I got two error messages. But these are easy to work around:
- `Esprima\JavascriptParser.cs(346,30): error CS0104: 'Range' is an ambiguous reference between 'Esprima.Ast.Range' and 'System.Range'`
    - workaround: explicitly use `Esprima.Ast.Range`
- `Jint\Native\Promise\PromiseConstructor.cs(16,19): error CS0518: Predefined type 'System.Runtime.CompilerServices.IsExternalInit' is not defined or imported`
    - workaround: add a .cs file with a dummy implementation: `namespace System.Runtime.CompilerServices { internal static class IsExternalInit {} }`
- After fixing these, I am able to use Jint in Unity. But the older version has some issues of course.

Unity may eventually support C# 10.
I don't expect you to refactor the code base to work with C# 9.
This is just FYI and for others who are thinking about using Jint with Unity.

**Comment by lahma** [comment]
Are you building Jint/Esprima from source or consuming the binary artifacts?

**Comment by achimmihca** [comment]
Building from source. Took the source code of the repositories and added it to Unity's `Plugins` folder.

I am a bit confused that there are relatively new issues that seem to use Jint in Unity.
Does a pre-compiled dll work in Unity?

**Comment by lahma** [comment]
Well the error about compiler features should not affect the actual binaries. If compiler produces IL code that Unity can consume you should be fine. I haven't done unity development but can you test out referencing the latest NuGet packages/DLLs (somehow) instead of compiling them.

**Comment by lahma** [comment]
In this tutorial the actual DLL is being pulled into Plugins folder: https://pleasenophp.github.io/posts/using-real-javascript-with-unity.html#1-create-project

**Comment by achimmihca** [comment]
Thanks, this seems to work. Have a nice day!
