### ISSUE TITLE
isNaN should test for empty arguments and return true

### ISSUE THREAD

**Issue by fvaneijk** [sebastienros/jint#143]
Here is the fix in \Jint\Native\Global\GlobalObject.cs:

        /// <summary>
        /// http://www.ecma-international.org/ecma-262/5.1/#sec-15.1.2.4
        /// </summary>
        public static JsValue IsNaN(JsValue thisObject, JsValue[] arguments)
        {
            if (arguments.Count() == 0)
            {
              return true;
            }
            var x = TypeConverter.ToNumber(arguments[0]);
            return double.IsNaN(x);
        }

**Comment by sebastienros** [comment]
What about a PR and a unit test? This way I could ensure all tests still pass correctly, and it would be a contribution your own instead of me copy pasting your code.

**Comment by sebastienros** [comment]
Oh and btw the issues is actually that we should use 'arguments.At(0)' instead of 'arguments[0]'. This will do boundary checks and also return 'undefined' if this is empty. You can also fix the other occurrences in the class.

**Comment by fvaneijk** [comment]
Good point I'll put a PR together

**Comment by fvaneijk** [comment]
PR https://github.com/sebastienros/jint/pull/145 is ready Please check it carefully as I am not completely sure I did it all correct.  I believe the code is fine but had some merges etc to do prior to creating the PR.  Also that field offset bug fix seems to have issues on a x64 platform. see https://github.com/sebastienros/jint/issues/139 and https://github.com/sebastienros/jint/pull/140

**Comment by postromantic** [comment]
Please don't checkin FieldOffset changes - it's not a solution. Jint should work on both x86 and x64 env

**Comment by fvaneijk** [comment]
I posted a new PR https://github.com/sebastienros/jint/pull/155  for this...
