### ISSUE TITLE
Error object doesn't have a stack trace if execution was invoked by ManualPromise.Resolve. 

### ISSUE THREAD

**Issue by tomatosalat0** [sebastienros/jint#1432]
Hi,

First of all: sorry for the wall of text. I tried to explain my problem as detailed as possible.

I've found an issue with the `Error` object. The `stack` property won't get filled on creation if the JavaScript execution was invoked by calling the `ManualPromise.Resolve()` method and the created `Error` object won't get thrown.

## Working Example
This is the simple and working example.

### JavaScript
```js
const error = new Error('test');
log(error)
```
### C# Code
```csharp
using var engine = new Engine();
engine.SetValue("log", new Action<JsValue>((error) => {
    Console.WriteLine((error as ObjectInstance)["stack"].ToString());
}));
engine.Execute( /* the JS code from above */ );
```

With this setup, I get the expected output: 
```
    at <anonymous>:1:15
```

## Not working Example
To get it to not work, I had to write the following:

### JavaScript
```js
const thePromise = getPromise();

thePromise.then(() => new Error()).then(e => log(e));
```

### C# Code
```csharp
using var engine = new Engine();

ManualPromise promise = engine.RegisterPromise();
engine.SetValue("log", new Action<JsValue>((error) => {
    Console.WriteLine((error as ObjectInstance)["stack"].ToString());
}));
engine.SetValue("getPromise", new Func<JsValue>(() => promise.Promise))

engine.Execute( /* the JS code from above */ );

// Calling this method will execute the JavaScript again.
promise.Resolve(JsValue.Undefined);
```

With this setup, the output within the console is 
```
undefined
```
but I would expect it have the value `at <anonymous> ...` .

## Cause
I tried to debug the problem and here is what I found:

Within `ErrorConstructor.Construct.BuildStackString`, `_engine.GetLastSyntaxElement()` will get executed. That one simply returns `_activeEvaluationContext?.LastSyntaxElement`. The problem is, that `_activeEvaluationContext` is null when inside the `promise.Resolve` method.

### Potential solution
I don't have deep knowledge about the internals of Jint, so I don't know if the following solution is actually the correct one. I consider it more like a suggestion 😉.

Inside `ScriptFunctionInstance.Call`, I found the following lines of code:

```csharp
// actual call
var context = _engine._activeEvaluationContext ?? new EvaluationContext(_engine);

var result = _functionDefinition.EvaluateBody(context, this, arguments);

// ...
```

Then I searched for all references of `new EvaluationContext(_engine)`, and most of the time (except in ScriptFunctionInstance), the `Engine._activeEvaluationContext` will be set if it is null. E.g. 

```csharp
private T ExecuteWithContraints<T>(bool strict, Func<T> callback)
{
    var ownsContext = _activeEvaluationContext is null;
    _activeEvaluationContext ??= new EvaluationContext(this);
    // ....
    if (ownsContext)
    {
        _activeEvaluationContext = null!;
    }
}
```

I locally changed the `ScriptFunctionInstance.Call` to set the `_activeEvaluationContext` to the newly created context if it was null and that change solved the issue for me - the `stack` property now got set correctly.

I hope I could make it clear.

Thanks!

**Comment by lahma** [comment]
Thanks for the detailed bug report, should be now fixed in main and soon available on MyGet feed.
