### ISSUE TITLE
callback from c# to js failed

### ISSUE THREAD

**Issue by changhaohao** [sebastienros/jint#144]
tests case throw ArgumentException
“System.Linq.Expressions.Expression`1[System.Action`1[System.String]]” 
can not convert to 
“System.Action`1[System.String]”
=======================
      public static void Main(String[] args)
        {
            var engine = new Engine(cfg => cfg.AllowClr());
            engine.SetValue("log", new Action<object>( delegate(Object obj) { Console.WriteLine(obj); } ));
            engine.SetValue("testCallBack", new System.Action<string, System.Action<string>>(delegate(string url, System.Action<string> cb) { cb("js callback from c# " + url); }));
            engine.Execute(@"  testCallBack('a',function(v){ log(v)  }) ");
            Console.Read();
        }
======reason ==========
DefaultTypeConverter will convert ScriptFunctionInstance.Call to Expression.Lambda but not a System.Action

**Comment by changhaohao** [comment]
add a Compile() to every return Expression.Lambda in DefaultTypeConverter.cs  seem to fix
return Expression.Lambda(...).Compile();

**Comment by changhaohao** [comment]
a question: DefaultTypeConverter use   Expression.Block   which is not avaliable for .net3.5
is there a way to  do not use Expression.Block so jint can work on .net3.5 ?

**Comment by regexing** [comment]
I run into the same issue.  The proposed fix works.

**Comment by regexing** [comment]
I created a fix and pull request, what else needs to be done to get this included into the master branch?
