### ISSUE TITLE
Array.from issue

### ISSUE THREAD

**Issue by huanent** [sebastienros/jint#1447]
Hi, There is a issue in Array.from. See the following example:
```
Array.from("fff", (s) => Number.parseInt(s, 16))
```
Real javascript env (chrome) result:
```
[15, 15, 15]
```
Jint result:
```
[ "f", "f", "f" ]
```

jint version: 3.0.0-beta-2045
dotnet version: 6.0
os: macOS 13

**Comment by lahma** [comment]
Thanks for the report, should now be fixed in main and soon available on MyGet feed.
