### ISSUE TITLE
Caching of "unstable" type conversions

### ISSUE THREAD

**Issue by h15ter** [sebastienros/jint#1453]
Hi Guys,

I am facing some issues with "unstable" conversions being cached for the lifetime of an application:
https://github.com/sebastienros/jint/blob/main/Jint/Runtime/Interop/DefaultTypeConverter.cs#L325

The problem with "unstable" conversions is bigger than just string -> number. For instance, `1.0 -> int` and `double.NaN -> int` is an obvious example, and there are much more, including the ones defined by interop types themselves.

What is the recommended way to deal with that? For now I use custom type converter with `TryConvert` override to skip caching of certain dangerous conversions I'm aware of. The problem is that I have to know in advance about all of them. Whenever something wrong is getting cached eventually, it causes persistent errors until the application is restarted because caches are static. 

Below is some example code:
```
public class MyClass {
    public int MyMethod(int input) => input;
}

public void RunScript(string script) {
    var engine = new Engine(cfg => cfg.AllowClr());
    engine.SetValue("MyClass", TypeReference.CreateTypeReference(engine, typeof(MyClass)));
    
    try {
        Console.WriteLine(engine.Evaluate(script));
    }
    catch (Exception e) {
        Console.WriteLine(e.Message);
    }
}

// run these after app restart
// good cache state example, output: [1, 2, error]
RunScript("new MyClass().MyMethod(1)");
RunScript("new MyClass().MyMethod(2)");
RunScript("new MyClass().MyMethod(NaN)");

// run these after app restart
// bad cache state example, output: [error, error, error]
RunScript("new MyClass().MyMethod(NaN)");
RunScript("new MyClass().MyMethod(1)");
RunScript("new MyClass().MyMethod(2)");

// run these after app restart
// another very stupid example of bad cache state example, output: [error, error, error]
RunScript("new MyClass().MyMethod(12345678901234567890)");
RunScript("new MyClass().MyMethod(1)");
RunScript("new MyClass().MyMethod(2)");

```

Thanks!

**Comment by lahma** [comment]
Can you create a failing xUnit test case against main? I did a quick try and all I got was errors about invalid types even on first try (trying to pass NaN).

**Comment by lahma** [comment]
Ah, never mind, I was missing the try-catch-scenario in test to proceed after error.

**Comment by lahma** [comment]
Tweaked logic a bit to detect unsafe floating point to integral caching, should hopefully cover this case.

**Comment by h15ter** [comment]
I don't think it solves the problem, but thanks :)

The major problem with this cache is that if the first conversion fails, all the successive conversions fail, forever. If many interop types implement IConvertible, the cache goes wild very easily.

How important is this cache performance-wise? If I understand correctly, the cache helps to do overload resolution for interop methods slightly faster. I think I have to drop it in my project, because the price of an erroneous conversion cached is much higher. Or maybe not drop, but prefill with some known good conversions, so bad ones never take the precedence...

@lahma Wdyt?

**Comment by lahma** [comment]
I think cache can be removed if it improves/ensures correctness. Want to help out with a PR?

**Comment by lahma** [comment]
Did some more tweaks.
