### ISSUE TITLE
3.0.0 Regex Error

### ISSUE THREAD

**Issue by fengxu-30338** [sebastienros/jint#1454]
I found 
![J4ZJ27JY0 3XCW% (JMS{MM](https://user-images.githubusercontent.com/72682109/220401938-69cb2f87-f179-4cd2-ab72-08d976fa6e29.png)

  return false but there are equal in browser

**Comment by fengxu-30338** [comment]
/\/\// .source == '\\/\\/'

**Comment by fengxu-30338** [comment]
![image](https://user-images.githubusercontent.com/72682109/220401239-9f8331de-cd59-4b8f-adcc-a206c6a0622c.png)
this return false in jint

**Comment by lahma** [comment]
Thanks for the report, should now be fixed in main and soon available on MyGet feed.
