### ISSUE TITLE
Weird crashes when sharing AST between multiple concurrent engines

### ISSUE THREAD

**Issue by ChrML** [sebastienros/jint#1457]
3.0.0-beta-2046

I have a test-project with a pretty large Javascript file that doesn't change, and a huge number of tests (1956 tests) that is run by xUnit using parallellisation. It took some time to run the tests (10 minutes), which I reduced down to 1 minute by avoiding to re-parse string to an AST for each test.

Here is what I did:
```c#
    public static class XunitJsSetup
    {
        // This method is called by each xUnit test from a theory-database of stuff to run.
        public static void Run(string className, string method, bool isAsync)
        {
            // Get the compiled code for the full runtime and the unit-test project just once for all tests.
            Esprima.Ast.Script compiledCode = GetOrCreateCompiledScript();

            // Run the script using the provided args.
            Engine engine = new();
            JsValue result = engine
                .SetValue("window", new Window())
                .SetValue("console", new ConsoleWrapper())
                .SetValue("className", className)
                .SetValue("method", method)
                .SetValue("isAsync", isAsync)
                .Evaluate(compiledCode);

            // Validate the output of the script.
            bool? resultBool = result.ToObject() as bool?;
            Xunit.Assert.True(resultBool, "Expected JS code to return true.");
        }

        static Esprima.Ast.Script GetOrCreateCompiledScript()
        {
            // return CompileScript();   // Add back this line, and the concurrency issues stop.

            if (cachedRuntimeScript != null)
            {
                return cachedRuntimeScript;
            }

            lock (lockObject)
            {
                if (cachedRuntimeScript != null)
                {
                    return cachedRuntimeScript;
                }

                Esprima.Ast.Script compiledCode = CompileScript();
                cachedRuntimeScript = compiledCode;
                return compiledCode;
            }
        }

        static Esprima.Ast.Script CompileScript()
        {
            string jsFull = " ... code here that builds a huge JS file ...";
            Esprima.JavaScriptParser parser = new();
            return parser.ParseScript(jsFull);
        }

        static Esprima.Ast.Script cachedRuntimeScript;
        static readonly object lockObject = new();
    }
```

I assumed this is safe since the AST looks immutable, and there is a separate `Engine` and execution context for each invocation. However some random number of tests (about 2-9 of 1956 tests) are failing each time, due to some internal corruption of the callstack or other issues that seem to be caused by concurrency. So there must be some shared state here that I don't know about. Running them single afterwards always succeeds.

Here are some:
<details><summary>Exception 1</summary><p>
  Message: 
System.InvalidOperationException : stack is empty

  Stack Trace: 
ExceptionHelper.ThrowInvalidOperationException(String message, Exception exception)
JintCallStack.Pop()
Engine.Call(FunctionInstance functionInstance, JsValue thisObject, JsValue[] arguments, JintExpression expression)
ObjectInstance.UnwrapFromGetter(PropertyDescriptor desc, JsValue thisObject)
ObjectInstance.Get(JsValue property, JsValue receiver)
ObjectInstance.Get(JsValue property, JsValue receiver)
RegExpPrototype.Replace(JsValue thisObj, JsValue[] arguments)
ClrFunctionInstance.Call(JsValue thisObject, JsValue[] arguments)
--- End of stack trace from previous location ---
ClrFunctionInstance.Call(JsValue thisObject, JsValue[] arguments)
<70 more frames...>
JintBlockStatement.ExecuteBlock(EvaluationContext context)
JintIfStatement.ExecuteInternal(EvaluationContext context)
JintStatementList.Execute(EvaluationContext context)
Engine.ScriptEvaluation(ScriptRecord scriptRecord)
Engine.ExecuteWithConstraints[T](Boolean strict, Func`1 callback)
Engine.Execute(Script script)
Engine.Evaluate(Script script)
</p></details>

<details><summary>Exception 2</summary><p>
  Message: 
System.InvalidOperationException : stack is empty

  Stack Trace: 
ExceptionHelper.ThrowInvalidOperationException(String message, Exception exception)
JintCallStack.Pop()
Engine.Call(FunctionInstance functionInstance, JsValue thisObject, JsValue[] arguments, JintExpression expression)
ObjectInstance.UnwrapFromGetter(PropertyDescriptor desc, JsValue thisObject)
ObjectInstance.Get(JsValue property, JsValue receiver)
ObjectInstance.Get(JsValue property, JsValue receiver)
RegExpPrototype.Flags(JsValue thisObj, JsValue[] arguments)
ClrFunctionInstance.Call(JsValue thisObject, JsValue[] arguments)
--- End of stack trace from previous location ---
ClrFunctionInstance.Call(JsValue thisObject, JsValue[] arguments)
<102 more frames...>
JintBlockStatement.ExecuteBlock(EvaluationContext context)
JintIfStatement.ExecuteInternal(EvaluationContext context)
JintStatementList.Execute(EvaluationContext context)
Engine.ScriptEvaluation(ScriptRecord scriptRecord)
Engine.ExecuteWithConstraints[T](Boolean strict, Func`1 callback)
Engine.Execute(Script script)
Engine.Evaluate(Script script)
</p></details>

<details><summary>Exception 3</summary><p>

This one doesn't fail if I run it alone:

  Message: 
Jint.Runtime.JavaScriptException : Property 'System$IEquatable$1$System.Int32$Equals$1' of object is not a function
---- Jint.Runtime.JavaScriptException+JavaScriptErrorWrapperException : Property 'System$IEquatable$1$System.Int32$Equals$1' of object is not a function

  Stack Trace: 
Engine.ScriptEvaluation(ScriptRecord scriptRecord)
Engine.ExecuteWithConstraints[T](Boolean strict, Func`1 callback)
Engine.Execute(Script script)
Engine.Evaluate(Script script)

</p></details>

<details><summary>Exception 4</summary><p>

  Message: 
System.NullReferenceException : Object reference not set to an instance of an object.

  Stack Trace: 
JintObjectExpression.BuildObjectFast(EvaluationContext context)
JintObjectExpression.EvaluateInternal(EvaluationContext context)
JintExpression.GetValue(EvaluationContext context)
JintCallExpression.ArgumentListEvaluation(EvaluationContext context)
JintCallExpression.EvaluateInternal(EvaluationContext context)
JintExpression.GetValue(EvaluationContext context)
JintExpressionStatement.ExecuteInternal(EvaluationContext context)
JintStatementList.Execute(EvaluationContext context)
ScriptFunctionInstance.Call(JsValue thisArgument, JsValue[] arguments)
JintCallExpression.EvaluateInternal(EvaluationContext context)
<43 more frames...>
JintVariableDeclaration.ExecuteInternal(EvaluationContext context)
JintStatementList.Execute(EvaluationContext context)
Engine.ScriptEvaluation(ScriptRecord scriptRecord)
<>c__DisplayClass71_0.<Execute>b__0()
Engine.ExecuteWithConstraints[T](Boolean strict, Func`1 callback)
Engine.Execute(Script script)
Engine.Evaluate(Script script)
</p></details>

<details><summary>Exception 5</summary><p>
  Message: 
System.IndexOutOfRangeException : Index was outside the bounds of the array.

  Stack Trace: 
JintCallStack.Pop()
Engine.Call(FunctionInstance functionInstance, JsValue thisObject, JsValue[] arguments, JintExpression expression)
ObjectInstance.UnwrapFromGetter(PropertyDescriptor desc, JsValue thisObject)
ObjectInstance.Get(JsValue property, JsValue receiver)
ObjectInstance.Get(JsValue property, JsValue receiver)
RegExpPrototype.Flags(JsValue thisObj, JsValue[] arguments)
ClrFunctionInstance.Call(JsValue thisObject, JsValue[] arguments)
--- End of stack trace from previous location ---
ClrFunctionInstance.Call(JsValue thisObject, JsValue[] arguments)
Engine.Call(FunctionInstance functionInstance, JsValue thisObject, JsValue[] arguments, JintExpression expression)
<75 more frames...>
JintBlockStatement.ExecuteBlock(EvaluationContext context)
JintIfStatement.ExecuteInternal(EvaluationContext context)
JintStatementList.Execute(EvaluationContext context)
Engine.ScriptEvaluation(ScriptRecord scriptRecord)
Engine.ExecuteWithConstraints[T](Boolean strict, Func`1 callback)
Engine.Execute(Script script)
Engine.Evaluate(Script script)
</p></details>

I assumed this would work. Is there anything I don't know about, or have missed? Or is there an issue somewhere?

**Comment by lahma** [comment]
What if you use Engine.PrepareScript?

**Comment by ChrML** [comment]
> What if you use `Engine.PrepareScript`?

Same effects. Had it like that first, but changed it to this to exclude issues

**Comment by lahma** [comment]
Should now be fixed in main and soon available on MyGet feed.

**Comment by ChrML** [comment]
Cool :) Nice job

**Comment by ChrML** [comment]
Can confirm that this resolved the issue.
