### ISSUE TITLE
Using JInt in ASP.NET apps

### ISSUE THREAD

**Issue by eyalpost** [sebastienros/jint#149]
What's the correct way to user Jint in a multi-threaded environment like ASP.NET?
Assuming I have the following structure:
- Multiple users will use the app at the same time
- Each user has defined his own script and this script can run many times during the user interaction with the system

I saw that it's possible to instantiate the Engine once, parse a script and the call functions from the script multiple times with much better performance than instantiating the engine repeatedly.
1. Is that safe? 
2. Looking at Jint's code there's a couple of [ThreadStatic] declarations which I'm note sure if will cause issues in server side apps or not. 
3. Can an Engine be used by multiple threads simultaneously?

**Comment by sebastienros** [comment]
An engine is not thread safe. You need one engine per request. If the scripts are shared you can cache their parsed tree and run against them concurrently though. I don't remember having introduced a `ThreadStatic`, but I will check why.

**Comment by sebastienros** [comment]
Ok, ThreadStatic here is fine, this is also a reason why engines are not thread safe. So you are fine if you use one Engine per request.
