### ISSUE TITLE
Reassigning a hoisted function (as constructor) to its instance doesn't keep prototype

### ISSUE THREAD

**Issue by rg1** [sebastienros/jint#1495]
Run this code in current jint:
```javascript
function clone1(parent) {
    { // extra block is relevant!
        function t(){};
	t.prototype = parent.prototype;
	t = new t();
        if (t.__proto__ !== parent.prototype) {
            throw "inheritance is broken!";
        }
        return t;
    }
}

clone1(function(){}); // doesn't really matter what object we pass
```
Note that the exception is thrown. This is unexpected and doesn't happen in node.
Neither does it happen with jint, with one of those small modifications:
- assigning to a separate variable
- assigning t from that separate variable or
- removing the extra block (not hoisting t).

What's happening?

**Comment by lahma** [comment]
That's part of [legacy behavior](https://tc39.es/ecma262/#sec-block-level-function-declarations-web-legacy-compatibility-semantics) that runtimes support differently. Jint doesn't support this legacy behavior, which is described in detail in section [B.3.2.6 Changes to BlockDeclarationInstantiation](https://tc39.es/ecma262/#sec-web-compat-blockdeclarationinstantiation).

**Comment by lahma** [comment]
When I checked this, my research lead me to point where the referred specification didn't initialize block-scoped functions the same way. Using the legacy mode behavior didn't throw error.

Jint 2.x was developed using ES5 spec which is what I believe the so-called legacy behavior.

**Comment by lahma** [comment]
If support for legacy mode is something you would like to work on, I think there could be option in engine options to allow the legacy mode. Them based on setting could deviate from spec based on guidance in the above links.
