### ISSUE TITLE
CatchClrExceptions handler executes when a function is called with apply()

### ISSUE THREAD

**Issue by tkovacs-dev** [sebastienros/jint#1500]
I'm running the latest beta (https://github.com/sebastienros/jint/releases/tag/v3.0.0-beta-2048).

When running this code:

```
var engine = new Engine(options =>
{
    options.CatchClrExceptions(e =>
    {
        Console.WriteLine("Caught exception: " + e);
        return true;
    });
});

engine.Evaluate(@"
    function throwError() {
        throw new Error();
    }

    // doesn't cause ExceptionDelegateHandler call
    try { throwError(); } catch {}

    // does cause ExceptionDelegateHandler call
    try { throwError.apply(); } catch {}
");
```

The `ExceptionHandlerDelegate` is called for the second invocation of `throwError`, but not for the first.

I expected no calls to the `ExceptionHandlerDelegate`, since there is no CLR code throwing exceptions.

**Comment by lahma** [comment]
Thanks for the report. Would you like to help out with developing the fix?
