### ISSUE TITLE
Evaluate automagically unwrap object?

### ISSUE THREAD

**Issue by JBBianchi** [sebastienros/jint#1523]
**Version used**

3.0.0-beta-2049

**Describe the bug**

When the evaluated expression is an object, its inner value is returned instead of the object itself.

**To Reproduce**
```csharp
[Fact]
public void Should_Return_Object_1()
{
    var expression = "{ foo: 'bar' }";
    var expected = new { foo = "bar" };
    var engine = new Engine();
    var result = engine .Evaluate(expression).ToObject();
    result.Should().BeEquivalentTo(expected)); // result = "bar";
}

[Fact]
public void Should_Return_Object_2()
{
    var expression = "{ foo: 'bar', fizz: 'buzz' }";
    var expected = new { foo = "bar", fuzz = "buzz" };
    var engine = new Engine();
    var result = engine .Evaluate(expression).ToObject(); // throws `Line 1: Unexpected token :'`
    result.Should().BeEquivalentTo(expected));
}
```

**Expected behavior**

In the first case, the returned value in `"bar"` but it should be `{ foo: "bar" }`.
The second case throws an exception even though it's valid.

**Comment by lahma** [comment]
Would you like to help with a PR?

**Comment by JBBianchi** [comment]
I just tested Jint for the first time today. I can try to dig in but it will probably take me some time to understand how it works and then track down the bug and maybe find a fix. So short anwser, I don't think so. I'll still try to have a look.

**Comment by JBBianchi** [comment]
Well, nevermind, this issue can be close, it's the expected behavior when running in strict mode.

**Comment by JBBianchi** [comment]
> I think the invalid syntax also comes from that you need to add parenthesis to your object expression, e.g. ` var expression = "({ foo: 'bar', fizz: 'buzz' })";`

Indeed, I tried my code in "sloppy mode" and it was working so I was surprised not to see it work in Jint. But your version is the proper one, valid with `"use strict"` and working fine.
