### ISSUE TITLE
`NullReferenceException` when creating object with specific setup

### ISSUE THREAD

**Issue by Genteure** [sebastienros/jint#1542]
**Version used**

main branch as of current, commit 8b0da8ad3a754b4bb5d7da9d2492acef7ab25aa4

**Describe the bug**

When creating C# object with a specific sets of constructors and calling arguments, `NullReferenceException` is thrown.

**To Reproduce**

```csharp
public class IssueTest
{
    [Fact]
    public void RunTest()
    {
        var engine = new Engine();
        engine.SetValue("Font", typeof(MockFont));

        var result = engine.Evaluate(@"new Font('fontname', 30)").ToObject();

        var font = Assert.IsType<MockFont>(result);
        Assert.Equal(2, font.ConstructorUsed);
        Assert.Equal("fontname", font.FamilyName);
        Assert.Equal(30, font.EmSize);
    }

    public enum MockFontStyle
    {
        One, Two, Three
    }

    public class MockFont
    {
        public int ConstructorUsed { get; }
        public string FamilyName { get; }
        public float EmSize { get; }
        public MockFontStyle Style { get; }

        public MockFont(string familyName, float emSize, MockFontStyle style)
        {
            ConstructorUsed = 1;
            FamilyName = familyName;
            EmSize = emSize;
            Style = style;
        }

        public MockFont(string familyName, float emSize)
        {
            ConstructorUsed = 2;
            FamilyName = familyName;
            EmSize = emSize;
        }
    }
}
```

```txt
Stack Trace: 
TypeConverter.CalculateMethodParameterScore(Engine engine, JsValue jsValue, Type paramType) line 1226
TypeConverter.CalculateMethodScore(Engine engine, MethodDescriptor method, JsValue[] arguments) line 1143
TypeConverter.FindBestMatch(Engine engine, MethodDescriptor[] methods, Func`2 argumentProvider)+MoveNext() line 1090
TypeReference.<Construct>g__ObjectCreator|11_0(Engine engine, Realm realm, ObjectCreateState state) line 160
TypeReference.Construct(JsValue[] arguments, JsValue newTarget) line 181
...
```

When calculating the score for the first constructor, three argument is passed into `TypeConverter.CalculateMethodScore`, with the third being real `null` (not `JsNull`), causing the `NullReferenceException`.

**Expected behavior**

Test passes.

**Additional context**

Based on reports in #1541

/cc @Zaitonn

I'm currently not able to make a pull request for this right now, but can spend more time and submit a fix if it's not fixed a few days later.

**Comment by Genteure** [comment]
Hi @mainlyer, [`argumentProvider`](https://github.com/sebastienros/jint/blob/8b0da8ad3a754b4bb5d7da9d2492acef7ab25aa4/Jint/Runtime/Interop/TypeReference.cs#L76) is last changed by you in #1517, maybe you're more familiar around this area.
If you have the time, could you check what went wrong?
Thanks.

**Comment by mainlyer** [comment]
Hi @Genteure, sure! I'll try to find a gap this weekend to review It.

**Comment by lahma** [comment]
I think this should be now resolved, available on soon MyGet feed for testing.
