### ISSUE TITLE
JsonParser doesn't work with JSON with spaces.

### ISSUE THREAD

**Issue by praneetnadkar** [sebastienros/jint#1544]
**Version used** - 2.11.58 or Latest Beta version 2049

**Description**
When we have a JSON that has spaces or is indented, the JSON parser does not seem to work. It throws an exception `Unhandled exception. SyntaxError: Unexpected token `

**To Reproduce**
`var json = "[    {      \"First Name\": \"John\",      \"Last Name\": \"Doe\",      \"Telephone\": \"999999999\",      \"Col A\": \"A\",      \"Col B\": \"QW\"    },    {      \"First Name\": \"John1\",      \"Last Name\": \"Doe2\",      \"Telephone\": \"999999999\",      \"Col A\": \"B\",      \"Col B\": \"1\"    },    {      \"First Name\": \"John2\",      \"Last Name\": \"Doe2\",      \"Telephone\": \"999999999\",      \"Col A\": \"C\",      \"Col B\": \"2\"    }  ]"; `

However, if you set the JSON like the following, it works:
`var json = "[{\"First Name\":\"John\",\"Last Name\": \"Doe\",\"Telephone\":\"999999999\",\"Col A\":\"A\",\"Col B\": \"QW\"},{\"First Name\":\"John1\",\"Last Name\":\"Doe2\",\"Telephone\":\"999999999\",\"Col A\":\"B\",\"Col B\": \"1\"},{\"First Name\":\"John2\",\"Last Name\":\"Doe2\",\"Telephone\":\"999999999\",\"Col A\":\"C\",\"Col B\":\"2\"}]";`

I am using the parser like this: `var value = new JsonParser(source).Parse(json);`

**Expected behavior**
It should not fail with JSON that has spaces.

**Comment by lahma** [comment]
Would you like to help out with a PR containing a fix and more test coverage? Please make sure that input also works under Node.js.

**Comment by lahma** [comment]
The JSON example parsers with latest main so maybe the parser has had a bug fix or something. Maybe you need to try again with next release whenever it's out or try latest from MyGet feed.
