### ISSUE TITLE
Ability to create readonly variables

### ISSUE THREAD

**Issue by christianrondeau** [sebastienros/jint#156]
It would be very interesting to be able to set readonly values, like `window` and `console` in a web browser. A real use case for this was a user of our JavaScript engine would override an object that is set prior to execution, and then understanding the problem became much harder.

An example of how I see this:

``` c#
engine.SetValue("myStatic", "This string is read only", ValueFlags.ReadOnly);
```

Then, in JavaScript, this would throw:

``` javascript
myStatic = "some other value";
```

**Comment by sebastienros** [comment]
Isn't that possible by creating a void setter on the Global object?

**Comment by christianrondeau** [comment]
Are you talking about using something like `engine.Global.FastAddProperty("myProp", "myValue", false, false, false);`? It looks like setting a new value on `myProp` does not crash. Can you give an example, or point me in the right direction?

**Comment by lahma** [comment]
Now that let and const are supported, it should work by setting `const myStatic = 'This string is read only';`. We can reopen if this is not a satisfactory solution.
