### ISSUE TITLE
Add convenience methods to ShadowRealm

### ISSUE THREAD

**Issue by gentledepp** [sebastienros/jint#1573]
https://github.com/sebastienros/jint/discussions/1406

I am trying to implement the "SetValue" convenience methods to ShadowRealm and add tests for them

**Comment by gentledepp** [comment]
So after understanding _how_ a ShadowRealm should work (sorry for not having known earlier) 
- I implemented a convenience overload to evaluate an `Esprima.Script` in a shadow realm
- added some tests (am I missing something here?)
- and created benchmarks

Unfortunately, the benchmarks do not seem as promising as I hoped they would:
`dotnet run -c Release --allCategories ShadowRealm`

```
|                         Method |       Mean |     Error |    StdDev |   Gen0 |   Gen1 | Allocated |
|------------------------------- |-----------:|----------:|----------:|-------:|-------:|----------:|
|                  ReusingEngine | 3,726.3 ns |  74.29 ns | 148.36 ns | 0.5417 | 0.0038 |   3.34 KB |
|              NewEngineInstance | 9,780.1 ns | 194.17 ns | 307.98 ns | 2.7618 | 0.1373 |  16.93 KB |
|                    ShadowRealm | 8,251.2 ns | 164.89 ns | 161.94 ns | 2.2888 | 0.1526 |  14.06 KB |
|     ReusingEngine_ParsedScript |   861.1 ns |  16.68 ns |  25.47 ns | 0.3204 | 0.0019 |   1.97 KB |
| NewEngineInstance_ParsedScript | 5,446.2 ns | 105.62 ns | 151.48 ns | 2.5253 | 0.1297 |  15.51 KB |
|       ShadowRealm_ParsedScript | 4,829.8 ns |  96.42 ns | 219.60 ns | 2.0599 | 0.1373 |  12.64 KB |
```

The fastest way is, obviously, re-using a single (static) `Jint.Engine`- even better, when reusing the already parsed `Esprima.Script`.

It seems the `ShadowRealm` is a **tiny bit** more memory efficient and faster than newing up a new `Jint.Engine` for every call.
However, I hoped it would be way faster. :-|


Any thoughts?

**Comment by lahma** [comment]
Most of the construction cost probably comes from global object building. Might need a re-read of the spec to see what can be avoided.

**Comment by lahma** [comment]
First iteration merged!
