### ISSUE TITLE
Read stack trace during runtime like console.trace

### ISSUE THREAD

**Issue by Zmarfan** [sebastienros/jint#1575]
### Feature Idea
When I was implementing a console object using Jint I wanted to make a sort of replica of the browser's console.trace where I can get the stacktrace in runtime without an error taking place. As far as I can tell that is currently not possible.

### What I've tried
While I could make some string replacement of my javascript code to replace "console.trace()" with throwing an error and immediately catching it to get the stacktrace it would not be accurate and work well. I noticed that where the Exceptions get their stack trace from lies within the engine class itself but is marked as internal (JintCallStack CallStack). I was also unable to use reflection to get that instance and use its ToString method as well, it just gave me "delegate" (which anyway is bad practice).

### Ideas for implementation
I am not well versed in the inner workings of Jint so I wouldn't know about any unforeseen consequences with making a public getter for JintStackTrace (and also making that class public) but I believe that would solve my issue. One could also make a method for just getting a string representation of the current stacktrace from the engine instance without exposing the inner classes. But it would be nice to get a more detailed copy of the stacktrace in case one would like to add/remove/change certain entries or what not, perhaps a function on the engine instance which provides a copy of the stack trace?

**Comment by lahma** [comment]
Added simple string presentation for now, accessible via `engine.Advanced.StackTrace`.
