### ISSUE TITLE
"Pseudo compilation" of .Net Wrapper

### ISSUE THREAD

**Issue by ZSalloum** [sebastienros/jint#159]
Hi,
Something that will certainly emerge from using .Net objects wrapped in Javascript, is the problem of interface changing. In case a property or a method is no longer available, this will only be seen when the the javascript code is run. For an application that has dozens of javascript files, this will be problematic.
For this reason it would be better if there is a way to "compile/verify" all the javascript code and ensure that the .Net calls are still valid or at least the properties and methods have not changed.

**Comment by SimonMeskens** [comment]
This is already available. Use TypeScript to annotate the Javascript with interfaces generated from C# classes. You can use T4TS as a build task to generate the appropriate TypeScript interfaces.

This way, whenever the interface changes, TypeScript will fail to compile.

The "Pseudo compilation" you describe is the main reason for TypeScript's existence.

**Comment by lahma** [comment]
I'm closing this as this is out of scope for Jint, and using TypeScript should help with type safety. There are tools like [Typewriter](https://frhagn.github.io/Typewriter/) to help you with the generation.
