### ISSUE TITLE
iOS compatibility: ExpandoObject

### ISSUE THREAD

**Issue by dominik-weber** [sebastienros/jint#161]
I noticed that you use a single `__IOS__` compiler condition inside JsValue.cs which replaces the ExpandoObject used in normal builds with a Dictionary<>.
This compilation setting is a bit tricky as I can not use the NuGet binary builds on iOS but have to download the source code and build it myself (with the `__IOS__` definition).

My question: Why do you prefer using ExpandoObject over the Dictionary in the first place? As far as I know there is no performance gain from using ExpandoObject, and your code seems to run fine with either the ExpandoObject or the Dictionary (in fact you cast the ExpandoObject to IDictionary<>, using only methods which are also available for Dictionary<>).

(There was also a discussion about this regarding .NET 3.5 compatibility: https://github.com/sebastienros/jint/issues/37 dropping the ExpandoObject would at least help to close this issue as well)

**Comment by lahma** [comment]
There should be no longer such compiler flag, I'm closing this as obsolete and we can reopen this is this relevant in .NET Core / >= NET 5 world.
