### ISSUE TITLE
3.0.0-beta-2050  The return is not supported

### ISSUE THREAD

**Issue by jiangzhuangxiansheng** [sebastienros/jint#1617]
**Version used**

With which version did you encounter this behavior. Please check against 3.x beta if you haven't yet, it might have the fix already.

**Describe the bug**
3.0.0-beta-2050  The return is not supported

**To Reproduce**

Ideally code samples or better yet, xUnit test against current `main`.

**Expected behavior**

**Additional context**
Engine.Evaluate("return 123", new ParserOptions {Tolerant = true}).ToObject()

error message: Line 1: Illegal return statement

**Comment by lahma** [comment]
As `return` is not allowed outside of functions per spec, you need to have:

```c#
new Engine()
  .Evaluate("return 123", new ParserOptions { Tolerant = true, AllowReturnOutsideFunction = true })
  .ToObject();
```
