### ISSUE TITLE
how can I remove added Event

### ISSUE THREAD

**Issue by KimJaeHak** [sebastienros/jint#162]
hello ? my name is jae hak. 

I assigned Event 
ex) 
Engine engin = new Engine(clr => clr.AllowClr()); 
//button assigned click evnet 
engin.Execute("button.add_Click(function(sender,eventargs){System.Windows.Forms.MessageBox.Show('hellow world')})"); 

//button remove click event 
engin.Execute("button.remove_Click(function(sender,eventargs){})"); 

but button click event not remove. 
please let me know how remove event.

**Comment by doronguttman** [comment]
You should probably remove the same instance of the added one. Try to
create a var function, then add it, then remove it.

**Comment by KimJaeHak** [comment]
hello doronguttman !!
I did it that you say but event is not removed from button.

**Comment by doronguttman** [comment]
Can you share your revised code?

**Comment by KimJaeHak** [comment]
hello  doronguttman
This is my code 

//c# code
    public partial class Form1 : Form
    {
        private System.Windows.Forms.Button button1;
        Engine engin;
        public Form1()
        {
            InitializeComponent();
            engin = new Engine(clr => clr.AllowClr(typeof(System.Windows.Forms.Button).Assembly));
            engin.SetValue("button1", this.button1);
            engin.Execute(@"
             var myFunc = function(sender , eventArgs)
                           {
                                System.Windows.Forms.MessageBox.Show(""TestString"");
                            };
             button1.add_Click(myFunc);
             button1.remove_Click(myFunc);
            
                ");
        }
    }

please tell me what problem?

**Comment by doronguttman** [comment]
If you try the following code it will result in a message box showing "False" since the added handler and the removed handlers are not the same (that is why it is not removed).
I'm guessing that when Jint is converting the function object to an eventhandler it is creating a new instance every time.
If you try to get the value of myFunc out of the engine you will see it is not an eventhandler, but a function instance. so it has to be converted when invoking add/remove, which creates a new object.
One way to solve it is to add caching to type conversions.

private event EventHandler _test;
        public event EventHandler Test
        {
            add
            {
                eh1 = value;
                _test += value;
            }
            remove
            {
                eh2 = value;
                _test -= value;
            }
        }

        private EventHandler eh1;
        private EventHandler eh2;
        Engine engin;
        public Form1()
        {
            InitializeComponent();
            engin = new Engine(clr => clr.AllowClr(typeof(System.Windows.Forms.Button).Assembly));
            engin.SetValue("frm", this);
            engin.Execute(@"
                var myFunc = function(sender , eventArgs)
                {
                    System.Windows.Forms.MessageBox.Show(""TestString"");
                };
                frm.add_Test(myFunc);
                frm.OnTest();
                frm.remove_Test(myFunc);
                frm.OnTest();
            ");

            System.Windows.Forms.MessageBox.Show((eh1 == eh2).ToString());
        }

        public virtual void OnTest()
        {
            var handler = _test;
            if (handler != null) handler(this, EventArgs.Empty);
        }

**Comment by KimJaeHak** [comment]
thank you for your help 
I understand your comment.
