### ISSUE TITLE
error No public methods with the specified arguments were found

### ISSUE THREAD

**Issue by hyzx86** [sebastienros/jint#1637]
**Version used**
 [3.0.0-beta-2052](https://www.nuget.org/packages/Jint/3.0.0-beta-2052)
**Describe the bug**

Hi ,

I used Jint and [FreeSql ](https://github.com/dotnetcore/FreeSql/) to encapsulate the changes of different databases and operate on the data. Recently, I encountered a problem.
Update from beta-2049 to beta-2052
An exception is thrown. `No public methods with the specified arguments were found. `

See the last line for an example

```c#
  var db = await new FreeSqlMethodsProvider().UseDbAsync(scope.ServiceProvider);
  var total = db.SelectTypedQuery("UserProfile").Where("1=1").Any();

  engine.SetValue("objSelect", objSelect);
  var result1 = engine.Evaluate("objSelect.where('1=1')");//pass
  engine.SetValue("result1", result1);
  var result2 = engine.Evaluate("result1.any()");//error No public methods with the specified arguments were found
```

ISelect<object> SelectTypedQuery(string)

 **Where Method:**

```C#
        /// <summary>
        /// 原生sql语法条件，Where("id = @id", new { id = 1 })<para></para>
        /// 提示：parms 参数还可以传 Dictionary&lt;string, object&gt;
        /// </summary>
        /// <param name="sql">sql语法条件</param>
        /// <param name="parms">参数</param>
        /// <returns></returns>
        TSelect Where(string sql, object parms = null);
```
https://github.com/dotnetcore/FreeSql/blob/be6f2fa9c2cc04ce5bf01fc38d2b01a493021088/FreeSql/Interface/Curd/ISelect/ISelect0.cs#L291-L298

**Any Method:**

```c#
        /// <summary>
        /// 执行SQL查询，是否有记录
        /// </summary>
        /// <returns></returns>
        bool Any();
```
https://github.com/dotnetcore/FreeSql/blob/be6f2fa9c2cc04ce5bf01fc38d2b01a493021088/FreeSql/Interface/Curd/ISelect/ISelect0.cs#L195-L200

When I debug in jint, I find that I want to call `bool Any(); `

But always call to`  bool Any(Expression<Func<T1, bool>> exp); `
And it's the only one of the methods

```c#
/// <summary>
        /// 执行SQL查询，是否有记录
        /// </summary>
        /// <param name="exp">lambda表达式</param>
        /// <returns></returns>
        bool Any(Expression<Func<T1, bool>> exp);
```

https://github.com/dotnetcore/FreeSql/blob/be6f2fa9c2cc04ce5bf01fc38d2b01a493021088/FreeSql/Interface/Curd/ISelect/ISelect1.cs#L36C1-L41C50

**Comment by viruscamp** [comment]
```c#
    public interface I0
    {
        string NameI0 { get => "I0.Name"; }
        string OverloadSuperMethod() => "I0.OverloadSuperMethod()";
        string SubPropertySuperMethod() => "I0.SubPropertySuperMethod()";
    }

    public interface I1 : I0
    {
        string Name { get; }
        string OverloadSuperMethod(int x) => $"I1.OverloadSuperMethod(int {x})";
        new string SubPropertySuperMethod => "I1.SubPropertySuperMethod";
    }

    [Fact]
    public void CallSuperPropertyFromInterface()
    {
        Assert.Equal(holder.I1.NameI0, _engine.Evaluate("holder.I1.NameI0"));
    }

    [Fact]
    public void CallOverloadSuperMethod()
    {
        Assert.Equal(holder.I1.OverloadSuperMethod(1), _engine.Evaluate("holder.I1.OverloadSuperMethod(1)"));
        Assert.Equal(holder.I1.OverloadSuperMethod(), _engine.Evaluate("holder.I1.OverloadSuperMethod()"));
    }

    [Fact]
    public void CallSubPropertySuperMethod()
    {
        Assert.Equal(holder.I1.SubPropertySuperMethod, _engine.Evaluate("holder.I1.SubPropertySuperMethod"));
        // Property and method cannot coexist
        Assert.Throws<Exception>(() => _engine.Evaluate("holder.I1.SubPropertySuperMethod()"));
    }
```
You PR pass `CallOverloadSuperMethod` but break `CallSubPropertySuperMethod`.

IMO, we'd better refactor TypeResolver , take care of the search order.
And fill property cache when loaded,  remove property lazyload.

**Comment by hyzx86** [comment]
> You PR pass `CallOverloadSuperMethod` but break `CallSubPropertySuperMethod`.

How is the holder instantiated in your code?

> IMO, we'd better refactor TypeResolver , take care of the search order. And fill property cache when loaded, remove property lazyload.

Yes I agree, suggest refactoring `TryFindMemberAccessor` into replaceable logic ，Just like the `MemberNameCreator` and the `MemberNameComparer`  😁

**Comment by Genteure** [comment]
I searched around in https://github.com/dotnetcore/FreeSql on GitHub (so not in an IDE) and I can't seem to find an implementation of `ISelect0`. Can you tell me what's the concrete type of `objSelect` in your initial example code please?

**Comment by hyzx86** [comment]
@Genteure  Here is a unit test in FreeSql

[SqliteSelectTest](https://github.com/dotnetcore/FreeSql/blob/d40036dce8ecdef8d5b618fc5dfc07d3714ce778/FreeSql.Tests/FreeSql.Tests/Sqlite/Curd/SqliteSelectTest.cs#L455-L457)

In my project ,my method will retrun a type of `ISelect<object>`  
like this:

```C#
        public ISelect<object> SelectTypedQuery(string typeName = default)
        {
            if (string.IsNullOrEmpty(typeName))
            {
                return FreeSql.Select<object>().AsType(typeof(ContentItemIndex));
            }

            var indexService = _serviceProvider.GetRequiredService<IDynamicIndexAppService>();
            var type = indexService.GetDynamicIndexType(typeName);
            if (type != null)
            {
                return FreeSql.Select<object>().AsType(type);
            }
            else
            {
                throw new Exception($"Type not found. ： {typeName} ");
            }
        }

```

**Comment by Genteure** [comment]
@hyzx86 我是想问它的实际运行时的类型是什么，方便我确认一下现在的 unit test 是否能代表实际你遇到的问题。我对那个项目不熟悉，项目里面的抽象层又太多，我在 GitHub 上搜索代码找不到一个实现了 `ISelect0`, `ISelect1` 的 concrete type。

```csharp
objSelect.GetType().FullName
```

**Comment by hyzx86** [comment]
@Genteure  
With the help of @viruscamp , I have reproduced this problem using the code he provided.

![image](https://github.com/sebastienros/jint/assets/15613121/97ad0ecc-4e2a-4a23-8202-fd7bcd27f9b1)

**Comment by hyzx86** [comment]
@Genteure 回复完 我愣了一下。。。我以为浏览器开了翻译。。原来你发的就是中文🤣
