### ISSUE TITLE
Make function call itself crash without any exception

### ISSUE THREAD

**Issue by seyacat** [sebastienros/jint#1639]
3.0.0-beta-2049
3.0.0-beta-2052

With which version did you encounter this behavior. Please check against 3.x beta if you haven't yet, it might have the fix already.

**Describe the bug**

Jint make application crash without advice

Ideally code samples or better yet, xUnit test against current `main`.

			Jint.Engine machine;
			machine = new Jint.Engine(options =>
		{
			// Limit memory allocations to MB
			options.LimitMemory(100_000);

			// Set a timeout to 4 seconds.
			options.TimeoutInterval(TimeSpan.FromSeconds(1));

			// Set limit of 1000 executed statements.
			options.MaxStatements(100);

			// Use a cancellation token.
			//options.CancellationToken(cancellationToken);
		});
			machine.SetValue("test", "");
			machine.Execute(
					@"
					test=e=>this.test()
					test()
				"
				);

Max Statement or Timeout expected

**Comment by seyacat** [comment]
options.LimitRecursion(10);

solves the issue

**Comment by lahma** [comment]
@seyacat so is there a problem here or just that you need to account for this via configuration (limit recursion)?

**Comment by seyacat** [comment]
No issue here, the LimitResursion options solves the problem ty
