### ISSUE TITLE
CLR objects not enumerable

### ISSUE THREAD

**Issue by jmorgannz** [sebastienros/jint#164]
Object.keys and for (var prop in obj)  { } return empty arrays for CLR wrapped objects.
They only pull/push through the values on a get/set of individual properties.

I'd consider this a breaking change from old jint to this new codebase (which looks great internally by the way)

I had a play, and from what I can see it would just be Jint.Runtime.ObjectWrapper and Jint.Runtime.TypeReference that need patching to fix this.
Not sure there's any reason to enumerate over a CLR function (/delegate)

**Comment by asdfgasdfsafgsdfa** [comment]
> I had a play, and from what I can see it would just be Jint.Runtime.ObjectWrapper and Jint.Runtime.TypeReference that need patching to fix this.

Can you share what I'd have to do to fix this?

**Comment by asdfgasdfsafgsdfa** [comment]
For now I'm using the below code, which seems to work.
But I wonder if there isn't a better way to do it.
Especially if objects have nested arrays / List<T>s and IEnumerable<T>s in general.

` public static ObjectInstance CreateArray<T>(this Engine engine, IEnumerable<T> items)
        {
            var jsArray = items.Select(x => JsValue.FromObject(engine, x)).ToArray();
            return js.Array.Construct(jsArray);
        }`

But it would be way better if jint would do that for us.
Is this the right way to go about it? @sebastienros 
If not, what would you suggest I do?

**Comment by sebastienros** [comment]
Is the scenario to enumerate .NET properties through `.keys` or the dynamic properties added with javascript?

**Comment by asdfgasdfsafgsdfa** [comment]
This is not about the properties, its about being able to do this:

SetValue("ar", new List<int> {1,2,3})

and then in js

for(i in ar) ...

this will not work when you have custom objects.
Example:
class MyObj { public string Name = "abc"; }
SetValue("ar", new[] { new MyObj(), new MyObj(), ... })

in js: for(x in ar) print(x.Name);


this will not work (print is a delegate to Console.WriteLine)

**Comment by Ghostbird** [comment]
I'd love to see this fixed, it confused me for a second that some objects in my Javascript seemed to be empty when enumerated, Object.keys() on it returned an empty array. But when trying to access the properties, they worked fine. Other objects didn't have the problem at all. After some head-scratching I realised that this only happened for objects that were created by CLR functions. The objects created in Jint itself are fine.

### Examples
It's fine when `obj` is created inside a piece of javascript interpreted by the Jint engine:
``` javascript
var obj = { x : 1 };
Object.keys(obj); // Returns ['x']
```
But when `obj` is created by the CLR, you've got to jump through hoops to get it working.
``` javascript
// This CLR function returns an object with one C# property: int x = 1;
var obj = MyExposedClrFunction();

Object.keys(obj); // Returns [] unexpectedly
Object.keys(JSON.parse(JSON.stringify(obj))); // Returns ['x']
```

**Comment by simonjlawson** [comment]
I have come up against the same bug for Object.Key's handling of Dictionaries.  Adding the following to the Jint.Native.Object.ObjectConstructor.Keys class works but doesnt feel final as I am calling class specific code in a general function.  Any advice would be very welcome :)

```
            var t = o.ToObject().GetType();
            if (t.IsGenericType && t.GetGenericTypeDefinition() == typeof(Dictionary<,>))
            {
                var dictionaryKeys = new List<KeyValuePair<string, PropertyDescriptor>>();
                foreach (var prop in o.ToObject() as IDictionary<string, object>)
                {
                    dictionaryKeys.Add(new KeyValuePair<string, PropertyDescriptor>(prop.Key, new PropertyDescriptor(null, false, true, false)));
                }
                enumerableProperties = dictionaryKeys.ToArray();
                n = enumerableProperties.Length;
            }
```

**Comment by lahma** [comment]
With https://github.com/sebastienros/jint/pull/750 this code now prints as expected:

```
var engine = new Engine(cfg => cfg.AllowClr());

engine
	.SetValue("print", new Action<object>(Console.WriteLine))
	.SetValue("obj", new { x = 2 })
	.SetValue("obj2", new Dictionary<string, object>(){ {"y", 2 }});

engine.Execute("print(JSON.stringify(Object.keys(obj)));");
```

Output:
```
["x"]
["y"]
```
