### ISSUE TITLE
JsTypedArrays values getting passed as empty ExpandoObject in Type Converter.

### ISSUE THREAD

**Issue by graphnode** [sebastienros/jint#1641]
**Version used**

3.0.0-beta-2052

**Describe the bug**

When I try to pass a Float32Array from javascript to .net and convert it using an custom ITypeConverter I get an empty ExpandoObject because ObjectInstance [ToObject](https://github.com/sebastienros/jint/blob/da88d1ea53d836710aa47c24a3a2fbdf65fe911d/Jint/Native/Object/ObjectInstance.cs#L980) ignores JsTypedArrays unlike [JsArrays](https://github.com/sebastienros/jint/blob/da88d1ea53d836710aa47c24a3a2fbdf65fe911d/Jint/Native/Object/ObjectInstance.cs#L1039) which work ok.

**To Reproduce**

Set a custom ITypeConverter and pass a Float32Array (and any other typed array) to .net.
The type converter is unable to get the array values since its an empty ExpandoObject.

```c#
public class JsToDotNetConverter : DefaultTypeConverter
{
    public JsToDotNetConverter(Engine engine) : base(engine)  {}

    public override object Convert(object? value, Type type, IFormatProvider formatProvider) {
        // value is empty ExpandoObject when Float32Array is passed but is object[] when an array is passed.
        return base.Convert(value, type, formatProvider)!;
    }

}
```

**Expected behavior**

Instead of an empty ExpandoObject the value should be an array.

**Comment by lahma** [comment]
@graphnode would you like to create a PR with some test coverage to improve the current behavior?

**Comment by graphnode** [comment]
> @graphnode would you like to create a PR with some test coverage to improve the current behavior?

Done. Pull request #1646 was created.

**Comment by graphnode** [comment]
Merged with main.

Maybe in the future we can think of a way to improve performance by giving readonly access to the JsArrayBuffer _arrayBufferData but that might require major changes to how we handle object conversion.
