### ISSUE TITLE
JS Proxy on Clr Object

### ISSUE THREAD

**Issue by martinbu** [sebastienros/jint#1643]
Hi,
I am using Jint 3.0.0-beta-2052. I am testing the Js Proxy where I get exceptions if I access a property that exists on a clr object that the proxy was created on. If the property does not exist on the clr object, everything works as expected.
Also everything works fine if the proxy is created on a class created in JS instead of a clr class.

Example

```C#
class TestClass
{
     public string Name => "My Name is Test";
}

```

```C#
new Engine()
    .SetValue("T", new TestClass())
    .Execute("""
        const handler = {
            get(target, property, receiver) {

                if (!target[property]) {
                    return (...args) => "Not available";
                }

                // return target[property];
                return Reflect.get(target, property, receiver);
            }
        };

        const p = new Proxy(T, handler);
        const t = p.GetX();
        // const name = p.Name; // When commenting this in, an exception is thrown
    """);
```

Am I doing something wrong here or did I understand something wrong? Or isn't it supported to use a Proxy on a clr object?

**Comment by viruscamp** [comment]
It's the right behavior in [ECMAScript Language Specification](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-proxy-object-internal-methods-and-internal-slots-get-p-receiver).  
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/get#invariants   
>The value reported for a property must be the same as the value of the corresponding target object property if the target object property is a non-writable, non-configurable own data property.

All CLR Object Property is non-configurable, and the `Name` property is obviously non-writable in your code.
