### ISSUE TITLE
CLR Objects no longer extensible

### ISSUE THREAD

**Issue by jmorgannz** [sebastienros/jint#165]
It seems that CLR wrapped objects are no longer extensible ?
Adding properties to them is just silently ignored.

This was a great feature before.
I can see why maybe CLR types should be extensible: false,
but being able to extend object instances was useful.

Is this a new default by design?

**Comment by WinInsider** [comment]
May someone comment on the above... 

I have also run into this issue

`var engine = new Engine();
engine.SetValue("alert", new Action<object>(msg => Debug.WriteLine(msg)));
engine.SetValue("ClrClass1", TypeReference.CreateTypeReference(engine, typeof(ClrClass1)));
engine.Execute("var c = new ClrClass1(); c.dynamicJSProperty = 'aaaaaa'; alert(c.dynamicJSProperty);");
`

... alert will output empty string.

**Comment by sebastienros** [comment]
This is not supported OOB, but I assume if you created your own wrapper class it could be. Look at what `TypeReference.CreateTypeReference`, and create custom type that could handle properties that are not defined on the inner type.

**Comment by WinInsider** [comment]
@sebastienros thanks for reply... 

Am I wrong to think that "Construct" method in "TypeReference" class will be invoked whenever "new" operator of CLR object instantiated? 

In the above example would be for "new ClrClass1()"... if so, could one create wrapper object inside "Construct" method?

**Comment by sebastienros** [comment]
This is exactly what should be done, but maybe not with `TypeReference` more something like `ExtensibleTypeReference` that would return a different wrapper on `Construct` which would accept properties that don't exist on the wrapped CLR object.

**Comment by lahma** [comment]
In order to support extending CLR types from class declarations `class X extends MyClrType {}` we made the extension process possible for types registered via TypeReference.
