### ISSUE TITLE
Misleading behavior around namespace interop

### ISSUE THREAD

**Issue by jmorgannz** [sebastienros/jint#166]
In vanilla JS, typing an undefined string of properties will yield an undefined error:

```
  thisis.a.chain.of.properties.that.does.not.exist;
```

If the first identifier (thisis) is a namespace, in Jint this line would be silently ignored.

This can make diagnosing script issues a nightmare, as often it may just be a missing assembly, but Jint is allowing the 'namespace reference chain' anyway.

It also means that if the righthand most identifier on the object chain is supposed to be a method call, jint thinks you're trying to instantiate a generic.

I had a fiddle with a patch that adds a 'namespaceCache' to Jint.Engine, just like the typeCache.
This just caches the tree structure of namespaces in a navigable way, and is populated the first time Jint.Runtime.NamespaceReference falls through it's type lookup checks and is about to return a new instance of a NamespaceReference.

It also does the check at that point, and if the namespace it is about to create a ref for isn't in the cache, it throws a nice type error with which part of the object chain is undefined.

With my own experimenting I found this very useful, although there is obviously some penalty associated with scanning through all the types in the included assemblies to find all their namespaces.

Happy to supply patch if it would be of any use :)

**Comment by lahma** [comment]
I'm closing this in the hope of reopen if there's a PR/patch that would supply the desired outcome. All help appreciated!
