### ISSUE TITLE
No support for UInt8Array?

### ISSUE THREAD

**Issue by djMax** [sebastienros/jint#168]
Doesn't appear that the runtime has a UInt8Array. Any chance we can add that? I can write the C# equivalent easily enough, but not sure how to plug it in.

**Comment by sebastienros** [comment]
I assume it's an ECMAScript 6 feature. 

Is it time to start an ES6 branch ?
Or should we add ES6 features in master ...

**Comment by djMax** [comment]
It's possible - it's kind of confusing since it says "superseded by es6"

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays

But I know it works in Rhino/ClearScript/JavaScriptCore which don't (at least officially) support es6 yet?

**Comment by djMax** [comment]
Any chance you could write a sentence or two on how to expose a new type to the runtime? I figured I could use Array as a base, but I don't quite understand how Constructor, Instance, Prototype and the Engine play together. Links to existing related info also welcome.

**Comment by sebastienros** [comment]
The best info to understand is really to look at the ECMA 261 specification. Take any class, like Date, then look at the specs, and you will be able to map one by one the lines of code and the spec.

**Comment by tolstenko** [comment]
I fixed this problem changing the original js to use this typed array implementation: https://github.com/substack/typedarray

**Comment by dehghani-mehdi** [comment]
Any plan to fix this issue?

**Comment by lahma** [comment]
@dehghani-mehdi contributions are more than welcome, do you have any plans to implement this?

**Comment by dehghani-mehdi** [comment]
@lahma No, I have no plan to contribute to Jint, but I like to contribute, so I'll try to check the source code to see if I can help, no promise tho.

**Comment by lahma** [comment]
https://github.com/sebastienros/jint/pull/925
