### ISSUE TITLE
New NuGet package

### ISSUE THREAD

**Issue by ryanthompson0123** [sebastienros/jint#169]
I'm affected by issue https://github.com/sebastienros/jint/issues/128, which has been fixed. If anyone has time, I would really appreciate it if a new version of the NuGet package could be pushed to NuGet.org. :smile:

**Comment by sebastienros** [comment]
Will do this WE. If you don't see it please ping me, and harass me if necessary, please!

**Comment by karoberts** [comment]
Just a reminder that we're all anxiously awaiting a new nuget package

**Comment by postromantic** [comment]
@sebastienros yep, it's time for the new nuget version

**Comment by sebastienros** [comment]
Finally ... and built a script so that next time it's easier to do so. Sorry for the delay ...
https://www.nuget.org/packages/Jint/2.5.0
