### ISSUE TITLE
What are the threading expectations?

### ISSUE THREAD

**Issue by djMax** [sebastienros/jint#170]
I'm having some very strange behavior. Not totally able to pin it down yet, but I get an exception when trying to call a constructor on an object I got from a JsValue stored as a member on a class. It says it's null in the exception, but the debugger shows it having the expected value. It started happening when I hooked up some bluetooth "activities" to the engine, which I'm guessing are happening on other threads. What is the expectation for interacting with the engine from multiple threads?

**Comment by sebastienros** [comment]
An engine is not thread safe, and can only be used by a single thread.

**Comment by MaitreDede** [comment]
Hi :)

"used by a single thread" : if I ensure that the engine can be accessed by only one thread at a time, using ```lock``` for engine calls or executions, is it ok ?
