### ISSUE TITLE
Error when using 'select' to output an object

### ISSUE THREAD

**Issue by xxyuze** [sebastienros/jint#1702]
**Version used**

3.0.0-beta-2057

**Describe the bug**

```
let someArray = [ 2, 4 ];
let newArray = someArray.Select(m => ({a:m,b:m})).ToArray();
```
The error message "Object must implement IConvertible"

Select(x => x * x)  works

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by lahma** [comment]
Correct JavaScript syntax is:

```JavaScript
let someArray = [ 2, 4 ];
let newArray = someArray.map(m => ({a:m,b:m}));
```
