### ISSUE TITLE
Got "Unexpected token {" using Destructuring assignment

### ISSUE THREAD

**Issue by carlosjorger** [sebastienros/jint#1704]
**Version used**

2.11.58

**Describe the bug**

The following code isnt working
` var jsExpression = @"const person={name:'Carlos', age:26}; const {name}= person";
 var engine = new Engine().Execute(jsExpression)
`
Got "Unexpected token {"

**To Reproduce**

Ideally code samples or better yet, xUnit test against current `main`.

**Expected behavior**

**Additional context**

**Comment by lahma** [comment]
Please use v3 beta to get support for new ECMAScript features like destructuring.

**Comment by carlosjorger** [comment]
Thank you very much, but my boss wants an stable version sadly

**Comment by carlosjorger** [comment]
Thanks for this extra information and for your time lahma. I will convince my boss, I promise

**Comment by sebastienros** [comment]
We should rename it `3.0.0-nogenerators` 

![image](https://github.com/sebastienros/jint/assets/1165805/0b06bec2-574b-4e8e-87c0-889d01a6be53)
