### ISSUE TITLE
After using LINQ extension method, KeyValuePair properties stop working

### ISSUE THREAD

**Issue by ManuelHu** [sebastienros/jint#1742]
**Version used**

3.0.0-beta-2058

**Describe the bug**

I am not totally sure what the root cause of this bug might be, or if this description/the title is exhaustive.
After filtering a .NET Dictionary with a LINQ extension method, I cannot access some properties on the contents of the collections any more.

**To Reproduce**
Consider this simple test case that tries to get the last KeyValuePair from a dictionary, and tries to get its key:
```csharp
var engine = new Engine(opt =>
{
    opt.AddExtensionMethods(typeof(Enumerable)); // Allow LINQ extension methods.
});

var result = new List<string>();
void Debug(object? o) => result.Add($"{o?.GetType().FullName ?? "null"}: {o ?? "null"}");

engine.SetValue("debug", Debug);
engine.SetValue("dict", new Dictionary<string, string> { ["test"] = "val" });

engine.Execute("var t = dict.last(kvp => { debug(kvp); debug(kvp.key); return kvp.key != null; } );");
engine.Execute("debug(t); debug(t.key);");

```

In the end, the result list contains 4 entries (I removed some unneccessary type info):
```
System.Collections.Generic.KeyValuePair`2[[System.String, ...],[System.String, ...]]: [test, val]
System.String: test
System.Collections.Generic.KeyValuePair`2[[System.String, ...],[System.String, ...]]: [test, val]
null: null
```

**Expected behavior**

So, we have two times a `KeyValuePair`, but accessing the key after filtering does not work -- I think the last line should also be `System.String: test`.

**Comment by lahma** [comment]
Thanks for the detailed problem report, should now be fixed in `main`.
