### ISSUE TITLE
Unexpected memory overflow/leak

### ISSUE THREAD

**Issue by JBBianchi** [sebastienros/jint#1772]
**Version used**

3.0
(the same concept worked with 3.0.0-beta-2049 without raising this issue)

**Describe the bug**

When setting an iterable variable in the engine, we changed the prototype of the said variable to the array prototype in order to access methods like `.map()`, `.filter()`, ... However, since the migration from `3.0.0-beta-2049` to `3.0`, the same methodology have a huge impact on the memory for unknown reasons (to us at least). 

As an alternative to illustrate a normal memory usage, we made a test case using `Array.from` instead.

**To Reproduce**
See attachment, the code was too big because of the sample data payload.
[array_bug_test.txt](https://github.com/sebastienros/jint/files/14166317/array_bug_test.txt)

**Expected behavior**

The expression to be evaluated without having to raise the memory limit.

**Additional context**

Related to https://github.com/sebastienros/jint/discussions/1733 and https://github.com/sebastienros/jint/issues/1030#issuecomment-1919747531

**Comment by lahma** [comment]
What is huge impact? How much it was before and how much is it now?

**Comment by JBBianchi** [comment]
More than seven times. Before, for the same dataset (or with `Array.from()`), the 1Mb limit was not reached. With 3.0, the limit needs to be raised to around 7Mb.
