### ISSUE TITLE
Unable to sort because the IComparer.Compare() method returns inconsistent results on Typograf lib

### ISSUE THREAD

**Issue by nktdrkhv** [sebastienros/jint#1789]
**3.0.0 (same problem with 2.11.58)**

**Description**

It's getting
`System.ArgumentException: Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results.`
while trying to invoke a test funtion. 
[err.txt](https://github.com/sebastienros/jint/files/14393265/err.txt)

**To Reproduce**

Create a regular console app. *Typograf* is a Typescript lib which I got with `npm install typograf` and then copied `typograg.js` from `node-modules/typograf/dist/typograf.js`

```csharp
using Jint;
var engine = new Engine();
engine.Execute(File.ReadAllText("typograf.js"));
engine.Execute("""
function test() {
    var tp = new Typograf({locale: ['ru', 'en-US']});
    return tp.execute('"Привет мир - привет!..."');
}
""");
Console.WriteLine(engine.Invoke("test"));
```

**Expected behavior**

Printing: «Привет мир — привет!..»

**Additional context**

I tried different ways to import and use a module but result is the same 
With JSEngineSwitcher too

**Comment by scgm0** [comment]
Looks like the same problem as #1028

**Comment by lahma** [comment]
I'll close this as there's existing issue and we need to wait for a PR.

**Comment by lahma** [comment]
NiL.JS is a wonderful project, it's very performant and handles common flow very well, deviates sometimes from the JS spec a bit though.
