### ISSUE TITLE
Readonly engine

### ISSUE THREAD

**Issue by SebastianStehle** [sebastienros/jint#1816]
**Is your feature request related to a problem? Please describe.**

I have a use case, where it makes sense to keep everything readonly. So every dictionary and object I pass in should not be mutable.

**Describe the solution you'd like**

Just a flag, that makes everything immutable.

**Describe alternatives you've considered**

Having custom wrapper classes for all context values.

**Additional context**

**Comment by SebastianStehle** [comment]
I had a look to the code and it seems that this is actually the relevant method: https://github.com/sebastienros/jint/blob/23a2a2587750a98cd55e4697e4da8270bcf460db/Jint/Runtime/Interop/TypeResolver.cs#L51

But it is internal and all relevant types are internal as well.

This could be implemented by making a ReadonlyReflectionAccessor that wraps the actual accessor or something like that. Perhaps with a similar delegate like the member filter.

I can probably provide a PR for that.

**Comment by SebastianStehle** [comment]
I was not aware that there is `AllowClrWrite`.

**Comment by lahma** [comment]
So if this is only about interop scenarios, is the `AllowClrWrite` enough to fill the needs or is something else missing too perhaps?

**Comment by SebastianStehle** [comment]
No, for me it is perfectly fine :)

**Comment by lahma** [comment]
Cool, thanks for raising the issue and investigating!
