### ISSUE TITLE
HowTo: function to string

### ISSUE THREAD

**Issue by devmathews** [sebastienros/jint#188]
Is it possible to get the body of a function in Jint ? I have tried the toString() method but to no avail:

var x = function(){return "Something"}
x.toString();

Gives me: 
function() { ... }

Instead of:

function(){return "Something"}

**Comment by sebastienros** [comment]
There is no such thing right now. You can implement a custom visitor to render a `Program` instance to a string though. Would be a cool addition to Jint.

**Comment by asdfgasdfsafgsdfa** [comment]
I'd need function tostring as well :S 
I guess I'll write that visitor code then...

**Comment by sebastienros** [comment]
As long as you can make it a nuget package, i.e. it doesn't need any changes in Jint, then I don't want to take it into the main project. Main reason is that I can't be accountable for the bugs and missing features if there are any, or to maintain it when Jint adds new features. Does it make sense?

**Comment by deepakmlvd** [comment]
Is this feature now available?

**Comment by doronguttman** [comment]
@asdfgasdfsafgsdfa Can you share your implementation?

**Comment by MohamedSenouse** [comment]
Hello @scarletquasar,

Unfortunately, the code breaks after v4 when using the Cornomia library. Could you please check if there’s a workaround for this issue?

**Comment by lahma** [comment]
[I've created an extension point to configuration](https://github.com/sebastienros/jint/pull/2043) that one can use to resolve custom function code. Sample shows NuGet package `Acornima.Extras` usage and brute-force string substring alternatives.
