### ISSUE TITLE
How To Pass Unintialised Class

### ISSUE THREAD

**Issue by PijusPaulikas** [sebastienros/jint#189]
I have a class ConsoleJS;

engine.SetValue("Console", typeof(ConsoleJs));
engine.Execute ("var x = new Console()");

When I run the code I get Object can't be used as constructor error? Is it possible to do it?

**Comment by sebastienros** [comment]
Something like:

```
var Console = YourNamespace.Console;
var x = new Console();
```

And you can import your `YourNamespace`, there is an example in the readme.
