### ISSUE TITLE
Line number and column information in exceptions

### ISSUE THREAD

**Issue by jkut** [sebastienros/jint#190]
See #21: This issue has not yet been addresse fully.

The following code does not produce an exception instance that supports retrieval of the source code location:

``` javascript
var x = 3;
asdasd;
```

In that case a JavaScriptException is thrown which does not provide the source code information.

Update: It seems that the parser indeed provides information about the error position, but the execution does not.

**Comment by da3dsoul** [comment]
Any news on this? I would like to provide a simple ide implementation in a text area that highlights errors. I would need at least a line number and a message to give the user for such a thing.

**Comment by wewake4** [comment]
Any update on this ?
