### ISSUE TITLE
Array manipulation performance is awful

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/jint#194]
I have tracked down the performance issues to `Object.DefineOwnProperty`. It seems that all the code using `Nullable` values is making things slower than expected.

Just place the scripts from there: https://gist.github.com/rushfrisby/5491f25a82a979c5b15e with just the `unshift` calls and you will see. It's like 100 times slower than Jurassic or IronJs.

**Comment by fvaneijk** [comment]
ran the following in the benchmark app with iterations =1 and reuseEngine = true

var ret = [], tmp, num = 500, i = 1024;
ret = [];
for ( var j3 = 0; j3 < i; j3++ ) {
	ret.unshift(j3);

results are:

IronJs: 1 iterations in 52 ms
Jint: 1 iterations in 4220 ms
Jurassic: 1 iterations in 7 ms

Is this consistent with your results?

**Comment by sebastienros** [comment]
Right. I have seen that most of the time is spent in ObjectInstace.DefineOwnProperty, but it's purely following the spec. There might be some optimizations to do especially for ArrayInstance as the property descriptors are usually pretty standard and don't require custom flags (i.e., writable, enumerable, configurable).

I have also tried to optimize the index conversions from string to uint, but it didn't help much, it was measurable but not to the extent that it made sense on the overall perf. 

It feels like there is an obvious ugly mistake in the code that is making it very slow, and once we find it everything will be much faster.I will try to read it step by step with the spec, maybe I made a mistake.

**Comment by sebastienros** [comment]
I have already made some huge performance improvement with a simple optimization in DefineOwnProperty, which is also used extensively during Array manipulation. It halved a perf test.

And I also have found some nice improvements to do in ArrayInstance, first by optimizing IsArrayIndex, and then by defining custom implementation of property manipulation for numeric indexes, by using a standard array (dense array) and falling back to the ObjectInstance for named properties. Other engines also use distinct data structures for dense vs. sparse arrays.

**Comment by fvaneijk** [comment]
This is looking much better.  I suppose the motivation for these improvements is partially from:

http://rushfrisby.com/which-net-javascript-engine-is-the-fastest/

I ran the benchmark for both perfbase and trunk with a release and debug build.  When comparing to Jurassic and IronJs the release numbers only make sense.

For comparison here are some numbers:

debug build:
  perfbase branch:
  IronJs: 1 iterations in 1169 ms
  Jint: 1 iterations in 6652 ms
  Jurassic: 1 iterations in 235 ms

  trunk:
  IronJs: 1 iterations in 1146 ms
  Jint: 1 iterations in 24693 ms
  Jurassic: 1 iterations in 236 ms

release build:
  perfbase branch:
  IronJs: 1 iterations in 1153 ms
  Jint: 1 iterations in 3626 ms
  Jurassic: 1 iterations in 231 ms

  trunk:
  IronJs: 1 iterations in 1159 ms
  Jint: 1 iterations in 14082 ms
  Jurassic: 1 iterations in 237 ms

**Comment by sebastienros** [comment]
You can ignore Debug with these tests. I still need to improve the Arrays directly, have only improved DefineOwnProperty so far, so more benefit is expected.

**Comment by fvaneijk** [comment]
It seems you removed the following code around line 151 in ObjectInstance.cs on the perfbase branch.  This has a significant impact on performance (around 4x).  Was this intentional?

                if (ownDesc != PropertyDescriptor.Undefined)
                {
                  ownDesc.Value = value;
                  return;
                }

with this code inserted Test_10_6 ArgumentsIMapToActualParameter fails as well as some other ECMA tests.

Also, have you considered using a pool to improve allocation performance for PropertyDescriptor objects.  The following may help.

https://msdn.microsoft.com/en-us/library/ff458671(v=vs.110).aspx

**Comment by fvaneijk** [comment]
I implemented a simple pool for the PropertyDescriptors and it does not change performance significantly.  So I would suggest we don't go down that path.  I have noticed there is a pretty significant difference in performance between .net 4 and 4.5 4.5 seems about 30-40% better for the array benchmark.

**Comment by sebastienros** [comment]
I am still working on having all unit tests to pass with the current changes ...

**Comment by sebastienros** [comment]
@fvaneijk Can you elaborate on the 4.5 difference? I can't repro, can you provide your steps?
I will also try to restore the ownDesc change to support it when possible.

**Comment by fvaneijk** [comment]
Our software uses Jint as it's JavaScript script engine and has to run against the 4.0 framework.  I tried the array benchmark with it (i.e. 4.0) and also with the trunk version on github (i.e 4.5).  Our code is essentially in sync with the github trunk.  This is where I noticed the difference in performance.  Not sure if it makes a difference but we do not build our Jint as a PCL and we have added some minor customization's to the engine to support what we call external tags (i.e. JavaScript variables that obtain their values from application specific objects ).  I would not expect these implementation differences to account for the difference in performance between 4.0 and 4.5.  In addition the IronJs and Jurrasic tests show the same performance difference.  I will re-run the tests and try to post some numbers in the next day or so.

**Comment by fvaneijk** [comment]
Well, I stand corrected looks like there is no appreciable difference between 4.0 and 4.5.  But there is a difference between my version and the github trunk...  I'll have to look into that.

running with .net 4.0 (trunk release build)
IronJs: 1 iterations in 963 ms
Jint: 1 iterations in 7905 ms
Jurassic: 1 iterations in 129 ms

running with .net 4.5 (trunk release build)
IronJs: 1 iterations in 967 ms
Jint: 1 iterations in 7788 ms
Jurassic: 1 iterations in 129 ms

running with .net 4.0 (my release build)
IronJs: 1 iterations in 1642 ms
Jint: 1 iterations in 9182 ms
Jurassic: 1 iterations in 248 ms

running with .net 4.5 (my release build)
IronJs: 1 iterations in 1638 ms
Jint: 1 iterations in 9222 ms
Jurassic: 1 iterations in 247 ms

**Comment by fvaneijk** [comment]
Must have been something out of date with my version of the benchmark app.  I copied your version to mine and now I get very similar numbers...

IronJs: 1 iterations in 964 ms
Jint: 1 iterations in 8050 ms
Jurassic: 1 iterations in 128 ms

**Comment by fvaneijk** [comment]
To keep a record of the perf numbers here are the latest form a release build on the perftest branch.  There are now only 2 ECMA tests failing having to do with function arguments.

IronJs: 1 iterations in 1103 ms
Jint: 1 iterations in 2731 ms
Jurassic: 1 iterations in 188 ms

release perfbase branch: previous results on Jun 25
IronJs: 1 iterations in 1153 ms
Jint: 1 iterations in 3626 ms
Jurassic: 1 iterations in 231 ms

**Comment by sebastienros** [comment]
I am done with this first step, property access has been optimized and the gains are already great, pushed in master. My next step is to work specifically on the Array instances. I already have some easy picks to apply. When it's done I'll do a new release.

**Comment by fvaneijk** [comment]
Nice work...

Here are the numbers from the latest master release build:
IronJs: 1 iterations in 991 ms
Jint: 1 iterations in 6909 ms
Jurassic: 1 iterations in 131 ms

and the previous numbers from the master:
IronJs: 1 iterations in 1159 ms
Jint: 1 iterations in 14082 ms
Jurassic: 1 iterations in 237 ms

**Comment by fvaneijk** [comment]
With array performance updates on the perf/arrays branch:

Note this is not final as some tests are not passing.

IronJs: 1 iterations in 958 ms
Jint: 1 iterations in 1158 ms
Jurassic: 1 iterations in 131 ms

**Comment by fatalerrorx** [comment]
Awesome performance gains.

**Comment by sebastienros** [comment]
I have pushed the refactoring on ArrayInstance. There are two more things that can be done to optimize the perf: 
- Use a standard .NET Array for dense arrays, and switch to a custom data structure sparse ones. I assume the current implementation can be used for sparse one.
- Optimize the ArrayPrototype functions, like shift, slice, ... They are literally the specification, and could really be optimized with the same result. Their optimization is really dependent on the data structure though, so the previous work item might have an impact on their optimizations.

**Comment by fvaneijk** [comment]
Sweet, I'll post new perf numbers soon.

**Comment by fvaneijk** [comment]
Here are new perf numbers from current code on master:
IronJs: 1 iterations in 1057 ms
Jint: 1 iterations in 3737 ms
Jurassic: 1 iterations in 121 ms

**Comment by Happypig375** [comment]
Is this solved? Why is this still open?

**Comment by Happypig375** [comment]
Is this solved? Why is this still open?

**Comment by sebastienros** [comment]
I think there is a branch that is still around where I tried to improve it, but without much success. As explained in a previous comment, the next step is to use an hybrid array approach where we could switch to a sparse array. 

But first we need new numbers, a lot has changed since these ones. A baseline would be good to improve. And any change that breaks a single unit test is useless.

**Comment by lahma** [comment]
I've done first analysis [here](https://github.com/sebastienros/jint/pull/448) with some promising performance improvements by reducing memory allocations.

**Comment by lahma** [comment]
For those interested, 3.x beta offers some improvements over 2.x line, [see detailed results](https://github.com/sebastienros/jint/issues/451#issuecomment-356920873). I think this issue could be closed and maybe have more specific one(s) if needed, like for unshift performance.
