### ISSUE TITLE
Discrepancies in Array Sorting Between ExpandoObject and Native JavaScript Objects

### ISSUE THREAD

**Issue by sfmskywalker** [sebastienros/jint#1942]
### Description

My application needs to process JSON data received from external sources. This JSON data is initially deserialized into `ExpandoObject` instances in C#. I am observing an issue where arrays within these `ExpandoObject` instances do not seem to behave the same way as arrays within native JavaScript objects when using JavaScript array methods like `sort()`.

### Problem Statement

When a JavaScript array method such as `sort()` is invoked on an array contained within an `ExpandoObject`, the array is sorted, but the changes do not persist back into the `ExpandoObject`. This issue does not occur when using native JavaScript objects or objects converted to `JsObject`.

### My Approach

To resolve this, I am wondering if I should be converting `ExpandoObjects` (representing parsed JSON values in my app) to convert into a native JavaScript object (`JsObject`) by creating a helper method that recursively converts `ExpandoObject` and its nested properties to `Jint.Native.ObjectInstance`. This conversion seems to address the issue, allowing the array sorting to work as expected.

I've also tried to work with typed objects (e.g. `MyModel`, a C# class I wrote to test with) and wrap them using `JsValue.FromObjectWithType()`, but upon returning that model from the engine, its array property remains to be the original value. 

### Unit Tests

Below are the unit tests that I've used to explore this issue:

```csharp
using System.Dynamic;
using Jint.Native;
using Jint.Tests.Runtime.TestClasses;

namespace Jint.Tests.Runtime;

public class InteropTestsWithArraysAndObjectTests
{
    private readonly Engine _engine;

    public InteropTestsWithArraysAndObjectTests()
    {
        _engine = new Engine()
            .SetValue("log", new Action<object>(Console.WriteLine))
            .SetValue("assert", new Action<bool>(Assert.True))
            .SetValue("equal", new Action<object, object>(Assert.Equal));
    }

    [Fact]
    public void ExpandoObjectWithArrayCanSort()
    {
        dynamic myModel = new ExpandoObject();
        myModel.items = new[] { 1d, 8d, 3d };
        _engine.SetValue("myModel", myModel);
        var result = _engine.Evaluate("myModel.items.sort((a, b) => a - b); return myModel;");
        myModel = result.ToObject()!;
        var items = (double[]) myModel.items;
        
        // Fails.
        Assert.Equal<IEnumerable<double>>([1d, 3d, 8d], items);
    }
    
    [Fact]
    public void ConvertedExpandoObjectWithArrayCanSort()
    {
        dynamic myModel = new ExpandoObject();
        myModel.items = new[] { 1d, 8d, 3d };
        var convertedModel = ConverterHelper.ConvertToJsObject(_engine, myModel);
        _engine.SetValue("myModel", convertedModel);
        var result = _engine.Evaluate("myModel.items.sort((a, b) => a - b); return myModel;");
        myModel = ConverterHelper.ConvertJsValueToObject(result)!;
        var items = ((IEnumerable<object>) myModel.items).Cast<double>().ToArray();
        
        // Succeeds.
        Assert.Equal<IEnumerable<double>>([1d, 3d, 8d], items);
    }

    [Fact]
    public void TypedObjectWithArrayCanSort()
    {
        var myModel = new MyModel { Items = [1d, 8d, 3d] };
        _engine.SetValue("myModel", myModel);
        var result = _engine.Evaluate("myModel.Items.sort((a, b) => a - b); return myModel;");
        myModel = (MyModel) result.ToObject()!;
        var items = myModel.Items;
        
        // Fails.
        Assert.Equal<IEnumerable<double>>([1d, 3d, 8d], items);
    }
    
    [Fact]
    public void WrappedTypedObjectWithArrayCanSort()
    {
        var myModel = new MyModel { Items = [1d, 8d, 3d] };
        var wrappedModel = JsValue.FromObjectWithType(_engine, myModel, myModel.GetType());
        _engine.SetValue("myModel", wrappedModel);
        var result = _engine.Evaluate("myModel.Items.sort((a, b) => a - b); return myModel;");
        myModel = (MyModel)result.ToObject()!;
        var items = myModel.Items;
        
        // Fails.
        Assert.Equal<IEnumerable<double>>([1d, 3d, 8d], items);
    }
    
    [Fact]
    public void JsObjectWithArrayCanSort()
    {
        var myModel = new JsObject(_engine);
        myModel.Set("items", new JsArray(_engine, [
            JsValue.FromObjectWithType(_engine, 1d, typeof(double)),
            JsValue.FromObjectWithType(_engine, 8d, typeof(double)),
            JsValue.FromObjectWithType(_engine, 3d, typeof(double))
        ]));
        _engine.SetValue("myModel", myModel);
        var result = _engine.Evaluate("myModel.items.sort((a, b) => a - b); return myModel;");
        var dynamicObject = (dynamic)result.ToObject()!;
        var items = ((object[]) dynamicObject.items).Cast<double>();
        
        // Succeeds
        Assert.Equal<IEnumerable<double>>([1d, 3d, 8d], items);
    }

    [Fact]
    public void NativeJavaScriptObjectWithArrayCanSort()
    {
        var result = _engine.Evaluate("const myModel = { items: [1, 8, 3] }; myModel.items.sort((a, b) => a - b); return myModel;");
        var myModel = (dynamic) result.ToObject()!;
        var items = ((object[]) myModel.items).Cast<double>().ToArray();

        // Succeeds
        Assert.Equal<IEnumerable<double>>([1d, 3d, 8d], items);
    }
}
```

Below is the `ConverterHelper` utility class, for reference:

```csharp
using System.Dynamic;
using Jint.Native;
using Jint.Native.Object;
using Jint.Runtime.Descriptors;

namespace Jint.Tests.Runtime.TestClasses;

public class ConverterHelper
{
    public static ObjectInstance ConvertToJsObject(Engine engine, IDictionary<string, object> expando)
    {
        var jsObject = new ObjectInstance(engine);

        foreach (var kvp in expando)
        {
            var value = kvp.Value;
            var jsValue = ConvertToJsValue(engine, value);
            var propertyDescriptor = new PropertyDescriptor(jsValue, true, true, true);
            jsObject.SetProperty(kvp.Key, propertyDescriptor);
        }

        return jsObject;
    }
    
    private static ExpandoObject ConvertToExpandoObject(ObjectInstance jsObject)
    {
        var expando = new ExpandoObject();
        IDictionary<string, object> dict = expando;

        foreach (var property in jsObject.GetOwnProperties())
        {
            var key = property.Key.AsString();
            var value = jsObject.Get(key);

            dict[key] = ConvertJsValueToObject(value);
        }

        return expando;
    }

    public static object ConvertJsValueToObject(JsValue value)
    {
        if (value.IsObject())
        {
            var jsObj = value.AsObject();
            if (jsObj.IsArray())
            {
                var jsArray = jsObj.AsArray();
                var list = new List<object>();

                for (uint i = 0; i < jsArray.Length; i++)
                {
                    list.Add(ConvertJsValueToObject(jsArray.Get(i)));
                }

                return list;
            }

            return ConvertToExpandoObject(jsObj);
        }

        if (value.IsString())
            return value.AsString();
        if (value.IsBoolean())
            return value.AsBoolean();
        if (value.IsNumber())
            return value.AsNumber();
        if (value.IsNull() || value.IsUndefined())
            return null;
        return value.ToObject();
    }

    private static JsValue ConvertToJsValue(Engine engine, object value)
    {
        switch (value)
        {
            case IDictionary<string, object> dict:
                return ConvertToJsObject(engine, dict);
            case IEnumerable<object> list:
                {
                    var l = list.ToList();
                    var jsArray = engine.Realm.Intrinsics.Array.Construct(l.Count);
                    var index = 0;
                    foreach (var item in l)
                    {
                        jsArray.Set(index++, ConvertToJsValue(engine, item), true);
                    }

                    return jsArray;
                }
            case string str:
                return JsValue.FromObject(engine, str);
            case int:
            case double:
            case float:
            case decimal:
                return JsValue.FromObject(engine, Convert.ToDouble(value));
            case bool b:
                return JsValue.FromObject(engine, b);
            default:
                return JsValue.FromObject(engine, value);
        }
    }
}
```

### Observations

- **`ExpandoObject`**: When used directly, sorting arrays fails as changes do not persist.
- **Converted `ExpandoObject`**: Sorting arrays succeeds when `ExpandoObject` is converted to a native `ObjectInstance`.
- **Typed Objects**: When wrapped using `JsValue.FromObjectWithType`, array sorting fails (as in, the sorted array value is not assigned to the object property).
- **Native `JsObject`**: Sorting arrays succeeds, indicating that this issue seems to be related to what sort of .NET objects we provide to Jint.

### Request

Please provide insights or guidance on whether this is expected behavior. If not, is there a recommended way to ensure that .NET objects, including arrays, are fully compatible with JavaScript array methods like `sort()` when using Jint?

Thank you for your support!

**Comment by sfmskywalker** [comment]
I wonder if perhaps I should implement an `ExpandoObjectConverter : IObjectConverter` to automatically convert `ExpandoObject` objects to `JsObject` (using my `ConvertToJsObject` helper method or perhaps using an existing approach that I haven't encountered yet). I think it might make sense 🤔

**Comment by lahma** [comment]
Thanks for the detailed problem description. If I think this is what it is then.. the problem is that the automatic wrapping of native arrays from `double[]` => `JsArray` happens and pointer to old array is not used as array might need to grow and thus `JsArray` has a copy of the original array which is now independent. 

So executing `var copy = myModel.Items; copy.sort((a, b) => a - b); myModel.Items = copy; return myModel;` will probably have the intended effect as it will create new `JsArray`, sort it and then convert it back to target object.

I'm not sure if there's some idiomatic way to get this magically working as there's the case of `var copy = myModel.items; copy.push(123); copy.sort()` - this would not work against original data member as it's fixed size array and push cannot happen.

**Comment by sfmskywalker** [comment]
Thanks for the super speedy response! Yes, you are spot on; the issue is as you described with the copy of the array.
Which also means that you're right about using a List instead of an Array, which is proven by the following passing test:

```csharp
[Fact]
    public void ExpandoObjectWithListCanSort()
    {
        dynamic myModel = new ExpandoObject();
        
        // List instead of array works!
        myModel.items = new List<double> { 1d, 8d, 3d };
        _engine.SetValue("myModel", myModel);
        var result = _engine.Evaluate("myModel.items.sort((a, b) => a - b); return myModel;");
        myModel = result.ToObject()!;
        var items = ((List<double>) myModel.items).ToArray();

        // Succeeds.
        Assert.Equal<IEnumerable<double>>([1d, 3d, 8d], items);
    }
```

In this test, the sorted array is reflected back in the model that was passed in.

Now that the reason is clear to me, I will investigate the ramifications, if any, of producing ExpandoObjects where list-like values are represented as Lists instead of Arrays.

Thank you for your insights, that was immensely helpful.

**Comment by sfmskywalker** [comment]
> This part in interop/automatic is tricky and I don't know if it works logically now or will it never...

I completely agree. Given that the JavaScript environment and the .NET environment have inherently different characteristics and behaviors, it might be more practical to embrace these differences rather than attempting to unify them. This implies that when JavaScript object behavior is required, it makes sense to use a JavaScript object directly.

Currently, I’m considering one of two approaches:

1. **Convert ExpandoObjects to JsObjects**: I could implement a custom `IObjectConverter` to convert my C# `ExpandoObjects`, which represent parsed JSON data, into `JsObjects`. This approach allows my users to interact with these objects as if they were native JavaScript objects, preserving the expected JavaScript behavior.

2. **Use Lists for List-like Properties**: Alternatively, I could modify the deserialization process so that JSON is deserialized into `ExpandoObjects` where list-like properties are constructed as `List<T>` instead of arrays. This avoids the need for a custom `IObjectConverter` while still providing predictable behavior when manipulating these objects in JavaScript.

I’ll be doing further experiments to determine which approach is more practical in my scenario.

Thank you 🙏🏻
