### ISSUE TITLE
Cannot install Nuget - Error NU118

### ISSUE THREAD

**Issue by MikaelStalvik** [sebastienros/jint#1943]
**Version used**
4.0.1

With which version did you encounter this behavior. Please check against 3.x beta if you haven't yet, it might have the fix already.
The same issue applies to 3.x versions also.

**Describe the bug**
When trying to install the Nuget, Visual Studio 2022 reports the following error:
NU1108 Cycle detected.
              jint -> Jint (>= 4.0.1)
Package restore failed. Rolling back package changes for 'jint'.

Tested with two different machines running on Visual Studio 2022, 17.10.6 on Windows 11.

**To Reproduce**
Try to install the Nuget via Manage Nuget packages.

**Expected behavior**
The package should install properly.

**Additional context**
Tested on a clean Console application using .NET8.

**Comment by sebastienros** [comment]
@MikaelStalvik worked for me. Created a new console app targeting net8.0

![image](https://github.com/user-attachments/assets/98483fc7-87da-4416-98c4-e957b740389e)

Can you try to clear your nuget cache?

**Comment by MikaelStalvik** [comment]
Thanks for your comment. I flushed the Nuget cache and did a repair on VS2022 via the installer and that seems to have helped!
