### ISSUE TITLE
Exporting a default function without name isn't possible

### ISSUE THREAD

**Issue by viceice** [sebastienros/jint#1951]
**Version used**

4.0.1

**Describe the bug**

Can't get the default export of a module if it's a function without a name.

**To Reproduce**

```csharp
var engine = new Engine();
engine.Modules.Add("a", "export default function () { return 1; }"
engine.Modules.Add("b", "export default function main () { return 1; }"
engine.Modules.Import("a").Get("default"); //-> undefined
engine.Modules.Import("b").Get("default")(); //-> 1

```

**Expected behavior**

Both test cases above should work.

**Additional context**

none

**Comment by lahma** [comment]
Would you like to help out with a PR?

**Comment by viceice** [comment]
> Would you like to help out with a PR?

Sure, but i don't know where to start for finding the issue. It seems the parser reads successfully and there is the `default` in the exports list.

**Comment by lahma** [comment]
That's how it usually goes, a lot of debugging 😉

**Comment by viceice** [comment]
This is the environment of module a
![image](https://github.com/user-attachments/assets/5c6d18b6-b16d-469c-9381-0c2a93503efe)

And this the env of module b
![image](https://github.com/user-attachments/assets/eb30e5ec-432d-4c07-b542-fc4c3f4edc8c)

**Comment by viceice** [comment]
this Execute overwrites the `*default*` value inside the env.
https://github.com/sebastienros/jint/blob/1febd1be4f2e0799b8fdd83a0581fe3fff96dec4/Jint/Runtime/Modules/SourceTextModule.cs#L338-L340

the other entry isn't there because the funciton has no name.

**Comment by viceice** [comment]
https://github.com/sebastienros/jint/blob/1febd1be4f2e0799b8fdd83a0581fe3fff96dec4/Jint/Runtime/Interpreter/Statements/JintExportDefaultDeclaration.cs#L58

this code doesn't return the function instance, it returns empty which is converted to undefined

**Comment by viceice** [comment]
So this code sets the default export to undefined
https://github.com/sebastienros/jint/blob/1febd1be4f2e0799b8fdd83a0581fe3fff96dec4/Jint/Runtime/Interpreter/Statements/JintExportDefaultDeclaration.cs#L69-L75

**Comment by viceice** [comment]
https://github.com/sebastienros/jint/blob/1febd1be4f2e0799b8fdd83a0581fe3fff96dec4/Jint/Runtime/Interpreter/Statements/JintFunctionDeclarationStatement.cs#L13

This is maybe wrong?

**Comment by viceice** [comment]
@lahma I found a solution, but I'm nor sure if it's the right one

**Comment by viceice** [comment]
can you please release a fixed version? I'm currently stuck on that issue because almost all our scripts are using this pattern. 🙏

**Comment by lahma** [comment]
@viceice hard to argue with this request as you did all the legwork, you should see a new 4.0.2 release on NuGet now 🚀

**Comment by viceice** [comment]
thanks 🙏❤️
