### ISSUE TITLE
Incorrect line number in stacktrace for undefined function in module mode

### ISSUE THREAD

**Issue by trannamtrung1st** [sebastienros/jint#1967]
## Description:
When running in module mode, if a function is called that is undefined, the stacktrace reports an incorrect line number. It shows the line number of the next line instead of the line where the function is called.

## Steps to reproduce:
1. Create a JavaScript file with the following content:

```javascript
function main() {
  const a = test(1, 
    2, 3, {});
}
main();
```

2. Run this file in module mode using Jint.

3. Observe the stacktrace when it fails due to `test` being undefined.

## Expected behavior:
The stacktrace should show line 2 (where `const a = test(1,` is located) as the source of the error.

## Actual behavior:
The stacktrace incorrectly shows line 3 (where `2, 3, {});` is located) as the source of the error.

## Additional information:
- This issue seems to occur specifically when the function call spans multiple lines.
- The problem is observed in module mode. It may or may not occur in other execution modes.

## Environment:
- Jint version: 4.0.2

**Comment by lahma** [comment]
Can you submit a PR to propose a fix?

**Comment by trannamtrung1st** [comment]
I will try when I have time next week. 
I suspect that this issue is related to the parsing or statement tracking, so let's wait if there's anybody else who is more familiar with this process to give an idea.

**Comment by lahma** [comment]
Any updates?

**Comment by trannamtrung1st** [comment]
Sorry, I've been busy recently. It won't be anytime soon I think.

**Comment by lahma** [comment]
It's all OK,  I'll close the issue later on  if it's not that important.

**Comment by trannamtrung1st** [comment]
Sure, I guess if my company project's customers complain, I will be assigned to fix this lol.

**Comment by lahma** [comment]
Let's close this one and see if funding gets acquired.
