### ISSUE TITLE
Interop having difficulty finding properties in derived types

### ISSUE THREAD

**Issue by mspertus** [sebastienros/jint#1968]
**Version used**

4.0.1

**Describe the bug**
Sometimes we fail to find properties of a CLR object because we look in a base class as described in the unit test below, which gives an example of where we fail to access a `Lion` property of an `Animal` and another example of where it succeeds. Note that the same unit tests works in 2.11 (if you replace `Evaluate(...)` with `Execute(...).GetCompletionValue()` for compatibility with Jint 2.11).

Please observe that this is hard to work around since Javascript lacks a "downcasting" operator like C#  does.

**To Reproduce**
In the unit tests below, the first one fails while the second one succeeds even though both access the same property of a C# expression of static type `Animal` and runtime type `Lion`

```c#
    public class Animal
    {
        public virtual string name { get; set; } = "animal";
    }
    public class Elephant : Animal
    {
        public override string name { get; set; } = "elephant";
        public int earSize = 5;
    }
    public class Lion : Animal
    {
        public override string name { get; set; } = "lion";
        public int maneLength = 10;
    }
    public class Zoo
    {
        public Animal king { get => (new Animal[] { new Lion() })[0]; }
        public Animal[] animals { get => new Animal[] { new Lion(), new Elephant() }; }
    }

    [Fact]
    public void CanFindDerivedPropertiesFail() // Fails in 4.01 but success in 2.11
    {
        var engine = new Engine();
        engine.SetValue("zoo", new Zoo());
        var kingManeLength = engine.Evaluate("zoo.King.maneLength");
        Assert.Equal(10, kingManeLength.AsNumber());
    }

    [Fact]
    public void CanFindDerivedPropertiesSucceed() // Similar case that continues to succeed
    {
        var engine = new Engine();
        engine.SetValue("zoo", new Zoo());
        var lionManeLength = engine.Evaluate("zoo.animals[0].maneLength");
        Assert.Equal(10, lionManeLength.AsNumber());
    }
```

**Expected behavior**

Both tests succeed

**Additional context**

**Comment by mspertus** [comment]
Seems related to https://github.com/sebastienros/jint/pull/1613.  While the explicit interfaces introduced by that change are intentional, it doesn't seem right that an `Animal` and an `Animal[]` expose different methods on the objects.

Like the [last comment](https://github.com/sebastienros/jint/pull/1613#issuecomment-1751934115) on that PR, my code depends on the old behavior

> I do think the old behaviour should also be useful for a dynamic language like JS. (A good chunk of my codebase depends on it too)

While that comment suggests an option for turning off explicit types, it would be nice to have a solution that resolves [1611](https://github.com/sebastienros/jint/issues/1611) and makes it so that the and `Animal[]`

**Comment by mspertus** [comment]
I have submitted a PR that addresses this issue while continuing to pass all of the InteropTests and the InteropExplicitType tests. It should also satisfy the requests of the above referenced  [comment](https://github.com/sebastienros/jint/pull/1613#issuecomment-1751934115) without the need for engine options.

**Comment by mspertus** [comment]
Thanks, Marko!

**Comment by lahma** [comment]
You are most welcome, your both changes submitted via PRs are now available on NuGet 🚀
