### ISSUE TITLE
Differences on how Array.slice() behaves between .NET6 and .NET8

### ISSUE THREAD

**Issue by martin-shields-sage** [sebastienros/jint#1972]
**Version used**
4.0.3

**Describe the bug**
We are in the middle of upgrading some repos from .NET6 to .NET8 and we have some code that does the following as an example:
```
using (var engine = new Engine(cfg => cfg.LocalTimeZone(TimeZoneInfo.Utc)))
    {
        // data is an object that looks like this: {"TaskOutput":{"Task1":[1,2,3,4,5,6,7,8],"Task2":{"Success":true,"Age":20,"CreatedAt":"2024-09-27T08:05:54.8756768Z"}}}
        engine.SetValue("$", data);

        expression = "$.TaskOutput.Task1.slice(-1)"

        // get the json stringified result of the expression
        string value = engine.Evaluate($"JSON.stringify({expression}, null, 0)").AsString();

        return value;
    }
```

In .NET6 the `.slice(-1)` runs the evaluation without issue (we are doing this to get the last item in the array which in this case would be `8`) however when running the exact same code using .NET 8 we get the following exception:
```
Unhandled exception. Jint.Runtime.JavaScriptException: No public methods with the specified arguments were found.
 ---> Error: No public methods with the specified arguments were found.
   at slice <anonymous>:1:16
   at <anonymous>:1:16
   --- End of inner exception stack trace ---
   at Jint.Engine.ScriptEvaluation(ScriptRecord scriptRecord, ParserOptions parserOptions) in C:\Temp\jint\Jint\Engine.cs:line 458
   at Jint.Engine.<>c__DisplayClass99_0.<Execute>b__0() in C:\Temp\jint\Jint\Engine.cs:line 412
   at Jint.Engine.ExecuteWithConstraints[T](Boolean strict, Func`1 callback) in C:\Temp\jint\Jint\Engine.cs:line 818
   at Jint.Engine.Execute(Prepared`1& preparedScript) in C:\Temp\jint\Jint\Engine.cs:line 412
   at Jint.Engine.Evaluate(Prepared`1& preparedScript) in C:\Temp\jint\Jint\Engine.cs:line 372
   at Jint.Engine.Evaluate(String code, String source) in C:\Temp\jint\Jint\Engine.cs:line 349
```

**To Reproduce**

**Expected behavior**

I believe this should still work in the same way for .NET8, if I run the following in javascript it works and outputs the correct response
```
const $ = [1,2,3,4]

const a = $.slice(-1)

console.log(a)
```

**Additional context**

**Comment by martin-shields-sage** [comment]
We have done a little debugging to see if we can probe further and the difference between net6 and net8 behaviour is that when it picks up the slice method its linking it to the following method in net8: https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.slice?view=net-8.0

this method is not available in net6

**Comment by martin-shields-sage** [comment]
What we ended up doing to get around this was to create a function before the evaluation doing

```
Array.prototype.exampleslice = Array.prototype.slice
```

and the evaluation changed to `$.TaskOutput.Task1.exampleslice (-1)` ended up working out

**Comment by lahma** [comment]
You could also define a member filter in interop options to exclude the Slice from search results.

**Comment by martin-shields-sage** [comment]
OK thanks very much for your help this clears it up
