### ISSUE TITLE
Can't use Jint 4.x in Unity

### ISSUE THREAD

**Issue by U-100** [sebastienros/jint#1974]
I'm using jint in a Unity project. All went well until I tried upgrading to 4.x. It appears that acornima.dll is not working in Unity, gives this:
Could not load the file 'System.Runtime.CompilerServices.Unsafe.dll'
Note that jint 3.1.6 (which uses esprima.dll) works as expected.
I realize that this is not an issue with jint as such, but letting you know since you mention Unity as a potential usage example in readme.

**Comment by lahma** [comment]
Do you have that requested file in the folder where you have Acornima.dll?

**Comment by U-100** [comment]
I'm sorry. It's super-stupid that I didn't think about simply copying System.Runtime.CompilerServices.Unsafe.dll. I was under the impression that it must be in Unity-provided C# runtime. It appears not. After copying the dll everything works, thank you.
