### ISSUE TITLE
Why is class RegExpLiteral not used?

### ISSUE THREAD

**Issue by fvaneijk** [sebastienros/jint#201]
I've been working on a AST walker for Jint (initially to walk the tree and print the program) but I figure it will be useful for other things like some code analysis, transformation, etc  and ran into the following.

In the following method should we be allocating a RegExpLiteral object when the token is a RegularExpression instead of allocating a Literal object?

file: JavaScriptParser.cs

```
    public Literal CreateLiteral(Token token)
    {
        if (token.Type == Tokens.RegularExpression)
        {
            return new Literal
            {
                Type = SyntaxNodes.RegularExpressionLiteral,
                Value = token.Value,
                Raw = _source.Slice(token.Range[0], token.Range[1])
            };
        }

        return new Literal
            {
                Type = SyntaxNodes.Literal,
                Value = token.Value,
                Raw = _source.Slice(token.Range[0], token.Range[1])
            };
    }
```

**Comment by lahma** [comment]
If this is still an issue, please open it in esprima-dotnet repo as parsing has been extracted from Jint.
