### ISSUE TITLE
invalid cast from “Jint.Runtime.Environments.GlobalEnvironment” to “Jint.Runtime.Environments.FunctionEnvironment”。

### ISSUE THREAD

**Issue by artheru** [sebastienros/jint#2012]
**Version used**

4.1.0

**To Reproduce**

(quite difficult, deeply integrated in our project, trying to get a minimal reproducing snippet.).
it seems happen when csharp code await a javascript function.

**Expected behavior**

no exception.

**Additional context**
the problem line could happens on Engine.cs:
Ln1047: var env = (FunctionEnvironment) ExecutionContext.LexicalEnvironment;

**Comment by lahma** [comment]
Is you usage multi-threaded?

**Comment by artheru** [comment]
yes, i think it's the problem.
