### ISSUE TITLE
Date.now() returns null in extremely rare occurances

### ISSUE THREAD

**Issue by LovelyA72** [sebastienros/jint#2013]
**Version used**

4.1.0

**Describe the bug**

Date.now() sometimes return null and crashes the entire software

**To Reproduce**

repeatedly call Date.now() in a long time span and it might happen. It happened twice on me, one time when debugging in Visual Studio and the other time while running without a debugger attached.

**Expected behavior**

Date.now() working as expected

**Additional context**

.NET 8.0 WPF software on Windows 11 Workstation Edition

**Comment by LovelyA72** [comment]
It's a WPF app so there's a possibility?

**Comment by sebastienros** [comment]
@LovelyA72 don't declare a static or share and instance of Engine. Or if you do call Execute on a shared instance (because you need to evolve its state) then `lock` these usages.

**Comment by LovelyA72** [comment]
I used `lock` on all those usages, also I (should probably do this earlier) wrapped all the script executions with try catch. Everything seems fine now. Thank you!
