### ISSUE TITLE
access nest type of .net, like enum inside class

### ISSUE THREAD

**Issue by changhaohao** [sebastienros/jint#202]
modify end part of   TypeReference.GetOwnProperty(string propertyName) seem to solve the issue
but i am not sure if it is a best way to do it
=======original=============
            if (methodInfo.Length == 0)
            {
                return PropertyDescriptor.Undefined;
            }
            return new PropertyDescriptor(new MethodInfoFunctionInstance(Engine, methodInfo), false, false, false);
=======modified===========
if (methodInfo.Length > 0)
            {
                return new PropertyDescriptor(new MethodInfoFunctionInstance(Engine, methodInfo), false, false, false);
            }

```
        Type ntyp=Type.GetNestedType (propertyName);

        if (ntyp != null) 
        {
            return new PropertyDescriptor(CreateTypeReference(Engine,ntyp), false, false, false);
        }
        return PropertyDescriptor.Undefined;
```

**Comment by changhaohao** [comment]
i found this  issue in 2.4
i just found 2.5 released
may be 2.5 do not have this issue

**Comment by Willy-Kimura** [comment]
Yes, very well said. It seems to be quite an issue that only one accessor can be defined in .NET objects from Jint like: accessing a sub-class method within a class such as **myClass.subClass.methodInClass()** or accessing a property such as **myNumbers.Numbers.firstNumber**

Will be checking up on this issue if it exists in 2.5 and later...

**Comment by lahma** [comment]
Closing as obsolete.
