### ISSUE TITLE
Object.defineProperty over built-in functions

### ISSUE THREAD

**Issue by santiagoaguiar** [sebastienros/jint#207]
We are trying to load [babel](https://github.com/babel/babel) with Jint. It's a very large source code and jint handles it admirably.

It seems to work ok, except because jint throws a `TypeError` when doing something like:

    Object.defineProperty(Object.defineProperty, 'foo', { value: 1 });

It also fails over other built-in functions like:
* `String.prototype.slice`
* `Object.defineProperty`
* `Object.create`

Doing something like:

    Object.defineProperty['foo'] = 1

Also fails, beacase `CanPut` returns `false` because the function seems to be marked as not extensible (it returns [here](https://github.com/sebastienros/jint/blob/55b14dcf34f9aef7ed715b2d1829b603103380e9/Jint/Native/Object/ObjectInstance.cs#L226)).

The code above does work on Chrome at least.

Babel uses a module called `private` which uses that code [here](https://github.com/benjamn/private/blob/master/private.js#L22) to define `call` and `apply` for the reasons explained there.

I think the problem is that [ClrFunctionInstance](https://github.com/sebastienros/jint/blob/51da8829ba890e38bba5ff4968e89d39c0dc7566/Jint/Runtime/Interop/ClrFunctionInstance.cs)  are not `Extensible` by default. Would it be possible to make them `Extensible` by default? I think that is the default when a function is created through a `FunctionConstructor`, but not for `ClrFunctionInstance`. 

I think the spec is [open](http://www.ecma-international.org/ecma-262/5.1/#sec-8.12.4) with respect to if host objects have to be extensible or not, but since this behavior is allowed on most browser, maybe it wouldn't hurt to do the same on Jint.

**Comment by sebastienros** [comment]
Can you provide a PR with a unit test and the change you are suggesting?
