### ISSUE TITLE
Include line number and column in errors

### ISSUE THREAD

**Issue by Daniel15** [sebastienros/jint#21]
It'd be helpful if the line and column numbers were contained in errors. They appear to already be accessible in the AST via the `Location` class.

**Comment by jkut** [comment]
This does not seem to work with the current release. A Jint.Runtime.JavaScriptException is thrown, not a Jint.Parser.ParserException.

**Comment by HansLanger** [comment]
This is goes to  catch (Jint.Parser.ParserError ex)
var x=1;
...asd%&&&

This goes to  catch (Exception ex)  which does not have line number:
var x=1;
asd

any idea to get the line from a NON syntax error?
