### ISSUE TITLE
Using the TPL in JavaScript

### ISSUE THREAD

**Issue by rushfrisby** [sebastienros/jint#213]
Has anyone been successful in getting .NET Parallel (TPL) methods to work from JavaScript?

**Comment by sebastienros** [comment]
Do you have any feedback to share, or failing unit tests to understand what you are trying to do?

**Comment by rushfrisby** [comment]
```
namespace JintParallelSandbox
{
    class Program
    {
        static void Main()
        {
            const string code = @"
            var JintParallelSandbox = importNamespace(""JintParallelSandbox"");
            var parallel = new JintParallelSandbox.JsParallelLib();

            var items = parallel.GetConcurrentBag();
            items.Add(1);
            items.Add(2);

            parallel.ForEach(items, function(item) {
                items.Add(item + 2);
            });
            ";

            var engine = new Jint.Engine(cfg => cfg.AllowClr(typeof (JsParallelLib).Assembly));
            engine.Execute(code);
        }
    }
}
```

```
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace JintParallelSandbox
{
    public class JsParallelLib
    {
        public void Invoke(Action[] actions)
        {
            Parallel.Invoke(actions);
        }

        public void ForEach(IEnumerable<object> items, Action<object> action)
        {
            Parallel.ForEach(items, action);
        }

        public ConcurrentBag<object> GetConcurrentBag()
        {
            return new ConcurrentBag<object>();
        }
    }
}
```

This will work maybe 10% of the time. Mostly I get an error calling Parallel.ForEach. Inside of the aggregate exception I either get an Object reference exception (about 15%) or  a TargetInvocationException with inner exception of ArgumentException: "An item with the same key has already been added." (about 75%). It feels like a race condition.

**Comment by fvaneijk** [comment]
Tried a few experiments with this.

If I put locks around the manipulation of the _bindings collection in DeclarativeEnvironmentRecord.cs  and make sure we don't add multiple binding names to the collection by wrapping _bindings.Add in a HasBinding test in the create methods of this class things are more stable.  Not sure if this is all that's required.

To test I used:


using System;
using System.Collections.Concurrent;
using System.Threading.Tasks;

namespace Jint.Tests.Runtime.Domain
{
    public class JsParallelLib
    {
        private ConcurrentBag<object> _items;

        public void Invoke(Action[] actions)
        {
            Parallel.Invoke(actions);
        }

        public void ForEach(ConcurrentBag<object> items, Action<object> action)
        {
            Parallel.ForEach(items, action);
        }

        public ConcurrentBag<object> GetConcurrentBag()
        {
            _items = new ConcurrentBag<object>();
            return _items;
        }

        public object[] AsArray()
        {
            return _items.ToArray();
        }
    }
}

and 

        [Fact]
        public void TestTpl()
        {
            RunTest(@"
            function doWork(item) {
                items.Add(item + 2);
            }
            var domain = importNamespace('Jint.Tests.Runtime.Domain');
            var parallel = new domain.JsParallelLib();

            var items = parallel.GetConcurrentBag();
            items.Add(1);
            items.Add(2);

            parallel.ForEach(items, doWork);
            var ary = parallel.AsArray();

            log(ary[0]);
            assert(ary[0] == 3);
            assert(ary[1] == 2);
            assert(ary[2] == 1);
            assert(ary[3] == 3);
          ");
        }

**Comment by sebastienros** [comment]
The engine is not thread safe _at all_. I recommend you lock the statements you are calling in parallel for now.
