### ISSUE TITLE
I installed VS 2015 and now see some ECMA tests failing.

### ISSUE THREAD

**Issue by fvaneijk** [sebastienros/jint#214]
apparently it thinks \u180E is not white space.  Which is compatible with Unicode 6.3 (see: http://unicode.org/versions/Unicode6.3.0 ).  I suppose the VS update, updated unicode as well...

This seems to be...  \u180E is not white space in .NET 4.5 but is white spcace in .Net 4.0.
see: https://msdn.microsoft.com/en-us/library/system.char.iswhitespace(v=vs.110).aspx

Note I'm still debugging in VS 2013.

Anyone else seeing this?

for instance StringPrototypeTrimSIsAStringWithAllWhitespace fails

/// Copyright (c) 2012 Ecma International.  All rights reserved. 
/**
 * @path ch15/15.5/15.5.4/15.5.4.20/15.5.4.20-3-2.js
 * @description String.prototype.trim - 'S' is a string with all WhiteSpace
 */

function testcase() {

        var whiteSpacesStr = "\u0009\u000A\u000B\u000C\u000D\u0020\u00A0\u1680\u180E\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000\uFEFF";
        return (whiteSpacesStr.trim() === "");
    }
runTestCase(testcase);

**Comment by sebastienros** [comment]
I don't see it failing on my machine, and I have VS 2015, but I can see the CI failing since last month with the same issue.
