### ISSUE TITLE
How to set a global variable from within a function in strict mode

### ISSUE THREAD

**Issue by doronguttman** [sebastienros/jint#215]
Hello,
I have the following working JavaScript code:

```
(function () {
  globalVar = "foo";
})();

(function () {
  assert(typeof globalVar !== "undefined");
})();
```

but if I set strict mode, obviously, it will throw an exception on `globalVar = "foo";`:

```
"use strict";
(function () {
  globalVar = "foo";
})();

(function () {
  assert(typeof globalVar !== "undefined");
})();
```

In a browser I would have done the following and it would have worked, but there is no `window` in a jint engine and event if there was one, would it know to resolve `globalVar` as part of the window?:

```
"use strict";
(function () {
  window.globalVar = "foo";
})();

(function () {
  assert(typeof globalVar !== "undefined");
})();
```

**Comment by jsmota** [comment]
I have found a possible solution to add `window` into the jint engine.
Go to  [jint/Jint/Native/Global/GlobalObject.cs](https://github.com/sebastienros/jint/blob/master/Jint/Native/Global/GlobalObject.cs) , and add `FastAddProperty("window",this,false,false,false);` into the `public void Configure()` function.
I don't know the exact values the three Boolean parameters, but it works.

**Comment by ormico** [comment]
I think you want to do something like:

```
	DataUtil dataUtil = new DataUtil();
	var engine = new Engine()
		.SetValue("console", new JsConsole())
		.SetValue("util", dataUtil);
	string formatScript =
	@"
	var global = this;
	
	function process(p)
	{
		if(!global.count)
		{
			global.count = 0;
		}
		global.count++;
		console.log(count);
	}";

```
you can also take a look at http://2ality.com/2013/09/window.html

**Comment by doronguttman** [comment]
good thinking. thanks!

**Comment by sebastienros** [comment]
2 years old thread, OMG ;)

**Comment by ormico** [comment]
😁

**Comment by lahma** [comment]
Jint 3.x also supports [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) which allows access to setting variables in global context, like `globalThis.globalVar = "foo";`

Closing this as obsolete.
