### ISSUE TITLE
engine.Execute() throws SyntaxError with no line number or any other information

### ISSUE THREAD

**Issue by mhall1** [sebastienros/jint#218]
Sample code (underscore is a string containing the full contents of Underscore.js v1.8.3):

engine.SetValue("inputTemplate", template);
engine.Execute(underscore);
engine.Execute(@"var tmpl = _.template(inputTemplate); var result = tmpl({});");

**Comment by mhall1** [comment]
This is probably related to pull request #103

**Comment by sebastienros** [comment]
Is the issue about not have the line number of because underscore is failing? Or both?

**Comment by mhall1** [comment]
Well, ideally both, but I'm not convinced the latter problem is with jint.

**Comment by vicnaum** [comment]
Same here - I get a TypeError without any other info nor line numbers, when trying to load web3.min.js from https://github.com/ethereum/web3.js/releases/tag/v1.2.1

**Comment by lahma** [comment]
Tested and current 3.x gives better error messages. With latest web3.min.js I get `Uint8Array is not defined` , so might need polyfills or great PRs for missing data structures.

**Comment by lahma** [comment]
Closing as not specific, missing implementation yes, but other issues should track that.
