### ISSUE TITLE
Memory leak Jint.Runtime.Descriptors.PropertyDescriptor

### ISSUE THREAD

**Issue by jcarnus** [sebastienros/jint#221]
Hi,

I use a simple statement of jint : 
new Engine().Execute("").GetCompletionValue().ToObject().ToString().

But I do it very oftenly and I have a memory leak, the most one if for 
Jint.Runtime.Descriptors.PropertyDescriptor
000007fb4f8fb778    88186     22575616 Jint.Runtime.Descriptors.PropertyDescriptor

Is there any way of cleaing up this ?

Jérémy

**Comment by sebastienros** [comment]
How do you assume there is a memory leak? Do you get a memory exception or is it just that you see the memory growing? Or did you track the references and see they are not released?

**Comment by jcarnus** [comment]
I just see the memory growing.

I use a winbdg with dumphead - stat to see what is happining ?

Is the first time you see that ?

Jérémy

Le 02/09/2015 15:38, Sébastien Ros a écrit :
>
> How do you assume there is a memory leak? Do you get a memory 
> exception or is it just that you see the memory growing? Or did you 
> track the references and see they are not released?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sebastienros/jint/issues/221#issuecomment-137222854>.
>

-- 
Jérémy Carnus

**Comment by sebastienros** [comment]
Memory growing doesn't mean memory leak. If you do a `GC.Collect()` in your loop what happens?
If the memory goes down, then no memory leak. 

A memory leak at this point would be obvious to catch, it would mean there is a collection of completion objects which is kept, and it's not the case, so I am pretty confident. Are you familiar with how the GC works related to generations and when it will release the memory?

**Comment by sebastienros** [comment]
Please reopen if you find more clues.

**Comment by PierreLucB** [comment]
Hi there,
It seems to be a memory leak. I have a similar problem. My memory increase and I have a OutOfMemoryException after a while.

GC.Collect() doesn't reduce the memory.

Those are the objects which takes many memory : 

Dictionary<String, Jint.Runtime.Descriptors.PropertyDescriptor>	
Jint.Runtime.Descriptors.PropertyDescriptor	
Jint.Runtime.Interop.ClrFunctionInstance	
Jint.Runtime.MruPropertyCache2<String, Jint.Runtime.Descriptors.PropertyDescriptor>

I'm using AngleSharp 0.9.9 with Jint 2.9.1.

Have you encounter the problem ?

Thanks.

Pierre-Luc
