### ISSUE TITLE
Passing C# *instance* methods to javascript

### ISSUE THREAD

**Issue by AtmoEntity** [sebastienros/jint#224]
I see in the documentation (and unit tests) an abundance of examples on binding static functions, but I can't find anything on binding methods on instances. E.g.:

```C#
// Egg.cs
public class Egg
{
    public void Hatch() { Console.WriteLine("Hatching!"); }
    public void Die() { Console.WriteLine("Dying :("); }
}
```

```javascript
// javascript

// these are global functions
Hatch();
Die();
```

And the output would of course be:

```
Hatching!
Dying :(
```

Another similar question, is there a way to pass a single object instance directly to javascript? So for example if I have this C# code:

```C#
graphics = new CustomGraphicsWrapper(magicalGraphicsLibrary);
```

That I can pass it to javascript so I could do:

```javascript
graphics.drawImage( ... );
```

**Comment by AtmoEntity** [comment]
Well I'm continuing to mess around and I figured it out, so now I feel pretty silly...

Here's the answers if anyone else is wondering the same...

```C#
Engine e = new Engine();
Egg egg = new Egg();
e.setValue("egg", egg);
e.setValue("Hatch", new Action(egg.Hatch));
e.setValue("Die", new Action(egg.Die));
```

Then in javascript all the following works...

```javascript
egg.Hatch();
egg.Die();
Hatch();
Die();
```

**Comment by sebastienros** [comment]
And you don't even have to define `egg` in the Engine:

`e.setValue("Hatch", () => egg.Hatch());`
