### ISSUE TITLE
Assignment expression is evaluated from right to left

### ISSUE THREAD

**Issue by santiagoaguiar** [sebastienros/jint#225]
I'm using a library that has a code like the following:
```javascript
var keys = ['a'];
  , source = { a: 3};
  , target = {};
  , key;
  , i = 0;
target[key = keys[i++]] = source[key];
```

That code works OK on browsers, but fails with Jint. The issue seems to be that `key` is `undefined` when reading from `source`.

Checking the code I see that on `EvaluateExpressionAssignment` the [right hand is evaluted before the left hand](https://github.com/sebastienros/jint/blob/add78e623620b9affeb179e75e2cca2b262c7df6/Jint/Runtime/ExpressionIntepreter.cs#L42).

However on [11.13.1](http://www.ecma-international.org/ecma-262/5.1/#sec-11.13.1) it says left hand must be evaluated before right hand. 

Switching the evaluation order on `EvaluateExpressionAssignment` fixes the issue above. I can provide a PR, but to be honest, I'm not sure where to add the associated test case. They seem to be tests form a standard suite. Should I just add a .js on The ch11\11.13\11.13.1\ to test for this? 

I also have a patch for #207 to enable extension of built-in functions, which is also assumed by some of the libraries I use (which only requires marking `Extensible = true` on `ClrFunctionInstance`), but I don't know where to add the test case either.

**Comment by sebastienros** [comment]
Awesome. Please submit a PR for the fix, and a unit test in `Jint.Tests.Runtime.EngineTests`. You should not change the ones in the standard suite.

For the other one, please create a separate PR and put the test in InteropTests.

Thanks
