### ISSUE TITLE
ArrayInstance.IsArrayIndex() does not check if p == ToString(ToUInt32(p))

### ISSUE THREAD

**Issue by T917820981726** [sebastienros/jint#228]
Hi,

I wondered about the output when trying the following JavaScript code:
```javascript
var arr = ['A', 'B'];
log(arr['1'] === arr['001']);

arr['002'] = 'C';
log(arr.length);
```

On Jint, this outputs
```
True
3
```
whereas in Firefox, IE and Chrome (using console.log) this shows
```
false
2
```

When debugging, I found that when running ArrayInstance.SetOwnProperty, it is checked if the property is an array index in ArrayInstance.IsArrayIndex():
```C#
public static bool IsArrayIndex(JsValue p, out uint index)
{
    index = ParseArrayIndex(TypeConverter.ToString(p));

    return index != uint.MaxValue;

    // 15.4 - Use an optimized version of the specification
    // return TypeConverter.ToString(index) == TypeConverter.ToString(p) && index != uint.MaxValue;
}
```

So the code does not check that `ToString(ToUInt32(p)) == p`, therefore returning true when `p == '002'` (the code that would do the check is commented-out).

However, ECMAScript 5.1 says at [15.4](http://www.ecma-international.org/ecma-262/5.1/#sec-15.4):
>Array objects give special treatment to a certain class of property names. A property name P (in the form of a String value) is an array index if and only if ToString(ToUint32(P)) is equal to P and ToUint32(P) is not equal to 2^32−1.

I'm not familiar with those specs, but to me this seems to indicate that P = '002' is not an array index, as ToString(ToUint32(P)) == '2' which is not equal to '002'.

[15.4.5.1](http://www.ecma-international.org/ecma-262/5.1/#sec-15.4.5.1) (DefineOwnProperty) says:
> (...)
>- 4.Else if P is an array index (15.4), then 
>  - a. Let index be ToUint32(P).
>  - b. Reject if index ≥ oldLen and oldLenDesc.[[Writable]] is false.
>  - c. Let succeeded be the result of calling the default [[DefineOwnProperty]] internal method (8.12.9) on A passing P, Desc, and false as arguments.
>  - d. Reject if succeeded is false.
>  - e. If index ≥ oldLen i.Set oldLenDesc.[[Value]] to index + 1.
>    - ii. Call the default [[DefineOwnProperty]] internal method (8.12.9) on A passing "length", oldLenDesc, and false as arguments. This call will always return true.
>
>  - f. Return true.
>
>- 5.Return the result of calling the default [[DefineOwnProperty]] internal method (8.12.9) on A passing P, Desc, and Throw as arguments.

I read it so when calling `arr['002'] = 'C';` in the example above, it should not set the property '2' (and change 'length' to 3), but instead set the property '002' using the default DefineOwnProperty method.

So I would expect that Jint returned the same as Firefox, Chrome and IE when running the above example. Am I missing something?

Thanks!

**Comment by sebastienros** [comment]
Good catch, this is something that I must have introduced when I optimized the performance of arrays. And something which is also missing from the ECMA test suite. Let's see how the PR passes the unit tests ...
