### ISSUE TITLE
PropertyInfoDescriptor seems to contradict ECMAScript 5.1 section 8.6.2

### ISSUE THREAD

**Issue by kpreisser** [sebastienros/jint#233]
Hi,
I played with Jint's host interface by executing a Javascript that queries a property descriptor of a .Net host object that is set with Engine.SetValue.

I have the following Javascript that operates on a "hostobject" variable provided by the host:

``` javascript
function formatPropertyDescriptor(descr) {
    var isDataDescr = typeof descr.writable != 'undefined';
    var str = (isDataDescr ? 'data' : 'accessor') + ' descriptor:\t' 
        + ' Configurable: ' + descr.configurable + ', Enumerable: ' + descr.enumerable;
    if (isDataDescr) {
        str += ', Writable: ' + descr.writable + '\t - Value: ';
        try {
            str += String(descr.value).replace(/[\r\n]/g, ' ');
        } catch (e) {
            str += '[Ex]';
        }
    } else {
        if (typeof descr.set != 'undefined')
            str += ', set';
        if (typeof descr.get != 'undefined') {
            str += ', get: ';
            try {
                str += String(descr.get.call(orgObj)).replace(/[\r\n]/g, ' ');
            } catch (e) {
                str += '[Ex]';
            }
        }
    }

    return str;
}

var descr = Object.getOwnPropertyDescriptor(hostobject, 'counter');
var out = 'hostobject.counter: ' + formatPropertyDescriptor(descr) + '\r\n';
out += 'hostobject.counter = ' + hostobject.counter + '\r\n';
out += 'hostobject.counter = ' + hostobject.counter + '\r\n';

out;
```

I'm running this Javascript in the following C# program (insert the javascript into the "script" string variable):

``` C#
using Jint;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication1
{
    class JintTest
    {

        class MyHostObject
        {
            private int _counter;
            public int counter
            {
                get { return _counter++; }
            }
        }


        static void Main(string[] args)
        {

            string script = @"";  // <-- insert the Javascript code here

            var e = new Engine(cfg =>
            {
                cfg.Strict();
            });

            // Set the host object.
            e.SetValue("hostobject", new MyHostObject());

            var parser = new Jint.Parser.JavaScriptParser(true);
            var p = parser.Parse(script);
            e.Execute(p);

            string s = e.GetCompletionValue().ToString();
            Console.WriteLine(s);


            Console.ReadKey();
        }
    }
}
```

The C# program defines a class "MyHostObject" with a "counter" property that increments a field so it returns another value each time it is called. The Javascript then displays the property descriptor for the "counter" property of the "hostobject" object.

This is the output when the program is run:

``` text
hostobject.counter: data descriptor:     Configurable: false, Enumerable: false, Writable: false     - Value: 1
hostobject.counter = 3
hostobject.counter = 5
```

You can see that the property descriptor is a data descriptor with writable = false, but the property returns a different value each time it is called.

However, while ECMAScript 5.1 says at section [8.6.2](http://www.ecma-international.org/ecma-262/5.1/#sec-8.6.2) that "Host objects may support these internal properties with any implementation-dependent behaviour as long as it is consistent with the specific host object restrictions stated in this document.", it also says about data descriptors of host objects:

> The [[GetOwnProperty]] internal method of a host object must conform to the following invariants for each property of the host object:
> - If a property is described as a data property and it may return different values over time, then either or both of the [[Writable]] and [[Configurable]] attributes must be true even if no mechanism to change the value is exposed via the other internal methods.
> - If a property is described as a data property and its [[Writable]] and [[Configurable]] are both false, then the SameValue (according to 9.12) must be returned for the [[Value]] attribute of the property on all calls to [[GetOwnProperty]].
> -  If the attributes other than [[Writable]] may change over time or if the property might disappear, then the [[Configurable]] attribute must be true.
> - If the [[Writable]] attribute may change from false to true, then the [[Configurable]] attribute must be true.
> - If the value of the host object’s [[Extensible]] internal property has been observed by ECMAScript code to be false, then if a call to [[GetOwnProperty]] describes a property as non-existent all subsequent calls must also describe that property as non-existent.

My understanding of this is that the data descriptor in the javascript in the example above should not have writable = false and configurable = false as the returned value changes over time (1, 3, 5, ...). Is this correct?

Instead, I would expect e.g. that the data descriptor has writable = true or configurable = true, or maybe use an accessor descriptor that has only a "get" function.

Thanks!

**Comment by lahma** [comment]
This is an old issue that hasn't gained much traction - but thank you for the detailed explanation! If this is still an issue we would appreciate a PR improving things. I'm closing this for now, but of course we can reopen if needed.
