### ISSUE TITLE
Evaluating suitability of Jint for embedded DSL

### ISSUE THREAD

**Issue by mwpowellhtx** [sebastienros/jint#239]
Hello,

I did not find a Google group for Jint, so please forgive if this isn't the best forum. Will try to keep it brief as possible.

I am interested to embed a DSL into my .NET application. I will be providing the object(s) in the form of a DSL "context" object, not unlike the patterns one might find in Angular.

The integration will expect a modest set of functions / returns, though could mature over time; indeed I expect it to, as we learn about new end-user needs / wants.

Speaking in practical terms, picture a sports sim, and wanting to identify the coach's choices for the play. The host will provide a context that includes situation, play(s), perhaps even player(s), with whatever richness is required to make an informed choice.

The coach's functions would evaluate the context and return true/false, or perhaps a weight, that the game engine will use to determine which play(s) from which to choose.

The particulars are still in flux; the crux of the matter is that I want to isolate the host engine runtime from the embedded DSL environment as much as is practical to do; will be constructing the context and handing it to the DSL for evaluation; will call some function(s) and expect some response(s), which the engine can use to proceed.

Anyway, without being a design review, does this seem doable given what folks know about Jint? I am also encouraged by the fact that the project seems alive, if active, in recent days/weeks/months, including with customary delivery channels such as Nuget.

Thanks...

Best regards.

**Comment by sebastienros** [comment]
Totally adapted. Just a way to script your context object. It's used by mobile devs to host their game's logic or parameters. So others let users script some drawing application, ... And your scenario seems to be requiring very small scripts (in tens of lines) which means it will be as fast as a compiled solution.

Just a quick note, the project might also feel _dead_ it would still be complete. I am trying to fix the bugs that users find as fast as I can, or look at every PR, but right it's pretty stable and thorough.

**Comment by mwpowellhtx** [comment]
Thanks for the prompt response. Much appreciated. Will definitely have a go with it. Thanks again.
