### ISSUE TITLE
jQuery support

### ISSUE THREAD

**Issue by mwpowellhtx** [sebastienros/jint#240]
Hello,

I gather from studying a couple of the Jint.Tests that embedding jQuery support is possible? Or other JS libraries for that matter?

Thank you...

**Comment by sebastienros** [comment]
This requires a headless DOM, like https://github.com/tmpvar/jsdom, but even this one is on ECMAScript 6, which means it would first need to be converted using babel. But in theory it's doable, lot of work.

**Comment by sebastienros** [comment]
jsdom 6+ seems to be on ECMAScript 5.1

**Comment by mwpowellhtx** [comment]
I'm not sure what you mean, "headless DOM"... i.e. the initialized engine bits, injected context, etc, all stand on their own? Also, I am not as familiar with ECMAScript road map as relates to JavaScript. What would that mean for Jint? Untangling a versioning web?

**Comment by sebastienros** [comment]
JavaScript doesn't have anything to do with Window, Document, HTMLElement, InputElement, ... all the types that a browser adds to its javacsript engine and that jQuery will manipulate. So Jint, as a pure javascript engine, will need to know about these types and their methods. A headless browser is a set of tool that let you manipulate these types without a rendering engine. JsDom is a JavaScript implementation of these types, which means by running this script you should be able to run jQuery also. Jint is an implementation of ECMAScript 5.1, and jsdom is using a newer JavaScript version (6) which is not even fully implemented in the current browsers. Babel is a tool which will convert a script from version 6 to its equivalent in 5.1.

**Comment by sebastienros** [comment]
BTW, I have created a gitter forum if you want to chat, instead of using the issue tracked. I think you mentioned a lack of it yesterday. https://gitter.im/sebastienros/jint

**Comment by mwpowellhtx** [comment]
I think I'm tracking with you; sounds like the typical versioning leap frog. I don't know that I would necessarily need jQuery, but it might be interesting to support operations across ranges of contextual items, like situations, plays, etc, responding to the host, i.e. ranges of ids across some range of constrained items. Worst case I keep the interfaces simple and respond with scalar values. Thanks...
