### ISSUE TITLE
Calling async method

### ISSUE THREAD

**Issue by onyultd** [sebastienros/jint#241]
I'm calling asynchronous methods from my script and using the Task.ContinueWith function to return execution to the script once the async method has completed. 

for example 

"context.GetContact(id).ContinueWith(function(t) {var contact = t.Result; if (contact!=null) { ... } });"

I'm using a single engine instance and calling the script for each item in a listview.
Im having problems with thread safety. I.e. local variables defined within the script are seemingly not isolated within the execution context.

Do I have to invoke the script on a new engine instance here for each item or is there a better way or am I doing something really stupid?

Thanks :)

**Comment by sebastienros** [comment]
An engine instance is not thread-safe.

**Comment by onyultd** [comment]
OK thanks. Is there a big performance hit creating a new engine instance for each execution?

**Comment by sebastienros** [comment]
No, and it's recommended to do so. If your scripts are large then you can cache the parsed tree and reuse it though. You can also reuse engine instances (pool) across executions, just not in separate thread.

**Comment by onyultd** [comment]
Ok great. Thanks for your help.
