### ISSUE TITLE
.net class property called twice

### ISSUE THREAD

**Issue by riccardocecchini** [sebastienros/jint#246]
Hi, i (maybe) found an issue in Jint library. 
If i have a class in .net like this:
class Test{
List<TestNode> Nodes = new List<TestNode>();
 public dynamic this[string node] {
  get {
   var n = new TestNode(node);
   Nodes.Add(n);
  }
}

class TestNode{
string Node;
 public TestNode(string node){
  Node = node;
 }
}

and from Jint i execute:
var test = new Test();
var node = test['node'];

The node will be create two times:
first time for check if Property HasValue, second time for return value.

I solve the problem in ObjectInstance.cs on line 72 with these lines:
 var val = desc.Value;
 return val.HasValue ? val.Value : Undefined.Instance;
 //return desc.Value.HasValue ? desc.Value.Value : Undefined.Instance;

I'm not expert of the structure of jint so I have not taken the liberty of making a pull request.
Second: sorry for my english, i know that's terrible.

Regards

**Comment by sebastienros** [comment]
Please make a PR
