### ISSUE TITLE
Creating a Buffer from base64 string is very slow

### ISSUE THREAD

**Issue by amrish7** [sebastienros/jint#252]
I am running into some performance issues around instantiating a `Buffer` object.

The following command takes anywhere from 300-500 seconds for strings that are quite long.  

```
let bf = new Buffer(str, 'base64'); // Buffer is nodejs built in buffer
```

For example, for a `base64` string that is > 2 million characters long (I think it equates to roughly 4mb), the process of creating a buffer is very slow. It looks like the slowness is inherent to the `for...loop` and it is [this one in specific](https://github.com/beatgammit/base64-js/blob/master/lib/b64.js#L55) that is causing the slowness.

It's a long shot question, but is there a recommended approach to make the execution faster in my case?

**Comment by sebastienros** [comment]
Probably the `push` method which is known to be slow in Jint. I have an open issue for this as all Array operations are currently purely following the specification which is not optimized. So any operation on arrays could use some improvements.

**Comment by sebastienros** [comment]
Could you give me a hint a how I can use this library with Jint in order to repro your use case? Might be hard but you would save me a few brain cycles and google searches ;)

**Comment by amrish7** [comment]
@sebastienros Sorry for the delay! Here is the code snippet `b64ToByteArray` to duplicate the slowness

```
function _decode(elt) {
		var PLUS   = '+'.charCodeAt(0)
		var SLASH  = '/'.charCodeAt(0)
		var NUMBER = '0'.charCodeAt(0)
		var LOWER  = 'a'.charCodeAt(0)
		var UPPER  = 'A'.charCodeAt(0)
		var PLUS_URL_SAFE = '-'.charCodeAt(0)
		var SLASH_URL_SAFE = '_'.charCodeAt(0)
		var code = elt.charCodeAt(0)
		
		if (code === PLUS ||
		    code === PLUS_URL_SAFE)
			return 62 // '+'
		if (code === SLASH ||
		    code === SLASH_URL_SAFE)
			return 63 // '/'
		if (code < NUMBER)
			return -1 //no match
		if (code < NUMBER + 10)
			return code - NUMBER + 26 + 26
		if (code < UPPER + 26)
			return code - UPPER
		if (code < LOWER + 26)
			return code - LOWER + 26
	}
	
	/**
	 * Create a buffer
	 * @param {string} b64
	 * @returns {[int]} Buffer
	*/
	function b64ToByteArray (b64) {
		var i, j, l, tmp, placeHolders, arr

		if (b64.length % 4 > 0) {
			throw new Error('Invalid string. Length must be a multiple of 4')
		}

		var len = b64.length
		placeHolders = '=' === b64.charAt(len - 2) ? 2 : '=' === b64.charAt(len - 1) ? 1 : 0

		// base64 is 4/3 + up to two characters of the original data
		arr = new Array(b64.length * 3 / 4 - placeHolders)

		// if there are placeholders, only get up to the last complete 4 chars
		l = placeHolders > 0 ? b64.length - 4 : b64.length

		var L = 0

		function push (v) {
			arr[L++] = v
		}

		for (i = 0, j = 0; i < l; i += 4, j += 3) {
			tmp = (this._decode(b64.charAt(i)) << 18) | (this._decode(b64.charAt(i + 1)) << 12) | (this._decode(b64.charAt(i + 2)) << 6) | this._decode(b64.charAt(i + 3))
			push((tmp & 0xFF0000) >> 16)
			push((tmp & 0xFF00) >> 8)
			push(tmp & 0xFF)
		}

		if (placeHolders === 2) {
			tmp = (this._decode(b64.charAt(i)) << 2) | (this._decode(b64.charAt(i + 1)) >> 4)
			push(tmp & 0xFF)
		} else if (placeHolders === 1) {
			tmp = (this._decode(b64.charAt(i)) << 10) | (this._decode(b64.charAt(i + 1)) << 4) | (this._decode(b64.charAt(i + 2)) >> 2)
			push((tmp >> 8) & 0xFF)
			push(tmp & 0xFF)
		}

		return arr
	}
```

and the performance comparison between JINT and ClearScript while executing the `b64ToByteArray` for differeng string lengths

![untitled](https://cloud.githubusercontent.com/assets/1700689/12627055/9c41d32a-c4f0-11e5-99e6-72384c948f87.png)

**Comment by sebastienros** [comment]
Can you profile it? And get an idea where the perf impact is?

**Comment by sebastienros** [comment]
It seems that the overhead is from functions executions, due to context switching. In your example the `decode` method is called multiple times for each char.
There is a huge potential performance gain here. I will try to look into optimizations.

If anyone wants to give it a shot too, that would be great.

**Comment by sebastienros** [comment]
I have merged some significant perf improvements related to this scenario on the master branch. Please try with the source version and let me know how it compares now. It will be still slower than ClearScript but it should be better.

**Comment by sebastienros** [comment]
Please try 3.0-beta releases which has lots of perf improvements.
