### ISSUE TITLE
iOS script execution policy

### ISSUE THREAD

**Issue by globeport** [sebastienros/jint#255]
Apple has a strict policy on script execution and will reject apps that download javascript (unless executed via javascriptcore/WebKit framework). Where does JINT fit in this case? If I download and run script via JINT is it likely to be rejected by the Apple Store?

**Comment by sebastienros** [comment]
I know it has been used by the past on iOS, but I don't know the details. Maybe someone with more experience might want to answer that?

**Comment by jtothebell** [comment]
My understanding is that interpreted code is allowed on iOS as long as it is bundled with the app and not downloaded. See 3.3.2 in this document: https://developer.apple.com/programs/ios/information/iOS_Program_Information_4_3_15.pdf. I'm not 100% sure that that is the latest version, but I believe that is the current policy.

**Comment by globeport** [comment]
OK, in particular, from 3.3.2:

"The only exception to the foregoing is scripts and code downloaded and run by Apple's built-in WebKit framework or JavascriptCore"

So I think Jint is probably out if anyone is planning to incorporate downloaded javascript into their iOS app. That's a real shame!

**Comment by lahma** [comment]
I think there's not much to do here on Jint's side. Closing and we can reopen if some feature in Jint could help.
