### ISSUE TITLE
Apply Options._maxRecursionDepth also to other method instances

### ISSUE THREAD

**Issue by T18970237136** [sebastienros/jint#258]
Hi,

The **maxRecursionDepth** field in the [Options](https://github.com/sebastienros/jint/blob/master/Jint/Options.cs) allows to limit recursion in order to prevent StackOverflowExceptions. This is important when running foreign code because you can't catch StackOverflowExceptions in your code - the entire process will terminate.

However, it seems this number only applies to recursive invocations of the same function instance, but not to the general stack depth.

E.g. if you store different function instances in an array which call each other, the specified limit will not apply and the process will still terminate due to an StackOverflowException even if you call Config.LimitRecursion with a low value:

``` c#
using Jint;
using System;

namespace Jint_Test
{
    class Program
    {
        static void Main(string[] args)
        {
            var engine = new Engine(cfg =>
            {
                // Limit recursion to 5 invocations
                cfg.LimitRecursion(5);
                cfg.Strict();
            });

            try
            {
                engine.Execute(@"

var myarr = new Array(5000);
for (var i = 0; i < myarr.length; i++) {
    myarr[i] = function(i) {
        myarr[i + 1](i + 1);
    }
}

myarr[0](0);

");
            }
            catch (StackOverflowException)
            {
                Console.WriteLine("Can not catch StackOverflowExceptions...");
            }

            Console.WriteLine("Finished.");
            Console.ReadKey();
        }
    }
}
```

Could the implementation of maxRecursionDepth be extended to also include invocations of other functions?

Thanks!

**Comment by sebastienros** [comment]
Good point.
