### ISSUE TITLE
ECMA tests still failing on unicode white space character changes

### ISSUE THREAD

**Issue by fvaneijk** [sebastienros/jint#259]
related to 
https://github.com/sebastienros/jint/issues/214

if you use the trim functions of StringPrototype rather than string you can get further in getting the remaining failing ECMA tests to pass.

I have implemented this locally and if I get time I can try to put a PR together...

**Comment by sebastienros** [comment]
Please create a PR, I saw too they were failing, then got taken by some other tasks at work ...

**Comment by fvaneijk** [comment]
Will do, might take a few days to get to it, am also busy at work...

**Comment by fvaneijk** [comment]
I managed to get some time so here is the PR

https://github.com/sebastienros/jint/pull/260
