### ISSUE TITLE
No public methods with the specified arguments were found.

### ISSUE THREAD

**Issue by Waty** [sebastienros/jint#263]
The following code throws a JavaScriptException with the message "No public methods with the specified arguments were found.".
```
    public class X
    {
        private event Action<short, string> Callbacks;

        public void RegisterCallback(Action<short, string> callback)
        {
            Callbacks += callback;
        }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            var e = new Engine();
            e.SetValue("x", new X());
            e.Execute(@"x.RegisterCallback(function(version, patch){});");
        }
    }
```

Am I doing something wrong or is this a bug in the library?

**Comment by sebastienros** [comment]
I am not sure there is any implicit conversion of a `function` to an `Action`. You should try to accept a `JsValue` instead and wrap it to an `Action` by yourself.

**Comment by sebastienros** [comment]
Apparently there are some unit tests covering your scenario so it should work. Try to start from one of these unit tests and alter it to reach your example to see what the issue is.

**Comment by Waty** [comment]
I managed to find the issue causing the exception. The implicit conversion is unable to do it for value types:

`public void RegisterCallback(Action<short, string> callback)` throws the exception
`public void RegisterCallback(Action<string, string> callback)` works fine

I'll just use string objects for now, but a fix would be nice ;-)

**Comment by sebastienros** [comment]
I assume the expression needs to be wrapped into `Expression.Convert` when it's a value type ... if it can help you fix it as you found the reason.
