### ISSUE TITLE
Exceptions thrown from native code are not passed to the script

### ISSUE THREAD

**Issue by alexander-burkhardt** [sebastienros/jint#264]
Exception thrown in natice code clled from a script cannot be caught in the script. 

I added the following test case in interoperability (InteropTests.cs) locally:

```
    [Fact]
    public void ShouldThrowExceptionFromNativeCodeToScript()
    {
        _engine.SetValue("a", new A());
        // Action<int>
        RunTest(@"
            error = null;

            try
            {
                a.Call19(""Hallo"");
            }
            catch(e)
            {
                error = e.message
            }");
        Assert.Equal("Hallo", _engine.GetValue("error").AsString());
    }
```

and the method Call19 is implemented as follows:

```
    public void Call19(string message)
    {
        throw new Exception(message);
    }
```

I tried also with JavaScriptException instead of Exception. But in any case the runtime stopps executing and the exception is not passed to the script.

As solution I suppose adding a new exception class to the Runtime.Interop namespace for passing Exceptions from Native code to the script. Using the JavaScriptException would create the problem, that you need to have a reference to the script engine in order to throw the exception.

The reason, why the exception is not passed to the script is that the call to method.Invoke(...) (Runtime.Reflection) does not throw the original exception directly. Instead a MethodInvocationException is thrown.

**Comment by alexander-burkhardt** [comment]
Hi,

I prepared a solution and test. Would be great to have a solution in the official code base as well.
Thanks in advance!

Alexander

**This is the solution I have prepared. **

The test case:

        [Fact]
        public void ShouldThrowJavaScriptExceptionToScript()
        {
            _engine.SetValue("a", new A());

            RunTest(@"
                try
                {
                    a.Call19(""Hallo"");
                    assert(false);
                }
                catch(e)
                {
                    error = e.message;
                    assert(e.message == ""Hallo"");
                }");

        }

The method Call19(...) in class A:

        public void Call19(string message)
        {
            throw new NativeCodeException(message);
        }


The new class NativeCodeException:

    namespace Jint.Runtime.Interop
    {
        [Serializable]
        public class NativeCodeException: Exception
        {
            public NativeCodeException(string message)
                :base(message)
            {
            }
        }
    }

The change in the exception handling of StatementInterpreter.ExecuteStatementList:

        public Completion ExecuteStatementList(IEnumerable<Statement> statementList)
        {
            var c = new Completion(Completion.Normal, null, null);
            Completion sl = c;
            Statement s = null;

            try
            {
                foreach (var statement in statementList)
                {
                    s = statement;
                    c = ExecuteStatement(statement);
                    if (c.Type != Completion.Normal)
                    {
                        return new Completion(c.Type, c.Value.HasValue ? c.Value : sl.Value, c.Identifier)
                        {
                            Location = c.Location
                        };
                    }

                    sl = c;
                }
            }
            catch(JavaScriptException v)
            {
                c = new Completion(Completion.Throw, v.Error, null);
                c.Location = s.Location;
                return c;
            }
            catch(Exception e)
            {
                if (e.InnerException is NativeCodeException)
                {
                    c = new Completion(Completion.Throw, _engine.Error.Construct(
                        new JsValue[] { e.InnerException.Message }), null);

                    c.Location = s.Location;

                    return c;
                }
                else
                {
                    throw;
                }
            }

            return new Completion(c.Type, c.GetValueOrDefault(), c.Identifier);
        }

**Comment by PeterWone** [comment]
For anyone else finding this issue (why the hell is it still open?) there is now explicit configuration for this behaviour. 

```csharp
      var engine = new Engine(options =>
      {
        // allow script to deal with exceptions from injected host objects
        options.CatchClrExceptions(e => true);
      });
```

Why is it a delegate and not a simple bool? This is a callback that allows you to decide which exceptions to let the script manage and which ones mean everyone out of the pool, we're going home. My code above makes the script responsible for all exceptions that occur as a result of script action. This is not necessarily the right course of action. Some failures may require the host to do cleanup.

**Comment by sebastienros** [comment]
Thanks @PeterWone
