### ISSUE TITLE
JINT throwing exception on new object creation

### ISSUE THREAD

**Issue by hemashiv** [sebastienros/jint#265]
Hi:
I am trying to instantiate a new instance of System.Data classes in Jint.version 2.6
According to the documentation you can allow an engine to access any .NET class by configuring the engine instance like this:

```
var engine = new Engine(cfg => cfg.AllowClr());
```

Then you have access to the  System  namespace as a global value.

The JINT engine can successfully create other instances such as lists, dictionaries as well as custom assemblies that have been exported to it in AllowClr.

However, accessing System.Data.DataTable for example fails with  the following error:

For eg:
var myCnn = new System.Data.DataTable();

When run, this returns:

---
## OK   

Any help would be appreciated.

**Comment by quanganhtran** [comment]
+1, I have a constructor which can be invoked fine with `new` from C# but not in JS. In JS I will get *The object can't be used as constructor*

**Comment by apostrophesoftware** [comment]
I am getting the same problem, have you been able resolve this?

**Comment by sebastienros** [comment]
Please re-open this issue if the suggestion didn't work.
