### ISSUE TITLE
dotnet core compatibility

### ISSUE THREAD

**Issue by ciel** [sebastienros/jint#270]
Is there any plan to update the references for JINT to be compatible with the new .NET Core system?

**Comment by sebastienros** [comment]
It's there, use the `dnx` branch. At some point I will make a single project targeting all platforms, but I am waiting for the platform support story to be final.

**Comment by ciel** [comment]
Thank you so much for making this wonderful library. I'm so excited to see it is still being supported and worked on.

**Comment by jonjo-manywho** [comment]
We'd love to use Jint in a .NET Core project! Are there any updates to this now that it's officially released?

**Comment by ciel** [comment]
Yeah, I'm also looking forward to it.

**Comment by ciel** [comment]
Is it at least possible to use Jint with a `net451` import?

**Comment by sebastienros** [comment]
If you can't wait RavenDb has ported it already to Core. It would have been better they contribute to this repository directly, but they might have other constraints.

**Comment by ciel** [comment]
How can we help?

**Comment by sebastienros** [comment]
Targeting a specific branch will let me accept PRs from different committers even if there are issues.

**Comment by darkcamper** [comment]
Hi. I've just finished porting Jint to NetStandard 1.0 and it's currntly passing all tests except for  CommonScripts.ThreeDRayTrace (and I don't really know what's happening).

The bulk of the work has been replacing many changed or non-existent methods of System.Reflection

It's in pull request #337. This is my secound github contribution and I'm not reallly used to git and pull requests and stuff yet, so if I've made any mistake just tell me and I'll try to fix it.

**Comment by sebastienros** [comment]
Done, and it's on Nuget. Targets PCL, Net Standard 1.3 and .NET 45. Thanks @darkcamper for your help.

**Comment by darkcamper** [comment]
I don't think my contribution has been really useful 😅 . Thanks for sorting out everything and releasing it so quickly! (I'll make a good use of it)

**Comment by sebastienros** [comment]
It's called motivation.
