### ISSUE TITLE
Date constructor called with Date object as parameter leads to an exception thrown

### ISSUE THREAD

**Issue by RhinoDevel** [sebastienros/jint#271]
This might **not** be **an error** (see [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) and [question at stackoverflow.com](http://stackoverflow.com/questions/1090815/how-to-clone-a-date-object-in-javascript)) but it is different from what some popular browsers do (e.g. Firefox):

```javascript
var a = new Date(),
    b = new Date(a), // b = new Date(a.getTime()); works (as expected).

    s = String(b); // => Throws exception with Jint 2.7.1.
```

**Comment by sebastienros** [comment]
Only the spec will tell! let's see...

**Comment by sebastienros** [comment]
I just added a unit test and it works fine for me. Please check that the source code works fine and I will publish a new release.

**Comment by RhinoDevel** [comment]
Version 2.8 does no longer throw an exception.

Thanks for your very quick response and for this great and useful software! :+1:

**Comment by sebastienros** [comment]
Glad to hear!
