### ISSUE TITLE
Ecma v6

### ISSUE THREAD

**Issue by Jugolo** [sebastienros/jint#274]
Will jint support ecma version6?

**Comment by sebastienros** [comment]
Eventually. It's been a very popular question/request so I think it should be worth considering, even more that the current implementation looks quite complete and bug free. The new spec is about to be released in the next weeks, so why not start on it.

The plan could be to add support for specific features one by one and release as they are ready. The parser and object model could be done as a whole first, the same way I did for ES5, then tackle each ES6 feature. Could even be a common effort.

I also need to find a good test suite to validate the features.

**Comment by Jugolo** [comment]
Create will see if i can get some time to make puæl requst :)

**Comment by dested** [comment]
To achieve support for this I am passing the typescript source into jint, and passing my source into that. Its actually not as slow as I anticipated, and I have es6 support (as well as typescript!)


Some pseudocode


```    
var typescript = File.ReadAllText("js/typescript/typescript.js");
var mc = engine.Execute(typescript);
var tsc = mc.GetValue("ts");
var cc = tsc.AsObject().Get("transpile");
var c = cc.Invoke(YOURACTUALSOURCECODESTRING).AsString();
var result = engine.Execute(c);
```

**Comment by sebastienros** [comment]
Thought about it but had never tries, that's awesome. We could even imagine a mode where Jint would load typescript automatically to execute Ecma2015. With just an option.

Or something like:

```
var engine = new Engine();
var result = engine.Execute(someScript, Version.Ecma2015);
```

On the first call of this option, we just need to load TypeScript from a resource file. It would be reused across the engine calls, and would not impact the current perf as this would be injected on demand.

**Comment by dested** [comment]
I have done it with a fair amount of success. The initial transpile hit is rough, but post that the code it produces is clean and performant. Could be an interesting flag, you just need to keep up with the typescript versions which is ever changing.

**Comment by sebastienros** [comment]
Some news on ES6 side. For the past few months I have been actively working of implementing support for ES6. This is a huge work be I made some progress.

The plan is this:
- Port the ES6 version of the Esprima parser to C#, like I had done for ES5 which is currently used in Jint.
- Update Jint 2 to use the new ES6 parser instead, and deprecate the old parser.
- Implement each ES6 feature in parallel.

The new parser will probably be released as a separate package, just to ensure that one can use it by itself, to do crazy stuff with JS manipulation.

Good news is that as of this morning I have a complete ES6 parser. It is not in a packageable form yet, but all the unit tests from Esprima are working. It includes syntax errors and range/location information.
Once the parser is integrated, everyone will be able to help on implementing the new features, and benefit from it.

**Comment by sebastienros** [comment]
It's on github now: https://github.com/sebastienros/esprima-dotnet

**Comment by sebastienros** [comment]
Annoucement https://github.com/sebastienros/jint/issues/343

**Comment by Jugolo** [comment]
Create :) thanks :)

**Comment by nixonad** [comment]
@dested : I tried the suggested code to import typescript and use the transpiler. 
I get this "**Message: Esprima.ParserException : Line 27': Duplicate __proto__ fields are not allowed in object literals**" when executing the typescript.js file (version 2.6.2)

Anyone else using typescript like this?

**Comment by gentledepp** [comment]
@dested  could you provide some demo project? 

In general: I like the idea of having typescript-support in Jint.
However, I do believe that it is not its main focus.

So maybe there should be something like an additional jing-typescript package

E.g.
* jint
* jint.typescript (depends on jint, typescript)

**Comment by dested** [comment]
@gentledepp 

This was mid 2016, I was using TypeScript 1.6, I haven't tried it on later versions. The code worked something like this 

```
var typescript = File.ReadAllText("js/typescript/typescript.js");
var typescriptProgram = engine.Execute(typescript);
var tsc = typescriptProgram.GetValue("ts");
var transpileFunc = tsc.AsObject().Get("transpile");
var jsOuput = transpileFunc.Invoke(typeScriptProgram).AsString();
var jsProgram= engine.Execute(jsOuput);
```

**Comment by lahma** [comment]
Please follow #343 for updates, things are progressing and updates are sent there.
