### ISSUE TITLE
How to get corresponding syntax node location in C#

### ISSUE THREAD

**Issue by gavinwdev** [sebastienros/jint#283]
Hi, Jint is good to use, during using it, I meet a issue, please check below for detail.
`public class CustomObjectInstance: ObjectInstance`
`{`
`...`
`public void Test()`
`{`
`I want to get syntax node location in my C# logic, it is very useful for debugging script.`
`I try "this.Engine.getLastSyntaxNode()", then I can get near location, but that's not excepted.`
`}`
`...`
`}`
Thanks in advance.

**Comment by djMax** [comment]
#297 may do some of what you're after.

**Comment by lahma** [comment]
Engine has GetLastSyntaxNode, closing.
