### ISSUE TITLE
Build errors in "Options.cs" file

### ISSUE THREAD

**Issue by Willy-Kimura** [sebastienros/jint#290]
Seems that there are a number of new build errors in this project's version (2.8) mostly within the **Options.cs** file. There are also some warnings on Reference issues within the **Jint.Tests** project . Please please check them out and update the solution with fixes.

Thanks!

**Comment by fvaneijk** [comment]
The errors are related to c# 6.0 improvements.  Try using a C# 6.0 compiler.  Visual Studio 2015 supports C# 6.0.

**Comment by djMax** [comment]
We're not using 6.0 in Jint right? I'm seeing this error on Appveyor, but not locally.

**Comment by sebastienros** [comment]
We might be: http://kristian.hellang.com/building-csharp-6-code-with-appveyor/

**Comment by djMax** [comment]
Yeah, I fixed this by raising the VS version in the SLN file such that MSBuild 14 would be used.
