### ISSUE TITLE
__proto__ not working?

### ISSUE THREAD

**Issue by djMax** [sebastienros/jint#295]
One of the babel folks points out that this should be returning true:

```
var obj = {};
var parent = {prop: 4};
obj.__proto__ = parent; 
console.log('prop' in obj);
```

This was while debugging super() not working properly for babel-transpiled classes without es2015-loose mode. Would like to fix as I don't love requiring loose mode. Any thoughts?

**Comment by djMax** [comment]
I think this is indeed not working. I have a fix, will try to add a test.

http://pastebin.com/vrZJsRXx

**Comment by sebastienros** [comment]
there is no mention of `__proto__` anywhere in the specs.

**Comment by sebastienros** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto

> While Object.prototype.__proto__ is supported today in most browsers, its existence and exact behavior has only been standardized in the ECMAScript 6 specification as a legacy feature to ensure compatibility for web browsers. For better support, it is recommended that only Object.getPrototypeOf() be used instead.

**Comment by djMax** [comment]
Yeah, my related PR just focuses on Object.setPrototypeOf, along the lines of that guidance.

**Comment by sebastienros** [comment]
Well, I assume it's about time to start integration ES6 ... I will try to wrap up an ES6 features list, start a new __es6__ branch, and mention in on the readme. Any fix we do on the master branch will also be reflected on the es6 one.

**Comment by djMax** [comment]
Yeah, though ES6 seems like a significantly larger task than this "wasn't a standard but is a standard" kind of fix. In our case, I don't think we can wait for all ES6 stuff to show up to release our project that's using jint. The tricky bit is it's a project that other people would use as an SDK, so we very much wan't to go off NuGet packages. So I think the question is whether we (a) can get a fix for this into master/nuget or (b) temporarily fork off another NuGet package that we publish for the version of Jint we use or (c) Put this fix in an ES6 branch and then release that to the existing NuGet package somehow (not sure how forward versioning works in nuget, if at all).

**Comment by sebastienros** [comment]
My goal is to have the es6 branch be shipped in parallel on nuget using 3.x package version, with 2.x versions still going on to fix the es5 version of Jint. This is just a way to get things shipped that should not be in the es5 one.

**Comment by sebastienros** [comment]
Unless you think all the es6 dev could be done targeting the same branch, which I assume could also work, as long as we introduce a dev branch as a gating mechanism.

**Comment by djMax** [comment]
I guess what I'm asking is "would you be willing to release a version on NuGet as 3.0 that ONLY had this fix?"

**Comment by djMax** [comment]
I just want a version we can pin to that has the most relevant and timely bit in order to make our stuff work, not saying that nothing else can go in it, just that we'll need it soon-ish and I'm not trying to suggest a true ES6 release is an easy thing.

**Comment by loganfsmyth** [comment]
This is specifically an issue because without this it is hard to polyfill certain ES6 features, so while the timeline for implementing ES6 may be long, if mutating the prototype chain is supported, users can use transpilers like Babel to write ES6 code and run it in ES5 environments.

**Comment by sebastienros** [comment]
Maybe I am not clear here, the es6 branch would be released as frequently as the es5 branch. But not complete. You don't have to wait for the full es6 spec to be implemented.
Maybe the fact that I suggested two branch is confusing here.

So I assume it would be best for everyone that this gets in the same branch, and is shipped with the current 2.x releases. As nothing from es6 is a breaking change that would be simpler to comprehend.

**Comment by djMax** [comment]
Ok, I think I get it now. So where could I find some tests that would be "sufficient and well suited" to exercise this? I couldn't find the true source of the ones you used originally to see if there were relevant tests there.

**Comment by djMax** [comment]
(closed for the PR related to this, and a broader discussion about ES6)
