### ISSUE TITLE
Javascript objects defined from .NET dictionary

### ISSUE THREAD

**Issue by CPardi** [sebastienros/jint#298]
Hi, I am trying to pass a JavaScript object to Jint using a Dictionary<string, object> type. However, I am seeing some unexpected behavior that I would like to query. In particular the JSON.stringify function and looping through object properties, behave differently for objects create via a .NET dictionary and those created using a Javascript object initializer.

I have wrote the code below to demonstrate the problem.

``` cs
namespace Jint_Test
{
    using System;
    using System.Collections.Generic;
    using Jint;

    public class JsObjectIssue
    {
        public static void Main()
        {
            // Creat an engine.
            var engine = new Engine().SetValue("log", new Action<string>(Console.WriteLine));

            // Create a Javscript object using Javscript object initializer.
            engine.Execute("var jsObj = { 'key1' :'value1', 'Key2' : 'value2' }");

            // Create a Javscript object using a .Net dictionary.
            engine.SetValue("netObj", new Dictionary<string, object>()
            {
                { "key1", "value1" },
                { "key2", "value2" },
            });

            // Write key1 using bracket notation.
            Console.WriteLine("\nWrite key1's value using bracket notation.");
            engine.Execute("log('jsObj  : ' + jsObj['key1'])");
            engine.Execute("log('netObj : ' + netObj['key1'])");
            // EXPECTED RESULT.

            // Write a stringified version.
            Console.WriteLine("\nWrite a stringified version.");
            engine.Execute("log('jsObj  : ' + JSON.stringify(jsObj))");
            engine.Execute("log('netObj : ' + JSON.stringify(netObj))");
            // DIFFERENT RESULT.

            // Write properties on screen using showProps function defined on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects
            engine.Execute(@"function showProps(obj, objName) {
  var result = """";
  for (var i in obj) {
    if (obj.hasOwnProperty(i)) {
      result += objName + ""."" + i + "" = "" + obj[i] + ""\n"";
    }
    }
  return result;
}");
            Console.WriteLine("\nWrite properties on screen using showProps.");
            Console.WriteLine("jsObj properties:");
            engine.Execute("log(showProps(jsObj, 'jsObj'))");
            Console.WriteLine("netObj properties:");
            engine.Execute("log(showProps(netObj, 'netObj'))");
            // DIFFERENT RESULT.
        }
    }
}
```

Which yields the results:

```
Write key1's value using bracket notation.
jsObj  : value1
netObj : value1

Write a stringified version.
jsObj  : {"key1":"value1","Key2":"value2"}
netObj : {}

Write properties on screen using showProps.
jsObj properties:
jsObj.key1 = value1
jsObj.Key2 = value2

netObj properties:

Press any key to continue . . .
```

I have just started using Jint so I do not know if this is a bug, or simply me not understanding how to use the feature properly. Cheers.

**Comment by djMax** [comment]
Jint is different than other engines (in my experience) in that it doesn't automatically translate arrays and dictionaries. So if you want a JS dictionary, you should make one with Engine.Object.Construct and then set properties on it.

**Comment by sebastienros** [comment]
I assume we could add this feature.

**Comment by djMax** [comment]
We definitely could -it seemed a reasonable/performant thing to do to leave them unconverted. I assumed it was on purpose :)

**Comment by CPardi** [comment]
Hi, thanks for the responses. This has got me a bit further, however I have a couple of follow up questions.

Using the `Engine.Object.Construct` defined as
```cs
ObjectInstance Construct(JsValue[] arguments);
```
 * What does the `arguments` parameter refer to?
 * then do I assume correctly that I add properties using `FastAddProperty`?

Finally, in `.FastAddProperty` the value is a `JsValue` class. This inherits from `IEquatable<JsValue>`, so bools and strings can be passed. However, how would you go about passing a function? For example, say I had an instance of Func<string,string>. 

Finally, I assumed that a C# dictionary would create a JavaScript object because of the line `Object -> expando objects (IDictionary<string, object> and dynamic)` at the bottom Jint's help page. I am right in saying that this refers to the opposite direction? So an object in javascript when accessed from C# (say via `.GetCompletionValue`) would create a Dictionary? 

Cheers.

**Comment by jkgz** [comment]
I'm trying to do something similar, where I have JS code that needs to access a JS dictionary translated from a C# dictionary. Can you show a brief example of using Engine.Object.Construct to create the JS dictionary? In the example from @CPardi , this would take netObj and translate it to jsObj

**Comment by orlandow** [comment]
@CPardi, @jkgz, were you able to translate the C# dictionary to a JS dictionary? I tried using the `Engine.Object.Construct` and the `FastAddProperty` but got the same results.

**Comment by lahma** [comment]
ObjectWrapper needs to override GetOwnProperties the same way we made it understand GetOwnPropertyKeys.
