### ISSUE TITLE
Function declaration order breaks execution flow

### ISSUE THREAD

**Issue by yekaterina** [sebastienros/jint#303]
Jint does not return values that are declared before function() – only when they are after function().

Examples:

``` javascript
"Expected result"; 
function foo(){}
```

– JINT returns null (But should be "Expected result"!).

``` javascript
function foo(){}
"Expected result"; 
```

– JINT returns "Expected result" (OK).

Tested in various browsers, they return a result  when some values are returned before function() – while JINT returns null. For example, a valid case for browsers (Chrome, Safari, Mozilla) returning "expected result:

```
<script>
alert(eval("'Expected result';function foo(){};"));
</script>
```

**Comment by sebastienros** [comment]
I think it's because I rewrite the tree to move all functions up in case a previous statement is using one of these function ... It's a valid issue.

**Comment by lahma** [comment]
Current 3.x series now handles this after function code tweaks that were made. Currently in MyGet feed and later on NuGet.
