### ISSUE TITLE
Jint does not interperet System.Linq expressions

### ISSUE THREAD

**Issue by greenjeffreym** [sebastienros/jint#304]
for example, this code does not work:

var newArray = someArray.Select(function (x) {
    return X*X;
});

In my code I am using .Net assemblies and so I assume the arrays are declared as c# arrays. However, Jint throws an exception with the message: Object has no method 'Select'. I assume that since I am using the CLR that it would pick up the Linq methods.

**Comment by sebastienros** [comment]
Probably because they are extension methods and they need to be discovered differently.

**Comment by greenjeffreym** [comment]
How might that be done?

**Comment by sebastienros** [comment]
If you look where the reflection is used to find namespaces and members, and nothing is found, you could fallback to extension methods.
What I would suggest is to add an option on the engine, like for assemblies, to specify a set of classes that contain extension methods to lookup for.

Like `option.AddExtensionMethods<System.Linq.Enumerable>` for your example

**Comment by sebastienros** [comment]
I don't see any reason to close this issue so far, it's legitimate. Someone might want to implement it.

**Comment by lahma** [comment]
Thanks to @KurtGokhan 's work, this is now supported in dev branch (MyGet release as of writing):

```csharp
var engine = new Engine(cfg => cfg
    .AllowClr()
    .AddExtensionMethods(typeof(System.Linq.Enumerable))
);
```

```javascript
let someArray = [ 2, 4 ];
let newArray = someArray.Select(x => x * x).ToArray();
// newArray now has [ 4, 16]
```

I'm closing this issue and we can investigate more specific use cases if/when they rise. [Like described in the PR](https://github.com/sebastienros/jint/pull/896), some cases are hard to handle.
