### ISSUE TITLE
ArrayBuffer and TypedArray

### ISSUE THREAD

**Issue by MaitreDede** [sebastienros/jint#305]
Hi,
Is it possible to include either in main Jint or as an extension assembly support for ArrayBuffer and TypedArray ? Like Float32Array...
Thanks :)

**Comment by tolstenko** [comment]
+1

**Comment by sebastienros** [comment]
Related to this: https://github.com/sebastienros/jint/issues/274#issuecomment-250543093

**Comment by sebastienros** [comment]
Let's do it https://github.com/sebastienros/jint/issues/343

**Comment by lahma** [comment]
https://github.com/sebastienros/jint/pull/925
