### ISSUE TITLE
Replacing the Global object

### ISSUE THREAD

**Issue by MaitreDede** [sebastienros/jint#306]
Hi,
I would like to replace the Global object with another I built from scratch, to mimic the behavior of a web browser, for example :
- when in the root script, the global 'this' = 'window'
- functions can be used directly : writing 'setTimeout' is equivalent to 'window.setTimeout'
- 'console' object refers to 'window.console'...
  and so on...

Thanks.

**Comment by lahma** [comment]
There's now option by using `UseHostFactory<T>` which returns `Host` instance, you should be able to override this to return custom host that overrides `CreateGlobalObject`.

**Comment by DUXINYI** [comment]
> There's now option by using `UseHostFactory<T>` which returns `Host` instance, you should be able to override this to return custom host that overrides `CreateGlobalObject`.

Is it necessary that rewriting another GlobalObject class? Since I want to preserve the original properties of globalObject (e.g. Array,Object), and expose (extension) methods at the same time. Can provide some ways to customize?

**Comment by lahma** [comment]
You can add them to existing global object via API calls like `engine.SetValue("Array.prototype.superFunc", myFunc)`?

**Comment by DUXINYI** [comment]
> You can add them to existing global object via API calls like `engine.SetValue("Array.prototype.superFunc", myFunc)`?

Thanks for reply. 
There is problem using `engine.SetValue` cause the instance I want to replace is a CLR object with extension method, I didn't find a graceful way to enumerate all members of wrapped object in C#.

Here is my sample:

```
var wrapped = new ObjectWrapper(engine, new Exception());  
foreach(var prop in wrapped.GetOwnProperties()){
        // the (member and extension) methods of the Exception class missed.
        // engine.setValue(prop.Key,xxx
}
```

**Comment by DUXINYI** [comment]
> You can add them to existing global object via API calls like `engine.SetValue("Array.prototype.superFunc", myFunc)`?

Thanks for reply. 
There is problem using `engine.SetValue` cause the instance I want to replace is a CLR object with extension method, I didn't find a graceful way to enumerate all members of wrapped object in C#.

Here is my sample:

```
var wrapped = new ObjectWrapper(engine, new Exception());  
foreach(var prop in wrapped.GetOwnProperties()){
        // the (member and extension) methods of the Exception class missed.
        // engine.setValue(prop.Key,xxx
}
```

**Comment by lahma** [comment]
Maybe you should open a new discussion with a proper full repro about what you are trying to achieve, I'm a bit lost now what's the actual outcome that is desired.
