### ISSUE TITLE
JINT 2.8 still cannot access methods in DateTime class.

### ISSUE THREAD

**Issue by linusconcepcion** [sebastienros/jint#312]
I saw this ticket closed:
https://github.com/sebastienros/jint/issues/62

But as of now, the issue still exists in version 2.8.

jint> System.DateTime.Now
=> "2016-07-20T12:12:52.687Z"
jint> System.DateTime.Now.ToString()
TypeError: Object has no method 'ToString'

I cannot access DateTime functions like ToString() or AddDays(), etc..  Help!

**Comment by sebastienros** [comment]
Apparently the `DateTime` or `Int32` instances are automatically converted to JS objects like `Date` and 'Number`. This is why it can't find `ToString` but you can use 'toString` instead.

Does it solve your issue?

**Comment by linusconcepcion** [comment]
Thanks for responding.  Unfortunately, it does not solve my problem.

The issue I have is that our software has been using JINT 1.0 for several years, so many hundreds of scripts have been written against the older version, where script code like this worked:

var newDate = myObject.DateValue.AddDays(-10);
var output = "Date output: " + newDate.ToString("MM/dd/yyyy");

So, JINT back then was able to work with the C# versions of the base types.

Unfortunately, with JINT 1.0, we are now seeing some memory corruption issues that cause server instability.. which is forcing us to migrate to JINT 2.x.  Your new versions do not appear to have any memory corrupting issues, but it's handling of the core .NET types can't work for us without having to go back and rewrite hundreds of scripts running daily in production.

Is there anything I can do?  Would you recommend I stay with JINT 1.x here and try to see if the memory issue can be fixed there?

**Comment by sebastienros** [comment]
You could add some shim to the `Date` object that will handle `AddDays` or `ToString`.

Example:
```
Date.prorotype.AddDays = function(days) {
  this.setTime(this.getTime() + days * 86400000 );
}

Object.prototype.ToString = function() {
  return this.toString();
}
```

If you run it after the engine is initialized, then it will fix your issue.

**Comment by linusconcepcion** [comment]
It's an interesting idea, and I had considered going that route.  However, the ToString() version won't work because our scripts will have the C# formatting in their call to ToString().  In my example, I'm passing "MM/dd/yyyy" into ToString() for dates.

So, if I were to prototype this, I'd have to replicate C# behavior in javascript which can get pretty complicated given all the possibilities with the parameters.

Would it be possible for the javascript prototype to callback into C# with the C# types?  This way, I don't have to recode the implementations in javascript?

**Comment by doronguttman** [comment]
We had a similar issue, we ended up wrapping the property with a custom
class in the C# side of things...

**Comment by linusconcepcion** [comment]
It looks like using the a combination of sebastien's recommendation of using javascript shims to call back into C# functions works fine, so that's what we are going with.  The only annoying part is I have to create shims for a bunch of functions on DateTime and String, but it looks like it will work.

**Comment by lahma** [comment]
I believe there's not much to do here, there are workarounds and the current behavior is by design.
