### ISSUE TITLE
Jint cannot set Nullable properties

### ISSUE THREAD

**Issue by linusconcepcion** [sebastienros/jint#313]
This code will fail if the property is nullable.  For example, if I have this class:

```
public class MyObject 
{
  public int? NullableProp { get; set; }
}

```
Then this script will fail.

`myObject.NullableProp = 1`

The failure is in DefaultTypeConverter.cs, line 187 because System.Convert.ChangeType does not inherently support nullable types.

**Comment by doronguttman** [comment]
Did you try?:
myObject.NullableProp.Value = 1

**Comment by linusconcepcion** [comment]
I don't believe it is valid C# to assign to .Value in a nullable property.  It is read only.

**Comment by doronguttman** [comment]
You're right.
@sebastienros, looks like the issue may be deeper than the described, I
looked at the Nullable source code, and it appears that the way it is
implemented that is via an implicit and explicit operator override. I have
not tested jint with these yet, but it may be something that can be solved
generically there.

@linusconcepcion, you may be able to resolve the issue temporarily by using
an extension method for Nullable objects.
Look here: https://github.com/sebastienros/jint/issues/304

**Comment by linusconcepcion** [comment]
The solution seems simple to me, but needs a change to DefaultTypeConverter.cs.

Just add this code:

```
if (type.IsGenericType && type.GetGenericTypeDefinition().Equals(typeof(Nullable<>)))
{
       if (value == null)
              return null;

       type = Nullable.GetUnderlyingType(type);
}

```
before the call to System.Convert.ChangeType(), and I think you should be ok.

**Comment by sebastienros** [comment]
Please create a PR with some unit tests. Replace `Equals` by `==`.

**Comment by linusconcepcion** [comment]
Sure.  Bear with me since I'm new to Git.  I'll get it in.
