### ISSUE TITLE
Adding a prototype function to Object breaks for (x in y) behavior.

### ISSUE THREAD

**Issue by linusconcepcion** [sebastienros/jint#315]
Here is my test code:

```
class Program
{
        static void Main(string[] args)
        {
            var engine = new Engine(c => c.AllowClr());
            engine.SetValue("print", new Action<string>(Print));

            engine.Execute(@"
Object.prototype.ToString = function(format) {
    return this.toString();
}

var arr = ['AL','GL','APD','WC'];
for (var i in arr) {
    print(arr[i]);
}");

            Console.WriteLine("Done");
            Console.ReadLine();
        }

        static void Print(string message)
        {
            Console.WriteLine(message);
        }
    }

```

If I remove the Object.prototype.ToString lines from the script, everything works fine.  However, with those lines in the script, for (var i in arr) makes an extra loop at the end, and passes an invalid value to the print() function which causes the code to crash.

**Comment by lahma** [comment]
Tested and currently follows the way Node processes this code. Function is printed as string for last loop as it's a new member.
