### ISSUE TITLE
importNamespace issue in UWP app with Compile with Native .NET Tool Chain

### ISSUE THREAD

**Issue by anassisi2** [sebastienros/jint#318]
Unfortunately to publish my app in the Windows Store I have to use the Native .NET Tool Chain, which seams fine most of time, expect dreadfully slow in compiling.

The jint importNamespece is not working when I check the 'Compile with Native .NET Tool Chain' in the UWP project build properties.

> var IO = importNamespace('Mavericks.IO')
> var Color = IO.Color
>   Error: Operation is not supported on this platform.

As you can see, I don't get any error from the importNamespace itself but "Operation is not supported on this platform" when I try to map one of my classes.

Any help is greatly appreciated.
Thank you in advance,

**Comment by sebastienros** [comment]
In the meantime you can remove the part that doesn't compile related to reflection, you probably don't need it. The solution is to create a specific target for UWP that doesn't contain this part of the code.

**Comment by anassisi2** [comment]
Thank  you!

**Comment by lahma** [comment]
Closing as obsolete, if further improvements needed with 3.x version please file a PR.
