### ISSUE TITLE
setFullYear sets incorrect date when year is before 1970

### ISSUE THREAD

**Issue by binish** [sebastienros/jint#319]
Here is the test case

`

            var expression = @"(function(){ var d = new Date( '1969-01-01T08:17:00' ); d.setFullYear(2015,0,1); return d;})()";

            dynamic result = engine.Execute(expression).GetCompletionValue().ToObject();

            Assert.AreEqual(new DateTime(2015,1,1,8,17,0), result);`

**Comment by sebastienros** [comment]
Have you tried setting UTC when you create the `DateTime` object, I assume it will use the local timezone if not specified, and all dates are UTC in javascript.

**Comment by honestegg** [comment]
The following does seem to fail. `pre70` returns "12/31/2014 8:17:00 AM".
``` c#
var engine = new Engine();
var post70 = engine.Execute(@"(function(){ var d = new Date( '1970-01-01T08:17:00' ); d.setFullYear(2015,0,1); return d;})()").GetCompletionValue().AsDate().ToDateTime();
var pre70 = engine.Execute(@"(function(){ var d = new Date( '1969-01-01T08:17:00' ); d.setFullYear(2015,0,1); return d;})()").GetCompletionValue().AsDate().ToDateTime();

Assert.AreEqual(post70, pre70);
```

**Comment by sebastienros** [comment]
Me too, there is one day difference somewhere ... also looking at it

**Comment by sebastienros** [comment]
I think the issue is in the dichotomy in `DatePrototype.YearFromTime`

**Comment by sebastienros** [comment]
Fixed the bug, it was in `TimeWithinDay` which was not handling dates < 1970 correctly.

**Comment by sebastienros** [comment]
Another side effect of improving `YearFromTime` is that the time it takes for the CI has been halved ... crazy.
