### ISSUE TITLE
Program object is not thread-safe

### ISSUE THREAD

**Issue by honestegg** [sebastienros/jint#320]
We have been caching our parsed scripts (as `Program` objects) and reusing them each time we need to execute a program. Sometimes the `Program` object is used across multiple threads and this seems to randomly give us strange results. I have been able to track the issue down to the caching of literals in Jint. 

I don't know whether or not this is a reasonable expectation, but should I expect a `Program` object to be thread-safe?

I have a fix for the issue I am running into (I'll create a pull request soon), but I don't know whether or not a `Program` object should be used this way at all.

Here is a test program which illustrates the issue. It generally fails pretty quickly.

```c#
var Parser = new JavaScriptParser();
var IsNull = new Func<string, bool>(s => s == null);
var nums = Enumerable.Range(0, 10);

while (true)
{
	var p = Parser.Parse("IsNull('test')");

	Parallel.ForEach(nums, n =>
	{
		var engine = new Engine();
		engine.SetValue("IsNull", IsNull);

		var isNull = engine.Execute(p).GetCompletionValue().AsBoolean();

		if (isNull)
		{
			throw new ArgumentNullException("'test' should not be null");
		}
	});
}
```

**Comment by sebastienros** [comment]
That's a good point.

**Comment by honestegg** [comment]
Would you have expected the Program to be thread-safe before? With this fix, do you think it is probably safe to use in a multi-threaded environment?

**Comment by sebastienros** [comment]
This should be good, yes.

**Comment by honestegg** [comment]
Do you think there will be a new version published to NuGet in the next few weeks?

**Comment by sebastienros** [comment]
I can do one right away ...
