### ISSUE TITLE
c# throw generated by js throw, not caught by js try/catch block

### ISSUE THREAD

**Issue by ghost** [sebastienros/jint#327]
Jint Version: 2.9.1
.net version: 4.5 
[Program.cs.txt](https://github.com/sebastienros/jint/files/415303/Program.cs.txt)

I have the case where a js function that throws is passed to a c# method as a delegate when the c# invokes the js function it generates an exception that is ignored by the js try/catch block.

However If I call a c# method that throws directly the js try/catch block handles it correctly.

I've attached a demo program that shows the unexpected behavior.

**Comment by lahma** [comment]
I think this issue is obsolete. It should now work as expected.
