### ISSUE TITLE
.NET Standard Target

### ISSUE THREAD

**Issue by borrrden** [sebastienros/jint#332]
Are there any plans to move from PCL to [.NET Standard](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md)?  I have Jint as a dep and I'm investigating moving over to .NET standard myself (long term, it requires quite a bit of refactoring on my end).

**Comment by sebastienros** [comment]
There is already an issue to track this: https://github.com/sebastienros/jint/issues/270

Short answer: use the port that RavenDB had one already or help me and do it on the dedicated branch.
