### ISSUE TITLE
Camel Casing Option For Object Conversion

### ISSUE THREAD

**Issue by deevus** [sebastienros/jint#338]
When converting an object to a JsValue using `JsValue.FromObject` is there a way to get it to camel case the property names? 

I have our API configured to camel case properties when converting to JSON, so it would be nice to be able to support the same convention in Jint. 

Happy to look at this myself if you can guide me

**Comment by sebastienros** [comment]
`FromObject` returns a value, it doesn't care about properties. So I assume the question is different.

Could you provide a sample of what you are trying to achieve?

Something like this where both calls would work?
```
engine.SetValue('obj', new Point());
engine.Execute('return obj.x');
engine.Execute('return obj.X');
```

**Comment by deevus** [comment]
That would solve my problem, yeah.

**Comment by sebastienros** [comment]
Interestingly, I am almost sure it has already been implemented ... let me check

**Comment by sebastienros** [comment]
I think I found where it's done with the help of @fvaneijk 

https://github.com/sebastienros/jint/blob/master/Jint/Runtime/Interop/ObjectWrapper.cs#L145
