### ISSUE TITLE
case of .net property and method names question

### ISSUE THREAD

**Issue by fvaneijk** [sebastienros/jint#342]
It seems that there is a fallback method to match the name of the property or method of a .net object that uses a custom case insensitive compare.  This seems wrong to me.  To me the comparison should be an exact match.  What is the reason to allow this fallback compare?  I am under the impression that JavaScript is a case sensitive language.

see GetOwnProperty() and EqualsIgnoreCasing() in /Jint/Runtime/Interop/ObjectWrapper.cs

Thanks

**Comment by sebastienros** [comment]
The idea is that some users want to access .net properties with camel casing which is more widely used in JavaScript. I assume we should be specific about the camel casing thing instead of ignoring the case altogether. 

Agreed to make it an option too.

See #338 which is the opposite ask.

**Comment by fvaneijk** [comment]
Thanks for the clarification.  I agree that the comparison behavior should be specified by an option.  I.E. Exact or CamelCase maybe?  CamelCase being the current implementation.  Does this also apply to native JavaScript objects?

**Comment by sebastienros** [comment]
Solution is to add an option to the Options class, like `CamelCasedProperties`, maybe in `AllowClr`, then have the constructor take a `StringComparer` implementation from this options, that is used in this class.

**Comment by lahma** [comment]
#952 will allow supplying a `StringComparer` instance via options to customize the matching procedure.
