### ISSUE TITLE
[question] generating c# bindings for JS?

### ISSUE THREAD

**Issue by 0xFireball** [sebastienros/jint#344]
I've successfully got C# to call JS (compiled TypeScript, in this case) which depends on C# classes that implement certain interfaces.

For example, the TS code (not the code i'm referring to, I'm just explaining what I mean):

```
function sayHello(IConsole console) {
 console.log("Hi!");
}
```

can use a .NET class that implements the console. This has been working fine so far.

My TS code uses the given C# implementation to create a TS/JS object that is passed back to my .NET code.

What I want to do now is generate C# bindings for that JS object's methods:

I want to be able to go `jsObjectWithBindings.DoSomething()` from C# without invoking the method from a string. I want to generate strongly-typed C# bindings that when called, will just invoke the methods on the underlying JS object.

How can I accomplish this?

Thanks for your time!

**Comment by tpetrina** [comment]
Depends on where your interfaces are defined. You can generate them using a T4 file or using some other code generation tool. This way the file will be generated and built with the app itself.

**Comment by lahma** [comment]
Closing as no actionable things left.
