### ISSUE TITLE
Update cicle

### ISSUE THREAD

**Issue by Thejuster** [sebastienros/jint#346]
Hello is possibile make Jint similar Lua?

for example:

in my old project whit lua, once loaded a file the script are executed in memory

```
lua.loadFile("file.lua");

while(true)
{
lua.DoString("Update();");
}
```

for jint is possibile this?

C#

```
Jint.Engine js = new Jint.Engine();
js.Execute(file_content);
js.Execute("var i = 0;");

while(true)
{
   js.Execute("Update();");
}
```

File contents:

```
function Update()
{
   var b = new Bitmap();
   
   i++;

  b.Draw(image,x + i,y);
};
```

When i execute in while the scrip, the variabile declared i is 0
i++ dont increment the value.

I need this feature for my game engine.
is possibile?

**Comment by sebastienros** [comment]
It should work, it looks like a bug.

**Comment by doronguttman** [comment]
Try running

js.Execute("var i = 0;");

before

js.Execute(file_content);

**Comment by Thejuster** [comment]
hi doronguttman tanks for your example, your code work.
but one question. 

see this simple script
http://pastebin.com/eMaas1Y6

My Javascript Example file

```
//Scene Game

function Scene_Game() 
{
  this.Bitmap = new Bitmap();
};

Scene_Game.prototype.Initialize = function () 
{
 var x = 0;
 var y = 100;
};


Scene_Game.prototype.Update = function()
{
   x++;
   this.Bitmap.Draw(x,y);
};

```

First i need to load this script.
After need first to call  Scene_Game.Initialize() for set var x and y value.
Next, in my (Monogame App) need to call in render cycle.

This is my example C# code

```
public void Scene_Game_Initialize()
{
   js.Execute(LoadScript("SceneGame.js") + "var temp = new Scene_Game(); temp.Initialize(); );
   
}


public void Scene_Game_Update()
{
   spriteBatch.Begin();
  js.Execute("SceneGame.Initialize();");
  spriteBatch.End();
}
```

i see again x = 0;

**Comment by doronguttman** [comment]
You are missing the 'this.' before the 'x++'. See below:

Scene_Game.prototype.Update = function()
{
   this.x++;
   this.Bitmap.Draw(x,y);
};

I suggest you use a good JavaScript editor and lint your code.
Try vscode

Also, you may want to write your code in TypeScript and transpile to
JavaScript. It will mistakes like that with no issues.

**Comment by sebastienros** [comment]
@Thejuster I just added the `question` tag and this is what appears now

![image](https://cloud.githubusercontent.com/assets/1165805/20066677/48198100-a4c7-11e6-8a94-4dc120992590.png)


Did you do that just before me? Or is it a bug in github, I don't think you can technically do that, can you?
