### ISSUE TITLE
return C# value to javascript

### ISSUE THREAD

**Issue by Thejuster** [sebastienros/jint#348]
Hello i need to return value from my function to javascript.

example C#

```
public int Get_Screen_Width()
{
 return 800;
}
```

Example javascript

`var screen_w = Get_Screen_Width();`

anyone can help me?

**Comment by sebastienros** [comment]
This is the first example from the home page. Here is an updated form for your question:

```
    var engine = new Engine()
        .SetValue("getScreenWidth", new Func<int>(Get_Screen_Width))
        ;

    engine.Execute(@"
      var screen_w = getScreenWidth();
    ");
```
