### ISSUE TITLE
Walker dosent work correctly in parenthesis

### ISSUE THREAD

**Issue by SoheilHasankhani** [sebastienros/jint#350]
walker ignore parenthesis in some cases
for example:
`
string script = @"((a < b) && (c = -1)) || ((a > b) && (d = +1)) || (e = 0)";

Jint.Parser.JavaScriptParser parser = new Jint.Parser.JavaScriptParser();
var statement = parser.Parse(script);
var result = Jint.Walker.JintWalker.GetStatementAsString(statement, true);
Console.WriteLine(script);
Console.WriteLine(result);
Console.WriteLine();
Console.WriteLine();
Console.WriteLine();
script = @"(function test(){alert('Hello World')})()";
parser = new Jint.Parser.JavaScriptParser();
statement = parser.Parse(script);
result = Jint.Walker.JintWalker.GetStatementAsString(statement, true);
Console.WriteLine(script);
Console.WriteLine(result);
Console.ReadKey();
`

**Comment by sebastienros** [comment]
What is `Walker`? Is that something that you made or you got from an external library?

Would you mind providing a test repro?

**Comment by SoheilHasankhani** [comment]
it was added to forked repository based on this issue:
https://github.com/sebastienros/jint/pull/289

**Comment by sebastienros** [comment]
Sorry I can't help you with that, it's not part of this project.
