### ISSUE TITLE
Incorrect indexer support when multiple indexers available

### ISSUE THREAD

**Issue by lorond** [sebastienros/jint#352]
Test case:

    static void Main()
    {
        var e = new Engine();
        e.SetValue("test", new TestIndexer());
        e.Execute(@"test[0]");
        Console.WriteLine(e.GetCompletionValue());
    }

    public class TestIndexer
    {
        public string this[object key]
        {
            get { return "object: [" + (key == null ? "null" : key.GetType().Name) + "] " + key; }
        }

        public string this[int key]
        {
            get { return "integer: " + key; }
        }
    }

Result is: `object: [String] 0`
Despite the fact that number was used as a indexer parameter, indexer with `object` parameter was selected.
The problem is that `key` parameter in `IndexDescriptor` is a string regardless of what value actually was passed.

Also indexers in `TestIndexer` could be reordered:

    static void Main()
    {
        var e = new Engine();
        e.SetValue("test", new TestIndexer());
        e.Execute(@"test[0]");
        Console.WriteLine(e.GetCompletionValue());
        e.Execute(@"test['str']");
        Console.WriteLine(e.GetCompletionValue());
    }

    public class TestIndexer
    {
        public string this[int key]
        {
            get { return "integer: " + key; }
        }

        public string this[object key]
        {
            get { return "object: [" + (key == null ? "null" : key.GetType().Name) + "] " + key; }
        }
    }

Result is `integer: 0` on `test[0]` script and `FormatException` thrown on `test['str']` script, as `str` cannot be converted to int (look like first found indexer was cached and used later).

But if you reorder `test[0]` and `test['str']`:

    static void Main()
    {
        var e = new Engine();
        e.SetValue("test", new TestIndexer());
        e.Execute(@"test['str']");
        Console.WriteLine(e.GetCompletionValue());
        e.Execute(@"test[0]");
        Console.WriteLine(e.GetCompletionValue());
    }

Result is:

    object: [String] str
    object: [String] 0

Indexer with `object` key used for both `test['str']` and `test[0]` (again, looks like once found it was cached).

**Comment by lahma** [comment]
This has been probably fixed in current preview builds. We can reopen if still an issue.
