### ISSUE TITLE
How do I access a method on an object within Jint

### ISSUE THREAD

**Issue by CarbonMan** [sebastienros/jint#356]
This is not an issue, but more of a noob question.

Using .Execute(...) I load the Jint engine with this script

var myObj = function IoTkey() {
    var parameters = {};

    this.received = function (id, value) {
        var result = JSON.parse(value);
        return result.value;
    };
    this.request = function (id) {
        var req = {id:id, type:"get"};
        return req;
    };
 };

Next I try and access the myObj variable. My code is
result = engine.Execute("myObj.request()").GetCompletionValue();
which results in an error
"Object has no method 'request'"
What am I doing wrong?
Thanks.

**Comment by Jugolo** [comment]
Try to change 
engine.Execute("myObj.request()").GetCompletionValue();
To
engine.Execute("(new myObj()).request()").GetCompletionValue();

This should work ;) 

Hilsen Ronnie
