### ISSUE TITLE
Json.parse with a long string of the escape character is very time-consuming, what is the solution to it

### ISSUE THREAD

**Issue by Chenfengf** [sebastienros/jint#357]
Hi,
I have a uwp project that uses our jint engine.
When I am using json.parse () method to analysis the time with the escape character of a string and long will be very time-consuming, but if the string with escape short words is very fast
For more details, please see the attached
[App3.zip](https://github.com/sebastienros/jint/files/654233/App3.zip)

**Comment by sebastienros** [comment]
Would you have time to do some little investigation on your side by debugging what it's doing, or even better running a profiler on your test?

**Comment by Chenfengf** [comment]
Hi:
    The sample is simple, just to invoke 'JSON.parse' to prase a string with jint 2.10.2 .
    
    The main code is as followed:
            
            var add = new Engine();
           
            var file = Windows.Storage.StorageFile.GetFileFromApplicationUriAsync(new Uri("ms-appx:///res/ssx.json")).AsTask().Result;
            

            string data = FileIO.ReadTextAsync(file).AsTask().Result;//return 155kb json string

            add.Execute("function add(a) { return JSON.parse(a) ; }");            
            var result1 = add.Invoke("add", data);

    'parse' code consume about 10 second. Compare with v8 in android and JSCore in ios, the duration are all less than 500 millisecond.

    It should be mentioned that the content of the 'ssx.json' is a JSON string after invoked 'JSON.stringify',just like:
            {\"key\":\"value\"}
    If changed the content to JSON object like
            {"key":"value"}
    The 'JSON.parse' is very fast.

    Is there any good solution?
[ssx.zip](https://github.com/sebastienros/jint/files/659972/ssx.zip)
