### ISSUE TITLE
[question]Any idea about create WPF window in JS?

### ISSUE THREAD

**Issue by G-monitor** [sebastienros/jint#359]
I'm trying to create a WPF Window in javascript without "AllowClr".
My test code: [gist](https://gist.github.com/G-monitor/c94483c39de952cb4eaee20800f0254d)

I tried to call `window.Show();` in javascript, and it gives me an error "The calling thread cannot access this object because a different thread owns it".
Then I tried to run in STA thread ([code](https://gist.github.com/G-monitor/c94483c39de952cb4eaee20800f0254d#file-program-cs-L46)), got the same error again.
![STARun Error](https://cloud.githubusercontent.com/assets/11240579/21547827/6f6aeda4-ce23-11e6-961d-56b53b147fb4.png)

I tried `window.Dispatcher.InvokeAsync()` too ([code](https://gist.github.com/G-monitor/c94483c39de952cb4eaee20800f0254d#file-program-cs-L131)), and it's auto cancel/aborted.(really dont know why, it's should work in normal C#)
![Canceled Task](https://cloud.githubusercontent.com/assets/11240579/21548103/2843bb66-ce25-11e6-9e53-84c4ee7c262a.png)

Run `window.Dispatcher.Invoke` in javascript ([code](https://gist.github.com/G-monitor/c94483c39de952cb4eaee20800f0254d#file-program-cs-L56)) not get any exception, but seems not woking too.

Any idea?

**Comment by doronguttman** [comment]
http://stackoverflow.com/questions/9732709/the-calling-thread-cannot-access-this-object-because-a-different-thread-owns-it

**Comment by G-monitor** [comment]
@doronguttman thanks, but I tried this. It's not woking in javascript side.[code](https://gist.github.com/G-monitor/c94483c39de952cb4eaee20800f0254d#file-program-cs-L56)

**Comment by doronguttman** [comment]
Just for the sake of it... Can you try creating a poco class that has one
method that creates the window you want, then call that method from jint?
Obviously please make sure it works if called from the .Net code first.
The next step would be to split that method to several others and see which
part doesn't work from jint

**Comment by G-monitor** [comment]
solved 😃
