### ISSUE TITLE
JSON.stringify breaks floats

### ISSUE THREAD

**Issue by mazhuravlev** [sebastienros/jint#362]
`engine.Execute(@"var o = {z: 99.20 * 0.23, x: "dfdf"}; return JSON.stringify(o);");`
returns 
`{"z":22.,816000000000003,"x":"dfdf"}`
There is a unneeded extra dot before the comma.

**Comment by sebastienros** [comment]
So, was it a non-issue?

**Comment by mazhuravlev** [comment]
Duplicate of [Number toFixed() incorrectly rounds fractions and negative numbers #158](https://github.com/sebastienros/jint/issues/158)
Still doesn't work in version 2.10.3

**Comment by sebastienros** [comment]
thanks, will fix

**Comment by RhinoDevel** [comment]
I guess this is related - I reproduced this behavior with v2.10.3 and 2.9.1:

    Jint.Engine e = new Jint.Engine();
    const string n = "n";

    //e.SetValue(n, "{\"a\":53.6841659}"); // => Leads to same problem.
    e.SetValue(n, "[53.6841659]");

    Jint.Native.JsValue val = e.Execute("var o = JSON.parse(n);JSON.stringify(o);").GetCompletionValue();

    Console.WriteLine(val.AsString()); // => Output: "[53.,6841659]"

**Comment by RhinoDevel** [comment]
Pull request here: https://github.com/sebastienros/jint/pull/369
