### ISSUE TITLE
regex state wrongly shared cross functions

### ISSUE THREAD

**Issue by superyyrrzz** [sebastienros/jint#364]
I'm using Jint 2.10.3 and meet a bug in regex. See the example below:

```cs
var engine = new Engine().SetValue("log", new Action<object>(Console.WriteLine));

engine.Execute(@"
    var url = 'https://www.example.com';

    log(/^(\w+:)?\/\//g.test(url));  // return true
    log(/^(\w+:)?\/\//g.test(url));  // return true
    log(/^(\w+:)?\/\//g.test(url));  // return true
    
    log(isAbsolutePath(url)); // return true
    log(isAbsolutePath(url)); // return false ???
    log(isAbsolutePath(url)); // return true

function isAbsolutePath(path) {
    return /^(\w+:)?\/\//g.test(path);
}
");
```

I assume 6 "true"s should be loged, but actually there's a "false". Seems the regex in different function calls is optimized to using the same regex object, and the state is saved.

**Comment by doronguttman** [comment]
look here:
http://stackoverflow.com/questions/1520800/why-regexp-with-global-flag-in-javascript-give-wrong-results

**Comment by superyyrrzz** [comment]
@doronguttman I know the result may change if I use the **same** regular expression object to test string. If I use `/^(\w+:)?\/\//g.test(url)` directly, it should not track the `lastIndex`.

**Comment by doronguttman** [comment]
When you create the function it saves the regex as an instance in the
closure. So it is the same instance.
That is why you are getting the unexpected result when calling your
function instead of calling a new instance every time.
I do agree with you, however, that this is not the expected behavior.

**Comment by superyyrrzz** [comment]
Interesting. Seems it's the root cause 👍

**Comment by sebastienros** [comment]
@doronguttman 

>I do agree with you, however, that this is not the expected behavior.

You mean this is actually a bug in Jint

**Comment by doronguttman** [comment]
Don't know if it is a bug in jint, but v8 behaves differently.

**Comment by superyyrrzz** [comment]
@sebastienros I come cross this issue when upgrading Jint from 2.5.0 to 2.10.3

**Comment by sebastienros** [comment]
I have a tentative fix, not sure it works yet as I couldn't compile locally so I am trying this on the CI directly. But I understand the problem and how Jint is wrong.

**Comment by sebastienros** [comment]
Looks like all is good now. If you need I can ship a new version on nuget.

**Comment by superyyrrzz** [comment]
Yes, I need a new version on nuget. Thank you for your quick fix!

**Comment by superyyrrzz** [comment]
Hi @sebastienros , would you please ship a new version on nuget?

**Comment by vicancy** [comment]
HI @sebastienros , is the latest package containing this fix?
