### ISSUE TITLE
Line Numbers Incorrect

### ISSUE THREAD

**Issue by wewake4** [sebastienros/jint#365]
Hi,

I am getting Parser Exception Line Numbers wrongly.

'use strict';
var mainScript = {
  whileApplicationRunTimer: 1000
  whileApplicationRun: function () {
   },
  onApplicationUnload: function () {
    }
};

> , is missing in Line 3 but Parser Exception gives the line no as Line 5.

My C# code
try
            {
                var engine = new Engine();
                engine.Execute(richTextBox1.Text);
            }
            catch (Jint.Parser.ParserException ex)
            {
                MessageBox.Show(ex.LineNumber + ex.Message);
            }
            catch (Jint.Runtime.JavaScriptException ex)
            {
            }

Please let me know is their any issue with my implementation.

**Comment by lahma** [comment]
It seems that v3 handles this nicely reporting correct line numbers, can reopen if there's another repro.
