### ISSUE TITLE
dtoa is slower than System.Convert.ToString()

### ISSUE THREAD

**Issue by imacks** [sebastienros/jint#368]
I did this quick test off my surface pro 3. Does this mean we are better off without FastDtoa?

`
void Main()
{
	var r = new Random();
	Stopwatch t = new Stopwatch();
	string a;
	
	int i = 0;
	t.Start();
	while (i < (int.MaxValue / 100))
	{
		i += 1;
		a = Convert.ToString(r.NextDouble());
	}
	t.Stop();
	Console.WriteLine("Using Convert.ToString() --- {0}", t.Elapsed);
	t.Reset();

	i = 0;
	t.Start();
	while (i < (int.MaxValue / 100))
	{
		i += 1;
		a = FastDtoa.NumberToString(r.NextDouble());
	}
	t.Stop();
	Console.WriteLine("Using FastDtoa --- {0}", t.Elapsed);
	t.Reset();
}

// Using Convert.ToString() --- 00:00:06.4969824
// Using FastDtoa --- 00:00:15.8320978

`

**Comment by sebastienros** [comment]
Interesting actually, would not have thought that, but I did it mostly for conformance reasons.

Can you try these values are correctly rendered by Convert.ToString?

                assert(String(14.915832707045631) === '14.915832707045631');
                assert(String(-14.915832707045631) === '-14.915832707045631');
                assert(String(0.5) === '0.5');
                assert(String(0.00000001) === '1e-8');
                assert(String(0.000001) === '0.000001');
                assert(String(-1.0) === '-1');
                assert(String(30.0) === '30');
                assert(String(0.2388906159889881) === '0.2388906159889881');

**Comment by sebastienros** [comment]
Oh, and by the way, instead of using a random double which will have an integral value, try with a decimal number.

**Comment by imacks** [comment]
14.915832707045631 -> 14.9158327070456
-14.915832707045631-> -14.9158327070456
0.000001 -> 1E-06
0.2388906159889881 -> 0.238890615988988

Yeah I see your point. System.Convert is missing out on 2 pts.

Random double gets a value between 0 to 1. I have also tried real numbers larger than 1 but still about 3x slower than Convert.
