### ISSUE TITLE
Compile for .NET Framework 3.5

### ISSUE THREAD

**Issue by styfle** [sebastienros/jint#37]
I am trying to compile with the target framework .NET Framework 3.5 since the NuGet only supports 4.0 or higher.

It looks the `JsValue.cs` class is the only one with compiler errors.

```c#
using System.Diagnostics.Contracts;
using System.Dynamic;
```

After removing those imports I also removed the `[Pure]` attributes but the last thing was the `ExpandoObject` which appears to be part of the dynamic namespace. I replaced that with `Dictionary<string,object>` and so far so good.

Maybe consider adding support for 3.5? If not, then others can reference these changes.

**Comment by jgriffith** [comment]
sharepoint 2010 runs .net 3.5     If we could support 3.5 then in theory we could provide server side scripting capabilities to sharepoint.

**Comment by kissxrl** [comment]
Winform    Many places need to  Net2 / 3.5

**Comment by Nogrod** [comment]
created a fork with .net 3.5 support if anyone is interested

**Comment by longde123** [comment]
i done a fork with .net 3.5  

https://github.com/longde123/jint


it work unity 3d  if anyone is interested

**Comment by flts** [comment]
I also created a .NET Compact Framework 3.5 port: 
https://github.com/flts/jint

**Comment by styfle** [comment]
It's been over 2 years and I no longer need 3.5 support. I'll just close this.
