### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by PierreLucB** [sebastienros/jint#370]
Hi there,

I think I found a memory leak in Jint. I'm using it within AngleSharp in a foreach loop.
My memory increase and I have a OutOfMemoryException after a while.

GC.Collect() doesn't reduce the memory.

Those are the objects which takes many memory :

Dictionary<String, Jint.Runtime.Descriptors.PropertyDescriptor>
Jint.Runtime.Descriptors.PropertyDescriptor
Jint.Runtime.Interop.ClrFunctionInstance
Jint.Runtime.MruPropertyCache2<String, Jint.Runtime.Descriptors.PropertyDescriptor>

I'm using AngleSharp 0.9.9 with Jint 2.9.1.

Have you encounter the problem ?

Thanks.

Pierre-Luc

**Comment by sebastienros** [comment]
Can you provide a repro? Maybe you are just not releasing some objects after some time.

I will try to repro by doing the same thing as on the other issue you commented, if you can create a console app the reproduces the issue in a very simple way that would be very helpful.

**Comment by sebastienros** [comment]
Here some code I am running and can't repro your issue. I intentionally use reflection.

```
			var step = 0;
			while(true)
			{
				var e = new Engine();
				e.SetValue("foo", new Point());
				var v = e.Execute("foo.x = 3; foo.x;").GetCompletionValue().AsNumber();

				if (v != 3)
				{
					throw new Exception();
				}

				if (step++ == 1000)
				{
					step = 0;
					Console.Write(".");
					GC.Collect();
				}
			}
```

with 
```
	public class Point
	{
		public int X;
	}
```

You can also use a memory profiler to find out what is holding a reference on the root objects.

**Comment by sebastienros** [comment]
I am using 2.10.4

**Comment by sebastienros** [comment]
@PierreLucB any information on the reason you closed it? Hopefully you found there were no issues with Jint?
