### ISSUE TITLE
for-in loop through string

### ISSUE THREAD

**Issue by Rast1234** [sebastienros/jint#371]
Hello. I am not sure if this behavior is defined in any JS-related standard, but i see Firefox and Chromium doing this:

    for(i in 'abc'){i}
    // results in "2"
    // with Jint, reslts in nothing

I overcame this with `for(i in 'abc'.split('')){i}` but this works in Jint:

    'abc'[2]

so i think for-in loop should work as well.

**Comment by sebastienros** [comment]
I have created a PR fixing this.
However the specification doesn't mention this behavior. The for-in statement is supposed to enumerable the [[Enumerable]] keys, but he String object doesn't specify that its keys should contain the indices.

https://www.ecma-international.org/ecma-262/5.1/#sec-12.6.4

Could it be a new behavior in ECMA 6.0 (or later)

**Comment by sebastienros** [comment]
Actually I found a test that was related and it validates the issue is real.
The spec mentions "property names" so I adapted the code.

**Comment by Rast1234** [comment]
thank you for your quick reply and fix! 👍
