### ISSUE TITLE
How to let to work with dapper?

### ISSUE THREAD

**Issue by ringls** [sebastienros/jint#373]
I try to use dapper like this:

```
 [HttpGet]
        public string JIntTest() {
            Stopwatch sw = new Stopwatch();
            sw.Start();
            SqlConnection sc = new SqlConnection("Server=127.0.0.1;Database=dbtest;User Id=sa;Password=123;");
            var engine = new Engine(cfg => cfg.AllowClr()).SetValue("sc",sc);
            engine.Execute("function getList() { return  sc.Query(\"select * from users where 1=1\").ToList(); }");
            engine.Invoke("getList");  
            sw.Stop();
            return sw.ElapsedMilliseconds.ToString() + "\r\n";
        }
```

but it has error.Object has no method 'Query'.

it looks like jint no support c# Extended method.

how do i do?

**Comment by sebastienros** [comment]
If you mean that Query is an extension method then it's possible that it's not supported. Try to call the static method from the static class instead: `SqlMapper.Query(connection, ...)` and you will need to add the SqlMapper namespace in the engine options, or pass it using a TypeReference like it's described in the readme file.

**Comment by sebastienros** [comment]
BTW, maybe you should provide a more javascript friendly API to your scripts. Like create your own class with simple methods to do queries. If you intend to let people write scripts and do queries it makes more sense usually.

**Comment by ringls** [comment]
thank you very much.
I create a c# class with owner methods, and it works very well.
