### ISSUE TITLE
Const is behaving as var

### ISSUE THREAD

**Issue by Happypig375** [sebastienros/jint#379]
According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const reassigning to a const should fail. However, `const A = 4; A = 6;` does not fail and reassigns the constant.

**Comment by Happypig375** [comment]
Another example: redeclaring a variable with the same name as a constant should fail
`const ff = 9;
var ff = 3;
var ff = 4;
const ff = 1;
var ff = 2;
ff` outputs 2.

**Comment by sebastienros** [comment]
I assume this is because it's only supported in es6, which jint doesn't handle yet.
