### ISSUE TITLE
"A numeric comparison was attempted on "$(TargetPlatformVersion)"" project error

### ISSUE THREAD

**Issue by Daniel15** [sebastienros/jint#38]
Not sure if it's a Jint issue or an issue with my environment, but I'm getting this error when trying to open the Jint solution using Visual Studio 2013:

```
A numeric comparison was attempted on "$(TargetPlatformVersion)" that evaluates to "" instead of a number, in condition "'$(TargetPlatformVersion)' > '8.0'"
```

I searched around and some people reported getting this with ReSharper 8.2. I'm only on ReSharper 8.1 so I don't think that's the same issue.

Edit: `msbuild jint.sln` works fine so I'm using that to build

**Comment by kant2002** [comment]
I have this error when adding ApplicationInsights to the project.
I add ApplicationInsights to the already existing project.
