### ISSUE TITLE
deprecated functions not available?

### ISSUE THREAD

**Issue by girishjjain** [sebastienros/jint#380]
Am getting below exception:
JavaScriptException: unescape is not defined

I understand the unescape function has been deprecated but I don't own the JavaScript library that I am referring to. If I understand correctly, this function should still be supported as per ECMAScript 5.1 specification:

http://www.ecma-international.org/ecma-262/5.1/#sec-B.2.2

Kindly suggest.

**Comment by sebastienros** [comment]
I can't disagree with that, I can see that browsers still have these.
We could have it as an option on the engine, but it can't hurt to have it by default.

This should be pretty straightforward to implement if you want to give it a try.

**Comment by girishjjain** [comment]
I can give it a try. I will clone the repo and would try to go through code. If you could give some initial pointers to get quickly up with code, that would help. Thanks.

**Comment by sebastienros** [comment]
As an example for `escape` look at how `escapeURIComponent` is implemented https://github.com/sebastienros/jint/blob/d098d6e0242acaa89cfac7bde1e8fe62bdb51593/Jint/Native/Global/GlobalObject.cs#L384 and added to the Global Object https://github.com/sebastienros/jint/blob/d098d6e0242acaa89cfac7bde1e8fe62bdb51593/Jint/Native/Global/GlobalObject.cs#L61

You will find that most of the implementation is just following what the specification states for this method. So it should be simple to find out how which specification step for `escape` means, as it should be similar to `escapeURIComponent`.

Then similarly you can add the `substr` method to the `StringPrototype` class as the spec states. There are lots of method examples for this class.

Finally please provide some unit tests to ensure the methods work as expected, in the `EngineTests` class.

**Comment by girishjjain** [comment]
@sebastienros  I have implemented escape function and created pull request. If that looks good, will make changes for unescape function and submit another pull request.

**Comment by girishjjain** [comment]
Hi @sebastienros Can you take a look at the pull request? Thanks.

**Comment by sebastienros** [comment]
Merged, sorry for the delay, I must have missed the notification when you submitted it.
