### ISSUE TITLE
Calling .Net method with System.Action delegate argument from JS fails

### ISSUE THREAD

**Issue by genemars** [sebastienros/jint#39]
Calling a .Net method which has an argument of type System.Action fails: 

"No public methods with the specified arguments were found." 

The function is defined as:

```
public void Setup(Action functionBlock)
```

and called from Javascript as:

```
hg.Program.Setup(function(){
    // ...
});
```

other methods which belong to hg.Program class work fine.

**Comment by daveng-deep2** [comment]
@genemars https://atom-editor-allowable88.github.io/tanstack/
