### ISSUE TITLE
System.OverflowException

### ISSUE THREAD

**Issue by MagicIsArt** [sebastienros/jint#391]
In my code:
`js.Execute("log(eval(0x5973772948c653ac1971f1576e03c4d4))");`

not work.

But work in browser.
![image](https://user-images.githubusercontent.com/20385368/27309376-2cf10a06-555c-11e7-86f7-029777d4a211.png)

**Comment by MagicIsArt** [comment]
How i can create this method( 0x5973772948c653ac1971f1576e03c4d4 ) in C# ?

**Comment by WestDiscGolf** [comment]
@MagicIsArt What is the value you are trying to evaluate? I'm unsure there is a way to represent the value directly. I have tried, briefly, a couple of ways with the specific value but no joy.
