### ISSUE TITLE
CLR exceptions are not caught from CLR classes instantiated in JS

### ISSUE THREAD

**Issue by SammyROCK** [sebastienros/jint#393]
When creating a TypeReference of a CLR type with Jint, instantiating the class inside JS and calling any of it's functions that throws an exception the JS cannot catch CLR exceptions.

**Comment by sebastienros** [comment]
Should have been fixed by this PR, maybe it's not yet on nuget: https://github.com/sebastienros/jint/pull/374

Let me know if this is not what you meant

**Comment by SammyROCK** [comment]
No, it's not it. I'm going to Pull Request soon, that's why I didn't bother to go into much detail yet.
