### ISSUE TITLE
System.Console.WriteLine example no longer works

### ISSUE THREAD

**Issue by koromorix** [sebastienros/jint#395]
```cs
var engine = new Jint.Engine(cfg => cfg.AllowClr());
engine.Execute("System.Console.WriteLine('hello');");
```

Based on the [readme](https://github.com/sebastienros/jint#accessing-net-assemblies-and-classes) I would expect this to work. Instead I get: `Jint.Runtime.JavaScriptException: Invalid generic type parameter`.

**Comment by LegitSoulja** [comment]
@koromorix this is correct. I just tested this, and was not able to reproduce this exception.

**Comment by WestDiscGolf** [comment]
@koromorix can confirm it works in the latest dev branch. Please try again :-)

**Comment by stefano77it** [comment]
I'm having the same issue with .NET Core 3.1 but not with .NET Framework 4.7.2.

I wrote the following two sample test cases.

**_sample not working on .NET Core 3.1_**
[online snippet](https://dotnetfiddle.net/QMYNtg)

	using System;
	using Jint;

	public static class Program
	{
		public static void Main()
		{
			var engine = new Engine(cfg => cfg.AllowClr());
			string script;
			engine.Execute("System.Console.WriteLine('hello');");  // TypeError: Invalid generic type parameter
			script = "System.IO.File.Exists('test.txt')";
			Console.WriteLine(engine.Execute(script).GetCompletionValue());  // TypeError: Invalid generic type parameter
			script = "System.IO.File.Create('test.txt').Dispose()";
			Console.WriteLine(engine.Execute(script).GetCompletionValue());  // TypeError: Invalid generic type parameter
			script = "System.IO.File.Exists('test.txt')";
			Console.WriteLine(engine.Execute(script).GetCompletionValue());  // TypeError: Invalid generic type parameter
			script = "System.IO.File.Delete('test.txt'); System.IO.File.Exists('test.txt');";
			Console.WriteLine(engine.Execute(script).GetCompletionValue());  // TypeError: Invalid generic type parameter
			Console.WriteLine(engine.Execute("System.DateTime.Now").GetCompletionValue());  // this works also on .NET Core
		}
	}

**_sample working on .NET Framework 4.7.2_**
[online snippet](https://dotnetfiddle.net/81vVKc)

	using System;
	using Jint;

	public static class Program
	{
		public static void Main()
		{
			var engine = new Engine(cfg => cfg.AllowClr());
			string script;
			engine.Execute("System.Console.WriteLine('hello');");
			script = "System.IO.File.Exists('test.txt')";
			Console.WriteLine(engine.Execute(script).GetCompletionValue());
			script = "System.IO.File.Create('test.txt').Dispose()";
			Console.WriteLine(engine.Execute(script).GetCompletionValue());
			script = "System.IO.File.Exists('test.txt')";
			Console.WriteLine(engine.Execute(script).GetCompletionValue());
			script = "System.IO.File.Delete('test.txt'); System.IO.File.Exists('test.txt');";
			Console.WriteLine(engine.Execute(script).GetCompletionValue());
			Console.WriteLine(engine.Execute("System.DateTime.Now").GetCompletionValue());
		}
	}

**Comment by stefano77it** [comment]
I found a way to resolve the error with .NET Core 3.1, replacing the line 

    var engine = new Engine(cfg => cfg.AllowClr());

with

    var engine = new Engine(cfg => cfg.AllowClr(typeof(System.IO.File).Assembly, typeof(System.Console).Assembly));

the [fiddle](https://dotnetfiddle.net/QMYNtg) is updated and was tested with Jint version 3.0.0-beta-1632 and 2.11.58
