### ISSUE TITLE
ArrayInstance : should provide native accessors to length and indexed values

### ISSUE THREAD

**Issue by MaitreDede** [sebastienros/jint#396]
Hi,
I am using Jint 2.10.4 (nuget). I am trying to write code between C# and javascript.

I am exposing a function, that takes an array as parameters. The native function is :
```
        public void MyFunc(JsValue argValue)
        {
            ArrayInstance args = argValue.AsArray();
            //code
        }
```

Is it possible to expose natively the Length property of the array (as readonly) ? So I could write `for(int i=0; i<args.Length;i++)` and also expose an indexer so array can be acessed easily `JsValue item = args[i]` ?

Thanks.

**Comment by MaitreDede** [comment]
Also, if possible, add a `ToArray()` method to have `JsValue[] values = args.ToArray();`.

**Comment by krzysztof90** [comment]
For now you can use
`foreach (JsValue item in args.GetOwnProperties().Select(p => p.Value.Value))`

**Comment by lahma** [comment]
The 3.x has Length and indexer with get support, I'll close this as original request has been fulfilled.
