### ISSUE TITLE
PropertyDescriptor with setter null throws NullReferenceException

### ISSUE THREAD

**Issue by MaitreDede** [sebastienros/jint#398]
Hi,

Using Jint 2.10.4 (nuget).
I have added a property to an object using a code of this kind :
```
        private void Sample(Engine engine)
        {
            ObjectInstance myobj = engine.Object.Construct(Arguments.Empty);

            Func<string> nativeDelegate = () => "Hello world";
            JsValue getter = JsValue.FromObject(engine, nativeDelegate);
            JsValue setter = JsValue.Null;

            myobj.DefineOwnProperty("prop", new PropertyDescriptor(getter, setter, true, false), true);
        }
```
So the property is "readonly".

When I try to call `obj.prop = 'newvalue'`, I should have a Javascript Error, but instead, I have a NullReferenceException.

Here is the line it is thrown : https://github.com/sebastienros/jint/blob/master/Jint/Native/Object/ObjectInstance.cs#L194

**Comment by MaitreDede** [comment]
Maybe the [test in CanPut](https://github.com/sebastienros/jint/blob/master/Jint/Native/Object/ObjectInstance.cs#L219) should also test `null` ?

**Comment by lahma** [comment]
Tested with 3.x line an no longer a problem there. You should upgrade from 2.x to 3.x betas as they are as well tested, faster and offer more features.
