### ISSUE TITLE
Don't support "return" in scripts.

### ISSUE THREAD

**Issue by wcbzcy** [sebastienros/jint#400]
var square = new Engine()
        .SetValue("x", 3) // define a new variable
        .Execute("return x * x;") // execute a statement
        .GetCompletionValue() // get the latest statement completion value
        .ToObject(); // converts the value to .NET

Run the sample code: Error -  Illegal return statement

Or other solution for my case. I try set the javascript code in Function run is OK, but i can't wrap it to function because product design.

Thanks,

**Comment by Happypig375** [comment]
I think it is standard JavaScript that does not allow return statements...
```
var square = new Engine()
.SetValue("x", 3) // define a new variable
.Execute("x * x") // execute a statement
.GetCompletionValue() // get the latest statement completion value
.ToObject(); // converts the value to .NET
```
^^ Do it like this

**Comment by sebastienros** [comment]
Correct, `return` is part of a function's body. @Happypig375  shows the correct way to do it.
You can also assign the value to a variable, then do `square.GetValue("y")` from your code.
