### ISSUE TITLE
Strict comparison of objects

### ISSUE THREAD

**Issue by MaitreDede** [sebastienros/jint#401]
Hi,
For the strict equality comparison operator (the `===`), I have a NullReferenceException.
The code is here : https://github.com/sebastienros/jint/blob/master/Jint/Runtime/ExpressionIntepreter.cs#L479-L488
```
			if (typea == Types.Object)
			{
				var xw = x.AsObject() as IObjectWrapper;

				if (xw != null)
				{
					var yw = y.AsObject() as IObjectWrapper;
					return Object.Equals(xw.Target, yw.Target);
				}
			}
```

In my case, `y` is not null, but not a `IObjectWrapper`. So `yw` is null, thus throwing an exception.

**Comment by lahma** [comment]
Closing as obsolete, should work with 3.x line nicely.
