### ISSUE TITLE
No line number in errors when "x.a < x.b" and x is null

### ISSUE THREAD

**Issue by christianrondeau** [sebastienros/jint#403]
When executing the following JavaScript:

    var x = undefined;
    var y = x.a < x.b;

I only get a generic `TypeError` exception, and the `engine.GetLastSyntaxNode().Location` property is null, so I can't tell what the problem is, nor where it happened.

To be specific, the problem happens here: https://github.com/sebastienros/jint/blob/2367a263dc81ed4e8ef83520e46faec76d570e77/Jint/Runtime/ExpressionIntepreter.cs#L760

I'm not sure why the location is not set for this specific cases. Pointers would be useful, since I won't have time to look into this for a while (this actually was an old _to do_ from March 2015, and I then hoped the problem would magically go away :P )

**Comment by psistorm** [comment]
I also have found this error quite annoying multiple times. It would be really helpful to get more information on where the "NullPointerException" occurred in the Script to be able to resolve it.

**Comment by sebastienros** [comment]
Can you try the dev branch (it's also on myget as a package), @ayende created a PR two days ago that displays this kind of message and a better stack trace.

**Comment by psistorm** [comment]
Awesome! Looks really good to me. Having the line number with this message will be really helpful.

**Comment by christianrondeau** [comment]
That's amazing! This was on my todo list for a long time now :) Any plans to update the NuGet package with this, or did you plan on waiting for more stuff? (Note: I didn't try it yet)

**Comment by sebastienros** [comment]
I am closing this issue and releasing the nuget package (it's automatic as I merge in master).

**Comment by christianrondeau** [comment]
For future readers: `engine.GetLastSyntaxNode().Location` is still null in the case of undefined objects exception, but it is set in the `JavaScriptException.Location` property :)
