### ISSUE TITLE
How to find my function in external js ?

### ISSUE THREAD

**Issue by HamedFathi** [sebastienros/jint#405]
I wrote code below 
    

    static void Main(string[] args)
        {
            var engine = new Engine();
            var file = File.ReadAllText(@"...\Desktop\beautify.js");
            var final = file + Environment.NewLine + "(function () {return js_beautify('var a = 2;');})();";
            var exec = engine.Execute(final);
            var r = exec.GetCompletionValue().ToString();
            Console.WriteLine(r);
            Console.Read();
    
        }

but the Jint show error

    Jint.Runtime.JavaScriptException: 'js_beautify is not defined'

How to register external js libraries like beautify.js and then call functions of them in Jint ?

**Comment by sebastienros** [comment]
This is some weird js syntax:
```
(function () {return js_beautify('var a = 2;');})();
```

What you should probably do is:
```
  var engine = new Engine();
  var file = File.ReadAllText(@"...\Desktop\beautify.js");
  var beautified = engine.Execute("js_beautify('var a = 2;'));
  var r = exec.GetCompletionValue().ToString();
  Console.WriteLine(r);
  Console.Read();
```

And you can also do this:
```
  var beautify = engine.GetValue("js_beautify");
  beautify.Invoke("var a = 2;");
```

**Comment by sebastienros** [comment]
Or,

```
engine.Invoke("js_beautify", "var a = 2;");
```

**Comment by HamedFathi** [comment]
@sebastienros 

Your first approach does not work, the same error as before `'js_beautify is not defined'`
I think `engine.Execute(file);` does not work!

Your last two approaches show me an error, a new one `'Can only invoke functions'`

**Comment by sebastienros** [comment]
I looked at the source and it seems that beautify tries to add itself to 'window' or 'global'. I will try this scenario as I think this is what is causing the issue.

**Comment by sebastienros** [comment]
Got the script to work. The issue is really in beautify.js, it's assuming too much of the host environment.

```
            var engine = new Engine().Execute("var global = {};").Execute(content);
            var js_beautify = engine.Execute("global.js_beautify").GetCompletionValue();
            var result = engine.Invoke(js_beautify, "var a = 2;").AsString();
```

**Comment by HamedFathi** [comment]
@sebastienros,

Thanks, works perfectly :)
