### ISSUE TITLE
Rebuild fails.

### ISSUE THREAD

**Issue by xatabhk** [sebastienros/jint#406]
Error occurred while restoring NuGet packages: The operation failed as details for project Jint could not be loaded.
1>------ Rebuild All started: Project: Jint, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>Done building project "Jint.csproj" -- FAILED.
1>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>Done building project "Jint.csproj" -- FAILED.
2>------ Rebuild All started: Project: Jint.Benchmark, Configuration: Debug Any CPU ------
3>------ Rebuild All started: Project: Jint.Repl, Configuration: Debug Any CPU ------
4>------ Rebuild All started: Project: Jint.Tests, Configuration: Debug Any CPU ------
5>------ Rebuild All started: Project: Jint.Tests.Ecma, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint.Benchmark\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
2>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint.Benchmark\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
2>Done building project "Jint.Benchmark.csproj" -- FAILED.
6>------ Rebuild All started: Project: Jint.Tests.CommonScripts, Configuration: Debug Any CPU ------
6>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint.Tests.CommonScripts\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
6>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint.Tests.CommonScripts\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
6>Done building project "Jint.Tests.CommonScripts.csproj" -- FAILED.
4>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
4>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
4>Done building project "Jint.Tests.csproj" -- FAILED.
3>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint.Repl\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
3>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint.Repl\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
3>Done building project "Jint.Repl.csproj" -- FAILED.
5>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint.Tests.Ecma\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
6>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint.Tests.CommonScripts\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
6>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint.Tests.CommonScripts\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
4>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
6>Done building project "Jint.Tests.CommonScripts.csproj" -- FAILED.
4>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
4>Done building project "Jint.Tests.csproj" -- FAILED.
5>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint.Tests.Ecma\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
5>Done building project "Jint.Tests.Ecma.csproj" -- FAILED.
5>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint.Tests.Ecma\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
5>C:\Program Files (x86)\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\temp\mx_104\Temp\OpenWorking\Open\dev\jint\Jint.Tests.Ecma\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
5>Done building project "Jint.Tests.Ecma.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 6 failed, 0 skipped ==========

**Comment by LegitSoulja** [comment]
@xatabhk try rebuilding nuget

**Comment by lahma** [comment]
This relates to project system / NuGet, nothing to do on Jint's side.
