### ISSUE TITLE
Null propagation?

### ISSUE THREAD

**Issue by ayende** [sebastienros/jint#409]
I'm 99% sure that this is going to be rejected, but our usage of Jint requires us to allow users to do things like:

```
return a.foo.bar.baz;
```

Where any of the above may be missing. 

The actual change is tiny:
https://github.com/ravendb/jint/commit/0470590a43d28dd5813b4fc1361388f219b0d02f

But it allows much nicer integration, and obviously this is protected by a feature flag.

**Comment by sebastienros** [comment]
This is something we use a lot in Orchard actually, using dynamic objects. We call it the Nil behavior.

But you are right this is not acceptable as is. Can we find a solution where we could change some logic by configuration, and you could plug your own? Like when the property is resolved? I will take a look too.

**Comment by sebastienros** [comment]
The idea is that I don't want to have to support unsupported behaviors ... and looking at your changes they are pretty limited. Can you find a solution when this piece of code you changed in Engine.cs can be replaced based on configuration, like externalizing from Engine? The default implementation will be the same, then you can plug yours easily.

Something likely called `IReferenceResolver`.
