### ISSUE TITLE
SyntaxError when evaluating 09/100

### ISSUE THREAD

**Issue by Waynezhi** [sebastienros/jint#418]
got error when calling Execute("09/100") ?

**Comment by sebastienros** [comment]
That's not a valid program. Try to create a function, or `var x = 09/100`;

**Comment by Waynezhi** [comment]
could you please give an example of EvaluateExpression ? @sebastienros

**Comment by sebastienros** [comment]
`EvaluateExpression` is used when passing an AST to it, an object representation, which is also the result of a parsed expression. I don't think you need to use it, or at least it's not related to this issue you opened,

All the examples are on the readme.md file.
