### ISSUE TITLE
Mapping between NuGet package versions and GitHub exact sources

### ISSUE THREAD

**Issue by f-camera** [sebastienros/jint#419]
Hi,
as of today I can see the latest stable NuGet package version is 2.11.23. At the same time I see here on GitHub releases up to [2.11.10](https://github.com/sebastienros/jint/releases/tag/2.11.10) .

For internal regulations I have to archive the sources of the packages I use and I'm looking for a way of relating binaries and sources.
Should I assume they have not been modified since 2.11.10?
Would it be possible to adopt something like this way of making it known [https://www.nuget.org/packages/Microsoft.CodeAnalysis/2.3.2](https://www.nuget.org/packages/Microsoft.CodeAnalysis/2.3.2) where in the description you can find the info?

Thank you very much in advance.

**Comment by f-camera** [comment]
I think I found myself a partial answer: I looked at [https://ci.appveyor.com/project/SebastienRos/jint/build/23](https://ci.appveyor.com/project/SebastienRos/jint/build/23) I learn from the log that the changeset for package 2.11.**23** is fe76ca762055324963f595f0e7814d1c1adcb678 .

Is it correct?
I think it would be anyway useful to make it more evident.

Thanks again.

**Comment by sebastienros** [comment]
most probably

**Comment by lahma** [comment]
The 3.x beta releases now have source link support so it should cover this requirement.
