### ISSUE TITLE
Disposing of engine references

### ISSUE THREAD

**Issue by mtinnes** [sebastienros/jint#423]
Is there a method of releasing an existing engine which ensures all references and event callbacks are released? Something like `Engine.Dispose()`?  We have an issue where script engine references are hanging on to callbacks and not being released by the GC. When we go to execute a different script using a new Engine instance, the old callbacks are still being executed. No doubt this is because the old engine is still in memory and running.

**Comment by sebastienros** [comment]
There isn't, and I agree this is an issue. 

We should add a `Dispose` that will also remove the references to the properties in case they point to other external objects. Are you willing to do it?

**Comment by mtinnes** [comment]
I could take a stab at it but could use some guidance to familiarize with the code.

**Comment by sebastienros** [comment]
fell free to ask any question on the gitter rforum

**Comment by itswiki** [comment]
Is there still any one working on this? If not I'm going to give this a try next Monday. It would be pretty nice to have this :)

**Comment by tylerjwatson** [comment]
Hey @itswiki, let me necro this thread a bit.  Did you end up coming up with something concrete for this?  I'm coming up against a need for Engine to implement IDisposable as well.  Let me know :)

**Comment by itswiki** [comment]
@tylerjwatson No I did not sadly, personal life prevented me from working on this issue. Feel free to make your own pr (:

**Comment by sebastienros** [comment]
@mtinnes take a memory dump and open it in VS, it will show you which instances are still alive and what is holding onto it. You can also take snapshots and compare them.

**Comment by mtinnes** [comment]
Yep, I've been using the VS Diagnostic Tools to compare memory snapshots. From what I can tell any object added via:
```
public Engine SetValue(string name, object obj)
        {
            return SetValue(name, JsValue.FromObject(this, obj));
        }
```
Is not getting released when I call Dispose on the Engine. The value is added to the `GlobalObject` member of Engine in which I've also implemented `IDispose` for clearing and nullifying the following tables:

```
        private MruPropertyCache2<PropertyDescriptor> _intrinsicProperties;
        private MruPropertyCache2<PropertyDescriptor> _properties;
```

there must be a lingering reference somewhere I'm missing. Removing SetValue from the equation seems to fix things.

**Comment by sebastienros** [comment]
Call `GC.Collect()` to force collection before looking at the memory

**Comment by sebastienros** [comment]
can you also try with return `SetValue(name, new JsString("foo"));` to ensure it's not in the object wrapper?

**Comment by mtinnes** [comment]
I believe the issue is related to passing a dynamic typed object to SetValue. It's probably related more to the .NET runtime than Jint itself since passing a typed object seems to have fixed the issue.

**Comment by sebastienros** [comment]
Still valuable information. We should look into this or at least let it be known.

**Comment by lahma** [comment]
Maybe we should just close this issue by making `Engine` `IDisposable` with no-op implementation for now? Would future-proof it if needs arise.

**Comment by lahma** [comment]
I'm going to close this with a simple PR that just makes `Engine` implement `IDisposable`. Later can try to figure out per use case what the needs are. Like do we need some sort of disposal queue like in ASP.NET Core (which also adds some overhead).

We can reopen this if  needed or open more specific issues to track improvements.
