### ISSUE TITLE
sni.dll issue

### ISSUE THREAD

**Issue by ahmar20** [sebastienros/jint#426]
The latest version of Jint uses "sni.dll" and some APIs which are not supported in UWP system. That causes the store apps to fail certification due to security risks. Please improve it. Thanks

**Comment by sebastienros** [comment]
What target are you using ? netstandard1.3, net40, ...

**Comment by sebastienros** [comment]
I just added a netstandard2.0 target, can you try to get the package from the myget feed and test it?

**Comment by ahmar20** [comment]
How can I see the netstandard version from VS Community 2017? I think it should be the latest .Net 4.5 or 4.6 maybe. Your version 2.10.4 works fine and no issues in my project.

**Comment by sebastienros** [comment]
Can you check with the latest package I just released (2.11.58), I removed some package references that were related to SNI.

**Comment by sebastienros** [comment]
Closing to force people to comment ;)
