### ISSUE TITLE
Missing support for String.prototype.padStart() and padEnd()

### ISSUE THREAD

**Issue by aviv86** [sebastienros/jint#429]

**Comment by aviv86** [comment]
startsWith() and endsWith() are not supported as well

**Comment by WestDiscGolf** [comment]
Would the suggested implentations [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith) and [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith) be enough if implemented? Or would the more "fullfilled" pollyfills be required?

**Comment by sebastienros** [comment]
@WestDiscGolf if you intend to implement the other two ones, and anything else after all, please follow the reference implementation from the specification, and not MDN. It will be easier to understand. But feel free to use the test cases from MDN.

**Comment by WestDiscGolf** [comment]
@sebastienros sure thing! 👍
