### ISSUE TITLE
Module support

### ISSUE THREAD

**Issue by TheFlashBold** [sebastienros/jint#430]
Would it be possible to load modules, like node modules via require or something similar?

**Comment by tylerjwatson** [comment]
DISCLAIMER: I am the author of this module.

Check out [Jint.CommonJS](https://github.com/tylerjwatson/Jint.CommonJS) which is a basic CommonJS implementation for Jint.  Follow the instructions to get it to work. 

It is installable [from NuGet](https://www.nuget.org/packages/Jint.CommonJS).

Note:  You can't use it to load NPM modules.  It doesn't support reading package.json files, and Jint doesn't provide a NodeJS runtime, but you can register CLR types to internal modules which load when you call `require('lib')`.  You can also load any local files with `require('./my-mod')`.

**Comment by lahma** [comment]
https://tc39.es/ecma262/#sec-modules

**Comment by PeterWone** [comment]
Before I saw this issue I partially implemented node require in C# and injected it with modest success. Mine uses `package.json` to discover entry points but doesn't handle file paths. The big problem is that many node packages require modules that are supplied by node itself and cannot be found in `node_modules`. 

The upshot of this is that a loader on its own has limited usefulness; you really need all of node before you can install packages with npm and seriously expect them to work.

I looked at the source for node and on the face of things it seems like a straightforward job, though certainly a big job. Most of it seems to be written in JS with all the native stuff pulled out into a folder `externals`.

@pluethi1 What was the extent of your ambition with this?

**Comment by pluethi1** [comment]
@PeterWone I wasn't intending to support npm for this feature. More of a simpler approach to load modules - that you would have written yourself - from any location in the file system using the ES6 export/import syntax. Supporting npm I think is a bit more ambitious.

**Comment by PeterWone** [comment]
I didn't use the ES6 `import` syntax, I couldn't get that to work.

**Comment by zpxp** [comment]
ETA for release?

**Comment by PeterWone** [comment]
I think he was after an order of magnitude rather than a release date. Weeks? Months? Years? I suspect the answer is months tending toward years, but I don't know how much time you're able to put into it. Plus people who aren't haven't worked with a project of this complexity fail to understand that a single hiccup can turn into an entire subproject completely derailing any estimate one might give.

**Comment by lahma** [comment]
I think we can promise at least months, unless it's finished earlier. Completing features is mostly about prioritizing, I for example am currently working on getting latest version of test262 conformance test suite to work for easier testing and validation of new (and past) features.

**Comment by willfeerr** [comment]
any update?
