### ISSUE TITLE
Question: How to make an HTTP request?

### ISSUE THREAD

**Issue by Ghostbird** [sebastienros/jint#442]
I want to make an HTTP request from Javascript. How would I do that?
I _cannot_ allow unrestricted access to the CLR from Javascript.

**Comment by ayende** [comment]
Probably expose a method that would call to the CLR and make the call, then use a callback to get back to the script?

**Comment by Ghostbird** [comment]
Can I expose a .NET method without exposing the entire CLR?

**Comment by ayende** [comment]
Yes, but you don't expose the method directly, you expose a JS function instance that is implemented in CLR.
See for example: https://github.com/ravendb/ravendb/blob/v4.0/src/Raven.Server/Documents/Patch/ScriptRunner.cs#L114

**Comment by Ghostbird** [comment]
Thanks! I got it working. One more thing though.
How can I add a value/function from the CLR at a different level than `Engine.Global`?
I tried:
```
engine.SetValue("Http", new Object);
engine.SetValue("Http.Get", new ClrFunctionInstance(engine, HttpGet)
```
However, that doesn't work. When I try to call `Http.Get` in the script, it says that `Http` doesn't have a callable property `Get`.
I'd like to keep the global scope as clean as possible.

**Comment by sebastienros** [comment]
`Http.Get` is not a valid property name (on the `Global` object in this case). You can either pass a class that has a `Get` method, or you add a value to the `Http` object you just created. But for this I'd go with a raw JS object first, like `var http = engine.Execute("var Http = { }; return Http";).GetCompletionValue);` then use `http` from C# and find the method that adds a property to it, named `Get`.

But I assume creating the `Http` class directly in C# would be easier.

**Comment by Ghostbird** [comment]
Thanks!

**Comment by stephenquan** [comment]
This code demonstrates how to **bridge C# async tasks with JavaScript promises** using the Jint JavaScript engine.

- `FetchAsync` performs an HTTP GET request and returns the response body as a string (or throws an exception if something goes wrong).
- `FetchTest` sets up a Jint engine, exposes C# functions to JavaScript (`__fetch_bridge`, `__setResult`, `__setException`), and executes a JS snippet that defines a `fetch` function returning a Promise.
- The JavaScript code calls `fetch` with a sample URL, awaits the result, and passes it back to C# via a `TaskCompletionSource`.

This pattern allows JavaScript code running inside Jint to **call C# async methods as if they were native promises**, enabling seamless async interop between the two environments.

```c#
private static readonly HttpClient httpClient = new HttpClient();

public async Task<string?> FetchAsync(string url)
{
    var message = await httpClient.GetAsync(url);
    var text = await message.Content.ReadAsStringAsync();
    return text;
}

public async Task FetchTest()
{
    var tcs = new TaskCompletionSource<object?>();
    var engine = new Engine();
    engine.SetValue("__fetch_bridge",
        new Func<Action<string?>, string, Task>(
            (callback, a1) => Task.Run(async () => callback(await FetchAsync(a1)))
        ));
    engine.SetValue("__setResult", new Action<object?>(value => tcs.SetResult(value)));
    engine.SetValue("__setException", new Action<Jint.Native.JsValue>(
        err => tcs.SetException(new Jint.Runtime.JavaScriptException(err))
    ));
    var expression =
        $$"""
        const fetch = a1 => new Promise(resolve => __fetch_bridge(resolve, a1));

        (async() =>
        {
            try
            {
                var __result = await(async() =>
                {
                    // BEGIN YOUR CODE HERE
                    var result = await fetch('https://www.arcgis.com/sharing/rest/info?f=pjson');
                    return result;
                    // END YOUR CODE HERE
                })();
                __setResult(__result);
            }
            catch (err)
            {
                __setException(err);
            }
        })();
        """;
    engine.Execute(expression);
    var result = await tcs.Task;
}
```
