### ISSUE TITLE
Jint throws error when attempting to add event handler to System.Windows.Forms.Timer

### ISSUE THREAD

**Issue by fvaneijk** [sebastienros/jint#45]
Not sure if there is a "new" way of doing this but...

The following code throws: "TypeError: No public methods with the specified arguments were found."

when calling timer.add_Tick(doit);

Note: this worked in the previous version (0.9.2) of Jint.

var winForms = importNamespace('System.Windows.Forms');

function doit()
{
    print("timer fired");
}

var timer = new winForms.Timer();
timer.add_Tick(doit);

timer.Interval = 1000;
timer.Start();

**Comment by enowit** [comment]
var Timer = System.Windows.Forms.Timer;
var timer = new Timer();
timer.Tick += function(sender, e)
{
	alert("test");
};
timer.Interval = 5000;
timer.Start();

**Comment by enowit** [comment]
jint don't support += event. but i fixed this bug.

**Comment by fvaneijk** [comment]
please provide a PR for your fix.

Thanks
