### ISSUE TITLE
ToPrecision() not being evaluated as expected

### ISSUE THREAD

**Issue by peadarMc** [sebastienros/jint#459]
Hello,
I am currently looking at Jint as an alternative to MsScriptControl.

I was doing some preliminary testing and found that the ToPrecision javascript method isn't returning the values I would expect to see. Below is the console app I used for testing

        static void Main(string[] args)
        {
            var script1 = @"
            var num = 133.714;
            var n = num.toPrecision(2);
            n;
            ";

            var jsEngine = new Engine();
            string scriptResult;

            var ores = jsEngine.Execute(script1.ToString()).GetCompletionValue();
            scriptResult = ores.ToString(); // Jint is returning 133.7 here

            ScriptControl sc = new ScriptControl { Language = "Javascript" };
            string scriptResult2;
            object ores2 = sc.Eval(script1.ToString());
            scriptResult2 = ores2.ToString(); // Script control returns 130 
        }

**Comment by peader** [comment]
Anyone have a chance to look at this? The above example can just as easily be run in a browser console for comparison with Jint.

**Comment by lahma** [comment]
This has been now fixed in dev, ECMAScript test suite passes also for toPrecision.
