### ISSUE TITLE
Limiting memory usage?

### ISSUE THREAD

**Issue by 0xFireball** [sebastienros/jint#480]
Jint currently allows us to limit recursion and enforce time limits;
I have an application where we are accepting scripts from users, and we want to prevent a type of denial-of-service by filling up memory.

How would I be able to limit memory usage? If this feature does not exist, what would you suggest for implementing this?

**Comment by sebastienros** [comment]
There is not way to define a limit in terms of memory. Let's say a script just keeps concatenating strings ... I don't see any way to prevent it. Or just limiting the number of variables, and then the size of each JsValue, or associate an estimated memory consumption for each JsValue and have an engine based counter on this. That could work, but how would you ensure there is no other way to create more memory ...

Try to start with that.

**Comment by ayende** [comment]
That is actually not quite accurate any longer.
You can use `GC.GetAllocatedBytesForCurrentThread()` on CoreCLR to measure the amount of allocations.
That doesn't tell you how much memory is actually _in use_, but it can help to determine out of bound behavior.
I guess the idea is that you determine how much allocations you are willing to access within a script execution, and abort if there are too many.
Can do this check as part of evaluation expressions, or X number of steps.

**Comment by 0xFireball** [comment]
Thanks, I will give this a try using a separate execution thread for the JS engine.

**Comment by sebastienros** [comment]
And the thread affinity in Jint's case is not an issue as everything is sync. We can measure it at the `Execute` level, that should be good. I need to check if a single statement could eventually bypass this check by allocating more than allowed.

**Comment by 0xFireball** [comment]
From a cursory glance over the JS builtin specification, the only thing that stood out to us that might pose an issue is `Array.fill`, which wasn't introduced until ES6 and doesn't seem to be implemented in Jint.

**Comment by 0xFireball** [comment]
Thanks, I that GC method made it very straightforward:
I implemented it in my fork:
https://github.com/0xFireball/IridiumJS/commit/39b4a19be2e432541af1685f8f1a0419885f556f

I can send a PR to Jint if you would like? @sebastienros
