### ISSUE TITLE
delete does not work

### ISSUE THREAD

**Issue by s2quake** [sebastienros/jint#488]
i want to delete item of array, but item did not delete instead item was set to null

using remove method can delete item but that is not correct way i think

array has been created by Dictionary<string, object>

here is example code below
-c#
var engine = new Engine();
engine.SetValue("getData", new Func<IDictionary<string, object>>(() =>
{
    var props = new Dictionary<string, object>
    {
        { "a", 1 },
        { "b", 2 },
    };
    return props;
}));

-javascript
var data = getData();
delete data["a"];

**Comment by lahma** [comment]
This test case succeeds with latest dev, so should work as expected. We can reopen if there's still an issue or more specific test case.

```
        [Fact]
        public void ShouldBeAbleToDoDeleteWrappedDictionaryItems()
        {
            var engine = new Engine();
            engine.SetValue("getData", new Func<IDictionary<string, object>>(() =>
            {
                var props = new Dictionary<string, object>
                {
                    { "a", 1 },
                    { "b", 2 },
                };
                return props;
            }));

            engine.Execute("var data = getData(); delete data['a'];");
            var value = engine.GetValue("data['a']");
            Assert.Equal(JsValue.Undefined, value);
        }
```
