### ISSUE TITLE
Source map support

### ISSUE THREAD

**Issue by Enerccio** [sebastienros/jint#490]
Is there a support for source maps in jint?

**Comment by lahma** [comment]
What would this mean exactly? We'll close this if there's no concrete action plan.

**Comment by lahma** [comment]
Closing after six months of silence.

**Comment by thautwarm** [comment]
Source map maps the source code position from javascript to some "original" file.

This is usually useful when debugging javascript code generated from other languages(ReasonML, TypeScript, etc).

I'd like to request this feature, and if possible I'd like to help.

**Comment by thautwarm** [comment]
This can be well leveraged: https://github.com/microsoft/sourcemap-toolkit
Just add an option to `ParserOption` and remap the source code position.

**Comment by lofcz** [comment]
It would be nice if we could reopen this as even if this is done on Esprima's side, there is still integration TBD in Jint. Recently, there's been good progress in enabling high I/O scenarios (async <-> Task discussion, initial work on it by @lahma, perf).

The other thing such scenarios (think server back-end) need to be maintainable is typing, in the case of JS, there are multiple choices (TS prominently). These languages transpiling to JS generate a standardized source map as pointed out by @thautwarm

Implementing this would hence enable debugging of TS code - along with the proposed non-blocking async interop Jint could be effectively used in many new ways.

**Comment by lahma** [comment]
We can reopen if someone wants to take the implementation task and offer PRs, otherwise it's quite moot to keep a forever issue open.
