### ISSUE TITLE
Version is 0.0.0.0

### ISSUE THREAD

**Issue by iKeirNez** [sebastienros/jint#492]
From version 2.11.10 (on NuGet) and upwards, the version is 0.0.0.0.

This seems to be causing build issues due to not being able to resolve the dependency.

"C:\Program Files\dotnet\sdk\2.1.4\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Jint, Version=0.0.0.0, Culture=neutral, PublicKeyToken=2e92ba9c8d81157f, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors."

**Comment by ViceIce** [comment]
this is caused  by [Common.props#L14](https://github.com/sebastienros/jint/blob/0219295cfca99ac647e7b975bb8c3b10cd79e323/Common.props#L14)
