### ISSUE TITLE
Jint.Runtime.JavaScriptException: 'Map is not defined'

### ISSUE THREAD

**Issue by faviobol** [sebastienros/jint#496]
I have the following code.

**C# Code:**

var engine = new Engine();
JsValue require(string fileName)
{
 string jsSource = System.IO.File.ReadAllText(fileName);
var res = engine.Execute(jsSource).GetCompletionValue();
return res;
 }
engine.SetValue("require", new Func<string, JsValue>(require))
.SetValue("log", new Action<string>(System.Console.WriteLine));

JsValue name = engine.Execute(@"require('C:\\TensorFlow\\mycode.js')").GetCompletionValue();

**JavaScriptCode: (mycode.js)**

log('Hi.. Im Running mycode');
require('C:\\TensorFlow\\tfjs0.9.0.js');

what I am trying to do is to load the latest version of tensorflow FOR JAVASCRIPT:

YOU CAN DOWNLOAD IT HERE
https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.9.0

but I get the exception:

Jint.Runtime.JavaScriptException: 'Map is not defined'

Any help will be appreciated!

**Comment by tpetrina** [comment]
Map, which is added in ES6, is not yet implemented.

**Comment by sebastienros** [comment]
Map is actually defined on Array, https://github.com/sebastienros/jint/blob/dev/Jint/Native/Array/ArrayPrototype.cs#L52

Is it another `Map` that is missing?

**Comment by tpetrina** [comment]
`Map` as data structure, not `map` as method on an array.

**Comment by lahma** [comment]
Map has been implemented https://github.com/sebastienros/jint/pull/541 , enjoy!
