### ISSUE TITLE
Can't execute simple function

### ISSUE THREAD

**Issue by Hooch180** [sebastienros/jint#50]
Hello.

This is my code:
            var jsEngine = new Jint.Engine();
            jsEngine.Execute(rsaBiJs);
            jsEngine.Execute(rsaJs);
            jsEngine.SetValue("modStr", modStr);
            jsEngine.SetValue("expStr", expStr);
            jsEngine.SetValue("password", UserPassword);
            jsEngine.Execute(@"var pubKey = RSA.getPublicKey( modStr, expStr );");
            jsEngine.Execute(@"password = password.replace( /[^\x00-\x7F]/g, '' );");
            jsEngine.Execute(@"var encryptedPassword = RSA.encrypt( password, pubKey );");
            string encryptedPassword = jsEngine.GetValue("encryptedPassword").AsString();

Where:
rsaJs is string whitch contents this script: https://steamstore.map2.ssl.hwcdn.net/public/javascript/crypto/rsa.js

rsaBiJs:
https://steamstore.map2.ssl.hwcdn.net/public/javascript/crypto/jsbn.js

modStr and expStr are just strings. (Yes. Those have proper data in them).

It fails on this line:
jsEngine.Execute(rsaBiJs);

**Comment by lahma** [comment]
Closing as obsolete.
