### ISSUE TITLE
"No matching indexer found" w/ .net object assigned to prototype field

### ISSUE THREAD

**Issue by cr4yz** [sebastienros/jint#500]
code:

```c#
private void Start()
{
    var engine = new Engine(cfg => cfg.AllowClr(typeof(UnityEngine.GameObject).Assembly));
    engine.Execute(@"
var UnityEngine = importNamespace(""UnityEngine"");
var Vector3 = UnityEngine.Vector3;
var Color = UnityEngine.Color;

function BaseZone() { };
BaseZone.prototype.name = ""John"";
BaseZone.prototype.age = 42;
BaseZone.prototype.position = Vector3.zero;

var myZone = new BaseZone();

// works
UnityEngine.Debug.Log(myZone.position);

// works
myZone.position = Vector3.one;
UnityEngine.Debug.Log(myZone.position);

// errors
myZone.position = Vector3.one * 2;

// errors
UnityEngine.Debug.Log(""position:"" + myZone.position);

");
}
```

output:
![error](https://user-images.githubusercontent.com/9637557/39211533-8c9d3318-47d1-11e8-9ea1-009051fb2ecf.png)

**Comment by Chabinka** [comment]
Sure thing.  I got slightly different results in a standalone console app.  It looks like it's a issue with operators rather than prototypes

```
using System;
using Jint;

namespace ConsoleApp1
{
    public class Vector3
    {
        public Vector3(float x, float y, float z)
        {
            this.x = x;
            this.y = y;
            this.z = z;
        }
        public float x;
        public float y;
        public float z;
        public static Vector3 zero => new Vector3(0, 0, 0);
        public static Vector3 one => new Vector3(1, 1, 1);
        public static Vector3 two => one * 2;

        public static Vector3 operator *(Vector3 a, int b)
        {
            return new Vector3(a.x * b, a.y * b, a.z * b);
        }

        public override string ToString()
        {
            return string.Format("({0},{1},{2})", x, y, z);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var engine = new Engine(cfg => cfg.AllowClr(typeof(Program).Assembly));

            engine.Execute(@"
var ConsoleApp = importNamespace(""ConsoleApp1"");
var Print = ConsoleApp.Program.Print;
var Vector3 = ConsoleApp.Vector3;

function Something() { };
Something.prototype.pos = Vector3.zero;

var mySomething = new Something();

Print(""1: "" + mySomething.pos);

mySomething.pos = Vector3.one * 2;
Print(""2: "" + mySomething.pos);

mySomething.pos *= 4;
Print(""3: "" + mySomething.pos);

mySomething.pos = Vector3.two;
Print(""4: "" + mySomething.pos);

var myVector = new Vector3(8, 8, 8);
myVector *= 2;
Print(""5: "" + myVector);
");

            var myVector = new Vector3(12, 12, 12);
            myVector *= 2;
            Print("6:" + myVector);

            Console.ReadLine();
        }

        public static void Print(string message)
        {
            Console.WriteLine(message);
        }

        public static void Print(object message)
        {
            Console.WriteLine(message.ToString());
        }

    }
}
```

output:
![error](https://user-images.githubusercontent.com/9637557/39262328-b90c54e8-4884-11e8-9d21-c0ace6767a8c.png)

**Comment by sebastienros** [comment]
The issue seems to be that an overloaded operator is not taken into account from JS.

**Comment by Poyo-SSB** [comment]
This is correct. JavaScript does not support operator overrides. The current workaround would be to make functions like so:

```csharp
function scale(a, b) {
    return new Vector3(a.x * b, a.y * b, a.z * b);
}
```

and replace calls like `Vector3.one * 2` with `scale(Vector3.one, 2)`.

It's awful but it looks to be the only way to do it within the limits of JavaScript as a framework.

**Comment by sebastienros** [comment]
Or implement it, by detecting that it has an operator override if the two types are CLR wrappers.

**Comment by ViceIce** [comment]
I got the same error, if i pass an `ICollection` wrapped in `ObjectWrapper` to `Array.from`.

It crashes here:
https://github.com/sebastienros/jint/blob/1f8d87a4ced7865c7eb727f86c0f43e01fff13ab/Jint/Native/Array/ArrayConstructor.cs#L79

Stack
```
Result StackTrace:	
   at Jint.Runtime.ExceptionHelper.ThrowInvalidOperationException(String message)
   at Jint.Runtime.Descriptors.Specialized.IndexDescriptor..ctor(Engine engine, Type targetType, String key, Object item)
   at Jint.Runtime.Interop.ObjectWrapper.<>c__DisplayClass6_0.<ResolveProperty>b__3(Engine engine, Object target)
   at Jint.Runtime.Interop.ObjectWrapper.GetOwnProperty(String propertyName)
   at Jint.Native.Object.ObjectInstance.TryGetValue(String propertyName, JsValue& value)
   at Jint.Native.Object.ObjectInstance.get_IsArrayLike()
   at Jint.Native.Array.ArrayConstructor.From(JsValue thisObj, JsValue[] arguments)
```

My collection type has an `Guid` Indexer.

I think there should be another check like in `ArrayContructor.Create`:
https://github.com/sebastienros/jint/blob/1f8d87a4ced7865c7eb727f86c0f43e01fff13ab/Jint/Native/Array/ArrayConstructor.cs#L247-L249

My workaround is to use a `new Array` instead, which is working fine.

Regards
Michael

**Comment by lahma** [comment]
@ViceIce can you share minimal repro of your collection that triggers this exception?

**Comment by ViceIce** [comment]
OK, i will try to add a test case.

**Comment by ViceIce** [comment]
See https://github.com/sebastienros/jint/compare/dev...VisualOn:bug/500-invalidoperation

**Comment by ViceIce** [comment]
I've simplified the test.

**Comment by lahma** [comment]
@ViceIce thanks for the repro, I'm trying to tackle it with this https://github.com/sebastienros/jint/pull/579 . Automatic detection of IList which can be array-like and supports indexing.

**Comment by ViceIce** [comment]
@lahma Please think about `ICollection`, which we use. The `List<T>` was just an example. It should also work for `IEnumerable`. 

Regards
Michael

**Comment by lahma** [comment]
@ViceIce thanks for the clarification, I've updated the PR to also handle ICollection and IEnumerable.

**Comment by ViceIce** [comment]
Thanks, I will try the next beta. Any timeframe?

**Comment by lahma** [comment]
Should be available in dev feed https://www.myget.org/F/jint/api/v3/index.json , later on NuGet.
