### ISSUE TITLE
migration from Microsoft.ClearScript.V8

### ISSUE THREAD

**Issue by cilerler** [sebastienros/jint#504]
Trying to migrate from **Microsoft.ClearScript.V8** to **Jint** as suggested in here https://github.com/Microsoft/ClearScript/issues/9

the project I have to handle uses really limited amount of the features of the library but I have to understand if there is a pitfall here, can you help me to convert the code block below to Jint's syntax and inform me if there is anything that I may need to be aware of?  Thanks in advance...

```
using Microsoft.ClearScript.V8;

public class Parser : IDisposable
{
    // ...
    private V8ScriptEngine engine = null;

    public void ParseDataFile()
    {
        // ...
        
        using (engine = new V8ScriptEngine())
        {
            engine.AddHostObject("host", new Microsoft.ClearScript.HostFunctions());
            engine.AddHostObject("lib", new Microsoft.ClearScript.HostTypeCollection("mscorlib", "System.Core"));
            engine.AddHostObject("parser", this);
        }

        var codeStmt = (ParserCodeBlock)step;
        engine.Execute(codeStmt.Code);

        var context = new { obj = obj, property = property, value = value };
        engine.AddHostObject("context", context);
        string evaluated = engine.Evaluate((string)functionArguments).ToString();
        
        // ...
    }
    // ...
}
```

**Comment by cilerler** [comment]
> Sébastien Ros @sebastienros 13:39
> @cilerler should be pretty similar but it's hard to say what host and lib are in this context. Execute is the same, AddHostObject is SetValue, Evaluate is Execute(...).GetCompletionValue

**Comment by sebastienros** [comment]
We'll keep the discussion going on the gitter room if you don't mind.
