### ISSUE TITLE
Error message internationalization

### ISSUE THREAD

**Issue by mosseb** [sebastienros/jint#505]
Hi.

When executing code via the engine, when some errors occur and I catch a Jint.Runtime.JavaScriptException, the Message property is english only.

I tried this while instanciating the engine with no luck :

`
var engine = new Engine(cfg => { cfg.AllowClr(); cfg.Culture(CultureInfo.GetCultureInfo("fr-FR")); });
engine.Execute("somecrap");
`

the resulting exception message is still in english "somecrap is not defined"

Is there a simple way to switch to any locale ?
Thanks.

**Comment by lahma** [comment]
Closing as this is massive undertaking and would require too much work when there's no one to maintain such feature. So unfortunately not avaliable in the foreseeable future.
