### ISSUE TITLE
Javascript Regex parse error

### ISSUE THREAD

**Issue by dejanberic** [sebastienros/jint#506]
Some javascript libraries have this as regex:
F=/[^]*?(:[rp][el]a[\w-]+)[^]*/;
The issue is with [^], which means any character including line breaks in javascript regex but in C# it is not a valid regex.
I have fixed this issues by doing .Replace("[^]", "(?:.|\r|\n)").

**Comment by PeterWone** [comment]
@dejanberic This is exactly the problem I have. Where did you put the expression fixup?

**Comment by lahma** [comment]
The latest beta should have this working now: https://github.com/sebastienros/jint/releases/tag/v3.0.0-beta-2050
