### ISSUE TITLE
Use "debugger" as just another breakpoint

### ISSUE THREAD

**Issue by malware-dev** [sebastienros/jint#510]
Can I please have the option of having the `debugger` statement just function as a breakpoint rather than actually running a debugger launch?

Thank you.

**Comment by Jither** [comment]
Late, but I believe this was added by #810.

    var engine = new Engine(options => options
        .DebugMode()
        .DebuggerStatementHandling(DebuggerStatementHandling.Jint));

https://github.com/sebastienros/jint/blob/dev/Jint/Runtime/Debugger/DebuggerStatementHandling.cs

**Comment by lahma** [comment]
Thanks @Jither for tracking old issues, helps to clean up the backlog. It's fixed indeed and we can reopen if something is missing.
