### ISSUE TITLE
[Jint 3.0] net45 support

### ISSUE THREAD

**Issue by ViceIce** [sebastienros/jint#528]
Hi,

we want to use esprima and jint 3 in an net45 project. Can we add net45 suppoort?
I can send a PR. See sebastienros/esprima-dotnet#33

Regards
Michael

**Comment by sebastienros** [comment]
Out of curiosity, what prevents you from using net461? It's even forced by windows update so any machine  should have it.

In the meantime please create a PR, I want to see the impact.

**Comment by lahma** [comment]
net452 is still supported by Microsoft. [Quartz](https://www.nuget.org/packages/Quartz/), [Masstransit](https://www.nuget.org/packages/MassTransit/5.1.5.1603-develop) and [NServiceBus](https://www.nuget.org/packages/NServiceBus/) support it for example.

**Comment by ViceIce** [comment]
We are using it in an MS SharePoint project for a customer. There we are not allowed to install a newer .net framework. 😞

**Comment by ViceIce** [comment]
Jint 3.0 is compatible with net45 only `Array.Empty<T>()` is missing, so i added a small workaround.
