### ISSUE TITLE
Update Test to run on a different culture

### ISSUE THREAD

**Issue by AlPecin** [sebastienros/jint#531]
Hi,
is it possible to change the the line 1246 in EngineTests.cs
from 

>var expected = testDateTimeOffset.ToString("ddd MMM dd yyyy HH:mm:ss  'GMT'zzz");

to

> var expected = testDateTimeOffset.ToString("ddd MMM dd yyyy HH:mm:ss 'GMT'zzz", 
> CultureInfo.InvariantCulture);

because I got on an assertion on a German Windows.

Thanks

**Comment by lahma** [comment]
Created a PR for that: https://github.com/sebastienros/jint/pull/532
