### ISSUE TITLE
Access to an indexer of a userdefined csharp class failed.

### ISSUE THREAD

**Issue by AlPecin** [sebastienros/jint#534]
Hi 

I have  this class defined

> 
        public class UserClass
        {
            public Type TypeProperty { get; set; }
            public object Value { get; set; }

            public string this[int index]
            {
                get
                {
                    return "int";
                }
            }
            public string this[string index]
            {
                get
                {
                    return "string";
                }
            }
        }

> 

and I execute the following javascript snippets:

>  userclass['Whistler'] + ':' +  userclass[10];
    userclass[10] + ':' + userclass['Whistler'];
> 

so I got an error on passing the unit test in the attachment
[AccessIndexer.zip](https://github.com/sebastienros/jint/files/2323784/AccessIndexer.zip)

if I change the order of the snippets in the unit test, it passed without an error! 

What's going wrong?

**Comment by AlPecin** [comment]
IMHO it depends on the "static readonly Dictionary<string, bool> _knownConversions"!

**Comment by KurtGokhan** [comment]
Tested this. It seems to work now. Issue can be closed?
