### ISSUE TITLE
Missing new methods in ECMAScript 6.

### ISSUE THREAD

**Issue by AlPecin** [sebastienros/jint#538]
I'm missing the new methods in ECMAScript 6:

> 
Math.trunc(x)
Math.sign(x)
Math.cbrt(x)
> 

in the actual revision.

**Comment by AlPecin** [comment]
Thx for the hint with the new ECMA256 test suite (is missing in the jint.sln).

I added the missing methods to the MathInstance.cs and the Number.EPSILON 
(see attachment) an run the tests in the test suite
for (trunc, sign and cbrt). The test failed for the the name.js and the length.js test and jint doesn't deliver the correct result for 1/-0

[MathInstance.zip](https://github.com/sebastienros/jint/files/2357083/MathInstance.zip)

**Comment by lahma** [comment]
@AlPecin thanks for implementation, I've created a corresponding PR: https://github.com/sebastienros/jint/pull/539
