### ISSUE TITLE
Failure on equality test

### ISSUE THREAD

**Issue by AlPecin** [sebastienros/jint#540]
Hi, 
I tried to pass the "built-ins\Math\pow" an I got an assertion on "applying-the-exp-operator_A15.js".

I'm tried to find the reason and the result was the test method in the attachment.

[EqualityTest.zip](https://github.com/sebastienros/jint/files/2360311/EqualityTest.zip)

I don't know what's going wrong?

**Comment by lahma** [comment]
This will be resolved in https://github.com/sebastienros/jint/pull/569 , so will be in dev builds quite soon, thanks for your patience.
