### ISSUE TITLE
Is possible to add jQuery in Jint?

### ISSUE THREAD

**Issue by meloman001** [sebastienros/jint#546]
I need use jQuery functions, like ajax and much more, on .net core 2 project, but i cant send document and window statements to Jint? Have you way to add jQuery in Jint? Thanks

**Comment by LegitSoulja** [comment]
@meloman001 NO AND IT'S NOT POSSIBLE. This is an interpreter, not supposed to use the real V8. Everything wrote in JS must correlate to how C# would do things. As of AJAX, you would want to use something else like HttpWebRequest with C#.

**Comment by sebastienros** [comment]
Not out of the box, but it's not impossible. I have done it actually with the previous version, and even did a prototype of a server side jquery framework, that would render pages on the server.

What it requires is an implementation of the HTML DOM, like `document`, `HTMLElement`, and so on. But right now the best implementation is in es6 and Jint with it's current es6 support would not handle this library. One day maybe, but the use cases are very limited, and they are usually based on misunderstandings.

**Comment by dream811** [comment]
Hello, Sebastienros.
Thanks for your project!
I hope to import jquery-1.12.1.min.js in my project using JINT.
If you can give me some sample code, It will be my great pleasure.
````
using Jint;

namespace DaumMailPoster
{
    class CJSInterpretor
    {
        Engine m_Engine = new Engine();//jint engine
        string Daum;
        string JQuery;
        public CJSInterpretor()
        {
            Daum = File.ReadAllText(@"JSLibrary/daum.js");
            JQuery = File.ReadAllText(@"JSLibrary/jquery-1.12.1.min.js");
            m_Engine.Execute(JQuery);
            m_Engine.Execute(Daum);
        }

        public void Test()
        {
            Console.WriteLine(m_Engine.Execute("2+2-3").GetCompletionValue());
        }
    }
}
````
![image](https://user-images.githubusercontent.com/45660446/85301493-78c0e880-b4da-11ea-894c-ae9ace1001e4.png)

This is my error message.
Thanks again!

**Comment by lahma** [comment]
File parses correctly with 3.x but problem is that document is not defined. You would need to define documents object and add required methods to it. See comment above https://github.com/sebastienros/jint/issues/546#issuecomment-446770591 .

**Comment by lahma** [comment]
Closing this as more browser specific. Some clever document handling PRs are always appreciated.
