### ISSUE TITLE
Support for string templates (e.g. "`Hello ${firstName}`")

### ISSUE THREAD

**Issue by sfmskywalker** [sebastienros/jint#547]
Would be nice to support string templates, e.g.

```
engine.SetValue("firstName", "John");
engine.Execute("`Hello ${firstName}`");
```

Right now the Execute call fails with a `Jint.Parser.ParserException: Line 3: Unexpected token ILLEGAL` exception.

**Comment by xixilive** [comment]
JIINT supports ECAM5.1 only at present! 
and i don't think this is a necessary feature, that's just also a syntax-sugar in es6.

**Comment by TriLogic** [comment]
You could possibly leverage/convert this code on GitHub that does this:
https://github.com/TriLogic/VBA-TagReplacer

**Comment by sebastienros** [comment]
Or just work on a PR that will add support for it. Target the 3.0 branch (ES6 branch), it's already parsed correctly, we just need to follow the ECMA spec to interpret these fragments.

**Comment by lahma** [comment]
Done in https://github.com/sebastienros/jint/pull/570
