### ISSUE TITLE
System.InvalidCastException for enum type

### ISSUE THREAD

**Issue by AlPecin** [sebastienros/jint#552]
I have an user defined enum with the underlying type uint and I get a

System.InvalidCastException in JsValue.cs by

`            if (value.GetType().IsEnum)
            {
                return JsNumber.Create((int) value);
            }
`

**Comment by sebastienros** [comment]
We probably need to use `Convert.ToInt32` instead of the case, but then we have to ensure the conversion back to dotnet still works. We might also check with other types.

**Comment by AlPecin** [comment]
In my case I have changed to this:

`     
       if (value.GetType().IsEnum)
            {
                var underlyingType = System.Type.GetTypeCode(Enum.GetUnderlyingType(value.GetType()));
                switch (underlyingType)
                {
                    case TypeCode.Byte:
                    case TypeCode.Int16:
                    case TypeCode.Int32:
                    case TypeCode.Int64:
                        return JsNumber.Create(System.Convert.ToInt64(value));

                    case TypeCode.SByte:
                    case TypeCode.UInt16:
                    case TypeCode.UInt32:
                    case TypeCode.UInt64:
                        return JsNumber.Create(System.Convert.ToUInt64(value));

                    default:
                        break;
                }
                return JsNumber.Create(System.Convert.ToInt32(value));
            }
`

**Comment by Hamarz** [comment]
You have Byte and Sbyte in opposite places, and you really don't need to declare a variable if you're only going to use it as readonly. switch(System.Type.GetTypeCode(Enum.GetUnderlyingType(value.GetType()))) will do just fine.

**Comment by Hamarz** [comment]
> The following code works fine in my case:
> 
> ```
> if (value.GetType().IsEnum)
> {
>     var underlyingType = System.Type.GetTypeCode(Enum.GetUnderlyingType(value.GetType()));
>     switch (underlyingType)
>     {
>         case TypeCode.Byte:
>         case TypeCode.Int16:
>         case TypeCode.Int32:
>         case TypeCode.Int64:
>             return JsNumber.Create(System.Convert.ToInt64(value));
> 
>         case TypeCode.SByte:
>         case TypeCode.UInt16:
>         case TypeCode.UInt32:
>         case TypeCode.UInt64:
>             return JsNumber.Create(System.Convert.ToUInt64(value));
> 
>         default:
>             break;
>     }
>     return JsNumber.Create(System.Convert.ToInt32(value));
> }
> ```

Sbyte and Byte are in the opposite places, also reduntant declaration of variable.
Since you're using it as readonly the switch can simply be switch(System.Type.GetTypeCode(Enum.GetUnderlyingType(value.GetType())))

**Comment by AlPecin** [comment]
You are right.
Byte and SByte must be changed.
Witch the reduntant declaration is more easy for debugging.
