### ISSUE TITLE
Which branch to use?

### ISSUE THREAD

**Issue by curtisshipley** [sebastienros/jint#567]
Thanks for the great project!

I see there are some good changes in various branches that aren't part of the nuget. 

How stable are dev and the 3.0 beta branch?  

Which branch corresponds to the nuget package?

**Comment by lahma** [comment]
* PRs wait in line to get to dev which is automatically released to MyGet
* dev is occasionally merged to master which is automatically released to NuGet
* dev/master is 3.x beta work and all commits are tested against large test suite
* 3.x beta (dev/master) has more features, is faster and fulfills the same test suite as 2.x branch (and more), for example RavenDB uses dev branch

**Comment by sebastienros** [comment]
I think we should share this information on the Readme.

**Comment by curtisshipley** [comment]
Thanks!  And yes, having this information in the readme would be very useful.

**Comment by sebastienros** [comment]
I am adding it

**Comment by sebastienros** [comment]
Done
