### ISSUE TITLE
Engine.Execute can throw many unexpected exceptions

### ISSUE THREAD

**Issue by Metalnem** [sebastienros/jint#571]
**Engine.Execute** can throw many unexpected exceptions (**JavaScriptException** and **ParserException** are expected for malformed inputs) when executing scripts from the [attached archive]. These are:

- **ArgumentOutOfRangeException**
- **IndexOutOfRangeException**
- **InvalidCastException**
- **InvalidOperationException**
- **NullReferenceException**
- **OverflowException**

 You can run the following code to reproduce it (the **path** variable should contain the path to one of the extracted files):

```csharp
var text = File.ReadAllText(path);
new Engine().Execute(text);
```

Found via [SharpFuzz].

[attached archive]: https://github.com/sebastienros/jint/files/2707188/Exceptions.zip
[SharpFuzz]: https://github.com/Metalnem/sharpfuzz

**Comment by lahma** [comment]
Thank you for reporting these. We've created fixes for both Jint and Esprima .NET and they should now cover the cases you've reported, closing the issue.
