### ISSUE TITLE
Engine.Execute terminates the process by throwing a StackOverflowException (even with recursion limit)

### ISSUE THREAD

**Issue by Metalnem** [sebastienros/jint#572]
**Engine.Execute** terminates the process by throwing a **StackOverflowException** when executing script from the [attached archive] (even with recursion limit). You can run the following code to reproduce it (the **path** variable should contain the path to the extracted file):

```csharp
var text = File.ReadAllText(path);
new Engine(options => options.LimitRecursion(1)).Execute(text);
```

Found via [SharpFuzz].

[attached archive]: https://github.com/sebastienros/jint/files/2707200/StackOverflowException.zip
[SharpFuzz]: https://github.com/Metalnem/sharpfuzz

**Comment by ayende** [comment]
Very nice find!

**Comment by lahma** [comment]
Thank you for reporting this. This is a problem on Esprima's side where a lot of recursion is happening in this case, I've filed a separate issue in Esprima's repo: https://github.com/sebastienros/esprima-dotnet/issues/104 .
