### ISSUE TITLE
Constants keep available after leaving the scope.

### ISSUE THREAD

**Issue by steffen-liersch** [sebastienros/jint#583]
Tested with Jint 3.0.0-beta-1353. A demo is available here:
https://github.com/steffen-liersch/jint-demos/tree/master/jint-const

**Comment by sebastienros** [comment]
`const` is not yet supported in the 3.0 branch, but I already started to work on it.

**Comment by lahma** [comment]
This is duplicate of https://github.com/sebastienros/jint/issues/379 .
