### ISSUE TITLE
Error trying to use Ascii2MathML.js

### ISSUE THREAD

**Issue by garethhayter** [sebastienros/jint#588]
Hi

I'm trying to load the Ascii2MathML.js file, but I'm encountering errors with both the latest stable release as well as the latest beta release.

File: https://raw.githubusercontent.com/runarberg/ascii2mathml/gh-pages/dist/ascii2mathml.js
Project: https://runarberg.github.io/ascii2mathml/

Loading the file above using latest stable (2.11.58) gives an error: Jint.Parser.ParserException: 'Line 59: Unexpected token >'

Loading it with latest pre-release (v3.0.0-beta-1353) gives this error: Jint.Runtime.JavaScriptException: 'null'

The code is:
_JsEngine = new Jint.Engine();
_JsEngine.Execute(script1);

...where script1 is the contents of the file above.

Am I doing something wrong, or is this a bug?

Many thanks,
Gareth.

**Comment by sebastienros** [comment]
It's an es6 script. We do not support it yet (see progress on readme), which is why you don't get an exception in 3.0-beta but an evaluation issue.

**Comment by garethhayter** [comment]
Thanks very much. You are correct. Good luck with the progress of ES6!

**Comment by lahma** [comment]
I just tried with latest version from NuGet (3.x series) and there's no error when loading the example script. I believe it might have been caused by the Symbol usage which has been implemented recently. We can reopen if more problems found.
