### ISSUE TITLE
StackOverflowException caused by function JsValue.ToObject

### ISSUE THREAD

**Issue by steffen-liersch** [sebastienros/jint#589]
There is an issue with function JsValue.ToObject. It causes a StackOverflowException for objects with circular references. The issue exists in

- Jint 2.11.10
- Jint 3.0.0-beta-1353
- dev branch

This issue seems to be related with #509.

Here is an example project: https://github.com/steffen-liersch/jint-demos/tree/master/jint-stack-overflow

StackOverflowException occurs when passing "global" to a managed function:

```
engine.Global.FastAddProperty("global", engine.Global, true, true, true);
engine.Global.FastAddProperty("test", new DelegateWrapper(engine, (Action<object>)Test), true, true, true);
engine.Execute("test(global);");
```

**Comment by windischb** [comment]
@sebastienros @lahma 
Any chance to get this fixed soon in 3.x?
Are there any other Ideas to prevent my App crashing because of that?

**Comment by steffen-liersch** [comment]
@sebastienros @lahma
Perhaps we need a private overload for ToObject using a helper object that has dictionary containing already handled objects.

**Comment by lahma** [comment]
Jint will now throw `TypeError` when it detects cyclic reference.
