### ISSUE TITLE
Is it possible to mix strict scripts with "legacy" scripts?

### ISSUE THREAD

**Issue by steffen-liersch** [sebastienros/jint#590]
When using different "modules" in separate scopes (using EnterExecutionContext and LeaveExecutionContext) it seems as if it is not possible to mix strict and "legacy" scripts. Once the outer most script has used the "use strict" literal all sub scripts are also in strict mode.

**Comment by lahma** [comment]
Can you test the latest preview on NuGet, I think this was fixed already...

**Comment by lahma** [comment]
Closing as obsolete, we can reopen if problem persists.
