### ISSUE TITLE
Duplicate __proto__ fields are not allowed in object literals

### ISSUE THREAD

**Issue by windischb** [sebastienros/jint#598]
Hi!

I use "typescript.js" to transpile typescript code to javascript code.
Currently working with version 2.11.58
If i do exactly the same, with version 3.0.0-beta-1476 i'll get the following error:
```
Esprima.ParserException: Line 62: Duplicate __proto__ fields are not allowed in object literals
```
Is this a bug in Esprima, so duplicate `__proto__` fields sholud be allowed??
Or is this the correct behavior and the typescript.js library is not ES6 compliant?

**Comment by wizzard0** [comment]
I believe this is a known bug in Esprima, discussed in js version at https://github.com/jquery/esprima/issues/1485

**Comment by wizzard0** [comment]
ugly hack is set `"importHelpers": true,` in tsconfig and patch `tslib`, commenting out the line 
`({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||`

even uglier would be regex-replace this line in emitted helpers :)

**Comment by windischb** [comment]
If i understand it correct, Esprima .Net should behave exactly as the Esprima js version.
So if it's a gug in the js version, it's also a bug in the .Net version!

Sounds like there is a good chance that @sebastienros wil fix it also in the .Net version...

For now i can stay at Jint 2.11.58.
But in this version i'll get an Stackoverflow expection whit circular references, and i hoped that this is maybe fixed in Jint 3.x

**Comment by lahma** [comment]
I believe you just haven't confiured the JavaScript parser to be tolerant:

```
var engine = new Engine();
engine.Execute(
    "({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; })",
    new ParserOptions
    {
        Tolerant = true
    });
```

@sebastienros can chime in if the being non-tolerant is the wrong default..

**Comment by sebastienros** [comment]
About tolerant mode: https://esprima.readthedocs.io/en/latest/syntactic-analysis.html#tolerant-mode

But this doesn't excuse a stackoverflow, it should at least return a parse error.
Then does this duplicate proto definition follows the spec? https://tc39.github.io/ecma262/#sec-__proto__-property-names-in-object-initializers

If you think this instance is compliant with the spec then it should work in non-tolerant mode. If it doesn't follow the spec then you will need to enable the Tolerant mode.

**Comment by windischb** [comment]
I have tested a few things!

```csharp
var tsCode1 = "import {test} from 'test'";
var tsCode2 = "import {test} from 'test/test'";
```

It looks like the `/` character in the import statement is the Problem...


## Jint 2.11.57 & tsCode1
non minified typescript.ts
```javascript
Set is not defined
```
minified typescript.min.ts
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
```
## Jint 2.11.57 & tsCode2
non minified typescript.ts
```javascript
Set is not defined
```
minified typescript.min.ts
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
```

## Jint 3.0.0-beta-1495 & tsCode1 & Tolerant = false
non minified typescript.ts
```javascript
Line 62: Duplicate __proto__ fields are not allowed in object literals
```
minified typescript.min.ts
```javascript
Line 1: Duplicate __proto__ fields are not allowed in object literals
```
## Jint 3.0.0-beta-1495 & tsCode2 & Tolerant = false
non minified typescript.ts
```javascript
Line 62: Duplicate __proto__ fields are not allowed in object literals
```
minified typescript.min.ts
```javascript
Line 1: Duplicate __proto__ fields are not allowed in object literals
```


## Jint 3.0.0-beta-1495 & tsCode1 & Tolerant = true
non minified typescript.ts
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
```
minified typescript.min.ts
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
```
## Jint 3.0.0-beta-1495 & tsCode2 & Tolerant = true
non minified typescript.ts
```javascript
Object reference not set to an instance of an object.
```
minified typescript.min.ts
```javascript
Object reference not set to an instance of an object.
```

**Comment by wizzard0** [comment]
@lahma i believe `{ __proto__: [] }` is spec-compliant, the spec (simplified) says __proto__ should not occur twice in some circumstances, once should be fine

**Comment by lahma** [comment]
https://github.com/sebastienros/jint/pull/605 has a failing test case for this so I belive hopefully this issue can be addressed as part of that PR.

**Comment by lahma** [comment]
@windischb @wizzard0 can I ask you to give link to the source of the file that you are using to get this error, just to be sure that fix will work when we have the time to prepare fix and verify. Stock typescript.js (typescript@3.3.3 from NPM) seems to parse with current dev.

**Comment by windischb** [comment]
I have used version 3.2
here is a small test Repo: https://github.com/windischb/JintTypescript
I will try later today, with version 3.3.3

**Comment by windischb** [comment]
I have tried it with typescript 3.3.3 and ge tnearly the same result...
The only difference is that Jint 2.11.57 now also can transpile the code with the non minified version of typescript.

**Comment by wizzard0** [comment]
@lahma https://github.com/Microsoft/tslib/blob/master/tslib.js#L60
or just
```
engine.Execute(@"
  if({ __proto__: [] } instanceof Array) {}
");
```

**Comment by lahma** [comment]
@wizzard0 thank you, with current state of https://github.com/sebastienros/jint/pull/605 this would work out of the box.

**Comment by windischb** [comment]
Tested now with Jint 3.0.0-beta-1526 and Esprima 1.0.0-beta-1186
With tolerant mode, all is working now as expected!
Many thanks!
I'm sure if i can close this issue now...?

**Comment by lahma** [comment]
@windischb yes please do close if everything is working now as expected. We forgot to ping back here after release.
