### ISSUE TITLE
Number.toPrecision throws between 26 & 100

### ISSUE THREAD

**Issue by AmateurMemetics** [sebastienros/jint#599]
The buffer in dtoa is only ever allocated 25 digits, so `(3).toPrecision(n)` where `n` is between 26 and 100 throws an index out of bounds exception.

This can be fixed be reallocating the buffer in `DtoaNumberFormatter` if the fast case doesn't succeed (L65). However, this seems like a pretty complex rabbit hole and I'd appreciate more eyes on this.

I'm planning on tackling this after I merge in arrow functions (which will enable tests that fail due to this issue).

**Comment by lahma** [comment]
Thanks for reporting, I went ahead and fixed the problem. The formatting code path follows V8 logic and the size was not initialized correctly, now has the same logic for sizes and V8.
