### ISSUE TITLE
Rest parameters cause hang when not set

### ISSUE THREAD

**Issue by AmateurMemetics** [sebastienros/jint#600]
```jint> var fn = function (a, b, ...c) { return c; }
jint> fn(1, 2, 3)
=> [
  3
]
jint> fn(1, 2)
=> []
jint> fn(1)
```

Whilst calling this function with 3 parameters and 2 parameters causes the correct result, when just 1 or 0 parameters are passed, this function will hang. Jint goes through a huge array and is not happy. I'll try to tackle this after I've merged in arrow functions because they will enable a test case which will fail due to this bug.

**Comment by lahma** [comment]
Was this already sorted with the PR or stil an issue?

**Comment by AmateurMemetics** [comment]
Sorted in the PR

I realise I never included the function that this is testing in the original description.

```var fn = (a, b, ...c) => c```

This was it, and I've tested that it passes successfully now
