### ISSUE TITLE
Regex timeout

### ISSUE THREAD

**Issue by SebastianStehle** [sebastienros/jint#608]
My application (https://squidex.io, also open source) allows to enter regex to validate content. I remember that I had a scenario where a user entered a regex that actually crashed several servers after a while, because all Threads have been busy to execute these expressions. Unfortunately I cannot find this example.

I think it would be good to introduce a timeout for the regexp in jint.

What do you think?

**Comment by SebastianStehle** [comment]
I found the regex: `^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$`

**Comment by ssimontis** [comment]
@SebastianStehle You are absolutely correct that RegEx can cause major performance issues, particularly any expressions making heavy use of backtracking. OWASP has a [cheat sheet with various issues ranked by severity](https://github.com/attackercan/regexp-security-cheatsheet) and also provides [a static analysis tool](https://github.com/attackercan/regexp-security-cheatsheet/tree/master/RegexpSecurityParser) to inspect code for issues. The static analysis tool is just a PHP file, so it isn't pretty, but it lists Grep commands which can find issues. Hopefully your PR gets accepted, that would be a huge asset from a security standpoint!

**Comment by SebastianStehle** [comment]
My repo? I am another Sebastian

In my case the problem is that a user can enter a custom script so a static analysis tool would not help.
