### ISSUE TITLE
Improve engine creation performance

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/jint#615]
While doing some memory profiling I found that the main cost was during the initialization of the constructor objects when we create many `ClrFunctionInstance` and `PropertyDescriptor` instances like here:

https://github.com/sebastienros/jint/blob/dev/Jint/Native/Date/DateConstructor.cs#L77

I assume these objects should be immutable (they can still be replaced) and we should be able to mark them static and reuse them.

Snapshot of 50 requests in Orchard Core:

![image](https://user-images.githubusercontent.com/1165805/54468333-b3b96580-4748-11e9-9466-084157b0f34f.png)

**Comment by sebastienros** [comment]
@lahma what is your thought on that?

**Comment by lahma** [comment]
That sounds reasonable. There's the immutable property descriptor already for undfined, but it suffers slight performance penalty of having the CustomValue flag set that directs to virtual call. IIRC descriptors are created as new instances when re-configured, hopefully there are no pitfalls.

I've only profiled the run time of initialized engine so this is a path I've not set my foot on 🙂

**Comment by lahma** [comment]
PR https://github.com/sebastienros/jint/pull/625

**Comment by sebastienros** [comment]
You are mentioning descriptors, but I was thinking about riding the ClrFunctionInsrance instances inside them as static. These won't be accessed or changed.

**Comment by lahma** [comment]
The problem with static `ClrFunctionInstance` is that they reference engine, engine is used for error reporting etc. As `ClrFunctionInstance` is `ObjectInstance`, it holds a field and reference for the engine. So reusing would probably require a bigger refactor.. Probably `ClrFunctionInstance` could override exception throwing to use non-engine-bound rerporting, that would allow this - but it can get messy when ClrFunctionInstance would be a special case where you can't rely to have _engine set, like in FunctionInstance etc methods that have been inherited.

**Comment by sebastienros** [comment]
Having the engine be part of the state being an issue in some cases, this could be solved by passing a "context" as arguments where it makes sense. This would probably be the engine itself of something that contains it plus some other local information (like steps, debug info, ...)

**Comment by unruledboy** [comment]
Talking about performance, I wonder:
1. the parsed result can be reused to speed up the performance (I mean, is cache built-in?)
2. native compilation: think RegExp Compiled, so it won't be interpreted everytime

**Comment by lahma** [comment]
Can you share us the actual caching logic? It can be a slippery slope to find a caching logic that works with variable input.

**Comment by besthealthsolutions** [comment]
@lahma it is not really a native cache mechanism per say. I use DynamicExpresso (https://github.com/davideicardi/DynamicExpresso) in a project to do expression evaluation, I used ConcurrentDictionary to maintain the parameters per biz (an artificial text key based on the biz object).

For Jint, the cache I mentioned it is nothing but just not running `.Execute()` every time, it will run once and call `.Invoke() `repeatedly. I am not sure if I am using it properly, but with the test above, I believe that's what I am after.

**Comment by unruledboy** [comment]
@lahma it is not really a native cache mechanism per say. I use DynamicExpresso (https://github.com/davideicardi/DynamicExpresso) in a project to do expression evaluation, I used ConcurrentDictionary to maintain the parameters per biz (an artificial text key based on the biz object).

For Jint, the cache I mentioned it is nothing but just not running `.Execute()` every time, it will run once and call `.Invoke() `repeatedly. I am not sure if I am using it properly, but with the test above, I believe that's what I am after.
