### ISSUE TITLE
how to support like this "document.createElement('div')"

### ISSUE THREAD

**Issue by huangchuxian** [sebastienros/jint#622]

**Comment by huangchuxian** [comment]
document is not defined

**Comment by caifl** [comment]
engine.setValue('document', new DocumentXyz())

**Comment by SebastianStehle** [comment]
Jint does not run in the browser, therefore there is no DOM.

**Comment by lahma** [comment]
Like others have noted, you would need to implement document yourself to support such scenario. Unfortunately this is outside of Jint's functionality scope.
