### ISSUE TITLE
[Bug] function immidiately called

### ISSUE THREAD

**Issue by MeikelLP** [sebastienros/jint#635]
I want to implement a (for now) basic modding interface for my Unity3D game.

I want to define a mod in `module.exports` styled manner:

```js
module.exports = {
  name: 'Mod1',
  init () {
    registry.Add(new BlockPrototype('Dirt', 'assets/dirt.png'))
    registry.Add(new BlockPrototype('Grass', 'assets/grass.png'))
  }
}
```

And then call the individual phase while mod-loading (i.e. `init`). But sadly the function `init` is instantly called when I `Engine.Execute` this script block. This should not happen as I only define this function.

I tried to workaround this issue with defining the function separately as named `function init () {}` and then assign it but that didn't work as well.

**Comment by lahma** [comment]
What verion of Jint? Running such script with latest preview version doesn't give an error even though `registry` is not defined.

**Comment by MeikelLP** [comment]
I'm not at work right now so I can't say for sure. I directly downloaded from nuget today. Should be `3.0.0-beta-1525`. I'm adding more source code (especially C#) tomorrow.

**Comment by MeikelLP** [comment]
I cannot reproduce this bug anymore. I don't know how it fixed itself :/
