### ISSUE TITLE
Performance Concerns

### ISSUE THREAD

**Issue by atom0s** [sebastienros/jint#64]
I have just started looking into Jint after having very poor performance with NLua with a project of mine. After implementing Jint in its place I am seeing similar results in performance though. I'm fairly certain this is due to the conversions between C# -> scripting engine and back. 

My project consists of extending a plugin system to allow plugins to be written in a scripting language and not require compiling. This also allows for unloading/reloading of plugin scripts instead of having to hard-restart the server since .NET DLLs cannot be unloaded (unless they are ran in separate AppDomains etc.)

One of the tests I was using to check the performance is on the games Update call. This is called constantly as it is the games loop handler. From within my scripts callback for this handler, I loop the player list and do some checks and such on the objects like this:

``` javascript
function GameUpdate()
{
    for (var x = 0; x < SomeObject.SubArray.length - 1; x++) {
        if (SomeObject.SubArray[x] != undefined && SomeObject.SubArray[x].Active == true)
        {
            print(SomeObject.SubArray[x].Name);
        }
    }
}
```

SomeObject is a static object on the .NET side. Its SubArray is an array (255 static sized) array of another object type.

So in this case I am looping the 255 objects every frame of the server. If this is coded in C# itself, there is no performance drops noticeable. But with Jint, the game server is unplayable from the lag this produces.

(The lag is there even without the print, that was just to give an example. So it is not an output slowdown etc.)

My question would be is there something I am doing wrong or "bad" in a sense of how I am using Jint? 
Is there a better method to approach this with to prevent the lag?

**Comment by sebastienros** [comment]
I am closing this one as this should not be an issue anymore.
