### ISSUE TITLE
Can I access .net methods with javascript without allowing clr?

### ISSUE THREAD

**Issue by Shadowblitz16** [sebastienros/jint#647]
is there a way to link a global javascript function to a .net method without giving it access to clr?

I have a list of engines I am creating per script, and I want to allow javascript to access a static C# List of engines and return a script scope so I can do something like this..
```
//Script A
function tick() //Called by engine every frame
{

}
function DoSomething(a)
{

}
```

```
//Script B
function tick() //Called by engine every frame
{
    var a
    find(0).do_something(a); //find is a .net method and do_something() is from the script above ^
}
```

**Comment by sebastienros** [comment]
I think so. Just pass a CLR object with `SetValue` and access its methods directly.

**Comment by Shadowblitz16** [comment]
thank you I will try this.

**Comment by lahma** [comment]
Closing as resolved.
