### ISSUE TITLE
Try Execute value or method?

### ISSUE THREAD

**Issue by Shadowblitz16** [sebastienros/jint#648]
is there a built in way to execute a javascript method that may or may have not been defined yet without throwing errors?

I want to make a event hook I can call from my .net assembly. 

for example I might be calling ontick everyframe in .net but it might not exists yet in the java script

**Comment by sebastienros** [comment]
There is an example on the main readme. `Invoke`.

**Comment by Shadowblitz16** [comment]
this isn't really clear since the example on the readme executes function declaration before the invoke.
do these things get pasted into the string? do they make it so I cannot declare them in script since they are already declared?

please elaborate.
