### ISSUE TITLE
Can Only Invoke Functions?

### ISSUE THREAD

**Issue by Shadowblitz16** [sebastienros/jint#650]
what am I doing wrong here?
```
        internal static void Load()
        {
            Engine.Invoke("Init");
        }
```

its a hook so it shouldn't need to be defined unless I am using it.
is there a way check if a function exists?

**Comment by Zeon-4** [comment]
```
using Jint;
using Jint.Native;

Engine js = new Engine().SetValue("Console",typeof(Console));
var myres = js.Execute("Console.Write('Example invoke');").GetValue("Example");
// Check is function exists
if(myres != JsValue.Undefined){
    myres.Invoke();
}
```

**Comment by Shadowblitz16** [comment]
there doesn't seem to be a JsValue.Function.
```
        internal static void Load()
        {
            var myres = Engine.GetValue("Init");
            if (myres == JsValue.Function) Engine.Invoke("Init");
        }```

**Comment by Shadowblitz16** [comment]
ok I got it working for some reason doing..
```
function Draw(obj)
{
	Gfx.Fill(1,0,1,1);
}```

```
Engine.SetValue("Gfx", typeof(Gfx));
internal static void Draw()
{

        Engine.Execute("if (typeof Draw === 'function') Draw();");

}
```

it doesn't seem to like me setting the the value to caps like 'Engine.SetValue("GFX", typeof(Gfx));`
and it doesn't like me doing 
```
Engine.SetValue("Gfx.Col", new Action<float, float, float, float>(Gfx.Col));
Engine.SetValue("Gfx.Trans", new Action<float, float>(Gfx.Trans));
Engine.SetValue("Gfx.Scale", new Action<float, float>(Gfx.Scale));
Engine.SetValue("Gfx.Angle", new Action<float>(Gfx.Angle));
Engine.SetValue("Gfx.Fill", new Action<int, int, int, int>(Gfx.Fill));
Engine.SetValue("Gfx.FillRect", new Action<int, int, int, int>(Gfx.FillRect));
Engine.SetValue("Gfx.FillCirc", new Action<int, int, int, int>(Gfx.FillCirc));
Engine.SetValue("Gfx.Line", new Action<int, int, int, int>(Gfx.Line));
Engine.SetValue("Gfx.LineRect", new Action<int, int, int, int>(Gfx.LineRect));
Engine.SetValue("Gfx.LineCirc", new Action<int, int, int, int>(Gfx.LineCirc));
```
to limit the static methods I can use in js

**Comment by lahma** [comment]
If someone can provide a complete test case against latest main code base that shows the problem it would be easier to address.

**Comment by lahma** [comment]
Closing as stale, if more interest is being gained, we can reopen.
