### ISSUE TITLE
Is Options.DiscardGlobal obsolate or not implementated?

### ISSUE THREAD

**Issue by peterblazejewicz** [sebastienros/jint#655]
Hi,

As I understand access to global objects is not possible out of the box without a setup.
What's the purpose of the `DiscardGlobal`, as it seems to be not implemented?
https://github.com/sebastienros/jint/blob/dev/Jint/Options.cs#L36

I'm limiting configuration of engine to be as light way as possible, so this configuration option looked like one to use, hence my question.

Thanks!

**Comment by lahma** [comment]
The option probably should be removed. Building the global object isn't that expensive compared to script execution. A lot of things are going to be broken without the global so this option doesn't make much sense. You can also reuse the engine instances if you think you can track declared variables and overwrite them.

**Comment by peterblazejewicz** [comment]
@lahma thx for an update!
