### ISSUE TITLE
Object initializers with string keys do not work

### ISSUE THREAD

**Issue by logiclrd** [sebastienros/jint#658]
In JavaScript, it is legal to write an expression such as:

    { "a": 42 }

This is a core part of the subset of JavaScript that JSON leverages. The above string fails to evaluate in Jint, however. It does not fail in the Chrome developer console.

I don't know if this is the correct document, I located this part of the ECMA 262 standard addressing this issue:

https://www.ecma-international.org/ecma-262/10.0/index.html#prod-PropertyName

> ```
> PropertyDefinition[Yield, Await]:
> ...
>     PropertyName[?Yield, ?Await] : AssignmentExpression[+In, ?Yield, ?Await]
> ...
>
> PropertyName[Yield, Await]:
>     LiteralPropertyName
>     ComputedPropertyName[?Yield, ?Await]
>
> LiteralPropertyName:
>     IdentifierName
>     StringLiteral
>     NumericLiteral
> ```

So numeric literals should work as well, though I have not tested this.

## Expected results

An object with a property whose key is the string `"a"` and whose value is the number 42.

![image](https://user-images.githubusercontent.com/2349379/63979203-f2847300-ca7d-11e9-8627-7cc107044f10.png)

## Actual results

`Jint.Parser.ParserException : Line 1: Unexpected token :`

## Work-around

`JSON.parse` can handle this type of object expression, provided that the overall expression doesn't do anything that requires full JavaScript evaluation.

**Comment by lahma** [comment]
This is something that even the [original Esprima parser doesn't handle](https://esprima.org/demo/parse.html?code=%7B%20%22a%22%3A%2042%20%7D%0A). I wonder if this is some sugar that some runtimes put on top and translate to discarded variable? `var x = { "a": 42 }` works fine so you get the object you expect - so Jint handles this correctly, no?

**Comment by lahma** [comment]
Tested with FireFox console and output is:

```
{ "a": 42 }
SyntaxError: unexpected token: ':'
```

So I guess this is some browser/runtime specific feature.

**Comment by logiclrd** [comment]
Ahh, I've found the key piece of the standard. What I initially looked at was:
* `Statement` **:** `ExpressionStatement`
* `ExpressionStatement` **:** `Expression`
* `Expression` **:** (literally every possible type of expression in the precedence chain) **:** `PrimaryExpression`
* `PrimaryExpression` **:** `ObjectLiteral`
* `ObjectLiteral` **:** `{` `PropertyDefinitionList` `}`
* `PropertyDefinitionList` **:** `PropertyDefinition`
* `PropertyDefinition` **:** `PropertyName` `:` `AssignmentExpression`
* `PropertyName` **:** `LiteralPropertyName`
* `LiteralPropertyName` **:** `StringLiteral`

So, QED, right?

Reviewing it this morning, scratching my head as to why a parser that proudly announces standards compliance wouldn't accept it, I finally found this little sentence near the definition of `ExpressionStatement`:

> NOTE An _ExpressionStatement_ cannot start with a U+007B (LEFT CURLY BRACKET) because that might make it ambiguous with a _Block_.

So, absolutely, Chrome technically shouldn't be accepting this. But that gave me another question: Why does `{ a: 42 }` work when `{ "a": 42 }` doesn't? Esprima gave me the answer to that one too: It's not creating an object with property `a`, it's creating a code block with one statement in it `42`, and that statement is given label `a` e.g. for use with `goto`. :-P

Incidentally, Chrome creates an object with property `a` for `{ a: 42 }` too, breaking the standard there too. I did a bit of experimentation, though, and it looks like this extension applies only to the developer console line input. For instance, if I try to define a function with a statement `{ "a": 42 }` in the middle of it, Chrome also gives `SyntaxError: Unexpected token :`.

So I guess this is a non-issue then!

**Comment by logiclrd** [comment]
The real problem I am solving is injecting a blob of JSON into a Jint context as a JavaScript object so that it can be addressed by JavaScript code. The JSON is in the form of a Newtonsoft.JSON `JToken`. Is there something cleaner than serializing it to JSON string and then having Jint parse that string?

**Comment by logiclrd** [comment]
I ended up writing a converter that knows how to translate JSON objects directly between Newtonsoft's generic LINQ representation and Jint.Native objects.

**Comment by lahma** [comment]
Thanks for the investigative work and glad that you got the thing sorted out 👍
