### ISSUE TITLE
No globals when using LexicalEnvironment.NewObjectEnvironment() with an IDictionary<string, object>

### ISSUE THREAD

**Issue by dave3vans** [sebastienros/jint#662]
Hi,
I've found a problem when trying to create a new object environment using a Dictionary<string, object> (the same problem occurs with ExpandoObject).

The outer environment (in this case GlobalEnvironment) seems to disappear. The problem doesn't occur when using e.g. an anonymous object or POCO.

```
var engine = new Engine();

engine.SetValue("print", new Action<object>(Console.WriteLine));

var obj = new Dictionary<string, object> { { "test", "hello" } };

var environment = LexicalEnvironment.NewObjectEnvironment(engine,
    JsValue.FromObject(engine, obj).AsObject(), engine.GlobalEnvironment, false);

engine.EnterExecutionContext(environment, environment, null);
engine.Execute("print(test)");
engine.LeaveExecutionContext();

// Expecting:
// hello

// Instead got exception:
// Object has no method 'print'
```

I fixed it in my fork by making this change: 3ab07a4f4c8a6213d34fae7c4c50521487dda9b9, but I'm new to Jint and not familiar with the codebase so I might be doing it all wrong!

**Comment by lahma** [comment]
Custom environments are no longer supported via public API and can be probably be worked around with for example shadow realm functionality. If there's a specific use case that needs to be supported with reasoning, I think we can reconsider how to support it.
