### ISSUE TITLE
Jint.Engine.Execute(...) could accept System.IO.StreamReader or System.IO.Stream

### ISSUE THREAD

**Issue by Vinigas** [sebastienros/jint#663]
Currently Jint.Engine.Execute(...) only accept strings. This means large JS files needs to allocated in RAM; or you need to write your own code to execute file line by line.

Jint.Engine.Execute(...) could accept System.IO.StreamReader or System.IO.Stream. Reading could use async/await patterns.

**Comment by Vinigas** [comment]
Looks like this issue is more related to project dependency:
https://github.com/sebastienros/esprima-dotnet

**Comment by lahma** [comment]
Out of curiosity, how big files do you process when RAM starts to be concern? I know in ideal world we would stream and allocate little.

**Comment by lahma** [comment]
Closing as this should not really be an issue. If a real-world example is shown demonstrating the problem we can reopen.
