### ISSUE TITLE
Any way to serialize an environment to file?

### ISSUE THREAD

**Issue by c272** [sebastienros/jint#665]
I'm looking to serialize a `LexicalEnvironment`/list of `PropertyDescriptor` classes to file, so I can load them again later to preserve the environment.

However, it's become quite troublesome trying to use Newtonsoft/JSON.NET to serialize/deserialize, as:

1. `JsValue` has no constructor, so it fails to deserialize that class.
2. `JsValue`'s properties/fields are also mostly private, which prevents Newtonsoft serializing, at least on the settings I'm using.

So is there any way to serialize an environment to file?

**Comment by lahma** [comment]
Closing as this is unsupported feature and would create maintenance burden due to backwards compatibility concerns. If this is about performance we can hopefully tackle that in more specific issues. If it's "game save data" maybe custom solution on library consumer side is in order .
