### ISSUE TITLE
Memory limit and timeout bypassed with new Array and Join

### ISSUE THREAD

**Issue by DanSearle** [sebastienros/jint#683]
For my use case we need to evaluate Javascript expressions for validation. I wanted to test Jint security features to ensure that the there would be minimal impact to the application if a bad expression was run. I was testing to see if it was possible to exceed the run limits and the following test case allows the 0.5s timeout to be exceeded and the memory limit of 500 to also be exceeded.

Eventually the application fails with a .NET OutOfMemoryException.

```
var javascript = "new Array(2147483647).join('*')";
var result = new Engine(options =>
{
    options.LimitRecursion(1);
    options.Strict();
    options.DiscardGlobal();
    options.TimeoutInterval(TimeSpan.FromSeconds(0.5));
    options.MaxStatements(1);
    options.LimitMemory(500);
} )
.Execute(javascript)
.GetCompletionValue() 
.ToObject();
```

From browsing the source code it looks like the timeout and memory limits are only evaluated before each statement statement. Therefore the statement can exceed these limits and the execution only stops on the next statement. If it is not possible to resolve this case it is worth documenting this as a limitation of the timeout and memory limits.

**Comment by DanSearle** [comment]
I did some further diagnostics on this and it seems that this only occur when the debugger is not attached. When the debugger is attached I correctly get the memory limit exception. I'm not sure what affect not having the debugger attached has on the memory checks within Jint 

```
Unhandled Exception: Jint.Runtime.MemoryLimitExceededException: Script has allocated 600 but is limited to 500
```

My test project is a .NET v4.6.2 console project against the 3.0.0-beta-1632 package.

**Comment by lahma** [comment]
Pinging @0xFireball for possible insights about debugger attached vs no attached difference (contributed the original PR).

**Comment by sebastienros** [comment]
I think we should still look in this statement `new Array(2147483647)` as we might as well ensure that any single step that can allocate significantly should ensure it's preemptively looking at the defined boundaries. This case is obvious, and there might be others, like string manipulation methods.

**Comment by sebastienros** [comment]
even if the `MemoryLimitExceededException` is correctly thrown, you want it to be done as early as possible, or as close as possible to the limit, not when it went over it by a lot.

**Comment by lahma** [comment]
Chrome console gives:

```
Uncaught RangeError: Invalid string length
    at Array.join (<anonymous>)
    at <anonymous>:1:23
```

This is before trying anything, smaller size value will evaluate (and takes some time).

**Comment by gaw** [comment]
> Pinging @0xFireball for possible insights about debugger attached vs no attached difference (contributed the original PR).

When the debugger attached, the exception is thrown on the array creation statement, possibly due to a slightly larger memory consumption in this mode. If the array creation statement meets the memory limits, then the Join method starts, which will cause a .NET OutOfMemoryException.
The problem is that during the execution of the Join method, the time limit and memory limit are not checked. They are checked only between statements. This opens up the possibility for an attacker to raise .NET OutOfMemoryException or load cpu in lengthy operations using methods like Join.

**Comment by Ghostbird** [comment]
I ran into this issue as well. I wrote a unit test to verify correct exception handling of some parts of our system. For out of memory I allocated and `fill`ed a large `Array`. Imagine my surprise when neither the time, nor the memory limit worked, and finally the dotnet runtime itself was killed by the OS for misbehaving.

**Comment by lahma** [comment]
`MaxArraySize` constraint in #923 should address this.
