### ISSUE TITLE
No String.prototype.includes

### ISSUE THREAD

**Issue by l-o-l** [sebastienros/jint#684]
Seems to be missing, or I am missing something.

**Comment by lahma** [comment]
It's there, you just need to use the 3.0 preview version from NuGet. 2.x won't be getting any new features so it's recommended to switch to 3.x series.

**Comment by pauldotknopf** [comment]
Out of curiosity, what is the story around 3.0? It looks like it's been around for a while.

**Comment by lahma** [comment]
All new development happens there, there's a lot to do so that's way the preview label, things are moving around. It's backed by same set of thousands of tests like 2.x, and some more for new features.
