### ISSUE TITLE
RegExp CPU usage

### ISSUE THREAD

**Issue by andreminelli** [sebastienros/jint#687]
I have a usage scenario with lots of function calls and profiling pointed out that regex executions are the most CPU intensive.

I am using latest v2 release.
Was there any work over this on v3?

I have read that the static calls on .NET Regex object should have better performance, and even a [cache](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.cachesize?view=netcore-3.0) for compiled expressions, which would probably have a good effect on my scenario. 
This could be implemented on Jint?

**Comment by sebastienros** [comment]
I don't think we ever use Regexes if it's not part of the user script. At least in v3.

**Comment by andreminelli** [comment]
Sorry, I wasn't clear: the scripts being called have JS RegExp inside them. 
Profiler shows a lot of calls running on classes from Jint.Native.RegExp namespace.

**Comment by lahma** [comment]
Can you provide examples of the regexpses and the content they are being run against?

**Comment by andreminelli** [comment]
Those scripts are opaque to the application at this time. I can try to generate some log with them, but the issue at fist is about what performance improvements I can expect on V3 over RegExp, and maybe a guidance about the RegExp implementation for a possible PR over its performance.

**Comment by lahma** [comment]
Jint utilizes pretty much the .NET's built-in Regex with some cleanup/tweaks to input, but not much is happening on Jint's side. [You can check the implementation here](https://github.com/sebastienros/jint/tree/dev/Jint/Native/RegExp).

I'd recommend switching to v3. It's faster and passes the same test suite as 2.x and more.

**Comment by lahma** [comment]
Closing this as there's not much to do here, NET 5 is great candidate to run on as it has many regex related performance improvements (which Jint uses under the hood).
