### ISSUE TITLE
Object.keys throw when called with string or array

### ISSUE THREAD

**Issue by AllNamesRTaken** [sebastienros/jint#688]
Object.keys("text") should return ["0", "1", "2", "3"] (edit) but throws instead.
Object.keys("[1,2,3") should return ["0", "1", "2"] but throws instead.

In ObjectConstructor.cs the following code handles the .keys functionality in Object.
```
public JsValue Keys(JsValue thisObject, JsValue[] arguments)
        {
            var oArg = arguments.At(0);
            var o = oArg.TryCast<ObjectInstance>();
            if (ReferenceEquals(o, null))
            {
                ExceptionHelper.ThrowTypeError(Engine);
            }

            var enumerableProperties = o.GetOwnProperties()
                .Where(x => x.Value.Enumerable)
                .ToArray();
            var n = enumerableProperties.Length;

            var array = Engine.Array.ConstructFast((uint) n);
            uint index = 0;
            foreach (var prop in enumerableProperties)
            {
                var p = prop.Key;
                array.SetIndexValue(index, p, updateLength: false);
                index++;
            }
            return array;
        }
    }
```
And this does not handle the case when Object.keys is invoked with a string or array as input object, which is valid JS and should return an array with the characters of the string and an array with the indexes of the array respectively.

**Comment by graphnode** [comment]
Technically it should return `["0", "1", "2", "3", "4", "5"]` for `Object.keys("[1,2,3")` and `["0", "1", "2", "3"]` for `Object.keys("text")` since those are the keys for these arrays.

**Comment by AllNamesRTaken** [comment]
Interesting. Indeed you are right. Spec sais 0,1,2,4 as strings. I have no clue how I got the notion of anything else.

**Comment by lahma** [comment]
I think this was fixed as part of https://github.com/sebastienros/jint/pull/713 , so the latest in NuGet should work as expected. We can reopen if still an issue.
