### ISSUE TITLE
BindingFlags type converted to double when passed to GetField

### ISSUE THREAD

**Issue by mikecrews** [sebastienros/jint#69]
BasicDoor is a UnityEngine class. This script code is running under Jint 0.9.  Util.TryFindType passes the Type to an out variable, similar to Jint 2's importNamespace.

It looks as though Jint is casting my BindingFlags bitmap to a double.  Is there a way to do this that avoids this problem? Is this handled differently in Jint 2?

```
var bdoor, sysref;
Util.TryFindType("System.Reflection.BindingFlags", sysref);
Util.TryFindType("BasicDoor", bdoor);
var state = bdoor.GetField("state", sysref.NonPublic | sysref.Instance); //this line gives error, "System.InvalidCastException: Value is not a convertible object: System.Double to System.Reflection.BindingFlags"
UnityEngine.Debug.Log("works");
```

**Comment by lahma** [comment]
Closing  as obsolete, there's been numerous improvements to interop in 3.x, we can reopen if still s problem.
