### ISSUE TITLE
eval not work,how to use? thanks

### ISSUE THREAD

**Issue by dazhu6666** [sebastienros/jint#692]
source string:    `function aa(){return new Date().getTime();}`

packed string:
`eval(function(p,a,c,k,e,d){e=function(c){return(c<a?"":e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)d[e(c)]=k[c]||e(c);k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1;};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p;}('2 1(){0 5 4().3()}',6,6,'return|aa|function|getTime|Date|new'.split('|'),0,{}))`

I need packed string covert to source string.but not work.
demo:
```
var engine = new Engine();
var ff = "value=String(function(p,a,c,k,e,d){e=function(c){return(c<a?\"\":e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)d[e(c)]=k[c]||e(c);k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1;};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p;}('2 1(){0 5 4().3()}',6,6,'return|aa|function|getTime|Date|new'.split('|'),0,{}))";
 var kk = engine.Execute(ff).GetValue("value") ;
```

return the value "kk" is not collect.  please teach me how to write ! tanks

**Comment by lahma** [comment]
A bit of an obscure example, if there's problems with more readable code and maybe test case we can reopen.
