### ISSUE TITLE
TimeoutInterval does not work with synchronous functions

### ISSUE THREAD

**Issue by gentledepp** [sebastienros/jint#697]
# Jint 2.11.58

We try to limit the execution time of a script using "TimeoutInterval".
When testing with a long running c# `Delegate`, Jint does not throw a `System.TimeoutException` but keeps executing. In the worst case, you end up in an infinite loop.

```csharp


            var result = new Jint.Engine(o => o.TimeoutInterval(TimeSpan.FromMilliseconds(100)))
                .SetValue("slowFunction", new Func<string>(() =>
                    {
                        System.Threading.Thread.Sleep(TimeSpan.FromMilliseconds(200));
                        // or use spinwait...
                        // while (true)
                        //    System.Threading.Thread.SpinWait(1);
                        return "tadaaa!";
                    }))
                .Execute("slowFunction()")
                .GetCompletionValue()?.ToObject();

            // Expected: Exception
            // But is string "tadaaa!"
            

```

**Comment by sebastienros** [comment]
Please try with the 3.x version

**Comment by gentledepp** [comment]
sure - will do!

**Comment by gentledepp** [comment]
I just tried with **Jint 3.0.0-beta-1632**
Same result.
When changing to a `while(true){}` in `slowFunction()` the function runs forever.

For 2.11.58 this is not a blocking issue to us - just worth mentioning.
For 3.x, maybe this should be fixed.

By the way: Thanks for that **AWESOME** library! 🎉👊

**Comment by SebastianStehle** [comment]
How should this work? We can not just destroy the thread. We should use cancellation tokens and I have created a PR for that: https://github.com/sebastienros/jint/pull/709

**Comment by lahma** [comment]
There's not much that Jint can automatically do here as it's not code owned by Jint. The correct way is to check for constrains in your code from time to time, like you would observe `CancellationToken`.

https://github.com/sebastienros/jint/blob/7e193c64d3e17d1a34a58e9775bd8d8513bab069/Jint.Tests.PublicInterface/ConstraintUsageTests.cs#L53-L69

**Comment by gentledepp** [comment]
you are right.. my bad...
