### ISSUE TITLE
Engine cache or something...

### ISSUE THREAD

**Issue by monokot** [sebastienros/jint#700]
Dear sirs,

I discovered an issue when I run the following code:

```
var parser = new JavaScriptParser();
var program1 = parser.Parse("function square(a) { return a * a; }; square(2);");
var program2 = parser.Parse("square(2);");

var engine = new Engine();  // Creating the engine once

var result1 = engine.Execute(program1)
                .GetCompletionValue()
                .ToObject(); // return 4

var result2 = engine.Execute(program2)
                    .GetCompletionValue()
                    .ToObject();  // return 4 :(
```

The first call to GetCompletionValue returns 4 and this is expected, but for some reason the second call to GetCompletionValue also returns 4 (but I expect an error, because the square function is not actually defined). If I recreate the engine before the second call to GetCompletionValue, this problem does not occur. I am using the latest stable version of Jint 2.11.58.

Is there a workaround to fix this behavior? or I am missing something? 

Thanks!

**Comment by lahma** [comment]
This is how JS works, see the Node console:

```
Welcome to Node.js v12.13.1.
Type ".help" for more information.
> function square(a) { return a * a; }; square(2);
4
> function square(a) { return a * a; }; square(2);
4
> const a = 2;
undefined
> const a = 6;
Thrown:
SyntaxError: Identifier 'a' has already been declared
>
```

You should probably use the preview of 3.x from NuGet, way faster.
