### ISSUE TITLE
Deferred function arguments change over time

### ISSUE THREAD

**Issue by Ghostbird** [sebastienros/jint#704]
I'm stuck with a rather strange situation.
I have to asynchronously retry some CLR functions that are called from Jint, while ensuring their calling order is maintained.
Therefore, I defer such `Func<JsValue, JsValue[], JsValue>`s to a queue that tries the deferred function until it succeeds, and then continues with the next one.
The problem happens when I do something like this:
```javascript
// JavaScript
MyCLRFunctionRefWithRetry('foo');
MyCLRFunctionRefWithRetry('bar');
```
Both functions are called, deferred and after 30 seconds the first is retried. At this point `args[0]` of the deferred function call `MyCLRFunctionRefWithRetry('foo');` resolves to `'bar'` instead of `'foo'`.
Note that a lot of other stuff is going on around these function calls too, and they are not really called immediately after each other in the Jint engine.

Annoyingly I cannot reproduce this behaviour in my minimal-code example: https://github.com/Ghostbird/JintAsyncRetry

Could someone shed some light on why this happens? Maybe even suggest an avenue to fix it?
I've tried to integrate argument serialisation before deferring and de-serialisation on execution, however too much runtime type information is lost and the app goes down in a shower of `InvalidCastException`s.

**Comment by lahma** [comment]
Can it happen that engine is called concurrently? Engine is not thread-safe.

**Comment by Ghostbird** [comment]
I'm pretty sure that's not the case. The queue actually enforces that all methods are called consequently, as the minimal-code example shows.

**Comment by lahma** [comment]
Ok,  it's just that sometimes minimal example might lack behavior of the system as a whole. What version are you using?

**Comment by Ghostbird** [comment]
The minimal code example was designed to cover the _expected_ problematic factors such as multithreading. However it does not show the error.

On the other hand, I found that when I downgrade to the latests stable, I cannot reproduce the issue. The troublesome part is that we have always run the Jint 3 branch, and I don't know whether our software is backwards compatible. Running the older version just to take advantage of an implementation detail also seems like a bad idea to me. Additionally I have no proof that the error does not occur in the stable branch, and is just less likely to occur.

The whole behaviour reminds me of ARM [ROP-ing](https://en.wikipedia.org/wiki/Return-oriented_programming). Mainly the part where you enter a function with the function arguments of an earlier called function. This is possible in ARM since the function arguments are passed in a fixed set of registers. However it doesn't make much sense in a high-level automatically managed memory environment such as C#, since it would imply explicit faulty point re-use.

It could however be the result of an overzealous optimisation technique introduced in Jint 3. If so, can anyone confirm the existence of such a technique and provide a way to disable it?

**Comment by lahma** [comment]
Do you have javascript code that accesses function's implicit `arguments` object? Recent commit to dev changed the handling to be more robust. There's another fix in dev for string handling for concatenated strings. Both are available on dev feed, not yet in NuGet.org feed.

By running a branch do you mean you compile yourself or run NuGet.org packages?

**Comment by Ghostbird** [comment]
We don't have code that accesses the implicit `arguments`, and the problem is not related to concatenated strings.
I edited my post above to clarify that I meant the Jint 3 NuGet release.

For now I'm solving it on a higher level in our code by spawning new `Engine`s and copying the parts of the context we need to persist. So far this passes our tests, and seems like an acceptable solution.

I think time-complexity of `Engine` creation changes from O(_n_<sup>_i_</sup>) to O(_n_<sup>_i+1_</sup>) for our process. However I'm unsure of the exact value of _i_, and I expect this to still be a small part of our total process time-complexity, and therefore unlikely to heavily impact overall performance.

Should I close this issue – as my specific case has been worked around – or leave it open – as the general case remains unsolved?

**Comment by lahma** [comment]
Good to hear that that fresh engine instances solved your problem. So far my suspicion is that this is related to multi-threading and not engine itself. There's multitude of more-or-less complex tests being run against the code and none exhibit such problematic behavior; recursion, nested calls etc all work as expected.

The v3 engine should be quite lightweight to instantiate and we are always happy to try to improve speed if you find bottlenecks.

If you are fine with closing maybe that's easier for now as no way to reproduce. We can always reopen if the problem surfaces again.

**Comment by Ghostbird** [comment]
I'm pretty sure that the underlying cause is the stack contamination mentioned in #673. In my case it is not concurrent. But the stack of a deferred call may have been contaminated by a later call, by the time the first call is actually executed.
