### ISSUE TITLE
This is not really an issue, but a question about parsing, analysis and other things

### ISSUE THREAD

**Issue by DiaDeTedio** [sebastienros/jint#706]
Well, I developed a parser at Unity, with the help of Regex and a personal tokenizer (my creation), to support a certain form of "coroutines".
It will convert this (pseudocode):
```
$ BEGIN
function* f () {
  somecodehereA ...
  yield tokenshere; <- EOF
  somecodehereB ...
...
}
$ END
```
In that:
```
function f () {
  var y0 = function () {somecodehereA ...};
  var y1 = function () {somecodehereB ...};
  return [{func: y0, result: tokenshere}, {func: y1, result: undefined}];
}
```

My question revolves around the system internally, as this is a relatively fast process, but expensive in memory (by creating classes of tokens and string splits), I would like to know if there is any mechanism in your lib to customize the execution process , parsing or analyzing the script, in order to improve this system.

**Comment by lahma** [comment]
Not sure if this answers your question, but have a look at https://github.com/sebastienros/esprima-dotnet , it's the parser behind Jint that handles JS parsing and also offers [visitor pattern if you want to analyze nodes](https://github.com/sebastienros/esprima-dotnet/blob/dev/src/Esprima/Utils/AstVisitor.cs). There's always memory hit to produce AST for code.
