### ISSUE TITLE
Re-building source code from parsed expression tree

### ISSUE THREAD

**Issue by migajek** [sebastienros/jint#71]
Hi, would it be possible to re-generate the original JS source code from expression tree (slightly modified)? I'd love to use Jint for parsing AND manipulating source a bit.

**Comment by fvaneijk** [comment]
posted PR https://github.com/sebastienros/jint/pull/289 for this

**Comment by lahma** [comment]
esprima-dotnet has the required visitor pattern for this, closing as obsolete.
