### ISSUE TITLE
Bug with js indexer, when index equals 0x0

### ISSUE THREAD

**Issue by maxkatz6** [sebastienros/jint#710]
Minimal repro
1. Create new console project (netcoreapp3.1 in my case)
2. Add reference to Jint, version = 3.0.0-beta-1715 (which is latest in my case)
3. Put code below into Main method:
```csharp
var shouldBe1 = new Jint.Engine().Execute("var t = '1234'; var a = t[0x0]").GetValue("a");
Console.WriteLine(shouldBe1);
Console.ReadLine();
```

Expected result: "1"
Actual result: undefined

In the chrome devtool`s console I can see expected result with same JS code.
With '[0]' instead '[0x0]' everything works as expected.

**Comment by maxkatz6** [comment]
Any other hex value work as expected.
```js
var t = '1234'; var a = t[0x1];
```
Expected result: "2"
Actual result: "2"

So problem exists only with [0x0]

**Comment by lahma** [comment]
Thanks for reporting this, I've prepared a PR that should fix the issue https://github.com/sebastienros/jint/pull/711 .

**Comment by maxkatz6** [comment]
@lahma thanks!
