### ISSUE TITLE
Recursion inside a for statement not working properly on beta version

### ISSUE THREAD

**Issue by ceifa** [sebastienros/jint#714]
I'm having trouble when trying to interpret a JS code with recursion inside a for loop on the newest beta version. These are the files to reproduce:

> Program.cs:

```cs
var arg1 = @"
        [
            {
                ""description"": ""1"",
                ""options"": [
                    {
                        ""description"": ""1.1""
                    }
                ]
            },
            {
                ""description"": ""2""
            }
        ]
";

var engine = new Engine(options => options
    .AllowClr(typeof(Console).Assembly));

engine = engine.Execute(File.ReadAllText("script.js"));

engine.Invoke("run", arg1);
```

> script.js
```js
function recursion(arr) {
    for (let i = 0; i < arr.length; i++) {
        System.Console.WriteLine(arr[i].description);
        if (arr[i].options) {
	    recursion(arr[i].options);
        }
    }
}

function run(input) {
    let arr = JSON.parse(input);
    recursion(arr);
}
```

The output expected:

```
1
1.1
2
```

The output I'm receiving on the newest beta version:

```
1
1.1
```

When I execute on the stable version or in LTS node version, I receive the expected output.

**Comment by ceifa** [comment]
I just found the problem is in the lexical environment creation when a function is called, i managed to simulate this in a very much smaller and verifiable code:

```
function test() {
	let x = 9;
	test2();
}

function test2() {
	log(x); // Output: 9
}

test();
```

Seems like the same properties are being shared between the function which called and the function called.

**Comment by lahma** [comment]
I think this probably originates from the fact that let and const haven't been implemented yet. This means that they behave like var and can escape scope.

**Comment by ceifa** [comment]
Replacing the code with var works greatly and prints the expected. I realized that the variables declared with let simply go to the global scope, which is a different behavior from var and is also different from the expected behavior.

Thinking that let and const being supported can be a difficult task, it doesn't make sense for now to leave them with the same behavior as var (hoisting, function scoped, etc.)? I think this would minimize the amount of bugs and breaking changes for people who migrate to the beta.

**Comment by lahma** [comment]
I agree that them working in the same way (like `var`s for now) would be more logical. The problem is that the variable hoisting happens currently in Esprima library and it doesn't consider other declarations than `var`s.

One could even argue if it would make sense to throw when usage found and implementation is missing, so that people don't get surprised like this.
