### ISSUE TITLE
String member operator (e.g. "foo"[0]) returns undefined in app built for iOS (with Unity)

### ISSUE THREAD

**Issue by jldinh** [sebastienros/jint#717]
For context, I am using Jint in a Unity app. I noticed `"?BigNumber"[0]` returns `?` as expected when running it in the Unity Editor (on Mac), but for some reason, it returns `undefined` when building and running the app on iOS.

Interestingly, `"?BigNumber".charAt(0)` does not suffer from the same issue, leading me to think there is something that could be tweaked in the implementation of the member operator to solve this unexpected behavior on iOS.

I wanted to compare the implementations, but couldn't figure out where the member operator is implemented for strings. Does anybody have any pointers?

Version: 3.0.0-beta-1715

**Comment by lahma** [comment]
This might be another way of manifesting https://github.com/sebastienros/jint/issues/710 . The fix is not yet on NuGet, but you might want to try latest version from MyGet feed (  https://www.myget.org/F/jint/api/v3/index.json  ) .

**Comment by jldinh** [comment]
I can confirm it works properly on iOS as of 3.0.0-beta-1745 (from MyGet).
Do you have any idea what could have caused the bug to only occur on some platforms?

**Comment by sebastienros** [comment]
The issue is global to all runtimes afaik, why do you think it's only on iOS ?

**Comment by sebastienros** [comment]
Sorry, found it while reading your issue again

**Comment by sebastienros** [comment]
In the past I had found a bug related to integer overflow only in the mono runtime. They marked it as "won't fix" as the C# spec was not specific about the behavior :/ It must still be open somewhere. That would not explain this issue, but just to mention that runtimes might have bugs.

**Comment by jldinh** [comment]
Makes sense... But in that case, wouldn't the runtime bug be on Mac then? Because it did work when it shouldn't have...? Counter-intuitive, but anything's possible, I guess.
