### ISSUE TITLE
Check type of variable to see if it is a function or not

### ISSUE THREAD

**Issue by unlimitedcoder2** [sebastienros/jint#720]
How would I check too see if a JsValue returned from engine.GetValue is a funtion or not? It shows up as an object [img](https://sharethe.minecraftdoublesmoothstoneslab.website/i/qj8f.png)

**Comment by sebastienros** [comment]
You can try to cast it as `ICallable`.

```
if (value is ICallable function)
{
  function.Call(...);
}
```

**Comment by unlimitedcoder2** [comment]
This does not seem to work as when I run it it is not an ICallable [img](https://sharethe.minecraftdoublesmoothstoneslab.website/i/g766.png) 
[img2](https://sharethe.minecraftdoublesmoothstoneslab.website/i/zuo6.png)

**Comment by lahma** [comment]
With Jint 3.x series both are tests are true and console is written.

![image](https://user-images.githubusercontent.com/171892/79233587-c1707b80-7e71-11ea-9dee-be522d7976d5.png)
