### ISSUE TITLE
Does not work with anonymous objects

### ISSUE THREAD

**Issue by kidmar** [sebastienros/jint#724]
Hi
I tried to pass an anonymous object to the js engine.
I've modified one property of the object using js.
After the execution of js code the object wasn't changed and had the original value.
This happens with a very simple code so I don't know if it is not supposed to work (but the documentation says it should) of if I am doing something wrong.
Please tell me if you need the code, but it is very easy to reproduce.

Using a normal class insted of an anonymous object one works well.

**Comment by uffebjorklund** [comment]
I have the same issue, cant use anonymous... but if I declare a class it works as expected.
Not a show stopper, but it would have been great if it worked on anonymous types as well.

## Does not work
```
var p = new {
    Name = "Mickey Mouse"
};

var engine = new Engine()
.SetValue("p", p)
.Execute("p.Name = 'Minnie'");
Assert.Equal("Minnie", p.Name);
```

p.Name will still be `Mickey Mouse`

## Works
```
public class Person
{
    public string Name { get; set; }
}

var p = new  Person{
    Name = "Mickey Mouse"
};

var engine = new Engine()
.SetValue("p", p)
.Execute("p.Name = 'Minnie'");
Assert.Equal("Minnie", p.Name);
```

**Comment by lahma** [comment]
Unfortunately there's not much we can do here. Anonymous objects are immutable, see https://stackoverflow.com/questions/2328676/anonymous-type-property-setters . So CLR does not expose a setter to call and it works like any non-writable JS object, it's a no-op.
