### ISSUE TITLE
ExpandoObject cannot be set in 3.0.0-beta-1778

### ISSUE THREAD

**Issue by lekrus** [sebastienros/jint#725]
Below test works in 3.0.0-beta-1767
```c#
dynamic expando = new ExpandoObject();
expando.Name = "test";
engine.SetValue("expando", expando);
engine.Execute("expando.Name").GetCompletionValue().ToString().Should().Be("test");
```
but fails in 3.0.0-beta-1778 with
`System.ArgumentException: collection is supposed to either have Count or Length property`

the change is introduced in #721, probably it's better to add an exception for ExpandoObject not to treat it as IsArrayLike?

Thanks!

**Comment by lahma** [comment]
Thanks for reporting, https://github.com/sebastienros/jint/pull/726 should fix this.

**Comment by lekrus** [comment]
thanks a lot for the quick fix!
