### ISSUE TITLE
Window not defined

### ISSUE THREAD

**Issue by aemsoftwarearacatuba** [sebastienros/jint#727]
I'm writing the following code:

` public static dynamic HashBuilder(String pSession)
        {

            StringBuilder sb = new StringBuilder();

            var request = WebRequest.Create("https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js");

            using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
            {

                using (var responseStream = response.GetResponseStream())
                {
                    using (StreamReader reader = new StreamReader(responseStream))
                    {

                        sb.Append(reader.ReadToEnd());

                    }
                }
            };

            if (sb.ToString() != "")
            {

                try
                {

                    var engine = new Jint.Engine();
                    engine.Execute(sb.ToString());

                }
                catch (Jint.Runtime.JavaScriptException Ex)
                {
                    Console.WriteLine(Ex.Message);
                };

                return null;

            }
            else
            {

                return null;

            }

        }`

when executing the snippet: engine.Execute (sb.ToString ());

the following error occurs:
window is not defined

What will be the best way to use it?

**Comment by lahma** [comment]
That script is meant to be run in a browser.

**Comment by aemsoftwarearacatuba** [comment]
Do you have any suggestions on how I can do it?

**Comment by aemsoftwarearacatuba** [comment]
> That script is meant to be run in a browser.


Do you have any suggestions on how I can do it?

**Comment by lahma** [comment]
You need to implement window, not a small task, I'm afraid.

**Comment by aemsoftwarearacatuba** [comment]
> You need to implement window, not a small task, I'm afraid.


so the problem is that it is a webservice

**Comment by Gr3gorywolf** [comment]
@aemsoftwareracatuba  i guess that you should create a small wrapper that acts as a window object and its properties

**Comment by lahma** [comment]
I'm closing this as unfortunately this is quite hard to support in Jint's scope. DOM events and mutation are pretty much browser concerns and require substantial amount of work to get right (window emulation).
