### ISSUE TITLE
Separate the parser & interpreter

### ISSUE THREAD

**Issue by atifaziz** [sebastienros/jint#73]
I'd like to propose separating the parser infrastructure that was ported over from [Esprima](http://esprima.org) from the interpreter that's been built on top in Jint, for the following reasons:
- The parser can be used as shared infrastructure by the .NET community (much like the Esprima) to write other JavaScript-related tools, including experimentation in compilers and interpreters.
- The parser and interpreter can evolve independently & have separate release cycles, issue tracking and so on.
- It would give Jint more focus on just the runtime and execution bits.

I have forked a new project called [Escape](https://bitbucket.org/raboof/escape) that hosts just the parser bits and pushed it out as a [NuGet package](http://nuget.org/packages/Escape). Apart from the namespace change, I've kept the public API source-compatible deliberately so it can be linked back into Jint with minimal effort (the parser API needs some clean-up going forward so I wanted to make a 1.0 release before going forward). In fact, I've even attempted to do that in a local & would be happy to submit a PR if you like the idea.

**Comment by atifaziz** [comment]
> Done!

Where? [esprima-dotnet](https://github.com/sebastienros/esprima-dotnet)?

**Comment by lahma** [comment]
@atifaziz yep, that's the parser part that Jint uses.
