### ISSUE TITLE
Variables defined in forEach callback not captured by arrow functions defined inside the same callback

### ISSUE THREAD

**Issue by jldinh** [sebastienros/jint#732]
I have a situation where I define arrow functions in a forEach operation.
The arrow functions seem to capture the values of the forEach callback argument fine, but not those of variables defined in the callback.

If I run the following JS code (with `log` set to an appropriate function):
```
var funcs = [];
Object.entries({a: 1, b: 2, c: 3}).forEach(function(kv) {
    const x = kv[1]
    const cb = () => {
        log('using kv ' + kv[1]);
        log('using x ' + x);
    };
    funcs.push(cb);
});
funcs.forEach(x => x());
```
I get the following output:
```
using kv 1
using x 3
using kv 2
using x 3
using kv 3
using x 3
```
Even though I expect to get the same values regardless of whether I use `kv` or `x`, which I confirmed in the Chrome console.
I don't really know how the Jint engine works at a low level, but it seems to me that `x` is pointing to the same object in each of the `func` functions, while `kv` is not.

I used Jint 3.0.0-beta-1786 from myget.

**Comment by lahma** [comment]
I checked against the let/const branch and this example works there as expected. let and const are not currently handled, only var is supported. So I'd suggest to subscribe to that PR and wait it to hit the master.

**Comment by jldinh** [comment]
Oh I see, thanks for the clarification.
Indeed, the example works fine if I use `var` instead.
