### ISSUE TITLE
Ability to use NodeJS's require

### ISSUE THREAD

**Issue by bgribaudo** [sebastienros/jint#733]
Hello,

Thank you for Jint!

Are there any options out there for using Jint with node module require statements (e.g. `require("./SomeModule")`)?

@tylerjwatson's Jint.Commom provides support for CommonJS's `require` but (according to the project's readme) this doesn't work with node_modules.

Thank you,
Ben

**Comment by nathan130200** [comment]
Up! I'm searching about that too.

**Comment by sebastienros** [comment]
This could use some help. Good thing is that it shouldn't require (funny, right?) any new engine feature, mostly managing dependencies to load and run, with some extensibility to provide script sources (filesystem, network, db, cache ...).

Feel free to share links to specs, implementations of examples on this thread.

**Comment by lahma** [comment]
I'm closing this in favor of https://github.com/sebastienros/jint/issues/430 , please continue discussion there.
