### ISSUE TITLE
is it possible to disallow access to private Properties or fields and make Ivalue from interface?

### ISSUE THREAD

**Issue by kkohno** [sebastienros/jint#734]
is it possible to disallow access to private Properties or fields?

For example:

```csharp
// interface
public interface ITeamsBalancerService
{
	bool IsAutoBalance { get; }
}
// realisation
public class TeamsBalancerService: ITeamsBalancerService
{
	bool IsAutoBalance { get; private set;}
}

// following code can access to PRIVATE field on my API realisation
var context = new Engine();
context.SetValue("balancer", new TeamsBalancerService());
context.Execute(@"balancer.IsAutoBalance=true");
```

I need to allow work only with interface

**Comment by lahma** [comment]
JavaScript doesn't have interfaces so the concrete object is currently considered. Might require some sort of generic registration method that allows setting the exposed interface like `context.SetValue<ITeamsBalanceService>(new TeamsBalancerService())`.

**Comment by kkohno** [comment]
What about following?

```csharp
// interface
public interface ITeamsBalancerService
{
	bool IsAutoBalance { get; }
}
// realisation
public class TeamsBalancerService: ITeamsBalancerService, IEnumerable
{
	bool IsAutoBalance { get; private set;}
}

// set public interface.
// now TeamsBalancerService parsed by JsValue.FromObject only with interfaces 
// ITeamsBalancerService and Ienumerable
options.SetInterfaceOnly<ITeamsBalancerService>().To<TeamsBalancerService>();
options.SetInterfaceOnly<Ienumerable>().To<TeamsBalancerService>();
```

**Comment by lahma** [comment]
Another thing to consider is if property has private setter it probably shouldn't be considered writable in JS sense. Might require property access strategy like in JSON parsers whether private access is allowed.

**Comment by kkohno** [comment]
in in my case main think is that i have public api for users (only interfaces) and private realization (may has critical functions, that can break the whole program process). 
But in above codes If need strattegy for building JsValues for class we can make another Interface-strattegy and Wrapper for class TeamsBalancerService, inherited this interface strattegy and set up in engine this wrapper

```csharp
// interface-strattegy 1
public interface IStrattegy1
{
	bool IsAutoBalance { get; }
}

// interface-strattegy 2
public interface IStrattegy2
{
    bool AnotherProp { get; } // only get!
    void AnotherMethod();
}

// target class
public class MyClass: IStrattegy1, IEnumerable
{
	bool IsAutoBalance { get; private set; }
    bool AnotherProp { get; set; }
    void AnotherMethod();
}

// target class wrapper
public class MyClassWrapper: IStrattegy2
{
    MyClass m_Object;

    MyClassWrapper(MyClass object)
    {
        this.m_Object = object;
    }

    bool AnotherProp => m_Object.AnotherProp // may have setter
    void AnotherMethod()
    {
        m_Object.AnotherMethod();
    }
}

// withoiut wrapper - only MyClass inherited interfaces.
options.SetInterfaceOnly<IStrattegy1>().To<MyClass>();
options.SetInterfaceOnly<IEnumerable>().To<MyClass>();

// or only one inherited interface
options.SetInterfaceOnly<IStrattegy1>().To<MyClass>();

// if strattegy is not inherited by MyClass
options.SetInterfaceOnly<IStrattegy2>().To<MyClassWrapper>(); 
```

**Comment by lahma** [comment]
I think current member filtering functionality in interop should suffice for this. You can write custom logic to check whether target is available on allowed interfaces and maybe use attributes too.

https://github.com/sebastienros/jint/blob/7e193c64d3e17d1a34a58e9775bd8d8513bab069/Jint.Tests/Runtime/InteropTests.MemberAccess.cs
