### ISSUE TITLE
LimitRecursion skips recursion within object getters

### ISSUE THREAD

**Issue by lekrus** [sebastienros/jint#735]
Hello! The following code always results in StackOverflowException:
```c#
var code = @"
var obj = {
  get test() {
    return this.test + '2';
  };
obj.test;
";
var engine = new Engine(cfg=> cfg.LimitRecursion());
engine.Execute(code).GetCompletionValue();
```

I checked the sources and see the recursion is checked for CallStatements only, and seems like getters are bypassed. Is it feasible to enhance recursion checks to catch samples like above?

Thank you!

**Comment by lekrus** [comment]
Hello,  could you please consider this issue or share your thoughts on how to mitigate it?
As soon as we cannot catch StackOverflowException, the plain Js code above can be used to terminate any process that uses Jint? 
Thank you!

**Comment by lahma** [comment]
This should now also be restricted in latest dev feed release, get/set functions are observed for recursion.

**Comment by lekrus** [comment]
thank you a lot!
