### ISSUE TITLE
Allow configuring options per Execute calls

### ISSUE THREAD

**Issue by lahma** [sebastienros/jint#738]
Allow overriding defaults for max statements for example for trusted scripts, otherwise would run with engine level constraints. This would probably mean creating a context that would pass through statement calls, context would have options which is engine default or user provided.

Relates to RavenDB's [need to change max statement](https://github.com/ravendb/jint/commit/e7d511a6c81dcd36fa62ba5fa32b84342d78b549) on use case basis.

**Comment by ppekrol** [comment]
In RavenDB we have 3 flows for this:
1. Change it permanently to X value
2. Change it temporarily to X value, then go back to original (using dispose pattern)
3. Disable it temporarily (set to int.MaxValue), then go back to original (using dispose pattern)

If 1. will return the old value, then 2. and 3. could be easily handled by us, no need to for a built-in mechanism for that.

As @lahma wrote, the reasoning is the source of the script, when it is an internal one (e.g. parsing our built-in scripts or a library - done on engine initialization) then we do not care about the max statements constraint, but when the script is passed by the user, then we need to have some safe guards.

**Comment by lahma** [comment]
Hey @ppekrol sorry for the long wait. I think I've solved this in https://github.com/sebastienros/jint/pull/789 where we also want to disable constrains when initializing engine pool. Basically for your use case:

```csharp
var options = new Options(); // the defaults you want to go with
var engine = new Engine();
using (engine.ActivateTemporaryConstraints(Array.Empty<IConstraint>()))
{
    // do a lot of things with engine
}

var tempConstraints = new Options().MaxStatements(42).LimitMemory(1024).CancellationToken(token).BuildConstraints();
using (engine.ActivateTemporaryConstraints(tempConstraints))
{
   // allow calling engine with limited resources
}
```
Please note that we are also in that PR building a safer (but probably not bullet proof) context that is able to dispose registered variables etc.

API may change and all feedback welcome!

**Comment by ppekrol** [comment]
Hi @lahma 

Will there be an ability to change just one constraint? Now I see you need to create new options for those each time. Can options be cloned maybe? What do you think?

**Comment by lahma** [comment]
My thinking was that you have like three sets of constraints pre-built. You can build those as static arrays using the example Options and then just switch between them during your specific use case. There's no need to build them every time.

In other words you would switch between constraint sets instead of replacing constraint in one set.

**Comment by lahma** [comment]
And correcting previous, because constraints have state,  they need to be build per use case,  but the options are static.

**Comment by lahma** [comment]
I'm closing this as there are workarounds and this would be non-trivial to implement.
