### ISSUE TITLE
Collisions with overload resolution

### ISSUE THREAD

**Issue by h15ter** [sebastienros/jint#74]
Hi Sebastien,

First of all, thank you man for a great project!

The big issue I see so far is .NET method overload resolution collisions. Overloads with different arguments number are resolved fine, but the ones which have the same number of arguments of different types become royal pain in the ass really. 
As far as I can see from TypeConverter.FindBestMatch and MethodInfoFunctionInstance.Invoke implementations, it simply iterates through the overloads trying to convert every single argument to desired argument type, and invokes the first overload where all arguments are converted successfully. This basically means that if I have two overloads with the same arguments length, I can't really be sure which one will be called unless I make converter to be very strict. This also means that I can't have overloads (like F(object) and F(string)) and pass null to it because it simply fails in FindBestMatch method when trying to read argument type. At the same time real C# compiler resolves such overloads properly through scanning class tree.

Do you have any plans for handling that? If not, could you share your thoughts/ideas on what is the best way to solve that?

PS: In the end of FindBestMatch method there is a totally redundant loop through methods doing actually nothing. Probably just some copy-paste trash left, but still it strikes the performance greatly...

**Comment by lahma** [comment]
Closing this as at least latest beta 3.x has quite good overload resolution capabilities.
