### ISSUE TITLE
Cannot pass function as argument to object type parameter

### ISSUE THREAD

**Issue by RachamimYaakobov** [sebastienros/jint#742]
If I run the following code, I get an error:
No public methods with the specified arguments were found.
```
 _engine = new Engine(cfg => cfg.AllowClr());
 _engine.SetValue("window", new jsWindow());
 _engine.Execute("window.setTimeout(function(){return 9;});");

public class jsWindow
{
    public int setTimeout(ref object expression)
    {
        return 0;
    }
}
```
A brief investigation revealed that JINT is unable to convert a function to an object [here](https://github.com/sebastienros/jint/blob/dce29b4598d2522b46ce5fb215ec8655966d70c7/Jint/Runtime/Interop/DefaultTypeConverter.cs#L277) and [here](https://github.com/sebastienros/jint/blob/dce29b4598d2522b46ce5fb215ec8655966d70c7/Jint/Runtime/Interop/DefaultTypeConverter.cs#L41).

Is there a bug here, or am I wrong about something?

**Comment by lahma** [comment]
Sounds similar to this issue https://github.com/sebastienros/jint/issues/739 ? So might be just that you need to declare input parameter as `JsValue`.

**Comment by lahma** [comment]
Closing as no new information, can reopen if still an issue.
