### ISSUE TITLE
Scope of let is unexpected

### ISSUE THREAD

**Issue by stefan-msft** [sebastienros/jint#743]
I do not know whether this is a javascript or a jint problem, but the following behaviour of let is unexpected:
```
jint> function a( i ) { let y=0; print("Function A: y is " + y ); }
jint> let y = 200;
jint> a(10);
Function A: y is 0
jint> y
=> 0
jint>
```
Could you clearify whether you expect y to be 0 or 200 ?

**Comment by stefan-msft** [comment]
Maybe this illustrates the problem better:
```
jint> function inner() { let y=100; print( "Inner " + y ); }
jint> function outer() { let y=50; print( "Before Inner " + y); inner(); print( "After Inner " + y ); }
jint> outer()
Before Inner 50
Inner 100
After Inner 100
jint>
```

I was expecting ``After Inner 50``

**Comment by sebastienros** [comment]
We might not have update the nuget package since we have let/const support ...

**Comment by sebastienros** [comment]
Or are you using the package on MyGet? I am release a new version right now.

**Comment by stefan-msft** [comment]
We are using 3.0.0.beta-1767 from NuGet

**Comment by sebastienros** [comment]
When this build is done it will be available on nuget.org.
https://ci.appveyor.com/project/SebastienRos/jint

let/const was merged last week

**Comment by sebastienros** [comment]
https://www.nuget.org/packages/Jint/3.0.0-beta-1828

Let us know if it's still broken after that

**Comment by stefan-msft** [comment]
I just double-checked: This works as expected now. Thank you very much !
