### ISSUE TITLE
[Question] Setting to Ignore Undefined Methods / Properties?

### ISSUE THREAD

**Issue by ooikengsiang** [sebastienros/jint#747]
I try to search around but cannot find any answer.
Is there any setting I can use to ignore undefined methods / properties when executing JavaScript that accessing .NET object passed using SetValue?
Expecting to skip that line and continue execute the next line inside JavaScript.
Or is there any other way I can work around this to achieve the same result?
Thank you.

**Comment by lahma** [comment]
I think this can be done with custom `IReferenceResolver` , here's an example: https://github.com/sebastienros/jint/blob/dev/Jint.Tests/Runtime/NullPropagation.cs

**Comment by lahma** [comment]
Closing this unless there's new information on the subject. Reference resolver should probably work here.
