### ISSUE TITLE
FunctionInstance no longer extendable

### ISSUE THREAD

**Issue by viceice** [sebastienros/jint#753]
I seems to be a regression of #722, since then i can no longer extend the  `FunctionInstance` class, because all constructors are internal

https://github.com/lahma/jint/blob/3b8a2de4627ab1c9bbda1589f4a3cd82b63ca80c/Jint/Native/Function/FunctionInstance.cs#L31-L51

You you accept a pr to make one of them at least `protected internal` or adding a protected cxtor?

**Comment by lahma** [comment]
Yes of course, I'm sorry for your trouble. I haven't seen functions extended outside of Jint so the hiding might have been a bad idea. It would be great if you could create a PR with some extending class(es) in test project to verify that your use case is covered in the future. You might need to open some other types too like `FunctionThisMode`.

I would be nice to hear about your use case too to learn more, if you would like to elaborate.

**Comment by viceice** [comment]
Thanks, i'll submit a pr the next days.

My use-case is to have a native  `UUID` (`Guid`) object type in js engine which will be auto converted to .net `Guid` when calling a `Guid` indexer on a .net class instance. For that i've implemented a `UuidConstructor`, a `UuidPrototype` and a `UuidInstance`.

So the only problem for now are the internal `FunctionInstance` ctor while updating from `3.0.0-beta-1778` to `3.0.0-beta-1828`.
