### ISSUE TITLE
How to create ArrayInstance in C#?

### ISSUE THREAD

**Issue by mytiope** [sebastienros/jint#760]
Maybe just a question, but maybe a bug.  Should I be able to create an ArrayInstance in C# code and have the length be set?  It appears to not set the length on creation (whether specifying initialLength or not).

This code (on 3.0.0-beta-1828):

```
var array = new ArrayInstance(engine, 0);
var length = array.Length;
```

Throws this exception:

```
Exception has occurred: CLR/System.NullReferenceException
An unhandled exception of type 'System.NullReferenceException' occurred in Jint.dll: 'Object reference not set to an instance of an object.'
```

I'm managing it right now by having my own method to create an ArrayInstance and manually set the length property to zero.  FYI, it had the same issue with 3.0.0-beta-1353, using array.GetLength() caused the exception to be thrown.

Note that creating the array in JS-land like below results in a C#-land ArrayInstance with the length property set as expected.

```
var array = engine.Execute("x = [];").GetCompletionValue().AsArray();
```

**Comment by lahma** [comment]
Thanks for reporting this, I've created a PR to fix the issue https://github.com/sebastienros/jint/pull/761
