### ISSUE TITLE
Serialization of NaN date throws a RangeError

### ISSUE THREAD

**Issue by olliejm** [sebastienros/jint#763]
I had a case where in an object that we can simply as the following:

```js
var problematicObj = {
  date: new Date(NaN)
};
```

Throws a range error when `JSON.stringify(problematicObj);` is invoked by Jint.

Expected was a JSON string result like so:

```json
{
  "date": null
}
```

Which is the result given when running `JSON.stringify({date: new Date(NaN)});` in the browser console.

The error occurs [here](https://github.com/sebastienros/jint/blob/dev/Jint/Native/Date/DatePrototype.cs#L662) as `t == NaN` and therefore `IsFinite(t)` returns `false`.

I solved the error to get the expected behaviour for my specific case by altering the code like so:

```cs
var t = thisTime.PrimitiveValue;

if (double.IsNaN(t)) 
{
  return Null;
}

if (!IsFinite(t))
{
  ExceptionHelper.ThrowRangeError(_engine);
}
```

Though I'm not familiar enough with the Jint code to know if that solution is really correct/desirable.

The error can be reproduced by this unit test:

```cs
[Fact]
public void NaNFromObject()
{
    _engine.Execute("function date() { return JSON.stringify({ date: new Date(NaN) }); }");

    var result = _engine.Invoke("date");

    Assert.True(result.IsString());
}
```

**Comment by sebastienros** [comment]
From the specs, the internal time value (tv) of the date should be `NaN` in this case, and the string representation should be `"Invalid Date"`. I think no exception should be thrown in this case.

**Comment by sebastienros** [comment]
Just looking at the code, I would have thought that it would be handled correctly. What version are you using?
Anything starting 2.x would explain.

**Comment by lahma** [comment]
This is peculiar... With Chrome console it works:

```
JSON.stringify({ date: new Date(NaN) });
"{"date":null}"
```

But with date constructor:
```
new Date(NaN) 
Invalid Date
```
So there might be some relaxation in this case to get the JSON out even with invalid date.

**Comment by lahma** [comment]
This might do the trick: https://github.com/sebastienros/jint/pull/764

**Comment by lahma** [comment]
@olliejm thanks for reporting, the fix is not in dev and available as part of the dev feed from MyGet.
