### ISSUE TITLE
Can I use jint to run JS/HTML code from C#?

### ISSUE THREAD

**Issue by LittleNewton** [sebastienros/jint#765]
Hi, I am developing a small **plugin/Add-in** for Microsoft Word.

## **I need a code highlighter**
I want to develop a new code highlighter by myself. After several days' attempt, I find it was so difficult to support multi language and style. So I turned into highlight.js. Recently, I have develop a good JS highlighter using **highlight.js**.

However, the Win Form's webBrowser object in .Net was awful. I cannot call my JS code from C# easily. After a lot of browsing on google, it turned that the built-in webBrowser class in C# was the same as IE6 so it cannot support the newer JS.

Can `Jint` do that?

My code: https://github.com/LittleNewton/Equation_and_Codebox

You can see my JS file in `src/highlight/` folder.

**Comment by sebastienros** [comment]
You should probably use WebView2 which is based on Edge: https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms

Jint won't provide the HTML dom so that wouldn't help you.
