### ISSUE TITLE
Executing THE SAME code on android give different result then windows

### ISSUE THREAD

**Issue by LagradOst** [sebastienros/jint#767]
Given this code I get 0 on my xamarin forms project running on android while it gave me 99 on my windows computer running a console project both running the latest stable version 2.11.58. (99 is the correct value of the code, can check here https://js.do/) and I cant for the life of me figure out why.

`
string _f = @"
            a = 34; U = -1278073289; l = 12; i = 5; L = 1560;
            ((a = ((U >> (l -= 8)) & 0xff)) || (i < (L - 2))) && (alert(a));";
            var fengine = new Engine().SetValue("alert", new Action<int>((a) => { Console.WriteLine(a); }));
            fengine.Execute(_f);
`

**Comment by LagradOst** [comment]
after some trying I found out that -[any negative number] & 0xff will return 0 on xamarin forms android for some reason

**Comment by onefreddy** [comment]
Hi, just wanted to create a similar topic. I have a completely different code, namely the code for calculating MD5 will parse it differently! Because of this, hashes on android are wrong

**Comment by lahma** [comment]
Is there an emulator or something where this can be tested?

**Comment by sebastienros** [comment]
Mono doesn't apply the same logic on integer overflow. At some point someone filed an issue but the mono team I think closed it stating that the behavior was not defined in the c# ecma spec and then they could decide to be correct. Nothing to do with javascript, or jint.

**Comment by onefreddy** [comment]
Thanks for your quick response. Here's an example. I'd love to make it work identically. do not check on a virtual device, you need a real one arm device
[md5.zip](https://github.com/sebastienros/jint/files/5900394/md5.zip)

**Comment by sebastienros** [comment]
So you are able to narrow it down to `[neg number] & 0xff`. Have you tried it in C# without using Jint at all?
Could you confirm that this is nothing special to Jint? In which case the issue needs to be filed on Mono. Or you need to adapt your algorithm to use a different way to calculate the hash.
