### ISSUE TITLE
Do you have any plan to support dotnet core3?

### ISSUE THREAD

**Issue by s2quake** [sebastienros/jint#768]
I am currently in the process of porting my personal project to dotnet core3.

    <TargetFramework>netcoreapp3.1</TargetFramework>
     ...
    <PackageReference Include="Jint" Version="2.11.58" />

The project is using the above format, but jint.dll is not copied to the output directory .

How can I use the dotnet3 version of jint.dll?

**Comment by lahma** [comment]
You should enable preview packages when upgrading with NuGet, 3.x supports .NET Standard 2.0. see here: https://www.nuget.org/packages/Jint/3.0.0-beta-1828
