### ISSUE TITLE
Error of parse "()"

### ISSUE THREAD

**Issue by tolkushkin** [sebastienros/jint#779]
I try parse following js code and get error  ParserException  Line 1: Unexpected token )
<pre>
let rn=(()=>{console.log('dd')});rn();
</pre>

code for example 
<pre>
var parser = new JavaScriptParser(false);
var program = parser.Parse(@"let rn=(()=>{console.log('dd')});rn();");
</pre>

**Comment by lahma** [comment]
What version are you using? I tried with the current dev and works as expected.

**Comment by tolkushkin** [comment]
Version: 2.11.58, that last version on https://www.nuget.org/packages/Jint

**Comment by lahma** [comment]
You should definitely enable preview releases and take the latest https://www.nuget.org/packages/Jint/3.0.0-beta-1828 (currently), a lot of new features and fixes.
