### ISSUE TITLE
Multiple indexers on the same type lead to AmbiguousMatchException

### ISSUE THREAD

**Issue by h15ter** [sebastienros/jint#78]
Hi Sebastien,

If .NET object has multiple indexers, property evaluation fails with AmbiguousMatchException.
I mean something like this:

```
public class My
{

    public string this[int index]
    {
        get { return null; }
    }

    public string this[string index]
    {
        get { return null; }
    }
}

        var engine = new Engine();
        engine.SetValue("$", new My());
        engine.Execute("var s = $[1];");
```

Basically this can be fixed in IndexDescriptor to enumerate all indexers and invoke first successful one (same as it's done for method overload resolution now). But it really leads to collisions hell... :(

**Comment by lahma** [comment]
Should be covered by current resolution algorithms, can be reopened if still an issue with 3.0 preview.
