### ISSUE TITLE
Have typed exceptions for Jint errors

### ISSUE THREAD

**Issue by christopheblin** [sebastienros/jint#780]
When I use Jint to invoke a function that does not exist, it throws an ArgumentException

I'd expect it to throw an exception inherited from JintException like NotCallableException

The code is located at https://github.com/sebastienros/jint/blob/4e86924d7e426b7bb0e7e9360b22600852afec73/Jint/Engine.cs#L665

Otherwise, in my code, I have some strange exception handling like:

            try
            {
                return engine.Invoke(functionName, arguments);
            }
            catch (ArgumentException)
            {
                throw new ProcessExecException(localizer.ExecEngineNotAFunction(functionName));
            }
            catch (JintException e)
            {
                throw new ProcessExecException(localizer.ExecEngineRuntimeError(e.Message));
            }
        
And now I am open to the fact that someone really throws an ArgumentException but not Jint itself and to have a misleading error message for the end user ...

Also, the error message could mention the NAME of the function instead of just "Can only invoke functions"

What do you think ?

**Comment by lahma** [comment]
Generally violating callable should create TypeError like here:

https://github.com/sebastienros/jint/blob/1fec0a93af62adea8368ee4c0dccef42b481251f/Jint/Native/Function/FunctionPrototype.cs#L68-L71

The error message is not set in stone so it could be more descriptive.
