### ISSUE TITLE
Is it possible to get the function list of  extenal .js file for .net?

### ISSUE THREAD

**Issue by softboy99** [sebastienros/jint#781]
i'm writing a expression editor, which define the expression used in .net. i need to populate it with the functions in extenal .js file.Is it possible to get the function list of  extenal .js file for .net?

**Comment by lahma** [comment]
You can write AST visitor that utilizes [Esprima](https://github.com/sebastienros/esprima-dotnet) and checks what constructs there are in file. Here's an example of recursive visitor that inspects functions:

https://github.com/sebastienros/jint/blob/24cda031a81033f49fa70ad0d3c66cc083e4066e/Jint/HoistingScope.cs#L111-L198

In your case your probably want to recurse and find all of type FunctionDeclaration.

**Comment by ayende** [comment]
You should also be able to inspect the global list of functions and see the new functions there, no?

**Comment by lahma** [comment]
Closing this as two viable options were given how to achieve the goal 🙂
