### ISSUE TITLE
MaxStatements constraint is not working

### ISSUE THREAD

**Issue by smadurange** [sebastienros/jint#790]
In the following code, I expect to see a `StatementsCountOverflowException` but I do not get any exception. Am I configuring it wrong?

```
class Program
{
    static void Main(string[] args)
    {
        var engine = new Engine(options =>
        {
            options.MaxStatements(1);
        });

        var x = engine.Execute("x = 0; x == 0").GetCompletionValue().ToObject();
    }
}
```

**Comment by lahma** [comment]
`x == 0` is an expression in JS sense so it isn't counted in statement count guard. See https://2ality.com/2012/09/expressions-vs-statements.html .
