### ISSUE TITLE
Writing int value to indexer causes ArgumentException

### ISSUE THREAD

**Issue by biwa** [sebastienros/jint#791]
Trying to write an int value to an object that has an indexer fails with an ArgumentException ("can't convert System.Double to System.Int32") - apparently the JS `number` type is not converted to C# `int` correctly, but to `double` instead. Here's a simple example showcasing the problem:

```
using System;
using Jint;

namespace JintTest
{
	class FakeIntArray
	{
		private int[] data;

		public FakeIntArray()
		{
			data = new int[5] { 123, 0, 0, 0, 0 };
		}
		
		public int this[int i]
		{
			get { return data[i]; }
			set { data[i] = value; }
		}
	}

	class Program
	{
		static void Main(string[] args)
		{
			Engine engine = new Engine(cfg => cfg.AllowClr(typeof(Program).Assembly));
			engine.SetValue("log", new Action<object>(Console.WriteLine));

			engine.Execute(@"

var JintTestNamespace = importNamespace('JintTest');

var fia = new JintTestNamespace.FakeIntArray();
log(fia[0]); // Reading works fine
fia[0] = 678; // Causes System.ArgumentException
log(fia[0]);


			");

			Console.Read();
		}
	}
}
```

**Comment by lahma** [comment]
Could you tell us the version of Jint you are using?

**Comment by biwa** [comment]
Happens with both 2.11.58 and the current 3.0 dev branch (30f26ced025e300a7ae07e6454f98b0facdc92ff) I compiled myself.

**Comment by lahma** [comment]
Created https://github.com/sebastienros/jint/pull/792 to fix the issue.

**Comment by biwa** [comment]
Thanks for the quick fix!
