### ISSUE TITLE
Array.splice not working if deleteCount parameter is not specified

### ISSUE THREAD

**Issue by junilo** [sebastienros/jint#793]
I encountered this issue today where if we use splice method and only specify start index

var myArray = ['a','b','c']
var deleted = myArray.splice(1)

The result of splice is empty

but if we do this:

var deleted = myArray.splice(1,2)

the result is correct.

is it a known issue or is the deleteCount (second parameter) required when running script on Jint?

**Comment by lahma** [comment]
Please try with 3.x beta, I think it should work.

**Comment by lahma** [comment]
Closing as not reproducible with latest 3.x series.
