### ISSUE TITLE
Access JObject in index failed

### ISSUE THREAD

**Issue by Oceania2018** [sebastienros/jint#797]
When I try to access vaue in `items[0]`, it threw error below:
![image](https://user-images.githubusercontent.com/1705364/98298800-30333480-1f7c-11eb-9515-d439ff91bf92.png)

To reproduce:
make a json string like
```
{
  "items": [{"p1": 1}],
  "row": 1
}
```
Then use `JObject.Parse(Response.Content)` to get a `JObject`.

Below is my ugly fix, convert string `"0"` to int `0`:
![image](https://user-images.githubusercontent.com/1705364/98298995-91f39e80-1f7c-11eb-9a98-51f72a0011dc.png)

**Comment by lahma** [comment]
* need to add more logic to check for IList which is obvious choice
* should also cache reflection search results
