### ISSUE TITLE
BindFunctionInstance removing duplicate arguments

### ISSUE THREAD

**Issue by mytiope** [sebastienros/jint#802]
Using "bind" on a function breaks the function arguments when there are duplicate arguments. 
 This example should produce two lines with the same output:
```
var testFunc = function (a, b, c) {
    console.log("TEST: " + a + ", " + b + ", " + c + ", " + JSON.stringify(arguments));
}

testFunc("a", 1, "a");
testFunc.bind("anything")("a", 1, "a");
```

But instead gives us:

```
TEST: a, 1, a, {"0":"a","1":1,"2":"a"}
TEST: a, 1, undefined, {"0":"a","1":1}
```
I think the root cause is CreateArguments from BindFunctionInstance.cs:

```
        private JsValue[] CreateArguments(JsValue[] arguments)
        {
            return Enumerable.Union(BoundArgs, arguments).ToArray();
        }
```
Enumerable.Union removes duplicate items, which causes problems if any two or more of the arguments have the same value.  The solution is probably just to change that line to Enumerable.Concat instead.

Thoughts?

**Comment by sebastienros** [comment]
You look like you are a step away from creating a unit test and fixing it.

**Comment by lahma** [comment]
Maybe even without the slow LINQ, using array and copy 😉

**Comment by sebastienros** [comment]
The linq implementation might be faster than yours ...
