### ISSUE TITLE
GetSetPropertyDescriptor alternative?

### ISSUE THREAD

**Issue by Jither** [sebastienros/jint#804]
I'm working on a project where several different classes collectively compose a JS object for consumption by scripts run by Jint. In other words, they're dynamically creating properties on an `ObjectInstance`, by using `FastAddProperty` directly, rather than relying on the POCO conversion. But as far as I can tell, FastAddProperty doesn't have any way of using accessor descriptors, so for that purpose, I've been using e.g.

`jsObject.DefineOwnProperty("key", new GetSetPropertyDescriptor(getter, null, true, false));`

Always figured that wasn't how it's meant to be done - and sure enough, in the latest beta, `GetSetPropertyDescriptor` is now internal. Is there an alternative that I'm missing?

**Comment by lahma** [comment]
I don't see a reason not to allow this as public, should also promote to `Jint.Runtime.Descriptors` as it's a more common than the "truly specialized ones". We've just marked many things as internal to reduce public API surface which needs to be worried about when refactoring.

**Comment by Jither** [comment]
I'm guessing the main (only?) public use case would be defining an accessor property - in my own fork, for my specific use case, rather than exposing the descriptor class, I've added two extension methods on ObjectInstance - one of which is just an alias for `FastAddProperty`, for naming symmetry - and the other doing the same work, but for accessor properties:

https://github.com/Jither/jint/blob/dev/Jint/Extensions/ObjectInstanceExtensions.cs
