### ISSUE TITLE
Generic Method Invocation Problem

### ISSUE THREAD

**Issue by windischb** [sebastienros/jint#814]
Hi!

While testing the new support for Extension Methods, i'll found a little bug.
I'm not sure if this only happens with Extension Methods or also with Instance Methods.

Again i'm testing with Flurl.
Flurl has an extension methods class named "ResponseExtensions"
In this class there are following Methods in the same order as below:

```csharp
public static async Task<T> ReceiveJson<T>(this Task<IFlurlResponse> response)
{
    using (IFlurlResponse resp = await response.ConfigureAwait(false))
        return resp == null ? default (T) : await resp.GetJsonAsync<T>().ConfigureAwait(false);
}

public static async Task<object> ReceiveJson(this Task<IFlurlResponse> response)
{
    using (IFlurlResponse resp = await response.ConfigureAwait(false))
        return resp == null ? (object) null : await resp.GetJsonAsync().ConfigureAwait(false);
}
```

If i want to use the second Method (Non-Generic) Jint usees the Generic one.
Seems that Jint just use the first method with matching name.
For testing i have created a custom extension method class with the same methods, but the Non-Generic Method first and registered the custom class before the "ResponseExtensions" class.

Now Jint uses the correct Method (Non-Generic).

Would it be possible the skip Generic Methods?
Or even better, find a Way to support Generic Methods?
Maybe in a Way similar to instantiate a generic object, like mentioned in the readme:

Generic types are also supported. Here is how to declare, instantiate and use a List<string>:
```js
    jint> var ListOfString = System.Collections.Generic.List(System.String);
    jint> var list = new ListOfString();
    jint> list.Add('foo');
    jint> list.Add(1); // automatically converted to String
    jint> list.Count; // 2
```
If it's a Generic Method, the first argument/s are/is the Generic Type/s, followed be the method parameters??

**Comment by lahma** [comment]
@windischb first of all, thank you for trying it out! I was hoping that some scrutiny would revel some edge cases. Would you want to have a try with a PR resolving the issue?

**Comment by windischb** [comment]
Yes off course, I'll try my best.
But maybe there should be first made a decision if Generic methods should be supported, or not...
Or skip Generic Methods for now and try on that later, if a decision is made how to declare generic type arguments?

**Comment by lahma** [comment]
@windischb I updated the above comment, the true generic support might require some work so there might be a faster workaround by prioritizing methods.
