### ISSUE TITLE
When reviver of JSON.parse is not callable, "TypeError: Can only invoke functions"

### ISSUE THREAD

**Issue by dimaaan** [sebastienros/jint#818]
This violates ECMA 262 15.12.2.5.a
See http://www.ecma-international.org/ecma-262/5.1/#sec-15.12.2

Tested in branch dev.

Steps to reproduce:
1) In Jint REPL run
```js
 JSON.parse('{}', undefined)
```
"TypeError: Can only invoke functions" is thrown

2) In Chrome/Firefox dev console run same code.
Empty object returns

**Comment by lahma** [comment]
If you add a test class

```csharp
using Xunit;

namespace Jint.Tests.Test262.BuiltIns
{
    public class JSONTests : Test262Test
    {
        [Theory(DisplayName = "built-ins\\JSON")]
        [MemberData(nameof(SourceFiles), "built-ins\\JSON", false)]
        [MemberData(nameof(SourceFiles), "built-ins\\JSON", true, Skip = "Skipped")]
        protected void RunTest(SourceFile sourceFile)
        {
            RunTestInternal(sourceFile);
        }
    }
}
````
into `Jint.Tests.Test262\BuiltIns` there should be a good start for a PR 👍🏻

**Comment by dimaaan** [comment]
@lahma Thank you very much for your effort!
