### ISSUE TITLE
arguments.callee.caller Fixed as undefined

### ISSUE THREAD

**Issue by oujunke** [sebastienros/jint#819]
When the method queries the current method caller, it is found to be fixed to undefined, and the initialization in the code is fixed to undefined, but it has never been updated

**Comment by lahma** [comment]
Can you provide a code example that works in Chrome console and not in Jint?

**Comment by lahma** [comment]
If there's more information, we can reopen to investigate.

**Comment by oujunke** [comment]
Sorry for not replying in time

**Comment by oujunke** [comment]
Chrome console:function t1(){console.log(arguments.callee.caller+"")}function t2(){t1()}t2()
Result:VM2329:1 function t2(){t1()}
Jint.Repl:function t1(){print(arguments.callee.caller+"")}function t2(){t1()}
Result:undefined

**Comment by oujunke** [comment]
> If there's more information, we can reopen to investigate.

Sorry for not replying in time,Code already provided

**Comment by lahma** [comment]
The [functionality seems to be discouraged and non-standard](https://stackoverflow.com/questions/103598/why-was-the-arguments-callee-caller-property-deprecated-in-javascript) and it's not part of the current specification. I doubt that Jint will ever support this.

The link above lists various better workarounds to call recursive methods.

**Comment by oujunke** [comment]
![image](https://user-images.githubusercontent.com/26790160/103253636-ef283100-49bc-11eb-8a31-a792322c4fb3.png)
I solved it by adding this code, I don't know what side effects will be

**Comment by lahma** [comment]
Unfortunately that's not a generic fix. Execution context is created per scope which can even be for loop's initialization if let/const is present etc. So Last/top is might not be a function at all.

What's the underlying cause that you need this? Some legacy script that hasn't been ported to follow best practices?

**Comment by oujunke** [comment]
When running the test script, it was found to be inconsistent with the browser, so I want to fix it

**Comment by oujunke** [comment]
After the modification on my single script, it can be tested and passed. If I want to change it to general purpose, is there a better solution?

**Comment by lahma** [comment]
I don't know what's the correct way to implement this, it's not standard and not part of [the specification](https://tc39.es/ecma262/). It's just something that browsers have chosen to implement. Maybe you can consider fixing the script not to utilize non-standard feature?

**Comment by oujunke** [comment]
Then I temporarily adopt this scheme, try to repair the script

**Comment by sgf** [comment]
> I don't know what's the correct way to implement this, it's not standard and not part of [the specification](https://tc39.es/ecma262/). It's just something that browsers have chosen to implement. Maybe you can consider fixing the script not to utilize non-standard feature?

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Function/caller
