### ISSUE TITLE
JSON.parse('') crashes the entire program

### ISSUE THREAD

**Issue by KurtGokhan** [sebastienros/jint#823]
```
try {
  JSON.parse('');
} catch(err) {
  console.log('Error')
}
```

If you run this script in browser, it will print `Error` to console. However, Jint will halt the program entirely with `ArgumentOutOfRangeException` and will not go into the `catch` block. With any other invalid JSON, for example `JSON.parse('a')`, it will go into the catch block as expected.

**Comment by lahma** [comment]
I think this is on Esprima side where `Position` constructor throws error.
