### ISSUE TITLE
setMonth with negative argument

### ISSUE THREAD

**Issue by thorn0** [sebastienros/jint#825]
Same as #383. This wasn't fully fixed.

```C#
var engine = new Engine().SetValue("log", new Action<object>(Console.WriteLine));

engine.Execute(@"
  var d = new Date(1610364592426);
  log(d);
  d.setMonth(-1, 31);
  log(d);
");
```

Result:
```console
11-Jan-21 11:29:52 AM
31-Jan-21 11:29:52 AM
```

Expected:
```console
11-Jan-21 11:29:52 AM
31-Dec-20 11:29:52 AM
```

E.g. this breaks Moment.js (which is a wrapper for `Date`). The following code
```js
moment(1609365600000).diff(1577829600000, 'years', true)
```
returns `Infinity` instead of expected `0.9973118279569894`.

**Comment by sebastienros** [comment]
Note: the second parameter sets the day of the month. It should be equivalent to `setMonth(-1); setDate(31);`

**Comment by sebastienros** [comment]
`setUTCMonth` and `setFullYear` probably have the same bug

**Comment by sebastienros** [comment]
What version of Jint are you using? It worked for me inside a unit test.

**Comment by thorn0** [comment]
2.11.58 from NuGet

**Comment by sebastienros** [comment]
Please use the 3.x version. It's fixed there, and is the recommended version. Less bugs and faster, even if it has the "beta" suffix.

**Comment by thorn0** [comment]
Ouch. I didn't realize how old it is. Probably the issue can be closed.
