### ISSUE TITLE
Memory Leak In Exception.

### ISSUE THREAD

**Issue by tricuongle** [sebastienros/jint#829]
I use the Jint Version: 13.0.0-Beta-1767.
I found the Memory Leak as bellow:

![image](https://user-images.githubusercontent.com/54373361/105882651-78706900-6038-11eb-828e-bc20d07d7a98.png)

Pls check it. Thank you.

**Comment by lahma** [comment]
Very nice screenshot. Can you attach code repro (as text, not image)?

**Comment by tricuongle** [comment]
This is my funtion: 

 public static string RunJavaScriptSchedule(GlobalScheduleModel _Schedule)
        {
            CancelTokenSourceEvent cancelToken = new CancelTokenSourceEvent();
            try
            {               
                SystemInterfaceBLL InterfaceFunctionObject = new SystemInterfaceBLL();          
                InterfaceFunctionObject.JavascriptScenesObj = _Schedule;          

                // For prevent the endless loop => Can't Refesh to change Command Data. 
                // => Check the Scription is running or not. 
                // => If not => Adding CancelationTokenSource for manual Cancel.
                
                bool isOk = false;
                foreach(var cancelSource in TriggerCheckingService.CancelEventList.ToList())
                {
                    if (cancelSource == null)
                    {
                        TriggerCheckingService.CancelEventList.Remove(cancelSource);
                        continue;
                    }

                    if ((cancelSource.Id == _Schedule.Id) && (cancelSource.Type == EventType.ScheduleTrigger))
                    {
                        if (cancelSource.NumberThread > 0) return "Error: More Than One Threads Are Running";     
                        cancelSource.NumberThread = 1;                  
                        isOk = true;
                        cancelToken = cancelSource;
                        break;
                    }    
                }
                if(!isOk)
                {
                    cancelToken = new CancelTokenSourceEvent(_Schedule.Id, EventType.ScheduleTrigger, 1);
                    TriggerCheckingService.CancelEventList.Add(cancelToken);
                }    

                var engine = new Engine(options =>
                {
                    // Use a cancellation token.
                    options.CancellationToken(cancelToken.CancelSource.Token);
                });

                engine.SetValue("SystemLib", InterfaceFunctionObject);
                string command = _Schedule.JavaScriptAction;

                var result = "";
                try
                {
                    result = engine.Execute(command).GetCompletionValue().ToString();
                }
                catch(Exception exp)
                {
                    result = exp.ToString();
                }

                if (result.Trim() == "undefined") result = "";
                TriggerCheckingService.CancelEventList.Remove(cancelToken);

                // Update Data Only
                if ((result != "null") && (result.Trim() != "")) result = result + "\n"; else result = "";    
                string debug = _Schedule.Debug ?? "";
              
                GlobalScheduleDB.UpdateDebug(_Schedule, result + debug);
                GlobalScheduleDB.UpdateLastTime(_Schedule, Helper.UnixTime.GetCurrentMilliSecond());

                return (result + debug);
            }
            catch (Exception exp)
            {
                TriggerCheckingService.CancelEventList.Remove(cancelToken);
                var result = exp.ToString();
                // Update Data Only
                if ((result != "null") && (result.Trim() != "")) result = result + "\n"; else result = "";
                string debug = _Schedule.Debug ?? "";
                GlobalScheduleDB.UpdateDebug(_Schedule, result + debug);
                GlobalScheduleDB.UpdateLastTime(_Schedule, Helper.UnixTime.GetCurrentMilliSecond());

                return result;
            }
        }

**Comment by lahma** [comment]
Created [an issue on Esprima side](https://github.com/sebastienros/esprima-dotnet/pull/144) as it's better to fix it there first and then flow it to Jint.

**Comment by tricuongle** [comment]
Thanks @lahma, I see you fixed it, and could you tell me how long for next fix release?

**Comment by lahma** [comment]
It should show up on NuGet pretty soon, just uploaded. Thanks for reporting and details!
