### ISSUE TITLE
Super slow performance in jint 3

### ISSUE THREAD

**Issue by vflam** [sebastienros/jint#832]
Hello,

I was super hyped with Jint because I have a large typescript codebase I want to integrate into a Unity 3D project.

I managed to get things to work using webpack to output javascript then used by Jint.

But I was very disappointed when I realized that Jint was so slow I might need to consider an other solution, recoding everything in C# or perhaps use an embedded Chrome to run my JS. I don't know what exactly causes this but an operation that is "instant", basically takes less than 0.5 second to execute on Chrome takes about 15 seconds to execute in Jint. I have a tree like structure made with arrays and algorithms searching the trees. My algorithms are not very optimized as I never had performance problems in web browsers I never worried much about it but with Jint it simply takes too long.

Do you have any idea what could cause this in particular, perhaps I could use a C# implementation of some function to get things running faster. I have a lot of for...in loop browsing arrays and I also use a lot of Maps. Perhaps it's the Map implementation that's slowing things down?

One additional detail, I am working in Ubuntu Linux, could this be caused by a slow implementation of C# in Linux?

Any help would be greatly appreciated!

**Comment by sebastienros** [comment]
We could probably help if you shared some repro that we can run locally and trace.
Otherwise there is not much to say. There might be a bug to fix, or maybe that's how slow this is. But this is not something we noticed to that extent.

So at least if you can isolate a part of your code that shows some slowlessness, that would help a lot.

And just to be sure, are you using 3.0-* since it's much faster than 2.0.

**Comment by vflam** [comment]
Thank you for the quick reply, I will try to pinpoint what's causing the slowdown. I wanted to ask just in case some function was known to be slow. I am using 3.0 and it's indeed much faster, I was using 2.0 before and it was even slower.

**Comment by vflam** [comment]
After looking at the problem again, I think it's just slow. My code does nothing special but loop through arrays basically.

I don't know if that's because of C# but it makes sense that a C# implementation of a Javascript engine be slower than a native implementation. I managed to gain some time by optimizing my code but it still takes a few seconds for something that should take 100ms. 

So I ended up taking a different approach, instead of using Jint, I made a small NodeJS web server that is started by my Unity app, Unity communicates with it through http and NodeJS runs the Javascript. This solution seems to work very well for me, the downside is that I have to bundle NodeJS into an exe file so my project doesn't depend on it being installed on the system, it takes 40mb but that's acceptable in my use case.

**Comment by lahma** [comment]
What kind of loops does your code utilize? Plain `for`?

**Comment by vflam** [comment]
Typically for loop with recursive calls. Perhaps recursivity is the problem?

Typescript:
`export function deepTrasverse(opt: OptionTree, callback: Function, condition: Function | null = null): void {
  let conditionMet = true;

  if (condition != null) {
    conditionMet = condition(opt);
  }

  if (conditionMet == true) {
    callback(opt);

    if (opt.options != null) {
      for (const child of opt.options) {
        deepTrasverse(child, callback, condition);
      }
    }
  }
}`

**Comment by lahma** [comment]
Thanks for the sample. Yes, recursion will definitely add some burden, but there's also that you traverse with for-of which can be more heavy-weight due to its semantics. If you can switch to for and change recursion to iteration it will be faster for sure. But as you've found an alternative approach I'm not sure whether it's worth your while, node will always be faster due to its design - but will of course have the penalty from HTTP call.

**Comment by vflam** [comment]
Indeed it's definitely a tradeoff, it would be way too much work for me to change my loops and switch to iteration. I think NodeJS probably turns these recursive calls into iterative loops in code optimization, that would explain the big difference in performance.

**Comment by lahma** [comment]
Would you mind sharing the shape of `OptionTree`? So if I have time I could create a benchmark against the this case. `opt.options` is just an array?

**Comment by vflam** [comment]
opt.options is an array of OptionTree, OptionTree is basically a structure with some data and an array of OptionTree (options).

I would have to share too many files from my project to give you the details but essentially this is what happens. Here is a small piece of code you could try to benchmark. I turned it directly into javascript for convenience.

I put a small dataset for the example but my actual project has a bigger tree, you can insert more nodes to the into the data variable for the benchmark and see how it goes in Jint compared to node. If you obtain similar performance then I guess the slowdown could be due to an other part of my code I could look into. If there is a significant performance difference, well then you found the problem :)

```
var data = {
  val: 100,
  options: [
    {
      val: 30,
      options: [],
    },
    {
      val: 40,
    },
    {
      val: 100,
      options: [
        {
          val: 15,
          options: [
            {
              val: 50,
            },
            {
              val: 50,
            },
            {
              val: -10,
              options: [
                {
                  val: 200000000,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      val: 50,
      options: [
        {
          val: 20,
        },
        {
          val: 30,
        },
      ],
    },
  ],
};

function deepTrasverse(opt, callback, condition) {
  var conditionMet = true;

  if (condition != null) {
    conditionMet = condition(opt);
  }

  if (conditionMet == true) {
    callback(opt);

    if (opt.options != null) {
      for (const child of opt.options) {
        deepTrasverse(child, callback, condition);
      }
    }
  }
}


function main() {
  let options = data;
  let total = 0;
  deepTrasverse(
    options,
    function (opt) {
      total += opt.val;
    },
    function (opt) {
      return opt.val >= 0;
    }
  );
  console.log(total);
}

main();
```
```
$ node test.js
485
```

**Comment by lahma** [comment]
Thank you, this is a great example to test against!
