### ISSUE TITLE
Any plans on supporting Web Assembly?

### ISSUE THREAD

**Issue by anna-git** [sebastienros/jint#849]
Hi there,

Thank you for creating and maintaining this very efficient engine. Are there any plans to support wasm at some point? 
I see the WebAssembly object is undefined in the logs for now.

Thank you

**Comment by lahma** [comment]
This might be out of scope, or if someone wants to champion the feature a PR would be nice.

**Comment by sebastienros** [comment]
No plan, and there are existing solutions in dotnet either by wrapping the c native implementation, or fully compiling it to IL.
There might be some synergies to find eventually, for tools that needs both.

**Comment by lahma** [comment]
I'm closing this as there's no plans for supporting, pretty much out of scope as a whole different scope from interpreting JS.
