### ISSUE TITLE
CalcEngine.Execute(Script).GetCompletionValue().ToObject() throw exception: "Line 1: Unexpected token ILLEGAL"

### ISSUE THREAD

**Issue by softboy99** [sebastienros/jint#850]
string script = "2019-09-19<2021-01-01";
CalcEngine.Execute(Script).GetCompletionValue().ToObject()

throw exception: "Line 1: Unexpected token ILLEGAL"

Jint version: v2.11.58;
.net framework: 4.8

**Comment by lahma** [comment]
Please use 3.x beta, works there as expected.

**Comment by sebastienros** [comment]
Though I am sure this script is not doing what seems to be what you want ...
`2019-09-19<2021-01-01` -> `(2019 - 09 - 19) < (2021 - 01 - 01)` -> `1991 < 2019` -> `true`

**Comment by softboy99** [comment]
Hi,
Thanks. console.log(2019-09-19<2021-01-01) -> true in browser
