### ISSUE TITLE
Using JSON.stringify with an ExpandoObject returns "{}" instead of useful results

### ISSUE THREAD

**Issue by craigfowler** [sebastienros/jint#855]
I have created [a small repo which contains a reproduction case for this].  To see the issue for yourself clone it and run it using `dotnet test`.  _This might be a duplicate of #347, although I want to specifically point out the behaviour relating to `ExpandoObject` instead of a statically-typed class instance._

If an `ExpandoObject` is added into a Jint environment via `SetValue` & subsequently an attempt is made to `JSON.stringify(theExpando)`, this will always produce a result of `"{}"`.  Instead I think it should produce appropriate results for the state of that expando object.

This is particularly troublesome because of the behaviour of `JSON.parse`.  When using `JSON.parse('{"foo":5,"bar":"A string"}')`, Jint will return an expando back to "the .NET world".  That's understandable; I don't think any other behaviour would make any sense.  Unfortunately, that returned object then can't be round-tripped back to JSON by executing JS via Jint, because of this issue.

[a small repo which contains a reproduction case for this]: https://github.com/craigfowler/jint-stringify-expandoobject

**Comment by craigfowler** [comment]
I forgot to mention, one of the test cases in the repro repository does pass.  It shows how it stringifies correctly if you give Jint a `Dictionary<string,object>`.  It's possible to convert expandos to that, so that might be a viable workaround for those who run into this.

**Comment by ayende** [comment]
Note that this means that Jint will have to understand `IDynamicObject` to support this.
