### ISSUE TITLE
Problem with using functions when Strict option is enabled, since 3.0.26

### ISSUE THREAD

**Issue by aviv86** [sebastienros/jint#857]
Hi
The following test passes in version 3.0.25 (and older), but started failing since 3.0.26 
```c#
using Jint;
using Jint.Native;
using Xunit;

namespace Tryouts
{
    public class Program
    {
        public static void Main()
        {
            var script = @"
function execute(doc, args){
    var i = doc;
    {
        function doSomething() {
            return 'ayende';
        }

        i.Name = doSomething();
    }
}
";

            var engine = new Engine(options =>
            {
                options.Strict();
            });
            engine.Execute(script);

            var user = new User();
            var args = new []
            {
                JsValue.FromObject(engine, user)
            };

            var call = engine.GetValue("execute").TryCast<ICallable>();
            call.Call(Undefined.Instance, args); // throws JavaScriptException: 'doSomething is not defined', since version 3.0.26


            Assert.Equal("ayende", user.Name);

        }

        private class User
        {
            public string Name { get; set; }
        }
    }
}


```

Note that if we remove from the script the curly brackets that start after `var i = doc;` then the test passes. 
Same if `Strict` option is disabled.

**Comment by lahma** [comment]
I think the curly brackets make the function block scoped function (at least in strict mode) and it will not be hoisted to outside scope, it's ES6 behavior.

**Comment by lahma** [comment]
Chrome console:

```
> function execute(doc, args){
    var i = doc;
    {
        function doSomething() {
            return 'ayende';
        }

        i.Name = doSomething();
    }
}

< undefined
> execute
ƒ execute(doc, args){
    var i = doc;
    {
        function doSomething() {
            return 'ayende';
        }

        i.Name = doSomething();
    }
}
> doSomething
VM117:1 Uncaught ReferenceError: doSomething is not defined
    at <anonymous>:1:1
(anonymous) @ VM117:1
```

**Comment by aviv86** [comment]
Also from chrome console :
![Screenshot-js](https://user-images.githubusercontent.com/23610777/113845730-7ba57500-979e-11eb-986e-0a3c752ba0d0.png)

**Comment by lahma** [comment]
I think the problem is here:

https://github.com/sebastienros/jint/blob/546f1e8960e00c791dce1e3cf5d293e88ae13384/Jint/Runtime/Interpreter/JintStatementList.cs#L114-L144

If you'd like to implement the missing bits, a PR would be most welcome.

**Comment by Jither** [comment]
Note that you can't necessarily compare with browser implementation in this - the ECMAScript spec defines different behavior for block level function declarations in browsers vs other ECMAScript implementations. ES6 strict mode *in a browser* will create both a block scoped and function scoped binding for the function. Outside a browser, things are simpler - the function will be block scoped (and thus not callable from outside the block) in both strict and non-strict mode. https://262.ecma-international.org/6.0/#sec-block-level-function-declarations-web-legacy-compatibility-semantics

**Comment by aviv86** [comment]
> ES6 strict m

Hi, thanks
I wasn't expecting function `doSomething` to be callable from outside the block. That's not the issue here.
In this test example, `dosomething` is only been called from within the same block where it was defined.
