### ISSUE TITLE
Any plans to implement ECMA 2020 Optional Chaining?

### ISSUE THREAD

**Issue by twehner** [sebastienros/jint#863]
Have very compelling need to support optional chaining/existential dereferencing (`myObject.someValue?.childValue` and `myObject.someMethod?.()`).  If this isn't on the roadmap yet, I'm definitely willing to devote my (or even some of my development team's) time to building it out, but this is a hefty codebase that I don't have experience with and any rough guidance on approach would be super helpful.

**Comment by lahma** [comment]
The implementation on Jint side won't probably be that complicated, but we need parsing support in Esprima.NET which waits for https://github.com/jquery/esprima/pull/2048 .

**Comment by twehner** [comment]
Ah, thanks.  Will keep an eye on that.
