### ISSUE TITLE
Trying to get an object's property modifies that property of object

### ISSUE THREAD

**Issue by KurtGokhan** [sebastienros/jint#865]
When a property is tried to be accessed in an `ObjectWrapper`, that property is modified. Suppose something like this:

```
// Suppose that 'value' is an ObjectWrapper and it does not have 'prop' property
console.log('prop' in value)  // Always true
console.log(value.prop) // Prints  System.Func`3[Jint.Native.JsValue,Jint.Native.JsValue[],Jint.Native.JsValue]
```

I tracked down the problem to this line:
https://github.com/sebastienros/jint/blob/dev/Jint/Runtime/Interop/ObjectWrapper.cs#L233

Is it supposed to be like this or is there a mistake?

**Comment by lahma** [comment]
There might be a bug. Ideally we detect if the member accessor is valid (for regular objects target must exists, for dynamic object maybe a different thing) and then register it for subsequent calls to work (that's why the SetOwnProperty is there).

 A PR with test case and a fix is always welcome.

**Comment by KurtGokhan** [comment]
I wanted to first ask if you were familiar with this issue.

@lahma  I found the solution but I I cannot reproduce the bug in isolation no matter what I do. It happens in my very crowded code. I will create a PR with the solution and maybe later I can add a test.
