### ISSUE TITLE
Iterating CLR objects not working

### ISSUE THREAD

**Issue by emilmuller** [sebastienros/jint#876]
I have a class which implements IDictionary<string, object>.
When using a for loop on an object which is an instance of my custom dictionary type, or if I use Object.keys(...) I will get back ["Count"], and not the keys in the dictionary (Count is not a key, but a property on IDictionary<string, object>).

I'm not sure if this is a bug or a change request. If the latter, is it possible to add support for iterating IDictionary<string, object>?
And meanwhile -- is there some workaround to use my custom IDictionary class?

Kind regards, Emil

**Comment by lahma** [comment]
What version are you using?

**Comment by emilmuller** [comment]
sorry, looks like it is 3.0.0-beta-2031 :)

**Comment by lahma** [comment]
I think I might have fixed this with https://github.com/sebastienros/jint/commit/c1179614790fe8d525e3c3c29575ad7e31436dc2 (still unreleased) . So could you try latest from [MyGet feed](https://www.myget.org/F/jint/api/v3/index.json) . If that still doesn't work maybe you can create a failing test case for us to work with?

**Comment by lahma** [comment]
Both `Object.keys` and `Object.values` iterate correct keys and values from CLR objects using the dev version.
