### ISSUE TITLE
"(()=>{}).hasOwnProperty('name')" returns true in safari but false in Jint

### ISSUE THREAD

**Issue by twop** [sebastienros/jint#888]
It seems that anonymous lambdas should have a name property.

I found it while debugging a failing ecma262 test. As it turned out it has a bug in it.
Context:
> I found a bug in ecma262 tests which in turn uncovered a bug in Jint
> "(()=>{}).hasOwnProperty('name')" returns true in safari but false in Jint
> Here is the test that surfaced it.
> https://github.com/tc39/test262/blob/main/test/built-ins/Promise/race/resolve-element-function-name.js
> The function that is checked is coming from here
> executor(() => {} <-------, () => {}); Which happens to be just anonymous lambda. The test intent is to check built-in funciton but it checks a func defined in script

**Comment by sebastienros** [comment]
`true` also in chromium

**Comment by sebastienros** [comment]
Returns an empty string (not undefined)
