### ISSUE TITLE
JSON.parse fails with tab in property name

### ISSUE THREAD

**Issue by mus65** [sebastienros/jint#897]
Consider the following JavaScript file `test.js`:

```
JSON.parse("{\"abc\\tdef\": \"42\"}");
```

Note that the property name contains a `\t` . The following code will fail:

```
var engine = new Jint.Engine();
engine.Execute(File.ReadAllText(@"TestFiles\test.js"));
```

Exception:

```
Jint.Runtime.JavaScriptException: Invalid character in property name 'abc	def'
   at parse <anonymous>:1:1
   at <anonymous>:1:1
```

The same code works fine in Edge:

![image](https://user-images.githubusercontent.com/1933789/118507302-64a75a80-b72e-11eb-866a-b4a6641fdc2d.png)

This only seems to affect property names, tabs in values work fine.

Version is latest beta v3.0.0-beta-2031

**Comment by lahma** [comment]
Thanks for reporting, created https://github.com/sebastienros/jint/pull/898 to fix the issue.
