### ISSUE TITLE
Unexpected Promise.all behavior

### ISSUE THREAD

**Issue by shestakov** [sebastienros/jint#908]
First of all, thank you very much guys for the new release and the support of promises! Great work!

I am testing promises right now, and run into an issue.

On some occasions, when I do

`var evaluationResults = engine.Evaluate("return Promise.all(someArray)").UnwrapIfPromise().ToObject();`,

and `someArray` does not contain any promises at all, but only contains _one_ object, namely a .Net `Dictionary<string, object>`,

instead of an array with a single element in `evaluationResults` I get array of `KeyValuePair<string, object>` of the dictionary within an array.

If instead of an instance of `Dictionary<string, object>` I put into that array a single simple JS object, it works just as expected.

If I simply add to `someArray` any additional element, say, `true`, it works like a charm.

**Comment by lahma** [comment]
Thanks for the report, could you please write a failing unit test case for us, would make investigation easier?

**Comment by shestakov** [comment]
> Thanks for the report, could you please write a failing unit test case for us, would make investigation easier?

Sure, [here it goes](https://github.com/shestakov/jint/blob/b50574f23649d7975dea7b26fc654aaa9ef39b1c/Jint.Tests/Runtime/PromiseTests.cs#L501).

Hope it helps and thanks for your great work.

**Comment by lahma** [comment]
@shestakov this is a bit weird, I created [baseline based with your test case](https://github.com/sebastienros/jint/pull/911), but it works?

**Comment by shestakov** [comment]
> @shestakov this is a bit weird, I created [baseline based with your test case](https://github.com/sebastienros/jint/pull/911), but it works?

Sorry I mislead you. I've made some _passing_ tests as an illustration. Replaced them with just one failing test [here](https://github.com/shestakov/jint/blob/aac65701e19f51ec8b71f00b1bd68d5d3fcadf4b/Jint.Tests/Runtime/PromiseTests.cs#L501).

**Comment by lahma** [comment]
Thanks, https://github.com/sebastienros/jint/pull/911 should fix this.

**Comment by shestakov** [comment]
> Thanks, #911 should fix this.

@lahma thanks a lot!

I've checked out the workaround you've added.

Could you please explain briefly (if it is possible to explain briefly) why those heuristics ([one](https://github.com/sebastienros/jint/blob/3b33cb1135e743040f7ba5078eb2ae495fb2a0ce/Jint/Native/Array/ArrayConstructor.cs#L332), [two](https://github.com/sebastienros/jint/blob/3b33cb1135e743040f7ba5078eb2ae495fb2a0ce/Jint/Native/Array/ArrayConstructor.cs#L339)) do exist? 

Maybe I could be of more help next time.

**Comment by lahma** [comment]
These are for the interop as you can call `new Array(myClrObject)` and it needs to translate to value enumeration at times. Here's a test case for example that hits this path:

```csharp
public void ArrayFromShouldConvertIEnumerable()
{
    var enumerable = new []
    {
        new Person {Name = "Mike"},
        new Person {Name = "Mika"}
    }.Select(x => x);

    _engine.SetValue("a", enumerable);

    RunTest(@"
        var arr = new Array(a);
        assert(arr.length === 2);
        assert(arr[0].Name === 'Mike');
        assert(arr[1].Name === 'Mika');
    ");

    RunTest(@"
        var arr = Array.from(a);
        assert(arr.length === 2);
        assert(arr[0].Name === 'Mike');
        assert(arr[1].Name === 'Mika');
    ");
}
```
Generally inside the engine we can skip using the public API that translates things and follows the JS spec when we know what kind of array needs to be produced. CLR interop adds some extra spice to the mix usually and causes some deviation from normal logic / spec.

**Comment by shestakov** [comment]
@lahma looked through [ArrayConstructor.Construct](https://github.com/sebastienros/jint/blob/3b33cb1135e743040f7ba5078eb2ae495fb2a0ce/Jint/Native/Array/ArrayConstructor.cs#L322). Seems like the bug spotted a deeper problem.

Should IDictionary<string, object> be ever treated as an array-like object (containing items of type KeyValuePair<string, object>), or should it always be treated as something object-like.

**Comment by lahma** [comment]
Makes sense, I've removed the array-likeness for dictionaries for now, until someone comes up with counter-example why they actually should be array like, oh the interop.

**Comment by shestakov** [comment]
@lahma thank you very much once again!
