### ISSUE TITLE
Suggestion: special syntax to call .NET indexers

### ISSUE THREAD

**Issue by h15ter** [sebastienros/jint#91]
Current .NET indexers support in JINT is a bit messy. 
1) It doesn't support multi-argument indexers
2) It's not strongly-typed (non-deterministic)
- let's say there are this[DateTime date], this[string key] and this[int index]
- there is javascript, clrObj['123'] = 'whatever'
- which indexer will be invoked?
  3) There is a quite high risk that .NET indexer will mess up with some javascript object's own property

I our case we had to write proxies/wrappers with no indexers around all our .NET types being exposed to javascript, because we don't feel the current indexer implementation is safe. Looks like some special syntax to access .NET syntax would be more reliable rather than 'clrObj[index]', maybe something like clrObj.getItem(param1, param2...) and clrObj.setItem(param1, param2...)

**Comment by merakod** [comment]
This has actually been one of our biggest issues after upgrading from Jint 0.9.2
We might try to fix this..

**Comment by sebastienros** [comment]
Can you refresh my mind and explain how it was behaving in Jint 0.9 ?

**Comment by lahma** [comment]
Closing this as the resolution is quite smart in 3.x series and one can always expose extra object methods to do the heavy lifting in CLR code.
