### ISSUE TITLE
Infinite loop when script contains Regex and AdaptRegexp = true

### ISSUE THREAD

**Issue by EricJangola** [sebastienros/jint#913]
Hi there,

I'm using Jint to execute script on an Application and when the scripts contains Regex, if the AdaptRegexp is enabled there's an error on Esprima to ParseScript.

On Engine.cs:

public Engine Execute(string source, ParserOptions parserOptions)=>; Execute(new JavaScriptParser(source, parserOptions).ParseScript());

The current script that I'm using is this:

function run(valor) {
	return res = "R$ " + valor.replace(/\,|[a-zA-Z]|\$/gmi, '').replace(/\./gmi, ',');
}

Any ideas? ( btw its working with Adapt off )

Best Regards,

**Comment by lahma** [comment]
I think we fixed this in the latest Jint release. Please check if problem persists and we can reopen if so.
