### ISSUE TITLE
I can't catch ExecutionCanceledException

### ISSUE THREAD

**Issue by yiszza** [sebastienros/jint#916]
i don't know why.....can you help me?
![QQ截图20210617181523](https://user-images.githubusercontent.com/42995476/122378211-57cd8f00-cf98-11eb-8734-741068f60428.png)

**Comment by lahma** [comment]
Please create a failing unit test case, code that can be copy-pasted to IDE please.

**Comment by yiszza** [comment]
the code is console app for dotnet6
--------------------------------------------------------------------------------------------------
using Jint;
using Jint.Constraints;
using Jint.Runtime.Interop;
using System;
using System.Threading;

namespace JintTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var constraint = new CancellationConstraint(new CancellationToken(false));
            var engine = new Engine(options =>
            {
                options.Constraint(constraint);
            });

            engine.SetValue("Thread", TypeReference.CreateTypeReference(engine, typeof(Thread)));
            engine.SetValue("print", new Action<object>(Console.WriteLine));

            try
            {
                engine.Execute(
                @"
                    print('run');
                    new Thread(() => { 
                        Thread.Sleep(5000);
                        for(let i = 0; i < 10; i++){
                            
                        }
                    }).Start();
                ");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
            Console.ReadKey();
            Console.WriteLine();
            Console.WriteLine("wait.......");
            constraint.Reset(new CancellationToken(true));
            Console.ReadKey();

        }
    }
}
