### ISSUE TITLE
ReflectionAccessor.SetValue causes stack-overflow on cyclic objects.

### ISSUE THREAD

**Issue by whizzter** [sebastienros/jint#919]
Checked out JInt yesterday ( c55a5e447b5682db1c9156e29569c8dba724b380 ) and built it, while trying to make a faux-dom good enough for Vue to be used for WinForms i ran into an issue.

My dom-nodes are implemented as extending dynamic-object (`System.Dynamic.DynamicObject`) and when Vue stores a reference of it's own state(that for some reason is self-cyclic) to the fauxdom-node this code path is touched.

On line 101 a call to "ToObject" is done and this one will recurse forever is the object is self-referring.
` converted = value.ToObject(); `

I'm not familiar with the internals at all so I'm not entirely sure if this is a big no-no due to dual representations of objects or if there are perf-issues at play so not sure what kind of solution would be the best here.

![image](https://user-images.githubusercontent.com/928807/122974493-ab721b00-d392-11eb-9627-64e91554d7fb.png)

**Comment by lahma** [comment]
Jint will now throw `TypeError` when it detects cyclic reference. If you'd prefer different behavior please open a PR to tweak.
