### ISSUE TITLE
JSValue ToNumber() and ToBoolean()

### ISSUE THREAD

**Issue by derekdiamond** [sebastienros/jint#950]
If we have JSvalue.IsNumber why not JSValue.ToNumber. 
I am using this in code:

var x = engine.Evaluate(...)
if (x.IsNumber)
{
   return (x as JsNumber).ToObject();
}
// This is super ugly!!! We do have JSvalue.ToDate()!!!

**Comment by lahma** [comment]
There is `x.AsNumber()` which returns `JsNumber`.

**Comment by lahma** [comment]
Closing as non-issue, there's the mentioned methods.
