### ISSUE TITLE
Security leak

### ISSUE THREAD

**Issue by koculu** [sebastienros/jint#993]
Security leak:
even I do not expose Assembly type it is accessible via any type like below:
```javascript
log(model.GetType().Module.GetType().Module.GetType('System.DateTime'));
```

```c#
var jintEngine = new Engine();
jintEngine.SetValue("log", new Action<object>(Console.WriteLine));
jintEngine.SetValue("model", new List<int>());
jintEngine.Execute(Code);
```
With this leak a script can access any .NET class in the system and can execute any arbitrary code using server privileges.
Is there any mechanism to prevent such leaks?

**Comment by lahma** [comment]
You can use interop configuration and MemberFilter to hide GetType. But as this seems to be a recurring theme I've created a PR https://github.com/sebastienros/jint/pull/994 to hide it by default.
